databricks/terraform-provider-databricks

website/content/Resources/job.md
The attribute in the jobs resource seems to be called `schedule` instead of `job_schedule` like it was mentioned in the docs
=> Fix jobs docs: schedule i.o. job_schedule

client/service/client.go, client/service/dbfs_test.go
Fixed 3 linting errors that were causing `make build` to fail: `S1039: unnecessary use of fmt.Sprintf (gosimple)`
=> fixed linting errors 1039 unnecessary fmt

databricks/resource_databricks_job.go
This fixes #25 and only sets the `new_cluster` field when it was also set in the schema
=> Only set new_cluster in the job when it's set in the schema

databricks/resource_databricks_notebook.go
The state func in the content argument for the notebook resource was called during the plan phase. Because I was using a templatefile with a dependency, the computed value was not available yet.
The state func got a guid instead of a base64 string so it fails to parse it (probably because the content is not available yet?)
The validation func should correctly verify if it's a valid base64 string and seems to handle the edge cases of when the value is not computed yet.
This fixes #47 
Maybe could you let me know why the state func was there in the first place? Thanks!
=> Fix for #47: notebook content state func is called at the wrong time

databricks/resource_databricks_cluster.go, databricks/resource_databricks_notebook.go, website/content/Resources/cluster.md, website/content/Resources/notebook.md
Hey! ✌️
Made the following changes to update the docs and smooth adoption for people, especially those hoping to use their deployed resources for Python notebooks, and deploying clusters to Azure:
- Update `spark_version` cluster resource parameter to "required"
- Update `node_type_id` cluster resource parameter to "required"
- Remove JUPYTER from the documented notebook format types. It was rejected when I used it, but SOURCE worked just fine for Python.
- Add example to notebook documentation for quick deployment of an empty Python notebook (common use case)
- Note that "absolute path" to deployed notebooks is not a regular file system path, but must start specifically with "/", giving an example for a notebook.
=> Documentation updates for correctness and demonstration 

Dockerfile
In order to support Alpine Linux the `CGO_ENABLED=0` flag is needed, which is set in `.goreleaser.yml` but was not set in the Dockerfile.
Before this change the binary built via the Dockerfile was not compatible with the hashicorp/terraform base image, which is based on Alpine Linux.
In other words this is what happened if you tried to build master and use it directly via the Dockerfile:
```
❯ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
❯ docker build -t jordanjennings/databricks-terraform:master .
Sending build context to Docker daemon  20.83MB
Step 1/9 : FROM golang:1.13
... lots of build output removed ...
Successfully built ed0089b8fd5d
Successfully tagged jordanjennings/databricks-terraform:master
❯ docker run --rm -it --entrypoint …
```
=> Fix Dockerfile compatibility with Alpine Linux

client/model/cluster_policies.go, client/service/apis.go, client/service/cluster_policies.go, databricks/provider.go, databricks/resource_databricks_cluster_policy.go, databricks/resource_databricks_cluster_policy_test.go, databricks/testdata/policy01.json, docs/resources/cluster_policy.md, website/content/Resources/cluster_policy.md
Added new resource, that will allow administrators to limit cluster resource consumption and lock down certain security aspects:
```
resource "databricks_cluster_policy" "external_metastore" {
name = "External Metastore Example"
definition = jsonencode({
"spark_conf.spark.hadoop.javax.jdo.option.ConnectionURL": {
"type": "fixed",
"value": "jdbc:sqlserver://<jdbc-url>"
},
"spark_conf.spark.hadoop.javax.jdo.option.ConnectionDriverName": {
"type": "fixed",
"value": "com.microsoft.sqlserver.jdbc.SQLServerDriver"
},
"spark_conf.spark.databricks.delta.preview.enabled": {
"type": "fixed",
"value": true
},
"spark_conf.spark.hadoop.javax.jdo.option.ConnectionUserName": {
"type": "fixed",
"value": "<metastore-user>"
},
"spark_conf.spark.hadoop.javax.jdo.option.ConnectionPassword": {
"type": …
```
=> [FEATURE] Added databricks_cluster_policy resource

client/service/client.go
Fixes: #160
This is based on https://github.com/Azure/go-autorest/blob/master/autorest/adal/sender.go the `func sender() Sender` configurations.
=> HTTP Proxy Settings fix

client/model/dbfs.go, client/service/dbfs.go, client/service/dbfs_integration_test.go, client/service/dbfs_test.go, databricks/resource_databricks_dbfs_file.go, databricks/resource_databricks_dbfs_file_test.go, databricks/resource_databricks_notebook.go, databricks/resource_databricks_notebook_test.go, databricks/utils.go, databricks/utils_test.go, docs/resources/dbfs_file.md, docs/resources/notebook.md, website/content/Resources/dbfs_file.md, website/content/Resources/notebook.md
DBFS File had a few issues. This will be refactoring these issues:
1. Introduces two new fields: `source`, `content_b64_md5`
2. The new field `content_b64_md5` is required and it is used for determining differences and changes.
3. Updated documentation
4. Added unit testing and integration testing
5. Gives way forward for not clogging up state file with "content" data by using `source` field and also allows to go over the 4mb limit problem of GRPC limitations created by terraform. You can find the test here: `TestAccDatabricksDBFSFile_CreateVeryBigFiles`
6. Updated documentation to include new fields.
=> DBFS Refactor & Fixes to support larger files

databricks/resource_databricks_cluster.go, databricks/resource_databricks_cluster_test.go, website/content/Resources/cluster.md, website/content/Resources/instance_pool.md
1. aws_attrbiutes (availability, zone_id, spot_bid_price_percent, first_on_demand, ebs_volume_type, ebs_volume_count, ebs_volume_size) are now Optional and Computed
2. instance_type_id now conflicts with "aws_attributes.0.availability", "aws_attributes.0.zone_id", "aws_attributes.0.spot_bid_price_percent", "aws_attributes.0.first_on_demand", "aws_attributes.0.ebs_volume_type", "aws_attributes.0.ebs_volume_count", "aws_attributes.0.ebs_volume_size".
3. `node_type_id` is now optional and computed
4. handleInstancePoolClusterRequest removes all attributes from model.Cluster that is not allowed when InstancePoolId is configured when making create/update request.
5. Added Integration Tests
6. TODO: Update and fix docs
=> Cluster instance pool fix

compute/acceptance/job_test.go, compute/clusters.go, compute/commands.go, compute/commands_test.go, internal/qa/testing.go, internal/qa/testing_test.go, storage/acceptance/aws_s3_mount_test.go, storage/aws_s3_mount.go, storage/aws_s3_mount_test.go, storage/mounts.go, storage/mounts_test.go
changes made
1. fixed contexts/status to get request
2. refactored EnvironmentTemplate and added unit tests for it
3. added acc test for IamMount
4. awsiammount struct config method returns empty map
5. NewMount creates an instance of the CommandsAPI if executor in the client is nil (both tests and prod path works) IMO this suffices for now. Not sure if we would ever mock some calls and let it actually "production" apis in the other half but dont really need that at the moment.
=> mounts patch

README.md, access/acceptance/secret_acl_test.go, access/acceptance/secret_scope_test.go, compute/acceptance/cluster_policy_test.go, compute/acceptance/cluster_test.go, docs/changelog.md, docs/data-sources/aws_crossaccount_policy.md, internal/sanity/utils_test.go, scripts/run.sh, storage/acceptance/adls_gen2_test.go, storage/mounts.go
* Added support for [local disk encryption](https://github.com/databrickslabs/terraform-provider-databricks/pull/313)
* Added more reliable [indication about Azure environment](https://github.com/databrickslabs/terraform-provider-databricks/pull/312) and fixed azure auth issue for Terraform 0.13
* Updated [databricks_aws_crossaccount_policy](https://github.com/databrickslabs/terraform-provider-databricks/pull/311) to latest rules
* Fixed missing importers for [databricks_scim_*](https://github.com/databrickslabs/terraform-provider-databricks/pull/290) resources
* Updated [Terraform Plugin SDK](https://github.com/databrickslabs/terraform-provider-databricks/pull/279) to latest version along with transitive dependencies.
* Added support disclaimers
* Increased code coverage to 65%
~FAIL: …
=> Prepare version 0.2.5

docs/resources/azure_adls_gen2_mount.md
Typo in the documentation for the use of the `databricks_azure_adls_gent2_mount` example.
=> update adls_gen_2 document example

access/resource_permissions.go, access/resource_permissions_test.go, docs/resources/cluster.md, docs/resources/group.md, docs/resources/instance_pool.md, docs/resources/job.md, docs/resources/notebook.md, docs/resources/permissions.md, docs/resources/secret_acl.md, docs/resources/secret_scope.md, docs/resources/user.md, identity/users.go
Fix #185 
```hcl
resource "databricks_permissions" "token_usage" {
authorization = "tokens"
access_control {
group_name = "Automation"
permission_level = "CAN_USE"
}
access_control {
group_name = "Engineering"
permission_level = "CAN_MANAGE"
}
}
```
```hcl
resource "databricks_permissions" "password_usage" {
authorization = "passwords"
access_control {
group_name = "Invited Users"
permission_level = "CAN_USE"
}
}
```
=> Add support for PAT usage permissions

access/acceptance/secret_acl_test.go, access/resource_secret_scope.go, access/resource_secret_scope_test.go, docs/changelog.md, docs/resources/secret_scope.md
If the scope is defined with `initial_manage_principal = ""`, then the corresponding field is omitted from the request body, and as result, `users` group won't get the `MANAGE` permission for created scope as [described in Secrets API docs](https://docs.databricks.com/dev-tools/api/latest/secrets.html#create-secret-scope).
This fixes #322
=> [bugfix] "Secret scope ACL is MANAGE for all users by default"

README.md, access/resource_permissions_test.go, compute/clusters.go, compute/clusters_test.go, compute/common_instances.go, compute/data_node_type.go, compute/data_node_type_test.go, compute/model.go, docs/data-sources/node_type.md, docs/index.md, docs/resources/cluster.md, docs/resources/instance_pool.md, docs/resources/job.md, provider/provider.go, storage/aws_s3_mount.go
Implements issue #346 to help customers pick node types easier:
```hcl
data "databricks_node_type" "with_gpu" {
local_disk  = true
min_cores   = 16
gb_per_core = 1
min_gpus    = 1
}
resource "databricks_cluster" "research" {
cluster_name            = "Research Cluster"
spark_version           = "6.6.x-scala2.11"
node_type_id            = databricks_node_type.with_gpu.id
autotermination_minutes = 20
autoscale {
min_workers = 1
max_workers = 50
}
}
```
=> Add databricks_node_type data source

compute/clusters.go, compute/clusters_test.go, compute/model.go, compute/resource_cluster.go
Right now, Cluster Events API doesn't allow to specify maximal number of items to fetch -
the existing `limit` parameter specifies the number of the items per page, not max count,
so this limit should enforced on the caller's site.
this fixes #380
=> Allow to specify max items to return in the Cluster Events API call (issue #380)

CHANGELOG.md, compute/resource_cluster.go, compute/resource_cluster_test.go
This PR adds detection of what cluster parameters were changed, and call `/clusters/edit`
only we changed parameters that are related to cluster directly, not things like
`is_pinned` or `library`...
This fixes #379
=> Don't restart cluster on changes that doesn't affect it (issue #379)

CHANGELOG.md, Makefile, README.md, common/http.go, common/version.go
=> Bump version to 0.2.9

access/resource_secret_scope.go
This problem was caused by the lazy initialization of the terraform provider - the call to
`IsAzure()` didn't recognize Azure because no HTTP call was made yet, and as result - no
authentication information was loaded.
It was easy reproducible with following:
```hcl
data "azurerm_key_vault" "example" {
name                = "some-kv"
resource_group_name = "some-rg"
}
resource "databricks_secret_scope" "example" {
name = data.azurerm_key_vault.example.name
keyvault_metadata {
resource_id = data.azurerm_key_vault.example.id
dns_name    = data.azurerm_key_vault.example.vault_uri
}
}
```
=> Fix error with creation of keyvault-based scope

CHANGELOG.md, common/azure_auth.go, common/azure_auth_test.go, common/env.go, common/env_test.go, docs/index.md, provider/provider.go
This PR should fix the issues #434 and #391.
This is my first PR so feedback is very welcome.
=> added support for other azure cloud environments

CHANGELOG.md, README.md, compute/clusters.go, compute/clusters_test.go, compute/data_spark_version.go, compute/data_spark_version_test.go, compute/model.go, docs/data-sources/node_type.md, docs/data-sources/spark_version.md, docs/index.md, docs/resources/cluster.md, docs/resources/instance_pool.md, docs/resources/job.md, provider/provider.go
This PR implements `databricks_spark_version` data source that allows to find DBR/Spark version that matches to specified filtering criteria.
This fixes #347
=> Data source for supported DBR/Spark versions

compute/acceptance/job_test.go, compute/clusters.go, compute/clusters_test.go, compute/common_instances.go, compute/common_instances_test.go, compute/resource_instance_pool_test.go, internal/qa/testing.go, internal/qa/testing_test.go, storage/acceptance/aws_s3_mount_test.go, storage/aws_s3_mount.go
instead of hardcoded Spark version obtained via `CommonRuntimeVersion`, now we can get Spark version via REST API
=> use spark_version data source in tests, etc.

common/client.go, common/http.go, go.mod, go.sum, provider/provider.go
=> Add global rate limit to HTTP calls

Makefile
right now, when the version of used package changes we need to explicitly run `make vendor` before calling `make build`, otherwise it fails. This PR makes this dependency explicit.
=> build target in Makefile should depend on vendor target

CHANGELOG.md, access/resource_permissions.go, access/resource_permissions_test.go, go.mod, go.sum
=> Prevent setting any permissions to admins group

common/client.go, common/testdata/corrupt/.databrickscfg, provider/provider_test.go
=> Make cleaner error message for no config profile

identity/resource_token.go, identity/resource_token_test.go
fixes #494 
- allow tokens without comment or expiration
- add acceptance test for tokens without comment & expiration
=> Fix token creation without comment or expiration

workspace/resource_notebook.go
Adds `filepath.ToSlash` on the input to mkdir to ensure that path separator stays consistent over different OSes. On Windows systems it would be translated to `\` before sending the request to databricks, which isn't supported. 
Fixes #496
=> Ensure consistent slashes in notebook paths for different OSes

.gitignore, README.md, access/resource_permissions.go, common/azure_auth.go, common/azure_cli_auth.go, common/http.go, common/http_test.go, compute/resource_job.go, docs/guides/workspace-management.md, docs/index.md, docs/resources/group.md, docs/resources/mws_credentials.md, docs/resources/mws_customer_managed_keys.md, docs/resources/mws_log_delivery.md, docs/resources/mws_networks.md, docs/resources/mws_storage_configurations.md, docs/resources/mws_workspaces.md, docs/resources/permissions.md, docs/resources/sql_endpoint.md, docs/resources/user.md, identity/resource_group.go, identity/scim.go, identity/users.go, internal/qa/testing.go, provider/provider.go, sqlanalytics/acceptance/sql_endpoint_test.go, sqlanalytics/resource_sql_endpoint.go, sqlanalytics/resource_sql_endpoint_test.go
=> [RESOURCE] databricks_sql_endpoint

compute/commands.go, compute/commands_test.go
When adding new mounts towards Azure Datalakes to the terraform configuration, it would sometimes cause a terraform crash. Mostly because of missing permissions on the container or the network blocked the traffic. Seemed like the error came from a HTTP 403 that came back to the commands running in databricks and it couldn't parse this when that error message came back to terraform. 
Related issue filed earlier with the error message: #448 
I identified that the problem in the parsing was the error message matching in the response from databricks, where with this particular kind of results gave an empty error message from the regular expression here: 
https://github.com/databrickslabs/terraform-provider-databricks/blob/67c7713895d8f71a29958fe0e04901c7b5827608/compute/commands.go#L26 …
=> Fix error message panic in command result parsing

exporter/command.go
Right now, when exporter is called from the command line, it receives not only
command-line arguments, but also the name of the program & `exporter` word, like this:
```
[./terraform-provider-databricks exporter -debug -directory output -listing workspace -services workspace]
```
and parsing fails, but without error, so default parameters are always used instead
=> fixed passing the command-line arguments

exporter/importables.go
Failed on terraform apply after `./terraform-provider-databricks exporter -match shared` config from one of the biggest test environments.
=> Fix dbfs file export

compute/resource_job.go
it also happened when `max_concurrent_runs` wasn't provided
this fixes #530
=> fix applying changes in absence of the email_notifications block

common/azure_auth.go, common/client.go, common/client_test.go, compute/resource_cluster.go, compute/resource_job.go, identity/resource_group.go, identity/scim.go, workspace/resource_notebook.go
also: 
* added `url` field for clusters & groups.
* small cosmetic fixes to make linter happy
=> Fixed formatting of URLs for notebooks and jobs

common/reflect_resource.go, common/reflect_resource_test.go
We have polymorphic parameters in SQLA queries. For `text` and `number` parameters, there isn't a whole lot to configure, except for the default value (which is differently typed, depending on the parameter type). If the default value isn't set (or is set to be empty), the whole type wrapper object isn't set, and no longer shows up in `*schema.ResourceData`. I'm fixing this by making the default value a required field.
However, if the value was empty, it still didn't show up in `*schema.ResourceData`. This was caused by the reflection code ignoring all empty strings in nested types, instead of checking the schema first, as is done for top level fields.
Intuitively, if a field is required, it should always show up in `*schema.ResourceData`.
=> Ensure required fields in nested objects are set

common/client.go, compute/clusters.go, compute/common_instances.go, compute/resource_instance_pool_test.go, exporter/util.go
Added `IsGcp` & `IsAws` functions, changed relevant places when we have AWS specific functionality, etc.
=> Preparations for GCP support

docs/guides/experimental-exporter.md, docs/resources/aws_s3_mount.md
in some places `databricks_s3_mount` was used instead of `databricks_aws_s3_mount`
=> fix the name of S3 mount resource

CHANGELOG.md, common/http.go, exporter/exporter_test.go
The root cause is that for URL query parts the path escaping was applied that didn't escape the `&` character, so query was split incorrectly
This fixes #565
=> Fix incorrect escaping of special characters in URL query

docs/resources/azure_adls_gen2_mount.md
Fixes #567, look there for a more detailed explanation.
The `client_id` and the `application_id` are used interchangeably. This PR adds this to the documentation.
=> Add application object id to mount docs

CHANGELOG.md, compute/model.go, compute/resource_cluster.go, compute/resource_cluster_test.go, compute/resource_instance_pool.go, docs/resources/cluster.md, docs/resources/instance_pool.md
This PR adds support for Azure spot instances for clusters & instance pools. It also adds an additional support for preemptible executors on GCP (only for clsuters)
=> Support for spot instances on Azure

common/client.go
The rate limiter was initialized with a maximum of 1 request per second with a
burst size of `RateLimitPerSecond`. Because we only use the `limiter.Wait()`
API, we can fix the burst at 1.
=> Fix the HTTP request rate limiter

CHANGELOG.md, compute/model.go, compute/resource_job.go, compute/resource_job_test.go, docs/resources/job.md
Changed pause_status from the schedule config block in jobs to a optional+computed field rather than a computed field (least amount of disruption to existing state). 
(Users can choose to omit it if the do not want terraform to nitpick that it has changed. Changing it to just optional will give the behavior of always tracking state and always must be managed by terraform.)
=> added support for job to have pause_status

docs/index.md
also documented missing parameters
=> [DOCS] Move non-auth provider configs into separate section

compute/clusters.go, compute/clusters_test.go
This would help with debugging in cases when cluster can't start for some reason, such as provider error.   Existing debugging doesn't help because `ClusterInfo.StateMessage` doesn't include full error message
=> More verbose logging of termination reason

common/http.go, compute/clusters.go, compute/clusters_test.go
also, reworked the reporting of termination information
=> apply debug_truncate_bytes also for response dumps

docs/resources/sql_endpoint.md, sqlanalytics/resource_sql_endpoint.go, sqlanalytics/resource_sql_endpoint_test.go
The data source ID is needed to bind a SQLA query to an endpoint. It is not included in the API's endpoint payload. There is a 1:1 mapping between endpoints and data sources, so we can include it in the endpoint's state.
I verified the acceptance test with:
```
CLOUD_ENV=aws TF_LOG=debug go test -run ^TestPreviewAccSQLEndpoint$ -v github.com/databrickslabs/terraform-provider-databricks/sqlanalytics/acceptance
```
It already failed before this PR because of defaults that are populated by the API (see #600). If fails in the same way with this PR, which reasonably implies that this PR didn't affect it.
=> Include data source ID in the endpoint state

CHANGELOG.md, README.md, docs/resources/mws_networks.md, docs/resources/mws_private_access_settings.md, docs/resources/mws_vpc_endpoint.md
=> Add 0.3.3 changelog

common/version.go, compute/model.go, compute/resource_cluster.go, compute/resource_instance_pool.go, compute/resource_job.go, docs/resources/cluster.md, docs/resources/instance_pool.md, docs/resources/job.md
We don't need to specify empty blocks for aws_attributes/azure_attributes/gcp_attributes to prevent edit/re-creation of the clusters/jobs/instance pools.
For instance pools even specification of empty blocks didn't work because we were need to specify availability & other attributes as well to prevent recreation of objects
=> Fix handling of empty blocks for clusters/jobs/instance pools

docs/resources/instance_pool.md
Minor change, fixes a link in the docs to go to the correct link. Looking through git history, doesn't look like `data-source` ever existed as a directory under `docs`, so probably just a spelling mistake.
=> chore(docs): fix link to point to correct path

CHANGELOG.md, README.md, access/resource_sql_permissions.go, docs/guides/aws-workspace.md, docs/guides/workspace-management.md, docs/index.md, docs/resources/mws_customer_managed_keys.md, mws/resource_customer_managed_key.go, mws/resource_customer_managed_key_test.go, scripts/modules/aws-mws-common/kms.tf
* Fixed state refresh bugs in `databricks_sql_permissions` ([#620](https://github.com/databrickslabs/terraform-provider-databricks/issues/620), [#619](https://github.com/databrickslabs/terraform-provider-databricks/issues/620))
* Fixed `workspace_ids_filter` mapping for `databricks_mws_log_delivery` ([#635](https://github.com/databrickslabs/terraform-provider-databricks/issues/635))
* Multiple documentation improvements ([#597](https://github.com/databrickslabs/terraform-provider-databricks/issues/597), [eb60d10](https://github.com/databrickslabs/terraform-provider-databricks/commit/eb60d103ea63221a1eb0069723ba3a0af45dbe3b), [edcd4b1](https://github.com/databrickslabs/terraform-provider-databricks/commit/edcd4b121254e3ff3130bed9c4ef9d849d342561), …
=> Prepare 0.3.4

docs/data-sources/user.md, identity/data_user.go, identity/data_user_test.go
Issue: https://github.com/databrickslabs/terraform-provider-databricks/issues/647
=> add data source user

CHANGELOG.md, compute/model.go, compute/resource_instance_pool.go, docs/resources/cluster.md, docs/resources/instance_pool.md
=> added support for preloading of docker images into instance pools

access/resource_permissions.go, access/resource_permissions_test.go, exporter/exporter_test.go
The "main" permissions API is not in the preview anymore, so I switched from
`/preview/permissions` to `/permissions`
This fixes #661
=> Use correct API endpoint for SQLA Endpoints

CHANGELOG.md, README.md, docs/guides/aws-workspace.md, docs/guides/workspace-management.md, docs/index.md, docs/resources/service_principal.md, exporter/exporter_test.go, exporter/importables.go, exporter/test-data/get-cluster-policy.json, exporter/util.go, identity/acceptance/resource_service_principal_test.go, identity/resource_service_principal.go, identity/resource_service_principal_test.go
* Fixed setting of permissions for SQLA endpoints ([#661](https://github.com/databrickslabs/terraform-provider-databricks/issues/661))
* Added support for preloading of Docker images into instance pools ([#663](https://github.com/databrickslabs/terraform-provider-databricks/issues/663))
* Added the `databricks_user` data source ([#648](https://github.com/databrickslabs/terraform-provider-databricks/pull/648))
* Fixed support for `spot_instance_policy` in SQLA Endpoints ([#665](https://github.com/databrickslabs/terraform-provider-databricks/issues/665))
* Added documentation for `databricks_pipeline` resource ([#673](https://github.com/databrickslabs/terraform-provider-databricks/pull/673))
* Fixed mapping for `databricks_service_principal` on AWS …
=> Prepare release 0.3.5

docs/resources/sql_query.md, sqlanalytics/api/query.go, sqlanalytics/resource_query.go, sqlanalytics/resource_query_test.go
=> Add run_as_role field to databricks_sql_query

docs/resources/cluster.md
the DBFS URL should use the single `/` instead of two (that is used only for host-based URLs: https://datatracker.ietf.org/doc/html/rfc3986#section-3)
=> fix DBFS urls in the documentation

docs/resources/directory.md, docs/resources/permissions.md, provider/provider.go, workspace/resource_directory.go, workspace/resource_directory_test.go, workspace/resource_notebook.go
Issue: https://github.com/databrickslabs/terraform-provider-databricks/issues/672
=> add resource_directory

access/resource_permissions.go, access/resource_permissions_test.go, docs/data-sources/user.md, docs/guides/passthrough-cluster-per-user.md, identity/data_user.go, identity/data_user_test.go
Fix #702 Add `id` attribute to user data resource
* error out, when permissions are attempted to be added for the current user, as it's not possible to decrease administrative privileges
* added a guide for dynamic single-user passthrough clusters
=> Ability to create dynamic passthrough clusters based on members of the group

CHANGELOG.md, common/resource.go, compute/model.go, compute/resource_job.go, compute/resource_job_test.go, docs/resources/job.md
* Implements feature #389
* Functionality is triggered only if `always_running` attribute is present
* Uses RunsList, RunsCancel and RunNow methods from Jobs API
=> Add functionality to restart always running jobs

CHANGELOG.md, access/resource_permissions.go, access/resource_permissions_test.go, access/resource_secret_scope.go, access/resource_secret_scope_test.go, common/azure_auth.go, common/azure_auth_test.go, docs/index.md, identity/data_user_test.go, provider/provider.go, provider/provider_test.go, qa/testing.go
* PAT token still could be used by setting `azure_use_pat_for_spn` to `true`
* Check was added to make sure that Azure KeyVault + SPN is detected during plan, not during execution
=> Azure auth with SPN now uses AAD token by default instead of PAT

access/resource_sql_permissions.go, access/resource_sql_permissions_test.go, docs/resources/cluster.md, docs/resources/sql_permissions.md
Also:
* added example of creation of high-concurrency cluster
* switched to single-node cluster for setting SQL permissions
this fixes #680
=> clarify cluster options to apply `databricks_sql_permissions`

docs/guides/aws-workspace.md
Add VPC endpoints to the E2 Terraform deployment to line up with existing [docs](https://docs.databricks.com/administration-guide/cloud-configurations/aws/customer-managed-vpc.html#regional-endpoints-1), for more direct connections and reduced costs
=> add vpc-endpoints to the workspace documentation

mws/mws.go, mws/resource_workspace.go, mws/resource_workspace_test.go, scripts/mws-integration/main.tf
I tried to create a workspace with public IPs for all workers and found it didn't work.
Turns out the `omitempty` on the `is_no_public_ip_enabled` field means a value of `false` doesn't make it to the API, where it then defaults to `true`. Therefore, it can't be `omitempty`, but it's not a required field either. To make matters more complicated, it's not returned as part of the GET response. This PR sets a `DiffSuppressFunc` ignores value changes and only sets the field on creation.
Removed the field from all responses in tests because the API doesn't return it.
=> Fix handling of is_no_public_ip_enabled

CHANGELOG.md, access/resource_sql_permissions.go, access/resource_sql_permissions_test.go, common/azure_auth.go, compute/model.go, docs/resources/sql_endpoint.md, identity/acceptance/group_test.go, identity/acceptance/resource_user_test.go, identity/groups.go, identity/groups_test.go, identity/resource_group_instance_profile.go, identity/resource_group_member.go, identity/resource_service_principal.go, identity/resource_service_principal_test.go, identity/scim.go, sqlanalytics/resource_sql_endpoint.go, sqlanalytics/resource_sql_endpoint_test.go, storage/mounts.go, storage/mounts_test.go
* Added support for hybrid pools ([#689](https://github.com/databrickslabs/terraform-provider-databricks/pull/689))
* Added support for `always_running` jobs, which are restarted on resource updates ([#715](https://github.com/databrickslabs/terraform-provider-databricks/pull/715))
* Azure CLI auth is now forcing JSON output ([#717](https://github.com/databrickslabs/terraform-provider-databricks/pull/717))
* `databricks_permissions` are getting validation on `terraform plan` stage ([#706](https://github.com/databrickslabs/terraform-provider-databricks/pull/706))
* Added `databricks_directory` resource ([#690](https://github.com/databrickslabs/terraform-provider-databricks/pull/690))
* Added support for hybrid instance pools ([#689](https://github.com/databrickslabs/terraform-provider-databr …
=> Prepare release 0.3.6

common/client.go, common/http.go, provider/provider.go
This PR makes it possible to use different URLs for accounts console when `development_mode = true` is added to provider. Reserved for internal use.
=> Skip common error clarity for alternative accounts console deployments

CHANGELOG.md, README.md, docs/index.md, docs/resources/obo_token.md, docs/resources/workspace_conf.md, identity/acceptance/obo_test.go, identity/data_group.go, identity/groups.go, identity/resource_obo_token.go, identity/resource_obo_token_test.go, provider/provider.go
This resource creates On-Behalf-Of tokens for a Service Principal in Databricks workspaces on AWS. It is very useful, when you want to provision resources within a workspace through narrowly-scoped service principal, that has no access to other workspaces within the same Databricks Account.
Creating a token for a narrowly-scoped service principal
```hcl
resource "databricks_service_principal" "this" {
display_name = "Automation-only SP"
}
resource "databricks_permissions" "token_usage" {
authorization = "tokens"
access_control {
service_principal_name = databricks_service_principal.this.application_id
permission_level = "CAN_USE"
}
}
resource "databricks_obo_token" "this" {
depends_on = [databricks_permissions.token_usage]
application_id = databricks_service_principal.this.application_id …
```
=> `databricks_obo_token` resource to manage PAT tokens on behalf of service principals in E2 workspaces

sqlanalytics/resource_visualization.go, sqlanalytics/resource_visualization_test.go, sqlanalytics/resource_widget.go, sqlanalytics/resource_widget_test.go
It's fine if the remote resource was deleted. Terraform will attempt to recreate.
=> Don't error if widget or visualization doesn't exist

CHANGELOG.md, CONTRIBUTING.md, access/resource_permissions_test.go, access/resource_sql_permissions_test.go, compute/resource_instance_pool_test.go, docs/resources/mws_networks.md, docs/resources/mws_workspaces.md, identity/resource_group.go, identity/resource_user_test.go, mws/mws.go, mws/resource_workspace.go, mws/resource_workspace_test.go, qa/testing.go, qa/testing_test.go, workspace/resource_directory_test.go, workspace/resource_notebook_test.go
* Each time there's a workspace change diff, it's checked only for the allowed fields to be updated
* `PATCH /accounts/.../workspaces/..` only contains allowed fields
This PR fixes #649
=> Fix #649 - Improve workspace update logic

access/resource_permissions.go, access/resource_permissions_test.go
Validation of the set of permissions available to each resources was added in #706.
The set for DBSQL resources was incorrect and broke permission handling. This PR corrects those.
=> Fix available permissions to DBSQL resources

compute/resource_job.go, compute/resource_job_test.go, docs/resources/job.md
Fixes #739
This PR makes `max_concurrent_runs` on the `job` resource an optional attribute which defaults to `1`.
**Testing**. I ran the unit tests with `make test` but I didn't run the integration tests via `make test-azcli` or `make test-awsmt`. I don't mind running this, but would ask for some help here on how to run this without using my company's wrokspace as a test environment.
=> feat: max_concurrent_run defaults to 1

CHANGELOG.md, docs/resources/instance_profile.md, identity/resource_instance_profile.go, identity/resource_instance_profile_test.go, storage/aws_s3_mount_test.go
* `InstanceProfilesAPI` now operates with `InstanceProfileInfo` instead of just ARN
* This commit implements feature request #444
=> Added IAM Passthrough support

common/azure_auth.go, common/azure_auth_test.go, common/azure_cli_auth.go, qa/testing.go, storage/adls_gen1_mount.go, storage/adls_gen2_mount.go, storage/aws_s3_mount.go, storage/azure_blob_mount.go, storage/mounts.go, storage/mounts_test.go
For all azure environments we have been using public cloud endpoint
which fails to deploy in other environments like govcloud and china. Use
environment variables to fetch the correct ActiveDirectoryEndpoint per
Azure Environment.
=> Fix ActiveDirectoryEndpoint in adls gen1-2 mounts

mws/resource_log_delivery.go
Today if someone wants to update their existing Billing Usage delivery to a different time, Terraform will plan as a valid operation and then will fail with `Error: doesn't support update`. This should make it recreate the resource disabling the existing log delivery and create the new one with the correct delivery_start_date.
=> force new on delivery_start_time change

identity/resource_token.go, identity/resource_token_test.go
Addresses issue  #775.
Code to fix and the accompanying unit test for the new functionality.
=> Squelch the 404 error on token delete

docs/resources/permissions.md
Add a service principal in the doc example for Databricks permissions for jobs creation.
To get somewhere an example.
=> Add service principal in permissions doc

docs/resources/cluster.md
The following block:
```
init_scripts {
file {
destination = "file:/my/local/file.sh"
}
}
```
will fail with the following error when applied:
```
Error: File init scripts (specified with a file:/ prefix) can only be specified for clusters with custom docker containers.
```
Adding a note in the docs to reflect this.
Signed-off-by: Ian Dexter D Marquez <iandexter@users.noreply.github.com>
=> Add caveat for using the `file` prefix in `init_scripts`

workspace/resource_workspace_conf.go, workspace/resource_workspace_conf_test.go
Created this PR to address issue #823.
The issue shows that a key is added which doesn't comply to the expected naming conventions. As a consequence, the user is unable to remove the key, because it defaults to an invalid type according to the Databricks API.
This change replaces the key-based default value lookup with a value-based lookup. The lookup first checks the value type, and second tries to parse boolean strings.
Like the old implementation, this defaults to the `"false"`-string for boolean values, and default to the empty `""` string for all other values.
=> Reset custom workspace configuration using value

CHANGELOG.md, access/resource_secret_scope.go, common/azure_auth.go, common/azure_auth_test.go, common/azure_cli_auth.go, common/azure_cli_auth_test.go, common/client.go, common/client_test.go, common/gcp.go, common/gcp_test.go, common/http.go, common/http_test.go, docs/index.md, identity/resource_service_principal.go, mws/resource_workspace_test.go, provider/provider.go, provider/provider_test.go
Since v0.3.8, it's possible to leverage [Azure Managed Service Identity](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/managed_service_identity) authentication, which is using the same environment variables as `azurerm` provider. Both `SystemAssigned` and `UserAssigned` identities work, as long as they have `Contributor` role on subscription level and created the workspace resource, or directly added to workspace through [databricks_service_principal](resources/service_principal.md).
```hcl
host = data.azurerm_databricks_workspace.this.workspace_url
azure_use_msi = true 
}
```
=> Initial support for Azure MSI authentication

CHANGELOG.md, common/http.go, docs/index.md
This PR fixes #818 
```hcl
host = "https://accounts.cloud.databricks.com/"
account_id = "aaaaaa-bbbb-cccc-dddd"
}
resource "databricks_user" "me_admin" {
user_name = "me@example.com"
}
```
=> Added support to create `databricks_user` on the account level

CHANGELOG.md, identity/resource_instance_profile.go, scripts/awsmt-integration/main.tf
* Whenever `databricks_instance_profile` is created with `skip_validation = true`, create any changes to the field after resource is created won't have any effect.
Fixes #860
=> Suppress instance profile skip_validation diff

CHANGELOG.md, compute/acceptance/job_test.go, docs/resources/job.md
* Added `private_access_level` and `allowed_vpc_endpoint_ids` to `databricks_mws_private_access_settings` resource, which is also now updatable ([#867](https://github.com/databrickslabs/terraform-provider-databricks/issues/867)).
* Fixed missing diff skip for `skip_validation` in `databricks_instance_profile` ([#860](https://github.com/databrickslabs/terraform-provider-databricks/issues/860)).
* Added support for `pipeline_task` ([871](https://github.com/databrickslabs/terraform-provider-databricks/pull/871)) and `python_wheel_task` ([#872](https://github.com/databrickslabs/terraform-provider-databricks/pull/872)) to `databricks_job`.
* Improved enterprise HTTPS proxy support for creating workspaces in PrivateLink environments ([#882](https://github.com/databrickslabs/terraform-provider-da …
=> Prepare release v0.3.10

common/azure_auth.go, common/azure_auth_test.go, common/testdata/az-bad-token1/az, common/testdata/az-bad-token2/az, common/testdata/az-bad-token3/az, common/testdata/az-good-token/az, docs/resources/aws_s3_mount.md, docs/resources/azure_adls_gen1_mount.md, docs/resources/azure_adls_gen2_mount.md, docs/resources/azure_blob_mount.md, docs/resources/mount.md, docs/resources/pipeline.md, go.mod, provider/provider.go, qa/testing.go, qa/testing_test.go, storage/adls_gen1_mount.go, storage/adls_gen2_mount.go, storage/aws_s3_mount.go, storage/azure_blob_mount.go, storage/azure_blob_mount_test.go, storage/generic_mounts.go, storage/mounts.go, storage/mounts_test.go, storage/resource_mount.go, storage/resource_mount_test.go
This PR solves the problem with customization of the mount options that isn't possible right now, for example, to create Azure credentials passthrough mounts, etc.
Resource implements two approaches:
* You specify two main options `uri` - URL to mount (service dependent), and `extra_configs` - map of Spark configurations that is necessary to mount the resource.  This is most flexible way to perform mounts - see example for Azure passthrough mounts in documentation. For example:
```hcl
resource "databricks_mount" "this" {
mount_name = "tf-test"
uri = "abfss://${local.container}@${local.storage_acc}.dfs.core.windows.net"
extra_configs = {
"fs.azure.account.auth.type":                          "OAuth",
"fs.azure.account.oauth.provider.type": …
```
=> Implementation of the generic resource for mounts, cloud independent

identity/resource_group.go, identity/resource_group_test.go
The SCIM API in use does not support updating group names.  This avoids:
```
2021-11-02T11:27:08.561Z [DEBUG] provider.terraform-provider-databricks_v0.3.9: 404 Not Found {
"detail": "Group not found.",
"schemas": [
],
"status": "404"
}: timestamp=2021-11-02T11:27:08.561Z
```
when trying to update group names
See: https://docs.databricks.com/dev-tools/api/latest/scim/scim-groups.html#update-group
=> Create new group instead of updating the name

workspace/resource_repo.go, workspace/resource_repo_test.go
=> Create parent directory for Repos if it uses non-standard location

access/resource_secret_acl_test.go, access/resource_secret_scope.go
=> Update secret scope validation to include `/` characters

sqlanalytics/resource_widget.go, sqlanalytics/resource_widget_test.go
This fixes #897.
I used the annotation introduced by @alexott in #799.
=> Force recreation of widget on changing its visualization ID

CHANGELOG.md, docs/resources/mount.md, docs/resources/sql_global_config.md, sqlanalytics/resource_sql_global_config.go, storage/adls_gen1_mount.go, storage/adls_gen2_mount.go, storage/aws_s3_mount.go, storage/azure_blob_mount.go, storage/mounts.go
* Added `databricks_sql_global_config` resource to provide global configuration for SQL Endpoints ([#855](https://github.com/databrickslabs/terraform-provider-databricks/issues/855))
* Added `databricks_mount` resource to mount arbitrary cloud storage ([#497](https://github.com/databrickslabs/terraform-provider-databricks/issues/497))
* Improved implementation of `databricks_repo` by creating the parent folder structure ([#895](https://github.com/databrickslabs/terraform-provider-databricks/pull/895))
* Fixed `databricks_job` error related [to randomized job IDs](https://docs.databricks.com/release-notes/product/2021/august.html#jobs-service-stability-and-scalability-improvements) ([#901](https://github.com/databrickslabs/terraform-provider-databricks/issues/901))
* Replace …
=> Prepare v0.3.11

docs/data-sources/current_user.md, docs/data-sources/group.md, docs/data-sources/user.md, docs/resources/group.md, docs/resources/user.md, identity/data_current_user.go, identity/data_group.go, identity/data_user.go, identity/groups.go, identity/resource_group.go, identity/resource_user.go, identity/scim.go
External ID could be propagated from linked identity provider, and is used for things like Unity Catalog
=> Add optional external_id field to SCIM users and groups

clusters/resource_cluster.go, clusters/resource_cluster_test.go, pipelines/resource_pipeline.go
This change will prevent Terraform to restart a cluster which AwsAttributes.zone_id = "auto", as this is an unneeded/unwanted behavior.
=> Ignore autoaz changes

CHANGELOG.md, docs/guides/migration-0.4.x.md, docs/resources/group.md, docs/resources/service_principal.md, docs/resources/sql_dashboard.md, docs/resources/sql_endpoint.md, docs/resources/sql_query.md, docs/resources/sql_visualization.md, docs/resources/sql_widget.md, docs/resources/user.md, identity/resource_group_test.go, identity/scim.go
Now `databricks_user`, `databricks_group`, and `databricks_service_principal` resources are more in line with Databricks SQL product naming.
Fixes #844
=> Rename `allow_sql_analytics_access` to `databricks_sql_access`

CHANGELOG.md, README.md, clusters/data_clusters.go, clusters/data_clusters_test.go, docs/data-sources/clusters.md, provider/provider.go
-> **Note** If you have a fully automated setup with workspaces created by [databricks_mws_workspaces](../resources/mws_workspaces.md) or [azurerm_databricks_workspace](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/databricks_workspace), please make sure to add [depends_on attribute](../index.md#data-resources-and-authentication-is-not-configured-errors) in order to prevent _authentication is not configured for provider_ errors.
Retrieves a list of [databricks_cluster](../resources/cluster.md#cluster_id) ids, that were created by Terraform or manually, with or without [databricks_cluster_policy](../resources/cluster_policy.md).
Retrieve all clusters on this workspace on AWS or GCP:
```hcl
data "databricks_clusters" "all" {
depends_on = …
```
=> Added `databricks_clusters` data source

CHANGELOG.md, clusters/resource_cluster.go, clusters/resource_cluster_test.go, libraries/libraries_api.go, libraries/libraries_api_test.go
Whenever a library fails to get installed on a running cluster, we automatically remove it, so that the clean state of managed libraries is properly maintained. Without this fix users had to manually go to Clusters UI and remove library from a cluster, where it failed to install. Libraries add up to CREATE and UPDATE timeouts of `databricks_cluster` resource.
Fixes #599
=> Remove failed libraries on running clusters

common/client.go, mws/resource_workspace.go, provider/provider.go
* eagerly resolve `host`, `username`, `password`, and `token` from the specified `profile`
* add explicit logging of auth parameters in debug logs
* make sure that `ClientForHost()` eagerly authenticates before passing parameters to a child client
* possibly fix #915
=> Improve Databricks CLI auth

.vscode/testing.code-snippets, CHANGELOG.md, docs/guides/aws-workspace.md, docs/resources/mws_workspaces.md, mws/mws.go, mws/resource_workspace.go, mws/resource_workspace_test.go, scripts/nightly/awsit.tf, scripts/nightly/main.tf
=> Added `token` block to `databricks_mws_workspaces` 

README.md, clusters/clusters_api.go, clusters/resource_cluster.go, common/reflect_resource.go, common/resource.go, docs/data-sources/current_user.md, docs/guides/workspace-management.md, docs/index.md, docs/resources/permissions.md, pipelines/resource_pipeline.go
* Propagate diff suppression also to nested fields of a configuration block, if it's marked for diff suppression.
* Log more precise log messages when this happens.
Fix #942
=> Propagate `tf:"suppress_diff"` to child attributes

CHANGELOG.md, Makefile, README.md, docs/guides/aws-e2-firewall-hub-and-spoke.md, docs/guides/aws-e2-firewall-workspace.md, docs/guides/aws-workspace.md, docs/guides/workspace-management.md, docs/index.md, scripts/azcli-integration/main.tf
* Added `databricks_library` resource to install library on `databricks_cluster` ([#904](https://github.com/databrickslabs/terraform-provider-databricks/pull/904)).
* Added `databricks_clusters` data resource to list all clusters in the workspace, which might be used to install `databricks_library` on all clusters ([#955](https://github.com/databrickslabs/terraform-provider-databricks/pull/955)).
* Fixed refresh of `library` blocks on a stopped `databricks_cluster` ([#952](https://github.com/databrickslabs/terraform-provider-databricks/issues/952)).
* Whenever a library fails to get installed on a running `databricks_cluster`, we now automatically remove this library, so that the clean state of managed libraries is properly maintained. Without this fix users had to manually go to Clusters …
=> Release v0.4.1

CHANGELOG.md, docs/resources/notebook.md, permissions/acceptance/api_test.go, workspace/data_notebook.go, workspace/data_notebook_paths.go, workspace/data_notebook_paths_test.go, workspace/data_notebook_test.go, workspace/file_resource.go, workspace/resource_directory_test.go, workspace/resource_notebook.go, workspace/resource_notebook_test.go
Fixes #988
```hcl
locals {
url = "https://files/XYZ.dbc"
}
// though this can be replaced with data http & local file
resource "null_resource" "dbc" {
triggers = {
on_version_change = local.url
}
provisioner "local-exec" {
command = "curl -o ${path.root}/.terraform/import.dbc ${local.url}"
}
provisioner "local-exec" {
when    = destroy
command = "rm ${path.root}/.terraform/import.dbc"
}
}
// "downloaded_file" module then... or hack with https://registry.terraform.io/providers/anschoewe/curl/latest/docs/data-sources/curl
data "null_data_source" "values" {
inputs = {
x = "${path.root}/.terraform/import.dbc"
}
depends_on = [null_resource.dbc]
}
data "databricks_current_user" "me" {
}
resource "databricks_notebook" "lesson" {
source = data.null_data_source.values.outputs["x"]
path = …
```
=> Added DBC format support for `databricks_notebook`

docs/resources/permissions.md
Use databricks_node_type and databricks_spark_version data sources for cluster definitions
=> Update runtime versions on `databricks_permissions`

CHANGELOG.md, common/azure_auth_test.go, common/client.go, common/client_test.go, common/resource.go, docs/index.md, provider/provider.go, provider/provider_test.go
Added optional `auth_type` provider conf to enforce specific auth type to be used in very rare cases, where a single Terraform state manages Databricks workspaces on more than one cloud and `More than one authorization method configured` error is a false positive. Valid values are `pat`, `basic`, `azure-client-secret`, `azure-msi`, `azure-cli`, and `databricks-cli`.
=> Added `auth_type` for multi-cloud states

CHANGELOG.md, common/client.go, mws/acceptance/workspace_test.go, mws/resource_workspace.go
=> Fixed creating workspaces with `token {}` block

README.md, docs/guides/aws-e2-firewall-hub-and-spoke.md, docs/guides/aws-e2-firewall-workspace.md, docs/guides/aws-workspace.md, docs/guides/workspace-management.md, docs/index.md
Version changelog:
* Added optional `auth_type` provider conf to enforce specific auth type to be used in very rare cases, where a single Terraform state manages Databricks workspaces on more than one cloud and `More than one authorization method configured` error is a false positive. Valid values are `pat`, `basic`, `azure-client-secret`, `azure-msi`, `azure-cli`, and `databricks-cli` ([#1000](https://github.com/databrickslabs/terraform-provider-databricks/pull/1000)).
* Added `DBC` format support for `databricks_notebook` ([#989](https://github.com/databrickslabs/terraform-provider-databricks/pull/989)). 
* Fixed creating new `databricks_mws_workspaces` with `token {}` block ([#994](https://github.com/databrickslabs/terraform-provider-databricks/issues/994)).
* Added automated …
=> Release v0.4.2

docs/guides/aws-workspace.md, docs/resources/mws_networks.md
Spotted on [StackOverflow](https://stackoverflow.com/questions/70484747/databricks-sample-terraform-code-causes-error-in-aws-vpc-module)
=> Return back public_subnets that is required when create_igw=true

CHANGELOG.md, common/client.go, common/http.go, common/http_test.go
Added `Using XXX auth` explanation to HTTP 403 errors, which should help troubleshooting misconfigured authentication or provider aliasing. Example error message now looks like: *cannot create group: /2.0/preview/scim/v2/Groups is only accessible by admins. Using databricks-cli auth: host=https://XXX.cloud.databricks.com/, token=`***REDACTED***`, profile=demo.* All sensitive configuration parameters (`token`, `password`, and `azure_client_secret`) are redacted and replaced with `***REDACTED***`
Fixes #821
=> Added explanation to HTTP 403 errors

CHANGELOG.md, docs/resources/mlflow_experiment.md, docs/resources/mlflow_model.md, docs/resources/permissions.md, mlflow/resource_model.go, mlflow/resource_model_test.go, permissions/resource_permissions.go
Valid [permission levels](https://docs.databricks.com/security/access-control/workspace-acl.html#mlflow-experiment-permissions-1) for [databricks_mlflow_experiment](mlflow_experiment.md) are: `CAN_READ`, `CAN_EDIT`, and `CAN_MANAGE`.
```hcl
data "databricks_current_user" "me" {}
resource "databricks_mlflow_experiment" "this" {
name              = "${data.databricks_current_user.me.home}/Sample"
artifact_location = "dbfs:/tmp/my-experiment"
description       = "My MLflow experiment description"
}
resource "databricks_group" "auto" {
display_name = "Automation"
}
resource "databricks_group" "eng" {
display_name = "Engineering"
}
resource "databricks_permissions" "experiment_usage" {
experiment_id = databricks_mlflow_experiment.this.id
access_control {
group_name       = "users" …
```
=> Added MLflow permissions

.vscode/launch.json, CHANGELOG.md, CONTRIBUTING.md, main.go
You can [run provider in a debug mode](https://www.terraform.io/plugin/sdkv2/debugging#running-terraform-with-a-provider-in-debug-mode) from VScode IDE by launching `Debug Provider` run configuration and invoking `terraform apply` with `TF_REATTACH_PROVIDERS` environment variable.
=> Add debugger mode for the binary

docs/resources/mount.md, exporter/context.go, provider/provider_test.go, storage/resource_mount.go
Generic solution for importing mounts is not possible in the current implementation of mounts, that rely on Command/Context APIs.
This PR removes documentation references and `exporter` generation for things, that have never been properly working.
Fix #1018
=> Remove `databricks_mount` import from docs

CHANGELOG.md, clusters/resource_cluster.go, clusters/resource_cluster_test.go
Allowed managing of libraries on `databricks_cluster` outside of Terraform state for resources without any `library` configuration blocks.
**Behavior changes**
* Whenever library is installed on `databricks_cluster` without any [`library` configuration blocks](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster#library-configuration-block), it won't be removed anymore.
=> Skip lib refresh for clusters with no libs

CHANGELOG.md, docs/resources/user.md, scim/resource_user.go, scim/resource_user_test.go
Add `force` parameter to `databricks_user`, so that SCIM sync corner cases might be simplified
=> Implicitly force import manually added user

docs/resources/mws_networks.md
This PR adds a bit of clarification on that fact that the public subnet created in network section is used by NAT gateway.
=> Clarification public subnet is for NAT

CHANGELOG.md, README.md, docs/guides/aws-e2-firewall-hub-and-spoke.md, docs/guides/aws-e2-firewall-workspace.md, docs/guides/aws-workspace.md, docs/guides/workspace-management.md, docs/index.md
* Clarified error messages around `azure_workspace_resource_id` provider configuration ([#1049](https://github.com/databrickslabs/terraform-provider-databricks/issues/1049)).
* Added optional `force` argument to `databricks_user` resource to ignore `cannot create user: User with username X already exists` errors and implicitly import the specific user into Terraform state, enforcing entitlements defined in the instance of resource ([#1048](https://github.com/databrickslabs/terraform-provider-databricks/pull/1048)).
* Added `databricks_user_role` resource, that can assign roles on Databricks Account or `databricks_instance_profile` for data access ([#1047](https://github.com/databrickslabs/terraform-provider-databricks/pull/1047)).
**Deprecations**
* `databricks_user_instance_profile` is …
=> Release v0.4.6

CHANGELOG.md, docs/resources/group.md, scim/resource_group.go, scim/resource_group_test.go
Add `force` parameter to `databricks_group`, so that SCIM sync corner cases might be simplified
Closes #1066
=> Implicitly force import manually added group

CHANGELOG.md, docs/resources/permissions.md, permissions/resource_permissions.go
=> Allow configuring permissions for all MLflow models

README.md, docs/guides/aws-e2-firewall-hub-and-spoke.md, docs/guides/aws-e2-firewall-workspace.md, docs/guides/aws-workspace.md, docs/guides/workspace-management.md, docs/index.md
* Added optional `force` argument to `databricks_group` resource to ignore `cannot create group: Group with name X already exists.` errors and implicitly import the specific group into Terraform state, enforcing entitlements defined in the instance of resource ([#1066](https://github.com/databrickslabs/terraform-provider-databricks/pull/1066)).
* Added support to configure permissions for all MLflow models ([#1044](https://github.com/databrickslabs/terraform-provider-databricks/issues/1044)).
* Fixed `databricks_service_principal` `display_name` update ([#1065](https://github.com/databrickslabs/terraform-provider-databricks/issues/1065)).
* Added documentation for Unity Catalog resources.
* Bump gopkg.in/ini.v1 from 1.66.2 to 1.66.3
Test run: Azure
---
Test …
=> Release v0.4.7

CHANGELOG.md, docs/resources/sql_global_config.md, sqlanalytics/resource_sql_global_config.go, sqlanalytics/resource_sql_global_config_test.go
Also added a new parameter `sql_config_params`
this fixes #1076
=> Fix destroy of SQL Global config with instance profile setup

CHANGELOG.md, scim/resource_group.go
=> Prevent creation of`users` and `admins` groups

sql/resource_widget_test.go
Whether the widget parameter sorter is covered by the existing tests is non-deterministic.
This means it shows up as increasing/decreasing coverage in unrelated PRs, for example #900: https://app.codecov.io/gh/databrickslabs/terraform-provider-databricks/compare/900/changes
This PR fixes that by adding a test.
=> Add test to ensure deterministic coverage on widget parameter sorter

docs/guides/aws-workspace.md
Provider configuration section mentions module.ai to access the host & token. But there isn't such module. So fixing the doc to use the generate token during E2 workspace creation
=> Provider doc update for WS management

CHANGELOG.md, docs/data-sources/group.md, scim/acceptance/data_group_test.go, scim/acceptance/resource_user_test.go, scim/data_group.go, scim/data_group_test.go
* Added `users`, `service_principals`, and `child_groups` exported properties to `databricks_group` data resource ([#1085](https://github.com/databrickslabs/terraform-provider-databricks/issues/1085)).
Fixes #1085
=> Added `users`, `service_principals` to group data resource

README.md, common/version.go, docs/guides/aws-workspace.md, docs/guides/unity-catalog.md, docs/guides/workspace-management.md, docs/index.md, scim/acceptance/data_group_test.go, scripts/gcp-integration/main.tf
* Prevent creation of `databricks_group` with `users` and `admins` reserved names ([#1089](https://github.com/databrickslabs/terraform-provider-databricks/issues/1089)).
* Added support for shared clusters in multi-task `databricks_job` ([#1082](https://github.com/databrickslabs/terraform-provider-databricks/issues/1082)).
* Added diff suppression for `external_id` in `databricks_group` ([#1099](https://github.com/databrickslabs/terraform-provider-databricks/issues/1099)).
* Added diff suppression for `external_id` in `databricks_user` ([#1097](https://github.com/databrickslabs/terraform-provider-databricks/issues/1097)).
* Added `users`, `service_principals`, and `child_groups` exported properties to `databricks_group` data resource …
=> Release v0.4.9

CHANGELOG.md, common/http.go, docs/data-sources/current_user.md, docs/resources/mlflow_webhook.md, scim/data_current_user.go
it helps to work with some resources, like, `mlflow_webhook` that require URL of the workspace
this fixes #1079
=> Add attribute workspace_url for current_user data source

common/http.go
suppressing multiple alerts in one line. follow up on https://github.com/github/codeql/issues/7992#issuecomment-1040380074
=> add `lgtm [go/clear-text-logging]` for request logging

docs/resources/sql_endpoint.md, sql/resource_sql_endpoint.go
It was impossible to disable Photon if necessary, because it was declared as `omitempty`, so `false` value wasn't sent, and then default `true` was used instead
=> Fixed a doc for SQL Endpoint + allow to disable Photon

docs/resources/permissions.md
Hi team,
This PR adds a small note in the doc to highlight that tokens permissions require to have at least 1 token in the workspace.
Closes https://github.com/databrickslabs/terraform-provider-databricks/issues/1122
=> docs: Updated permissions documentation with a note about Token Usage requirements

exporter/importables.go
Add to path values in importables.go
Fixes #1120
=> ISSUE-1120 Cluster Exporter uses Policy ID as value rather than reference

CHANGELOG.md, README.md, docs/guides/aws-workspace.md, docs/guides/experimental-exporter.md, docs/guides/unity-catalog.md, docs/guides/workspace-management.md, docs/index.md, exporter/command_test.go
* Added `workspace_url` attribute to the `databricks_current_user` data source ([#1107](https://github.com/databrickslabs/terraform-provider-databricks/pull/1107)).
* Fixed issue at `databricks_mount` where new cluster was created for S3 mount even when `cluster_id` was specified ([#1064](https://github.com/databrickslabs/terraform-provider-databricks/issues/1064)).
* Allow to disable auto-termination for Databricks SQL endpoints ([#900](https://github.com/databrickslabs/terraform-provider-databricks/pull/900)).
* Added new `gcp_attributes` to `databricks_cluster` and `databricks_instance_pool` ([#1126](https://github.com/databrickslabs/terraform-provider-databricks/pull/1126)).
* Added exporter functionality for `databricks_ip_access_list` and `databricks_workspace_conf` …
=> Release v0.5.0

CHANGELOG.md, common/reflect_resource.go, common/reflect_resource_test.go, common/resource.go, docs/data-sources/jobs.md, docs/resources/job.md, jobs/data_jobs.go, jobs/data_jobs_test.go, provider/provider.go, qa/testing.go
Retrieves a list of [databricks_job](../resources/job.md) ids, that were created by Terraform or manually, so that special handling could be applied.
-> **Note** Data resource will error in case of jobs with duplicate names.
Granting view [databricks_permissions](../resources/permissions.md) to all [databricks_job](../resources/job.md) within the workspace:
```hcl
data "databricks_jobs" "this" {}
resource "databricks_permissions" "everyone_can_view_all_jobs" {
for_each = data.databricks_jobs.this.ids
job_id   = each.value
access_control {
group_name       = "users"
permission_level = "CAN_VIEW"
}
}
```
Getting ID of specific [databricks_job](../resources/job.md) by name:
```hcl
data "databricks_jobs" "this" {}
output "x" {
value     = "ID of `x` job is …
```
=> Added `databricks_jobs` data resource

CHANGELOG.md, README.md, docs/guides/aws-workspace.md, docs/guides/unity-catalog.md, docs/guides/workspace-management.md, docs/index.md
* Added an extended documentation from provisioning AWS PrivateLink workspace ([#1084](https://github.com/databrickslabs/terraform-provider-databricks/pull/1084)).
* Added `databricks_jobs` data resource to get a map of all job names and their ids ([#1138](https://github.com/databrickslabs/terraform-provider-databricks/pull/1138)).
* Bump google.golang.org/api from 0.68.0 to 0.69.0
=> Release v0.5.1

docs/guides/aws-private-link-workspace.md
Update the guide on provisioning Databricks on AWS with PrivateLink.
The goal is to:
- Mention the remaining front-end endpoint
- Add reference to Private access setting object
=> Update PrivateLink AWS guide

CHANGELOG.md, catalog/resource_metastore_assignment.go, catalog/resource_metastore_assignment_test.go
Fixed `databricks_metastore_assignment` configuration drift by properly deleting metastore assignment and detecting manual changes from Account console. This also means that de-assigned metastore from a workspace would mark it as remotely removed. Manual assignment of different metastore would also trigger resource updates.
Fixes #1146
Closes #1147
=> Fix `databricks_metastore_assignment` config drift

sql/resource_sql_endpoint.go
Previously, `timeout` meta-block was documented, but resulting in error. It was due to `Timeouts: &schema.ResourceTimeout` not added on resource.
Fixes #1142
=> Fix `databricks_sql_endpoint` timeout propagation

CHANGELOG.md, README.md, docs/index.md
* Added `databricks_catalogs`, `databricks_schemas`, and `databricks_tables` data resources ([#1155](https://github.com/databrickslabs/terraform-provider-databricks/pull/1155)).
* Fixed `databricks_metastore_assignment` configuration drift by properly deleting metastore assignment and detecting manual changes from Account console. This also means that de-assigned metastore from a workspace would mark it as remotely removed. Manual assignment of different metastore would also trigger resource updates ([#1146](https://github.com/databrickslabs/terraform-provider-databricks/issues/1146)).
* Fixed `databricks_table` creation in managed mode ([#1151](https://github.com/databrickslabs/terraform-provider-databricks/issues/1151)).
* Fixed `databricks_sql_endpoint` timeout propagation …
=> Release v0.5.2

CHANGELOG.md, exporter/context.go
Failures in [exporter](https://asciinema.org/a/Rv8ZFJQpfrfp6ggWddjtyXaOy) resource listing no longer halt the entire command run.
Fixes #1166
=> Failures in `exporter` listing no longer halt

CHANGELOG.md, scim/resource_service_principal.go, scim/resource_service_principal_test.go
Remove client-side validation in `databricks_service_principal` for `application_id`, that may not always be available in the planning stage.
Fixes #1165
=> Remove validation for SPN resource for `application_id` on Azure

CHANGELOG.md, permissions/resource_permissions.go, permissions/resource_permissions_test.go, sql/resource_sql_endpoint.go
Use correct HTTP verb for `databricks_permissions` on `databricks_sql_endpoint`. Authorized user, assumingly part of `admins` group, is no longer sending `CAN_MANAGE` permission in the HTTP PUT request.
Fixes #1163
=> Use correct verb for permissions on SQL Endpoint

CHANGELOG.md, clusters/clusters_api.go, clusters/clusters_api_test.go
Added special case for handling `Cannot access cluster that was terminated or unpinned more than 30 days ago` error in `databricks_cluster` as an indication of resource removed on the platform side.
Fix #1177
=> Treat auto-purged `databricks_cluster` as removed

docs/resources/catalog.md, docs/resources/schema.md, docs/resources/table.md
Specific pages were missing 's' in the file names.
=> Found broken doc links in UC docs.

docs/guides/unity-catalog-aws.md, docs/guides/unity-catalog-azure.md, docs/resources/external_location.md, docs/resources/metastore.md, docs/resources/metastore_data_access.md, docs/resources/storage_credential.md
This PR adds the following:
- A guide for setting up Unity Catalog on Azure
- Azure examples for `metastore`, `external_location`, `storage_credential` and `metastore_data_access`
Closes #1176
=> Add more Unity Catalog docs on Azure

CHANGELOG.md, catalog/resource_grants.go, catalog/resource_grants_test.go
Read existing permissions from platform before updating them, further improving drift detection. Existing permissions are merged onto diffs as removals.
Fix #1164
=> Impement `replacePermissions` for `databricks_grant`

CHANGELOG.md, scim/resource_service_principal.go, scim/resource_service_principal_test.go
Users will receive a bit more crypting message, but things will work in a more predictable way.
Fix #1193
=> Removed custom client-side validation in `databricks_service_principal`

mlflow/resource_model.go
as described in https://github.com/databrickslabs/terraform-provider-databricks/issues/1195
the terraform provider makes incorrect assumptions about MLFlow API responses for models with versions.
This PR adjusts the schema to what the databricks MLFlow registry actually responds with.
Because this provider doesn't have support for mlflow model versions I can't write tests for this schema change just yet. Adding MLFlow model version support needs some leg work because there seems to be no go sdk for it today.
=> fix read MLFlow model with versions

common/client.go, common/client_test.go, common/gcp.go, common/gcp_test.go
Adding support for GoogleCredentials field in provider configuration. GoogleCredentials can take either a path to .json file, or JSON content itself. This works the same way as [`credentials`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#credentials) field in Google Terraform (Hashicorp).
It does not use impersonation flow. In this case, we only need the credentials of the service account that has permission to create Databricks workspace (i.e. SA2, not SA1).
Tested locally from a fresh environment. gcloud was not configured. It could create workspace and resources (notebook, clusters, ..) correctly.
CC: @nfx
=> Add `GoogleCredentials` config that takes JSON key

docs/guides/unity-catalog-azure.md
Document fix - Correct the [guide for Unity catalog on Azure](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/guides/unity-catalog-azure.md#create-a-unity-catalog-metastore-and-link-it-to-workspaces) to use correct abfss URI for the default ADLS container. 
Correcting to `abfss://<storage_container_name>@<storage_account_name>.dfs.core.windows.net/...`
Closes #1230
=> Fix the guide for Unity catalog on Azure to correct ADLS path

access/resource_ipaccesslist_test.go, common/resource.go, common/resource_test.go, permissions/resource_permissions.go, permissions/resource_permissions_test.go
This guarantees panic recovery and common error messages across all resources
=> Refactor `databricks_permissions` to common.Resource

CHANGELOG.md, README.md, common/version.go, docs/index.md, docs/resources/cluster.md
* Added configuration generators for `databricks_sql_*` resources in _experimental_ [Resource Exporter](https://asciinema.org/a/Rv8ZFJQpfrfp6ggWddjtyXaOy) ([#1199](https://github.com/databrickslabs/terraform-provider-databricks/pull/1199)).
* Added `google_credentials` provider agument that has the same semantics as [`credentials` argument](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#credentials) in official [`google` provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs) ([#1214](https://github.com/databrickslabs/terraform-provider-databricks/pull/1214)).
* Fixed `databricks_grants` on UC external location empty list error ([#1202](https://github.com/databrickslabs/terraform-provider-databricks/issues/1202)).
* …
=> Release v0.5.5

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
this will enable M1 Mac users to develop in dev containers.
Also had to update the version go go to 1.18.1 to make it work.
=> Update devcontainer to support ARM

storage/resource_mount.go
=> Add default timeout of 20m to `databricks_mount`

CHANGELOG.md, README.md, docs/index.md
* Added `databricks_views` data resource, making `databricks_tables` return only managed or external tables in Unity Catalog ([#1274](https://github.com/databrickslabs/terraform-provider-databricks/issues/1274)).
* Added default timeout of 20m to `databricks_mount` ([#1280](https://github.com/databrickslabs/terraform-provider-databricks/pull/1280)).
* Made `common.DataResource` deterministic ([#1279](https://github.com/databrickslabs/terraform-provider-databricks/pull/1279)).
* Fixed exporting text-only widgets ([#1278](https://github.com/databrickslabs/terraform-provider-databricks/pull/1278)).
* Updated devcontainer to support ARM ([#1256](https://github.com/databrickslabs/terraform-provider-databricks/pull/1256)).
* Various documentation fixes …
=> Release v0.5.6

catalog/data_views_test.go, catalog/resource_grants.go, common/resource_test.go, permissions/resource_permissions.go, permissions/resource_permissions_test.go, staticcheck.conf, storage/resource_mount.go
Lint error on Go 1.18:
```
provider/generate_test.go:250:18: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (SA1019)
qa/testing.go:458:17: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (SA1019)
```
=> Ignore new lint error & update formatting

CHANGELOG.md, docs/resources/service_principal.md, scim/resource_service_principal.go, scim/resource_service_principal_test.go
`external_id` may used for unity catalog. `force` is useful for AAD synchronization.
=> Added external_id & force options for service principals

CHANGELOG.md, docs/resources/git_credential.md, docs/resources/repo.md
Also updated Repos doc. Other files were updated as result of `make fmt-docs`
=> Added doc for Git Credentials

jobs/resource_job.go
Apply standard schema modification rules to `num_workers` field in shared job clusters.
Fix #1262
=> Fix `job_cluster`.`num_workers` in `databricks_job`

CHANGELOG.md, README.md, docs/index.md
* Added `external_id` and `force` attributes to `databricks_service_principal` resource ([#1293](https://github.com/databrickslabs/terraform-provider-databricks/pull/1293)).
* Added documentation for `datarbicks_git_credential` resource ([#1295](https://github.com/databrickslabs/terraform-provider-databricks/pull/1295)).
* Added documentation for `git_source` in `databricks_job` ([#1297](https://github.com/databrickslabs/terraform-provider-databricks/pull/1297)).
* Fix `job_cluster`.`num_workers` in `databricks_job` ([#1284](https://github.com/databrickslabs/terraform-provider-databricks/pull/1284)).
* Various documentation improvements ([#1292](https://github.com/databrickslabs/terraform-provider-databricks/pull/1292)), ([#1296](https://github.com/databrickslabs/terraform-provider-databri …
=> Release v0.5.7

docs/resources/mws_customer_managed_keys.md
Current KMS policy is too large allowing all actions by any AWS account. Restrict it to the caller AWS account.
=> Restrict KMS policy to caller AWS account

docs/guides/aws-private-link-workspace.md, docs/guides/aws-workspace.md, docs/resources/mws_private_access_settings.md, docs/resources/mws_vpc_endpoint.md, docs/resources/mws_workspaces.md
=> Clarify optionality of `databricks_mws_workspaces`.`deployment_name` in docs and examples

common/version.go, scim/resource_service_principal.go, scim/resource_service_principal_test.go, scripts/nightly/main.tf
* propagate `application_id` on SCIM PUT call for SPN on Azure
* behavior should not affect AWS
Fix #1319
=> Fix updating `databricks_service_principal` on Azure

mlflow/resource_experiment.go
=> Added `tf:suppress_diff` on `artifact_location` for `databricks_mlflow_experiment`

CHANGELOG.md, README.md, docs/index.md
* Update `aws_iam_policy_document` in `databricks_mws_customer_managed_keys` docs to restrict KMS policy to caller AWS account ([#1309](https://github.com/databrickslabs/terraform-provider-databricks/pull/1309)).
* Added `gcs` destination to `init_scripts` in `databricks_cluster` ([#1308](https://github.com/databrickslabs/terraform-provider-databricks/pull/1308)).
* Clarify optionality of `databricks_mws_workspaces`.`deployment_name` in docs and examples ([#1315](https://github.com/databrickslabs/terraform-provider-databricks/pull/1315)).
* Update `databricks_mws_log_delivery` docs ([#1320](https://github.com/databrickslabs/terraform-provider-databricks/pull/1320)).
* Fix updating `databricks_service_principal` on Azure ([#1322](https://github.com/databrickslabs/terraform-provider-databric …
=> Release v0.5.8

CHANGELOG.md, docs/resources/job.md, jobs/resource_job.go
Jobs API now allows to specify tags that will be used as cluster tags for created jobs clusters
=> Add ability to specify tags for jobs

docs/resources/job.md, jobs/resource_job.go
Adds `alert_on_last_attempt` flag to `email_notifications` in `databricks_job`.
=> Add `alert_on_last_attempt` to `databricks_job`

storage/aws_s3_mount.go, storage/aws_s3_mount_test.go, storage/resource_mount_test.go, storage/s3.go, storage/s3_test.go
=> Re-create purged cluster for `databricks_mount` for AWS S3

CHANGELOG.md, README.md, common/version.go, docs/index.md
* Added warning section for debug mode ([#1325](https://github.com/databrickslabs/terraform-provider-databricks/pull/1325)).
* Added ability to specify tags for `databricks_job` ([#1337](https://github.com/databrickslabs/terraform-provider-databricks/pull/1337)).
* Upgraded AWS provider for AWS guides. Added examples for account-level identities ([#1332](https://github.com/databrickslabs/terraform-provider-databricks/pull/1332)).
* Updated docs to use `application_id` as privilege for `databricks_service_principal` ([#1336](https://github.com/databrickslabs/terraform-provider-databricks/pull/1336)).
* Added `databricks_service_principal_role` resource ([#1340](https://github.com/databrickslabs/terraform-provider-databricks/pull/1340)).
* Fixed itegration testing image …
=> Release v0.5.9

catalog/resource_metastore.go, catalog/resource_metastore_test.go, docs/resources/metastore.md
added the following fields:
Optional non computed fields:
1.  `delta_sharing_enabled`
2. `delta_sharing_recipient_token_lifetime_in_seconds`
Added computed fields:
1. `region`
2. `cloud`
3. `global_metastore_id`
also added docs
=> Added `delta_sharing_*` support to `databricks_metastore`

docs/resources/git_credential.md, repos/resource_git_credential.go
If `personal_access_token` is not provided, it's sourced from the first environment variable of [`GITHUB_TOKEN`](https://registry.terraform.io/providers/integrations/github/latest/docs#oauth--personal-access-token), [`GITLAB_TOKEN`](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs#required), or [`AZDO_PERSONAL_ACCESS_TOKEN`](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs#argument-reference), that has a non-empty value.
Fixes #1352
=> Added `databricks_git_credentials` pat discovery from common environment variables

mws/resource_workspace.go, mws/resource_workspace_test.go
In GCP to use customer-manager VPC, the `network_id` is specified inside the `network` object, not at the top-level workspace object.
This allows the `network_id` to be specified at the correct place.
=> Added `network_id` to `network` block in `databricks_mws_workspaces` for GCP

docs/resources/permissions.md, permissions/resource_permissions.go, permissions/resource_permissions_test.go, pipelines/resource_pipeline.go, pipelines/resource_pipeline_test.go
=> Added `databricks_permissions` for `databricks_pipeline`

CHANGELOG.md, README.md, common/version.go, docs/guides/aws-workspace.md, docs/index.md, docs/resources/group.md, docs/resources/metastore_data_access.md, docs/resources/mws_workspaces.md, docs/resources/service_principal.md, docs/resources/storage_credential.md, docs/resources/user.md
* Added `delta_sharing_*` support to `databricks_metastore` ([#1334](https://github.com/databrickslabs/terraform-provider-databricks/pull/1334)).
* Added `databricks_git_credentials` pat discovery from common environment variables ([#1353](https://github.com/databrickslabs/terraform-provider-databricks/pull/1353)).
* Added `databricks_permissions` for `databricks_pipeline` ([#1361](https://github.com/databrickslabs/terraform-provider-databricks/pull/1361)).
* Added `network_id` to `network` block in `databricks_mws_workspaces` for GCP ([#1360](https://github.com/databrickslabs/terraform-provider-databricks/pull/1360)).
* Added `azure_managed_identity` block to `databricks_storage_credential` and `databricks_metastore_data_access` resources …
=> Release v0.6.0

CHANGELOG.md, README.md, common/version.go, docs/index.md, scripts/upgrade-namespace.py, scripts/versions-lock.hcl
* Add a warning in `databricks_permissions` token usage docs ([#1380](https://github.com/databrickslabs/terraform-provider-databricks/pull/1380)).
* Bump google.golang.org/api from 0.83.0 to 0.84.0
* Bump github.com/stretchr/testify from 1.7.2 to 1.7.3
Test run: Azure
---
Test run: AWS
---
=> Release v0.6.2

common/client.go, common/client_test.go, provider/provider_test.go
I was getting 401s when trying to use the accounts API on GCP, until I realized the host field in the provider configuration had a trailing slash. Removing the trailing slash fixed the issue. To improve the UX here, this PR removes a trailing slash prior to the authentication flow.
=> Sanitize host field prior to auth flow

exporter/importables.go, exporter/importables_test.go
=> explicitly generate resource name for exported notebooks

clusters/clusters_api.go, clusters/resource_cluster.go, pools/resource_instance_pool.go
Added use `tf:force_new` on Docker config only for `databricks_instance_pool`
this fixes #1434
=> Fixed `databricks_job` recreation on changed `docker_image` URL

docs/resources/mount.md
Change the input of `resource_id` to `azurerm_storage_container.this.resource_manager_id`, since the `resource_id` of `databricks_mount` expects an azure id.
`id` returns this format
`https://xxx.blob.core.windows.net/xxx`
while `resource_manager_id` returns this format
`/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/xxx/providers/Microsoft.Storage/storageAccounts/xxxx/blobServices/default/containers/xxx`
which is expected by `resource_id`.
In the current setup, you get the following error:
`Error: parsing failed for https://xxx.blob.core.windows.net/xxx. Invalid container resource Id format`
=> Use correct id for abfs mounts in the docs

mws/mws.go
- Databricks network config API does not support updating resources. https://docs.databricks.com/dev-tools/api/latest/account.html#tag/Network-configurations
- We need to handle it in Terraform itself by performing REPLACE instead of IN-PLACE-UPDATE when `vpc_endpoints` is added/updated in an existing `databricks_mws_networks` resource.
- At the moment we get `Error: doesn't support update` like below
```
databricks_mws_networks.ravi_test_tf_network: Refreshing state... [id=xxxxx/yyyyy]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "databricks_mws_networks" "ravi_test_tf_network" {
id                 = "xxxxx/yyyyy"
+ …
```
=> Added `tf:"force_new"` for `databricks_mws_networks.vpc_endpoints`

CONTRIBUTING.md, docs/index.md, docs/resources/obo_token.md, docs/resources/permissions.md
Fixes https://github.com/databricks/terraform-provider-databricks/issues/1223.
=> Improve docs for `databricks_permissions` and `databricks_obo_token`

CHANGELOG.md, README.md, common/version.go
* Added `metastore` to `databricks_grants` ([#1447](https://github.com/databricks/terraform-provider-databricks/pull/1447)).
* Added update support for `databricks_mws_log_delivery` ([#1439](https://github.com/databricks/terraform-provider-databricks/pull/1439)).
* Fixed name generation for exported `databricks_notebook` ([#1435](https://github.com/databricks/terraform-provider-databricks/pull/1435)).
* Fixed `databricks_job` recreation on changed `docker_image` URL ([#1437](https://github.com/databricks/terraform-provider-databricks/pull/1437)).
* Fixed replace `databricks_mws_networks` on `vpc_endpoints` change ([#1453](https://github.com/databricks/terraform-provider-databricks/pull/1453)).
* Fixed diff suppress in `databricks_external_location` on `skip_validation` …
=> Release v1.0.2

clusters/clusters_api.go, clusters/data_spark_version.go, common/reflect_resource.go, common/reflect_resource_test.go, mlflow/resource_mlflow_webhook.go, mws/resource_mws_workspaces.go, sql/resource_sql_endpoint.go, sql/resource_sql_endpoint_test.go, sql/resource_sql_widget.go
Quite often there are situations when field should be required in the JSON payload (so we send default values, such as `true`, `0`, ...) but it's really optional in the Terraform schema, so we need to explicitly modify the schema with code like:
```
m["enable_photon"].Optional = true
m["enable_photon"].Required = false
```
This patch adds the `optional` keyword that will be checked in the `tf` annotation, so we can avoid explicit schema modification
=> added `tf:optional` annotation to simplify the code

catalog/resource_table.go, catalog/resource_table_test.go, catalog/update.go
Close #1455
There must be a more programmatic way to do this...
=> Fixed `databricks_table` update for `column` block

internal/acceptance/acceptance.go, pipelines/acceptance/pipeline_test.go, pipelines/resource_pipeline.go, scim/acceptance/service_principal_test.go, scripts/README.md, scripts/nightly/awsit.tf
This fixes #1401 to unblock the production workloads.
But it should be investigated why we generated empty structs when using reflection
=> Fixed `databricks_pipeline` incorrect generation of `cluster` blocks

CHANGELOG.md, README.md, common/version.go
* Added `databricks_sql_warehouses` data resource to list all warehouses in a workspace with a name filter ([#1460](https://github.com/databricks/terraform-provider-databricks/pull/1460)).
* Added `databricks_sql_warehouse` data resource to list SQL warehouse attributes based on single id ([#1460](https://github.com/databricks/terraform-provider-databricks/pull/1460)).
* Added `databricks_cluster` data resource to list cluster attributes based on single id ([#1460](https://github.com/databricks/terraform-provider-databricks/pull/1460)).
* Added Azure Managed Identity documentation examples ([#1471](https://github.com/databricks/terraform-provider-databricks/pull/1471)).
* Added more attributes to `databricks_cluster` ([#1459](https://github.com/databricks/terraform-provider-databricks/pull …
=> Release v1.1.0

CHANGELOG.md, README.md, common/version.go
* Added [databricks_mws_permission_assignment](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_permission_assignment) resource ([#1491](https://github.com/databricks/terraform-provider-databricks/pull/1491)).
* Added [databricks_mws_workspaces](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/mws_workspaces) data resource ([#1497](https://github.com/databricks/terraform-provider-databricks/pull/1497)).
* Added exporter for [databricks_pipeline](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline) and [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) ([#1484](https://github.com/databricks/terraform-provider-databricks/ …
=> Release v1.2.0

common/azure_auth_test.go, common/azure_cli_auth_test.go, provider/provider_test.go
In Go 1.19 the Command and LookPath no longer allow results from a PATH search to be found relative to the current directory. https://go.dev/doc/go1.19#os-exec-path
=> Fix Azure CLI tests on Go 1.19

clusters/data_node_type.go, clusters/data_node_type_test.go
Also, fixed tests that use azure-cli - Go stopped to execute programs when PATH has relative paths
This fixes #1533
=> Fix node_type data source by skipping node types that aren't available from cloud provider

CHANGELOG.md, README.md, common/version.go
* Use resize API to scale `databricks_cluster` while it's running ([#1541](https://github.com/databricks/terraform-provider-databricks/pull/1541)).
* Updated to latest Unity Catalog privileges model ([#1556](https://github.com/databricks/terraform-provider-databricks/pull/1556)).
* Added cluster policy support for `databricks_pipeline` ([#1554](https://github.com/databricks/terraform-provider-databricks/pull/1554)).
* Fixed `databricks_node_type` by skipping nodes that aren't available in subscription/region ([#1534](https://github.com/databricks/terraform-provider-databricks/pull/1534)).
* Fixed sending of `active` flag in the `databricks_user` ([#1536](https://github.com/databricks/terraform-provider-databricks/pull/1536)).
* Fixed Azure CLI tests on Go 1.19 …
=> Release v1.2.1

CONTRIBUTING.md
1. Add version for gotestsum and goimports. @latest for now
2. Add note that dev contaners is not officially supported by databricks
=> Add dependency versions and disclaimer for devcontainers

docs/resources/catalog.md, docs/resources/external_location.md, docs/resources/grants.md, docs/resources/metastore.md, docs/resources/metastore_assignment.md, docs/resources/metastore_data_access.md, docs/resources/schema.md, docs/resources/storage_credential.md
Unity Catalog (UC) moved to General Availability last week, so we need to remove Public Preview marker from documentation for UC resources
=> Remove "Public Preview" marker from Unity Catalog resources docs

pipelines/resource_pipeline.go, pipelines/resource_pipeline_test.go
When the `storage` option isn't provided, DLT generates a temp one in the form of
`dbfs:/pipelines/<uuid>`.  But in the sequential apply the drift was detected, and
pipeline was recreated.  Marking it with `computed` or `suppress_diff` doesn't help
because it prevents the pipeline from the detection of change of `storage` from value
to null.
=> Custom suppress diff for `storage` in `databricks_pipeline`

catalog/resource_catalog.go, catalog/resource_catalog_test.go, catalog/resource_schema.go, catalog/resource_schema_test.go, docs/resources/catalog.md, docs/resources/schema.md
Add `force_destroy` flag to UC schema & catalog. This achieves the same functionality as the `purge` flag in the cli, which loop through all child schemas & tables and delete them before delete the parent securable
Closes #1576
=> add `force_destroy` flag to `databricks_schema` & `databricks_catalog`

permissions/resource_permissions.go, permissions/resource_permissions_test.go
extend #1507 to `databricks_cluster`
closes #1139
=> Fixed `databricks_permissions` for calling user to `CAN_MANAGE` on `databricks_cluster`

aws/resource_group_instance_profile.go, aws/resource_group_instance_profile_test.go, docs/resources/group_instance_profile.md, docs/resources/group_role.md, provider/provider.go, scim/resource_group_role.go, scim/resource_group_role_test.go
Major changes:
- Add databricks_group_role resource to allow attaching an AWS Role ARN to an existing group. Implementation for SCIM group role API https://docs.databricks.com/dev-tools/api/latest/scim/scim-groups.html#add-role-to-a-group-by-id
=> Add `databricks_group_role` resource

scim/resource_user.go, scim/resource_user_test.go
Backend API changes error messages, updating code to match
Closes #1549
=> Fix `databricks_user` creation with `force` on account

catalog/acceptance/mws_recipient_test.go, catalog/resource_recipient.go, catalog/resource_recipient_test.go, docs/resources/recipient.md, provider/provider.go
Examples:
```hcl
resource "databricks_recipient" "db2open" {
name = "db2open-recipient"
comment = "made by terraform"
authentication_type = "TOKEN"
sharing_code = "my code "
ip_access_list {
allowed_ip_addresses = [...] // fill out relevant IPv4 addresses (CIDR notation is accepted)
}
}
resource "databricks_recipient" "db2db" {
name = "sri-terraform-test-db2db-recipient"
comment = "made by terraform"
authentication_type = "DATABRICKS"
data_recipient_global_metastore_id = "<cloud>:<region>:<guid>"
}
```
=> Added `databricks_recipient` resource for Delta Sharing

docs/guides/unity-catalog-azure.md, docs/guides/unity-catalog.md
According to [Databricks official documentation](https://docs.databricks.com/data-governance/unity-catalog/compute.html#what-is-cluster-access-mode) using Python with Unity Catalog is already supported for Shared cluster mode.
I added the DBR 11.1 requirement based on [this notebook's requirements](https://docs.databricks.com/_static/notebooks/unity-catalog-quickstart-python.html). Would be good if someone from Databricks can update the official docs with this info as it gave me some headache to figure out why my DBR 10.4 cluster couldn't run Python
=> Docs fix: supported languages in Unity Shared clusters

CHANGELOG.md, README.md, common/version.go
* Added `force_destroy` flag to [databricks_schema](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/schema) & [databricks_catalog](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/catalog) ([#1578](https://github.com/databricks/terraform-provider-databricks/pull/1578)).
* Added [databricks_entitlements](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/entitlements) resource ([#1583](https://github.com/databricks/terraform-provider-databricks/pull/1583)).
* Added [databricks_group_role](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/group_role) resource ([#1575](https://github.com/databricks/terraform-provider-databricks/pull/1575)).
* Added …
=> Release v1.3.0

docs/index.md
Add the parameter to set HTTP timeouts for API responses.
=> Document `http_timeout_seconds` from `common/client.go`

exporter/exporter_test.go, exporter/importables.go, exporter/importables_test.go
This is a separate PR for things found during improving SQL exporting (separate PR):
* Make sure that names are unique for `databricks_group_member` and `databricks_group` resources - handling same names with different casing, and missing `DisplayName` for users
* Change selective export for DLT pipelines - built-in search wasn't case insensitive
* Adding export of SQL warehouses & handling references correctly for SQL & DBT tasks in `databricks_job`
=> Further improvements of exporter

docs/resources/sql_query.md
- add more examples for `parameter` blocks to make it easier for users
- add trouble shooting section to triage questions around `internal server errors`
~~general linting for `/docs` so new contributors should not longer see `hcl` parse errors when running `make fmt-docs`~~
linting moved to https://github.com/databricks/terraform-provider-databricks/pull/1606
=> expand documentation for `databricks_sql_query` resource

sql/acceptance/sql_dashboard_test.go
DBSQL resources are organized in a workspace structure as of recently. As such it is no longer possible to use the same name for different assets. This acceptance test used to use the same name for both the dashboard and the query and started failing. The solution here is to use a different suffix for the different resources.
=> Fix dashboard acceptance test

docs/guides/unity-catalog.md
aws_iam_policy.unity_metastore is referencing
aws_s3_bucket.unity_metastore.arn, which is non-existent. Fix to use aws_s3_bucket.metastore.arn instead. This also matches with the online tutorial.
https://docs.databricks.com/data-governance/unity-catalog/automate.html
=> Fix unity catalog docs to use correct metastore

README.md, docs/data-sources/catalogs.md, docs/data-sources/schemas.md, docs/data-sources/tables.md, docs/data-sources/views.md, docs/guides/aws-private-link-workspace.md, docs/resources/grants.md, docs/resources/group.md, docs/resources/group_member.md, docs/resources/metastore.md, docs/resources/mws_vpc_endpoint.md, docs/resources/service_principal.md, docs/resources/user.md
- remove references to `databricks_table` resource in the docs
- update privatelink workaround guide as auto-accept has been enabled
- link to AAD tokens how-to
- close #1609
=> doc updates for `databricks_table` and `databricks_mws_vpc_endpoint`

CHANGELOG.md, README.md, common/version.go
* Added autoscale `mode` configuration to [databricks_pipeline](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline) resource ([#1600](https://github.com/databricks/terraform-provider-databricks/pull/1600)).
* Fixed `gcp_availability` field in [databricks_insance_pool](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/insance_pool) resource ([#1610](https://github.com/databricks/terraform-provider-databricks/pull/1610)).
* Fixed `secret` field name in [databricks_mlflow_webhook](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mlflow_webhook) resource ([#1625](https://github.com/databricks/terraform-provider-databricks/pull/1625)).
* Further improvements of exporter …
=> Release v1.3.1

docs/resources/sql_visualization.md
- add example configuration for `file()` reference to hopefully avoid users passing incorrect `options` value
- add `known issues` section and link to https://github.com/databricks/terraform-provider-databricks/issues/1615
=> expand documentation for `databricks_sql_visualization` resource

docs/resources/permissions.md, permissions/resource_permissions.go, permissions/resource_permissions_test.go
relates to https://github.com/databricks/terraform-provider-databricks/issues/1615
this PR uses the fix from https://github.com/databricks/terraform-provider-databricks/issues/1504 to append `CAN_MANAGE` perms to the caller explicitly when modifying permissions on `databricks sql queries`
=> prevent stripping of `CAN_MANAGE` permission from caller of `sql_query` resource

CHANGELOG.md, README.md, common/version.go
* Added [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/job) data resource ([#1509](https://github.com/databricks/terraform-provider-databricks/pull/1509)).
* Fixed handling of references in [databricks_permissions](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/permissions) resource exporter ([#1631](https://github.com/databricks/terraform-provider-databricks/pull/1631)).
* Fixed stripping of `CAN_MANAGE` permission from caller of [databricks_sql_query](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_query) resource ([#1644](https://github.com/databricks/terraform-provider-databricks/pull/1644)).
* Fixed provider debug mode …
=> Release 1.4.0

CHANGELOG.md, README.md, catalog/acceptance/external_location_test.go, catalog/acceptance/schema_test.go, common/version.go
* Added `enable_serverless_compute` in the documentation for the [databricks_sql_global_config](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_global_config) ([#1655](https://github.com/databricks/terraform-provider-databricks/pull/1655)).
* Update [databricks_grants](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/grants) with new permissions model ([#1657](https://github.com/databricks/terraform-provider-databricks/pull/1657)).
* Exporter now adds the `force` flag to  users and groups ([#1661](https://github.com/databricks/terraform-provider-databricks/pull/1661)).
* Bump google.golang.org/api from 0.97.0 to 0.98.0 ([#1652](https://github.com/databricks/terraform-provider-databricks/ …
=> Release v1.5.0

CHANGELOG.md, README.md, common/version.go
* Added [databricks_share](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/share) resource, [databricks_shares](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/shares) data source, and [databricks_share](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/share) data source ([#1664](https://github.com/databricks/terraform-provider-databricks/pull/1664)).
* Documentation updates ([#1666](https://github.com/databricks/terraform-provider-databricks/pull/1666), [#1669](https://github.com/databricks/terraform-provider-databricks/pull/1669)).
=> Release v1.6.0

docs/resources/permissions.md, permissions/resource_permissions.go
[DBSQL Workspace Browser](https://docs.databricks.com/sql/user/workspace-browser/index.html) is recently released, which adds `CAN_VIEW` permissions for DBSQL objects
Close #1679
=> Added `CAN_VIEW` permissions for `databricks_sql_dashboard` and `databricks_sql_query`

docs/guides/aws-private-link-workspace.md, docs/resources/mws_private_access_settings.md, docs/resources/mws_vpc_endpoint.md, docs/resources/mws_workspaces.md, mws/resource_mws_workspaces.go, mws/resource_mws_workspaces_test.go
- allow updating `private_access_settings_id` for `databricks_mws_workspaces`
- update docs to reflect AWS PL GA status
=> Allow updating `private_access_settings_id` for `databricks_mws_workspaces`

pipelines/resource_pipeline.go, pipelines/resource_pipeline_test.go
=> Changed `databricks_pipeline` edition default value from `advanced` to `ADVANCED`

CHANGELOG.md, README.md, common/version.go
* Added `CAN_VIEW` permissions for [databricks_sql_dashboard](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_dashboard) and [databricks_sql_query](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_query) ([#1682](https://github.com/databricks/terraform-provider-databricks/pull/1682)).
* Added `webhook_notifications` support to [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) ([#1674](https://github.com/databricks/terraform-provider-databricks/pull/1674)).
* Allow updating `private_access_settings_id` for [databricks_mws_workspaces](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_workspaces) …
=> Release v1.6.1

repos/resource_repo.go, repos/resource_repo_test.go
It was reported by user that error message isn't understandable, so this PR improves this
=> Add validation for path in `databricks_repo`

CHANGELOG.md, README.md, common/version.go
* Added `runtime_engine` to [databricks_cluster](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster) ([#1686](https://github.com/databricks/terraform-provider-databricks/pull/1686)).
* Added validation for `path` in [databricks_repo](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/repo) ([#1702](https://github.com/databricks/terraform-provider-databricks/pull/1702)).
* Added auto-detection of AWS CodeCommit URLs in [databricks_repo](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/repo) ([#1704](https://github.com/databricks/terraform-provider-databricks/pull/1704)).
* Restricting access to S3 bucket by custom tag on the IAM identity according to security email in …
=> Release v1.6.2

access/resource_sql_permissions.go
Fixes #1729
We have an issue using the sql_permissions with database names that require escaping. Putting backticks in the database name seems to get filtered out somewhere in Terraform.
This change explicitly escapes every database name to avoid that issue, similar to the escaping we do for Tables and Views.
I would like to add a test case for this but I'll need some pointers on how the CommandMock works.
=> Escape database name in sql_permissions resource

CHANGELOG.md, README.md, common/version.go
* Added `warehouse_type` parameter to [databricks_sql_endpoint](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_endpoint) to support PRO SKU ([#1728](https://github.com/databricks/terraform-provider-databricks/pull/1728)).
* Correct exporting of the computed attributes for [databricks_cluster](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster) ([#1711](https://github.com/databricks/terraform-provider-databricks/pull/1711)).
* Escape database name in [databricks_sql_permissions](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_permissions) resource ([#1730](https://github.com/databricks/terraform-provider-databricks/pull/1730)).
=> Release v1.6.3

docs/resources/sql_endpoint.md, sql/resource_sql_endpoint.go, sql/resource_sql_endpoint_test.go
Rely on the platform to specify the default `warehouse_type`
=> Revert `PRO` as default `warehouse_type` in `databricks_sql_endpoint`

CHANGELOG.md, README.md, common/version.go
* Reverted `PRO` as default `warehouse_type` in [databricks_sql_endpoint](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_endpoint) ([#1741](https://github.com/databricks/terraform-provider-databricks/pull/1741)).
* Moved testing of clusters, instance pools, and SQL Warehouses to internally configured test environment variables ([#1739](https://github.com/databricks/terraform-provider-databricks/pull/1739)).
* Bump google.golang.org/api from 0.101.0 to 0.102.0 ([#1736](https://github.com/databricks/terraform-provider-databricks/pull/1736)).
=> Release v1.6.4

exporter/exporter_test.go, exporter/importables.go, exporter/importables_test.go, exporter/util.go, jobs/data_job.go, jobs/data_job_test.go, jobs/data_jobs.go, jobs/data_jobs_test.go, jobs/resource_job.go, jobs/resource_job_test.go
This patch switches to 2.1 version of Jobs API for List operation so we can more efficiently handle workspaces with huge number of jobs (> 3000).  It also uses new `name` parameter to search jobs by name in the `databricks_job` data source.
=> Use Jobs API 2.1 with name filter for `databricks_job` data source

exporter/context.go, exporter/importables.go
Fix for issue #1720 
Problem with old code shown below is that, it checks **only one** class of resources before quitting. The fixed code checks all references from Depends:
```
if traversal != nil {
break
}
```
=> Fixed `member_id` reference of nested groups and `databricks_group_member` for exporter

CHANGELOG.md, README.md, common/version.go
* Added `query_plan` attribute to `databricks_sql_visualization` ([#1752](https://github.com/databricks/terraform-provider-databricks/pull/1752)).
* Fixed `member_id` reference of nested groups and [databricks_group_member](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/group_member) for exporter ([#1723](https://github.com/databricks/terraform-provider-databricks/pull/1723)).
* Fixed auto-purged cluster behaviour for [databricks_library](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/library) ([#1745](https://github.com/databricks/terraform-provider-databricks/pull/1745)).
* Use Jobs API 2.1 with name filter for [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/j …
=> Release v1.6.5

docs/resources/sql_global_config.md
It got me wondering if `Serverlell` is an actual word at one point.
=> small syntax fix for enable_serverless_compute description in sql_global_config resource

docs/resources/grants.md
In the rest of Databricks documentation, service principals are viewed as distinct entities from users. For example in the [databricks_permission resource](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/permissions#access-control-argument). It is best to clarify that this possible here and to clarify how to reference it.
=> Clarify that service principals are possible

scim/resource_service_principal.go, scim/resource_service_principal_test.go
Closes #1779
In the [doc](https://docs.databricks.com/dev-tools/api/latest/scim/scim-sp.html#update-service-principal-by-id-patch)
> Update a service principal resource with operations on specific attributes, except for `displayName`, `applicationId`, and `id`, which are immutable.
=> Force replace when changing display_name of `databricks_service_principal`

docs/resources/service_principal.md, docs/resources/user.md, scim/resource_service_principal.go, scim/resource_service_principal_test.go, scim/resource_user.go, scim/resource_user_test.go
They will be used in Exporter to simplify references in paths, etc.
=> Added `home` & `repos` attributes to `databricks_user` and `databricks_service_principal`

exporter/exporter_test.go, exporter/importables.go, sql/resource_sql_global_config.go
=> Exporter for `databricks_sql_global_config` resource

jobs/data_job.go, jobs/data_job_test.go
This happens because we did not set expandTasks to the API when listing the jobs. For search by id, list without expandTasks and then re-search when job name is found 
This closes #1797
=> Fix missing attributes from `databricks_job` data source

exporter/context.go
Use `set -e` to fail on the first invalid resource - it will help detecting incorrect resources in the big imports
=> Exporter: fail fast in `import.sh` when can't import resource

docs/guides/experimental-exporter.md, docs/resources/service_principal.md, exporter/exporter_test.go, exporter/importables.go, exporter/importables_test.go, exporter/util.go, exporter/util_test.go, scim/data_service_principal.go, scim/data_service_principals.go, scim/resource_service_principal.go
plus small improvements like references for `single_user_name`, etc.
=> Added exporting of `databricks_service_principal` resource

exporter/importables.go, exporter/importables_test.go, exporter/util.go, go.mod, go.sum
Also, emit init scripts defined in the cluster policies
This fixes #1785
=> Export predefined `databricks_cluster_policy` as data sources

exporter/importables.go, exporter/importables_test.go
Fix for issue #1654
TF exporter creatingdatabricks_group resource, not data block for admins and users
=> Export `admin` and `users` groups as `databricks_group` data, not resource

.devcontainer/Dockerfile
According to the [official documentation](https://go.dev/doc/go-get-install-deprecation), `go get` has been deprecated for installing executables since v1.17. I see that the Go version has (relatively) recently been bumped to v1.18, but this causes the container building process to fail (since it looks for a `go.mod` that cannot possibly be there).
I also see that the other imports have successfully been fixed in [40c1d53c](https://github.com/databricks/terraform-provider-databricks/commit/40c1d53c3e3ebc9f3b48c7f423fe1f90e1fd7233), but then the TF formatter was added by using the old notation. Fortunately, the fix is relatively simple: changing `get` with `install` makes the container buildable once again without any issue.
I know it's a small one, and container support is not the top …
=> Replacing `go get` with `go install` in .devcontainer/DockerFile

clusters/clusters_api.go, docs/resources/cluster.md
This allows to specify path to init script as `abfss://container@storage.dfs.core.windows.net/path`
this fixes #1786
=> Allow init scripts on ADLS in `databricks_cluster` and related resources

docs/resources/job.md, jobs/resource_job.go
Document `webhook_notifications` field. Webhooks are configured in TF as follows:
```
webhook_notifications {
on_start {
id = "id3"
}
on_start {
id = "id1"
}
on_start {
id = "id2"
}
on_success {
id = "id2"
}
on_failure {
id = "id3"
}
}
```
OpenAPI spec added [here](https://go/pr/236233).
=> Document `webhook_notifications` for `databricks_job` resource

docs/resources/sql_global_config.md
Altered parameter value for the setting `spark.hadoop.fs.azure.account.oauth2.client.id` from `tenant_id` to `application_id` (the client_id should be the `Application (client) ID` for the service principal application on AzureAD and not the tenant_id
=> Altering parameter on Azure `data_access_config`

CHANGELOG.md, README.md, common/version.go
* Added support for Unity Catalog on GCP through `gcp_service_account_key` ([#1836](https://github.com/databricks/terraform-provider-databricks/pull/1836)).
* Added support for Jupyter (`.ipynb`) files in [databricks_notebook](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/databricks_notebook) resource ([#1801](https://github.com/databricks/terraform-provider-databricks/pull/1801)).
* Added [databricks_cluster_policy](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/cluster_policy) data source ([#1792](https://github.com/databricks/terraform-provider-databricks/pull/1792)).
* Added `catalog` parameter to `dbt_task` in [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resource …
=> Release v1.7.0

clusters/data_node_type.go, clusters/data_node_type_test.go, docs/data-sources/node_type.md
Due not completely correct sorting, instead of real smallest node, other node type was returned as smallest. For example, on Azure it was `L8` series.
Also added the `local_disk_min_size` selector to allow to select nodes with local disks not smaller than specified.
=> Use NVMe disk size for selection in the `databricks_node_type` data source

docs/data-sources/service_principal.md
replace the incorrect 'id' attribute with the correct 'sp_id' attribute in service principal data source docs example
=> replace the incorrect 'id' attribute with the correct 'sp_id' attribute

docs/resources/secret.md, secrets/resource_secret.go, secrets/resource_secret_test.go
The `config_reference` attribute exposes string value in form of `{{secrets/scope/key}}` for easier reference from Spark configuration or environment variables.
It will be also used later in exporter for handling dependencies
=> Add `config_reference` attribute to `databricks_secret` for easier reference from Spark configuration

exporter/exporter_test.go, exporter/importables.go, exporter/test-data/get-dlt-pipeline.json, exporter/util.go
Exporter now detects Spark conf and environment variables values that are references to secrets (the `{{secrets/scope/secret}}` syntax) and emit a secret scope referenced there.
P.S. It doesn't put explicit reference into the value, but it could be added after #1890 is merged (it will require addition of `substring` match type, but it's doable).
=> Exporter: emit secret scopes from Spark Conf and Env Vars

exporter/importables.go, exporter/util.go
- Use 1-based numeration in `databricks_secret_scope` listing instead of 0-based that is confusing for users
- Improve logging when listing `databricks_job` resources
=> Exporter: logging improvements

docs/guides/experimental-exporter.md, exporter/command.go, exporter/context.go, exporter/importables.go
New flag allows to export all users and service principals even if they are only part of the `users` group
This fixes #1827
=> Exporter: add command-line flag to export all users and service principals

common/reflect_resource_test.go, common/resource.go, docs/data-sources/service_principal.md, scim/data_service_principal.go, scim/data_service_principal_test.go
The `DataResource` function now checks if the provided schema has the field with name `id` and set its value as resource ID.  This will allow to have uniform references between normal resources and data sources. If this change is ok, then I'll proceed with other data sources. (See https://github.com/hashicorp/terraform-plugin-sdk/issues/607 for reference about definition of `id` attribute).
This change was already applied to the `databricks_service_principal` data source where old attribute (`sp_id`) was left for backward compatibility.
=> Allow to override resource ID for specific data source

catalog/resource_grants.go, catalog/resource_grants_test.go, docs/resources/grants.md
Provider now warns user when they use spaces instead of underscores for grants.
Closes #1820
=> Improve `databricks_grants` error messages

exporter/context.go, exporter/context_test.go, exporter/exporter_test.go, exporter/importables.go, exporter/model.go, exporter/test-data/get-dlt-pipeline.json, exporter/util.go, exporter/util_test.go
There are cases when reference isn't a full match of a given value but a prefix of it. For example, user's notebook has a path of `/Users/user@domain/notebook`.  To make it working correctly we need to emit user or service principal, and then make a correct reference with dependency on emitted user or notebook, like, `${databricks_user.user_domain.home}/notebook`.
This PR adds a new field to dependency specification: `MatchType` that may have following values:
- `prefix` - value of attribute of resource is a prefix of a given attribute
- `exact` (or empty string) - must have exact matching (previous behaviour)
this fixes #1777
=> Exporter: generate references that are matching only to a prefix

clusters/data_cluster.go, clusters/data_cluster_test.go, docs/data-sources/cluster.md, docs/data-sources/job.md, jobs/data_job.go, jobs/data_job_test.go
Also expose `id` for `databricks_cluster` & `databricks_job` data sources so it's easier to use results.
This is a follow up for #1885
=> add search by name for `databricks_cluster` data source

exporter/context.go, exporter/importables.go, exporter/importables_test.go, exporter/util.go
The `Add` function is called only from the `Emit` so it's safe to remove the check if resource was already imported or not.
this fixes #1838
=> Exporter: fix issue with exporting of resources with simple name

CHANGELOG.md, README.md, common/version.go
* Added support for GCP (Public Preview) with state upgraders for [databricks_mws_workspaces](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_workspaces) ([#1871](https://github.com/databricks/terraform-provider-databricks/pull/1871), [#1886](https://github.com/databricks/terraform-provider-databricks/pull/1886), [#1748](https://github.com/databricks/terraform-provider-databricks/pull/1748), [#1879](https://github.com/databricks/terraform-provider-databricks/pull/1879)).
* Added documentation for [databricks_permission_assignment](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/permission_assignment) ([#1880](https://github.com/databricks/terraform-provider-databricks/pull/1880)).
* Added `azure_attributes` to …
=> Release v1.8.0

docs/data-sources/cluster_policy.md, docs/data-sources/instance_pool.md, docs/guides/gcp-workspace.md, docs/resources/mws_workspaces.md, docs/resources/secret.md
* Added example of using `config_reference` of `databricks_secret` resource
* Reformatted docs with `make fmt-docs`
=> Documentation improvements

access/resource_sql_permissions.go, access/resource_sql_permissions_test.go
…ed code to correctly assign permissions without causing infinite loop
=> Fix bug in `privilege_assignment` of `databricks_sql_permissions`

CHANGELOG.md, README.md, common/version.go
* Added [databricks_mws_credentials](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/mws_credentials) data source ([#1909](https://github.com/databricks/terraform-provider-databricks/pull/1909)).
* Fixed incorrect diff for `num_clusters` and `min_num_clusters` for stopped [databricks_sql_endpoint](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_endpoint) ([#1927](https://github.com/databricks/terraform-provider-databricks/pull/1927)).
* Fixed `privilege_assignment` in [databricks_sql_permissions](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_permissions) ([#1872](https://github.com/databricks/terraform-provider-databricks/pull/1872)).
* Documentation improvements …
=> Release v1.9.0

pools/resource_instance_pool.go
This annotation means the field shows up in plans for Azure and GCP, where it doesn't make sense.
It was added in #1463. Not clear if it was intentional at that time.
=> Remove "computed" annotation for "aws_attributes"

clusters/clusters_api.go, docs/resources/cluster.md
=> Add support for `cluster_mount_info` in `databricks_cluster`

aws/resource_group_instance_profile.go, aws/resource_instance_profile.go, aws/resource_instance_profile_test.go, aws/resource_user_instance_profile.go, docs/resources/instance_profile.md
This PR adds support to manage an instance profile's IAM role ARN when it does not match the instance profile name. This feature is needed when managing instance profiles for use with Databricks SQL serverless.
See [Databricks REST API documentation for instance profiles](https://docs.databricks.com/dev-tools/api/latest/instance-profiles.html#add)
Fixes #1911 
Fixes #1710
=> Added support for `iam_role_arn` in `databricks_instance_profile`

CHANGELOG.md, common/version.go
* Added `max_clusters_per_user` to [databricks_cluster_policy](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster_policy) resource ([#1955](https://github.com/databricks/terraform-provider-databricks/pull/1955)).
* Added support for `cluster_mount_infos` in [databricks_cluster](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster) ([#1945](https://github.com/databricks/terraform-provider-databricks/pull/1945)).
* Added `parent` attribute to [databricks_sql_query](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_query) and [databricks_sql_dashboard](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_dashboard) …
=> Release v1.9.1

docs/resources/job.md
I found this advanced Terraform syntax a bit confusion, so I think it would be nice to give an example would it easier. 
We could alternatively also add it as a task in the main example? Is it possible to combine it with other types? I've only tried it as a stand separate thing.
Another option would be to include how to add in an job it in the [databricks_sql_query docs](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_query).
https://github.com/databricks/terraform-provider-databricks/issues/1951
=> Added SQL example for `databricks_job` documentation

scripts/awsmt-integration/data-security.tf
The `acl` and `versioning` parameters are deprecated on the `aws_s3_bucket` resource. The docs recommend using `aws_s3_bucket_acl` and `aws_s3_bucket_versioning` resources instead. From what I can gather, this helps with drift detection in Terraform.
=> Remove deprecated params from bucket

CHANGELOG.md, common/version.go
* Added `file` library type to [databricks_pipeline](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline) resource ([#1975](https://github.com/databricks/terraform-provider-databricks/pull/1975)).
* Added new node type selector to [databricks_node_type](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/node_type) data source ([#1957](https://github.com/databricks/terraform-provider-databricks/pull/1957)).
* Removed check for creation of Azure Key Vault-based [databricks_secret_scope](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/secret_scope) using Service Principals ([#1965](https://github.com/databricks/terraform-provider-databricks/pull/1965)).
* Reworked Graviton …
=> Release v1.9.2

docs/resources/user.md
=> Doc: fixed provider reference in example usage

catalog/acceptance/share_test.go, catalog/data_share_test.go, catalog/resource_share.go, catalog/resource_share_test.go, docs/resources/share.md
Closes #2004
Also fix diff detection, closes #2003
=> Add `start_version` and `cdf_enabled` support for `databricks_share`

docs/guides/gcp-workspace.md
Without these 3 permissions I couldn't create a MWS network
=> Update GCP guide with new permissions required to deploy `databricks_mws_networks`

docs/data-sources/job.md, docs/resources/job.md
Addresses #1986
- As explained in the issue, in the output of the data source `databricks_job`, the attribute containing the job ID is `job_id` and not `id`. This PR fixes that.
- Additionally, I saw that in the Databricks resource `databricks_job`, in the list of "additionally" exported values, only `url` is listed. Since the job ID is the most important exported attribute (it is needed for any permission that you may want to apply later) I also added `id` to the list of exported attributes. 
**Note:** There is an inconsistency in the job ID naming, since in the data source response the ID is under the attribute `job_id` and in the resource it is under `id`. This is quite confusing.
=> [DOC] Fix job datasource docs

CHANGELOG.md, common/version.go, docs/index.md, provider/provider.go
* Migrated client and configuration layer to [`github.com/databricks/databricks-sdk-go`](http://github.com/databricks/databricks-sdk-go) ([#1848](https://github.com/databricks/terraform-provider-databricks/pull/1848)).
* Added new attribute to [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) resource ([#1988](https://github.com/databricks/terraform-provider-databricks/pull/1988)).
* Added `history_data_sharing_status`, `partition` and `status` fields to [databricks_share](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/share) ([#2013](https://github.com/databricks/terraform-provider-databricks/pull/2013)).
* Added `start_version` and `cdf_enabled` support for …
=> Release v1.10.0

docs/guides/gcp-workspace.md, internal/acceptance/mws_customer_managed_keys_test.go, mws/resource_mws_customer_managed_keys.go
Tested acceptance test by running `bash-3.2$ scripts/run.sh gcp-accounts 'TestGcpaAccCustomerManagedKeysForStorage' --debug --tee` -
```
3 tf_rpc=ApplyResourceChange
2023-02-16T17:10:32.183-0800 [TRACE] sdk.helper_schema: Calling downstream: tf_resource_type=databricks_mws_customer_managed_keys tf_req_id=d4d9dd50-0291-96e6-a6b4-32e2ae934e85 tf_provider_addr=registry.terraform.io/hashicorp/databricks tf_rpc=ApplyResourceChange
2023/02/16 17:10:32 [INFO] Configured google-accounts auth: host=https://accounts.staging.gcp.databricks.com, account_id=9fcbb245-7c44-4522-9870-e38324104cf8, google_service_account=rohansa2-staging@databricks-staging-customer.iam.gserviceaccount.com
2023/02/16 17:10:33 [DEBUG] POST /api/2.0/accounts/9fcbb245-7c44-4522-9870-e38324104cf8/customer-managed-keys { …
```
=> 1. Add support for gcp cmk

catalog/data_catalogs.go, catalog/data_catalogs_test.go, catalog/resource_catalog.go, common/resource.go
This PR also introduces `common.WorkspaceData` to reduce code boilerplate. The minimal data resource is now to be defined as:
```go
return common.WorkspaceData(func(ctx context.Context, data *struct {
// now even possible with inline structs!
Ids []string `json:"ids,omitempty" tf:"computed,slice_set"`
}, w *databricks.WorkspaceClient) error {
catalogs, err := w.Catalogs.ListAll(ctx)
if err != nil {
return err
}
for _, v := range catalogs {
data.Ids = append(data.Ids, v.Name)
}
return nil
})
```
=> Migrate `databricks_catalogs` data to Go SDK

.goreleaser.yml, CHANGELOG.md, common/version.go
* Migrated [databricks_catalogs](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/catalogs) data to Go SDK ([#2038](https://github.com/databricks/terraform-provider-databricks/pull/2038)).
* Migrated [databricks_current_user](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/current_user) data source to Go SDK ([#2037](https://github.com/databricks/terraform-provider-databricks/pull/2037)).
* Migrated [databricks_workspace_conf](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/workspace_conf) to Go SDK ([#2035](https://github.com/databricks/terraform-provider-databricks/pull/2035)).
* Added new feature ([#2015](https://github.com/databricks/terraform-provider-databricks/pull/2015)) …
=> Release v1.10.1

permissions/resource_permissions.go, permissions/resource_permissions_test.go
This does not fix the issue, but adds more debug information to the error output.
=> Improve error messages for `databricks_permissions`

catalog/resource_grants.go, catalog/resource_table.go, common/resource.go, common/resource_test.go, jobs/resource_job.go, mws/resource_mws_workspaces.go, permissions/resource_permissions.go, permissions/resource_permissions_test.go
This PR removes SDK client as the argument to CustomizeDiff callback on the level of `common.Resource` framework. All customize diff validation must be hermetic and take only `schema.ResourceDiff` as the input. Any validation, that may require calls to the platform must be done in scope of Create or Update callbacks.
Fix #2052
=> Deterministic diff for `databricks_permissions`

CHANGELOG.md, common/version.go
* Databricks on Azure with PrivateLink - Simplified deployment ([#1977](https://github.com/databricks/terraform-provider-databricks/pull/1977)).
* Deterministic diff for [databricks_permissions](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/permissions) ([#2059](https://github.com/databricks/terraform-provider-databricks/pull/2059)).
=> Release v1.11.1

catalog/resource_metastore_data_access.go, catalog/resource_metastore_data_access_test.go, catalog/resource_storage_credential.go, catalog/resource_storage_credential_test.go, docs/guides/unity-catalog-gcp.md, docs/resources/external_location.md, docs/resources/metastore_data_access.md, docs/resources/storage_credential.md
- Add support for `databricks_gcp_service_account` attribute for `databricks_storage_credential` and `databricks_metastore_data_access` resources
- Update docs for UC resources to highlight GCP-equivalent syntax
- Adds a user guide for Unity Catalog on GCP
=> Add Unity Catalog on GCP support

docs/guides/gcp-private-service-connect-workspace.md
[PLAT-76309]Add doc guide to create a gcp private service connect workspace.
[PLAT-76309]: https://databricks.atlassian.net/browse/PLAT-76309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PLAT-76309]Add doc guide to create a gcp private service connect workspace.

CHANGELOG.md, common/version.go
* Added [databricks_sql_alert](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_alert) resource ([#2047](https://github.com/databricks/terraform-provider-databricks/pull/2047)).
* Added experimental GCP support for more resources ([#2088](https://github.com/databricks/terraform-provider-databricks/pull/2088), [#2091](https://github.com/databricks/terraform-provider-databricks/pull/2091), [#2090](https://github.com/databricks/terraform-provider-databricks/pull/2090), [#2089](https://github.com/databricks/terraform-provider-databricks/pull/2089), [#2080](https://github.com/databricks/terraform-provider-databricks/pull/2080)).
* Added suppress diff to `default_data_access_config_id` in [databricks_metastore](https://registry.terraform.io/providers/databr …
=> Release v1.13.0

docs/resources/ip_access_list.md
The previous description is a copy paste error? It doesn't seem to describe the same thing?
> ip_addresses` -  This is a field to allow the group to have instance pool create privileges.
New description was taken from the [official documentation](https://docs.databricks.com/security/network/ip-access-list.html#add-an-ip-access-list). 
Someone informed me that it otherwise depends on how the whitelist is implemented if you should specify "1.1.1.1/32" or "1.1.1.1". For example that some implementations will use the default mask if not implemented or that certain AWS won't be able to handle them without CIDR.
=> Clarify how single IP addresses should be specified

sql/resource_sql_endpoint.go, sql/resource_sql_global_config.go
=> Deprecate `enable_serverless_compute` on `databricks_sql_global_config` resource

docs/resources/job.md, jobs/resource_job.go
Add support for using `spark_python_task` with a `git_source` by adding the `source` parameter, same as `notebook_task`
Closes #2138
=> Added `source` parameter for `spark_python_task` in `databricks_job`

common/client.go, exporter/context.go, internal/acceptance/secret_scope_test.go, permissions/resource_permissions.go
* cache scim/me API
* manual
*  existing acceptance tests
* gcp-prod
* aws-prod
* azure-prod
* aws-prod-ucws
* aws-prod-ucacct
* azure-prod-acct
* gcp-prod-acct
=> Add caching of scim/me API to `databricks_current_user` data source and `databricks_permissions` resource.

permissions/resource_permissions.go, permissions/resource_permissions_test.go
- Automatically add `CAN_MANAGE` permission for calling user to `databricks_sql_endpoint` closes #2165
- Refactor some API calls in `databricks_permissions` to use Go SDK
=> Automatically add `CAN_MANAGE` permission on `databricks_sql_endpoint` for calling user

CHANGELOG.md, common/version.go
* Added caching of SCIM Me API call to [databricks_current_user](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/current_user) data source and [databricks_permissions](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/permissions) resource. ([#2170](https://github.com/databricks/terraform-provider-databricks/pull/2170)).
* Added example for automatically rotating a token ([#2135](https://github.com/databricks/terraform-provider-databricks/pull/2135)).
* Added `run_if` condition in [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) resource ([#2125](https://github.com/databricks/terraform-provider-databricks/pull/2125)).
* Added File Arrival trigger to …
=> Release v1.14.0

internal/acceptance/data_service_principals_test.go, scim/data_service_principals.go, scim/data_service_principals_test.go
- Avoid passing `displayName` filter to SCIM API when no filter string is provided.
- Add acceptance test
Closes #2178
=> fix `databricks_service_principals` data source issue with empty filter

CHANGELOG.md, common/version.go
* Allow rotating `token` block in [databricks_mws_workspaces](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_workspaces) resource by only changing `comment` field ([#2114](https://github.com/databricks/terraform-provider-databricks/pull/2114)).
* Exclude roles in SCIM API list calls to reduce load on Databricks SCIM service ([#2181](https://github.com/databricks/terraform-provider-databricks/pull/2181)).
* Fixed [databricks_service_principals](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/service_principals) data source issue with empty filter ([#2185](https://github.com/databricks/terraform-provider-databricks/pull/2185)).
* Update Go SDK to v0.6.0 …
=> Release v1.14.1

docs/resources/grants.md
This is to address #2176. The `CREATE_VIEW` grant is no longer needed, and is superseded by `CREATE_TABLE`.
=> Remove deprecated CREATE_VIEW grant

catalog/resource_share.go, catalog/resource_share_test.go
Improve diff detection by suppressing diff for `shared_as` field. Close #2167
=> Fix diff detection for `databricks_share` resource

CHANGELOG.md, common/version.go
* Explicitly include SCIM attributes for [databricks_group](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/group), [databricks_user](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/user), [databricks_user_role](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/user_role), [databricks_group_role](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/group_role), [databricks_group_member](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/group_member), [databricks_group_instance_profile](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/group_instance_profile), …
=> Release v1.14.2

workspace/resource_directory.go, workspace/resource_directory_test.go
Right now if we have directory declared as follows:
```hcl
resource "databricks_directory" "test" {
path = "/Users/user@domain/TF_DIR_WITH_SLASH/"
}
```
on update it's trying to recreate resource because REST API returns normalized path, without ending `/`, and this leads to following:
```
-/+ resource "databricks_directory" "test" {
~ id               = "/Users/user@domain/TF_DIR_WITH_SLASH/" -> (known after apply)
~ object_id        = 696671922817959 -> (known after apply)
~ path             = "/Users/user@domain/TF_DIR_WITH_SLASH" -> "/Users/user@domain/TF_DIR_WITH_SLASH/" # forces replacement
}
```
this patch fixes this behavior
=> Add suppress diff for `path` argument of `databricks_directory` resource when it ends with `/`

exporter/util.go, scim/data_group_test.go, scim/groups.go, scim/resource_group_test.go
We had a regression as specified in https://github.com/databricks/terraform-provider-databricks/issues/2193
The fix is to revert back to using the list groups API since that is not gated to admins
Tested using existing unit tests and manually with a non admin account with the following hcl
```
terraform {
required_providers {
databricks = {
source = "databricks/databricks"
}
}
}
profile = "aws-prod-nonadmin"
}
data databricks_group "this" {
display_name = "users"
}
```
=> Fixed regression in `databricks_group` data not to require workspace admin privileges

common/resource.go, common/resource_test.go, pipelines/resource_pipeline.go, repos/resource_repo.go
Added suppress diff for `edition` attribute for case when change is just case sensitivity, i.e., `CORE` -> `core`, etc.
Moved corresponding suppress diff function into the `common` package because it also was used in `databricks_repo`.
=> Suppress diff for `edition` attribute in `databricks_pipeline`

common/reflect_resource.go, common/reflect_resource_test.go, docs/resources/pipeline.md, pipelines/resource_pipeline.go
Add support for email notifications in `databricks_pipeline` resource
Also added support for `min_items` terraform annotation to simplify specificaiton of non-empty lists.
=> Add support for notifications in `databricks_pipeline` resource

CHANGELOG.md, common/version.go
* Add exporter support for [databricks_sql_alert](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_alert) ([#2207](https://github.com/databricks/terraform-provider-databricks/pull/2207)).
* Add support for notifications in [databricks_pipeline](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline) resource ([#2218](https://github.com/databricks/terraform-provider-databricks/pull/2218)).
* Add suppress diff for `path` argument of [databricks_directory](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/directory) resource when it ends with `/` ([#2204](https://github.com/databricks/terraform-provider-databricks/pull/2204)).
* Exporter: don't export `storage` when …
=> Release v1.14.3

docs/resources/job.md
=> Add example for for job tags

permissions/resource_permissions.go, permissions/resource_permissions_test.go
Jobs API returns 400 "Bad request" for non-existent pipelines instead of 404 "Not Found", and this breaks recreation of permissions if job was manually deleted:
```
2023-04-18T10:02:07.317+0200 [DEBUG] provider.terraform-provider-databricks: GET /api/2.1/jobs/get?job_id=998654886170278
< HTTP/2.0 400 Bad Request
< {
<   "error_code": "INVALID_PARAMETER_VALUE",
<   "message": "Job 998654886170278 does not exist."
< }: timestamp=2023-04-18T10:02:07.317+0200
```
This fix explicitly ignores such errors.  This fixes #2217
=> Ignore delete permission error for manually deleted jobs (issue #2217)

docs/resources/secret_scope.md, internal/acceptance/secret_scope_test.go
=> Remove note about Azure KeyVault-based secret scopes and service principals

clusters/clusters_api.go, docs/resources/cluster.md
This PR adds support for using workspace files as init scripts:
```hcl
init_scripts {
workspace {
destination = "/Users/user@domain/install-elk.sh"
}
}
```
=> Added support for running `databricks_cluster` init scripts from workspace files

docs/resources/cluster_policy.md, exporter/exporter_test.go, policies/data_cluster_policy_test.go, policies/resource_cluster_policy.go, policies/resource_cluster_policy_test.go
Migrate the cluster policy service to go SDK.
Closes #2247
=> Migrate `databricks_cluster_policy` to Go SDK

docs/guides/troubleshooting.md
we don't need this note anymore because this platform limitation is resolved
=> Remove a note about Azure KeyVault and Service Principal from `databricks_secret_scope` troubleshooting guide

docs/data-sources/node_type.md
Document it after it became publicly available
=> Document `fleet` selector in the `databricks_node_type` data source

catalog/resource_grants.go, docs/resources/grants.md
Add missing permissions to the mapping for `databricks_grant` resource, namely some new metastore permissions
=> Added missing permissions to `databricks_grants` resource

docs/resources/notebook.md, docs/resources/permissions.md, docs/resources/workspace_file.md, internal/acceptance/workspace_file_test.go, permissions/resource_permissions.go, permissions/resource_permissions_test.go, provider/provider.go, workspace/data_notebook_paths.go, workspace/resource_notebook.go, workspace/resource_workspace_file.go, workspace/resource_workspace_file_test.go
With recent release of the workspace file support it's now possible to store arbitrary files in the workspace, not only notebooks.  It's also recommended way to store init scripts to avoid security problems associated with storing init scripts on DBFS.
I deliberately didn't use the Go SDK as all code was already available. Migration to Go SDK will follow after discussions on the change required for supporting list command (see #2258)
This fixes #2206
=> Add `databricks_workspace_file` resource

docs/resources/job.md, jobs/resource_job.go, jobs/resource_job_test.go
This fixes #2270
The new configuration block allows to control handling of notifications for skipped & canceled runs for both email & webhook notifications.
=> Add `notification_settings` block to `databricks_job` resource

internal/acceptance/workspace_file_test.go
The test HCL template for TestAccWorkspaceFileBase64 was incorrect. With this change, the integration test passes.
=> Fix TestAccWorkspaceFileBase64

docs/resources/sql_table.md
Fixes sql_table example in documentation to use `name` from `databricks_catalog` and `databricks_schema` instead of `id`.
=> Update `databricks_sql_table` doc

aws/data_aws_crossaccount_policy.go, aws/data_aws_crossaccount_policy_test.go
One more permission that is necessary for fleet use was missing from the policy definition in our documentation (tracked as a separate Jira)
This is follow up fix for #2255
=> Add missing permission to `databricks_aws_crossaccount_policy` data source

internal/acceptance/metastore_data_access_test.go
TestUcAccMetastoreDataAccessOnAws does not pass on master due to the "metastore" catalog being defined. This PR changes this integration test to use a new, randomly-generated metastore each time it runs.
=> Fix TestUcAccMetastoreDataAccessOnAws

docs/resources/workspace_conf.md, exporter/context.go
given the recent advisory, there are asks for disabling the legacy global & named cluster init scripts via Terraform.  This PR documents them, and also add to the exporter
=> Document & export `databricks_workspace_conf` parameters for legacy init scripts

CHANGELOG.md, common/version.go
* Added [databricks_workspace_file](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/workspace_file) resource ([#2266](https://github.com/databricks/terraform-provider-databricks/pull/2266)).
* Added `notification_settings` block to [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) resource ([#2276](https://github.com/databricks/terraform-provider-databricks/pull/2276)).
* Added missing permission to [databricks_aws_crossaccount_policy](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/aws_crossaccount_policy) data source ([#2283](https://github.com/databricks/terraform-provider-databricks/pull/2283)).
* Fixed …
=> Release v1.16.0

docs/resources/group_role.md
Connects to https://github.com/databricks/terraform-provider-databricks/issues/1870
Connects to https://github.com/databricks/terraform-provider-databricks/pull/1881
Documentation for `databricks_group_role` gives an example using the deprecated `databricks_group_instance_profile`. Based on the rest of the documentation 
https://github.com/databricks/terraform-provider-databricks/blob/28cbf483fbd94a04f62821549d3f6678c1c3cc37/docs/resources/group_role.md?plain=1#L52
seems like `role` should be pointing to the same `databricks_instance_profile`. 
Is this the intended way forward with `databricks_group_role` and instance profiles?
=> Removed reference to deprecated `databricks_group_instance_profile` from `databricks_group_role` docs

docs/index.md, docs/resources/service_principal.md, docs/resources/service_principal_secret.md
- Add the resource `databricks_service_principal_secret` into the `docs/resources`
- Add the section `Authenticating with hostname, client_id and client_secret` in the `docs/index.md`
=> Added `databricks_service_principal_secret` documentation

docs/guides/azure-private-link-workspace-standard.md, docs/resources/job.md, docs/resources/secret_scope.md, docs/resources/sql_table.md
This includes following changes:
* Fix Azure Key Vault access policy example - this fixes #2293
* Add a warning that for AKV-baked secret scopes the Azure authentication should be used
* reformat docs
=> Update documentation for `databricks_secret_scope` resource

exporter/importables.go
Current Permissions API doesn't allow change of the permissions for the `/Shared` folder, so when we generate a permission resource for it, we get Terraform error.
fixes #2269
=> Exporter: don't emit `databricks_permissions` for `/Shared` directory

docs/resources/pipeline.md, pipelines/resource_pipeline.go, pipelines/resource_pipeline_test.go
Added missing `serverless` option to PipelineSpec
=> Added missing `serverless` option to PipelineSpec

access/resource_ip_access_list.go, access/resource_ip_access_list_test.go, exporter/exporter_test.go, exporter/importables.go, internal/acceptance/ip_access_list_test.go
- Migrate IP ACL to Go SDK 
- Update and enable integration tests
- Fix tests to use body for updates
- No relevant change is needed to be updated in docs since argument references are the same.
Integration test: internal/acceptance/ip_access_list_test.go. Full integration test suite is also running successfully.
=> Migrated `databricks_ip_access_list` resource to Go SDK

docs/guides/troubleshooting.md
=> Add entry about 32-bit problems into the troubleshooting guide

.goreleaser.yml
Removes 32-bit builds from .goreleaser.yml
Closes #2304
=> Remove support for releasing 32-bit binaries

permissions/resource_permissions.go
=> Automatically add `CAN_MANAGE` permission on `databricks_instance_pool` to calling user

CHANGELOG.md, common/version.go, internal/acceptance/init_test.go, internal/acceptance/model_serving_test.go, internal/acceptance/sql_table_test.go
* **Removed support for releasing 32-bit binaries** ([#2315](https://github.com/databricks/terraform-provider-databricks/pull/2315), [#2320](https://github.com/databricks/terraform-provider-databricks/pull/2320)).
* Added more information on impact of using a cluster policy in [databricks_cluster](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster) resource ([#2313](https://github.com/databricks/terraform-provider-databricks/pull/2313)).
* Added missing `serverless` option to [databricks_pipeline](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline) ([#2308](https://github.com/databricks/terraform-provider-databricks/pull/2308)).
* Updated `channel` and `edition` values in …
=> Release v1.17.0

catalog/resource_catalog.go, catalog/resource_catalog_test.go, catalog/resource_external_location.go, catalog/resource_schema.go
UC Engineering team changed a way how the storage URLs are normalized, and this caused an issue with existing UC resources (catalogs, schemas, ...) that used URLs like `s3://bucket` instead of `s3://bucket/`
This fixes #2335
=> Add suppress diff for URL change that only change `/` (remove or add) in UC resources

catalog/resource_volume.go, catalog/resource_volume_test.go, docs/resources/volume.md, internal/acceptance/volume_test.go
Address comments mentioned in: https://github.com/databricks/terraform-provider-databricks/pull/2324
=> Updated docs and tests for `databricks_volume` resource

exporter/exporter_test.go, scim/resource_user.go, scim/resource_user_test.go
The SCIM API attributes are case sensitive, so due to a typo in attributes (`externalId` vs. `externalID`), `externalId` was not returned and lead to permanent drifts
Closes #2209
=> Fix attributes typo in SCIM API

docs/resources/model_serving.md, docs/resources/permissions.md, internal/acceptance/model_serving_test.go, permissions/resource_permissions.go, serving/resource_model_serving.go
To support permissions assignment we also need to expose a new attribute with internal ID of the model serving endpoint.
fixes #2333
=> Added `databricks_model_serving` support to `databricks_permissions`

docs/resources/volume.md
Use names instead of ids.
Fixed some typos.
Removed Owner from the example. Owner can only be used to update the Volume. It is ignored at Create.
=> Fix some docs

CHANGELOG.md, README.md, common/version.go
* Added [databricks_volume](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/volume) resource in Unity Catalog ([#2324](https://github.com/databricks/terraform-provider-databricks/pull/2324)).
* Added [databricks_model_serving](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/model_serving) support to [databricks_permissions](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/permissions) ([#2331](https://github.com/databricks/terraform-provider-databricks/pull/2331)).
* Added suppress diff for URL change that only changes `/` (remove or add) in UC resources ([#2336](https://github.com/databricks/terraform-provider-databricks/pull/2336)).
* Fixed attributes typo in SCIM API …
=> Release v1.18.0

catalog/data_catalogs_test.go, catalog/resource_catalog.go, catalog/resource_catalog_test.go, catalog/resource_schema.go, docs/resources/catalog.md
Migrate `databricks_catalog` resource to Go SDK.
=> Migrate resource `databricks_catalog` to Go SDK

docs/data-sources/cluster_policy.md, policies/data_cluster_policy.go, policies/data_cluster_policy_test.go
Adds the following attributes to the data source cluster policy:
- description
- policy_family_id
- policy_family_definition_overrides
- is_default
Closes #1947 
I have modified the TestDataSourceClusterPolicy to test the cluster policy data structure using the new attributes.
=> Add attributes to `databricks_cluster_policy` data source

docs/resources/cluster.md
It's possible to restrict a workload type for a given `databricks_cluster` instance.  For example, it's possible to disable execution of jobs on a cluster.
Related to #2369
=> Document `workload_type` block in `databricks_cluster` resource

docs/resources/job.md, jobs/resource_job.go, jobs/resource_job_test.go
Added read-only runAsUserName field to job definition and write-only runAs field to job settings definition.
=> Add run_as and run_as_user_name field to job definition 

docs/guides/unity-catalog.md
Changes:
- Replaced `*` per `arn:aws:iam::${var.aws_account_id}:root` for the self assuming part of the UC policy document role
=> Adding less permissive principal for self assuming UC role

access/resource_permission_assignment.go, mws/resource_mws_permission_assignment.go, permissions/resource_permissions.go, repos/resource_git_credential.go
Explicit conversion of strings to `int64`. Instead of machine dependent conversion when using integer type `int` (bit size 0 in `strconv.ParseInt`), that will throw "value out of range" error for platforms that infer `int` as `int32`, when larger integers than `int32` is used.
=> Explicit conversion of strings to int64.

CHANGELOG.md, common/version.go
* Added `run_as` and `run_as_user_name` fields to [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) ([#2388](https://github.com/databricks/terraform-provider-databricks/pull/2388)).
* Added more attributes to [databricks_cluster_policy](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/cluster_policy) data source ([#2351](https://github.com/databricks/terraform-provider-databricks/pull/2351)).
* Added `force_destroy` to [databricks_external_location](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/external_location) resource ([#2353](https://github.com/databricks/terraform-provider-databricks/pull/2353)).
* Added less permissive principal for self assuming UC …
=> Release v1.19.0

internal/acceptance/cluster_test.go
Release is scheduled in release after next 2 weeks. Skipping this for now.
=> Skip `TestAccClusterResource_CreateClusterWithLibraries` integration test

catalog/resource_sql_table.go, catalog/resource_volume.go
Similar to changes in #2336 we need to suppress diff detection when storage URL is normalized by the backend, leading to creation of plans like this:
```
~ resource "databricks_volume" "this" {
id               = "main.tmp.tftest"
name             = "tftest"
~ storage_location = "s3://xxxx/catalog_test/vtest" -> "s3://xxxx/catalog_test/vtest/"
}
```
this fixes #2316
=> Add suppress diff for `storage_location` in `databricks_sql_table` and `databricks_volume` resources

exporter/context.go, exporter/importables.go
This includes following changes:
- fix exporting of groups membership as Account Users SCIM API doesn't return a list of groups in contrast to workspace SCIM API
- align exporting of all users with workspace level - you need to pass the `importAllUsers` to force it
- generate host/account ID parameters in the provider declaration
=> Exporter: improve export of users/groups on account level

catalog/resource_catalog.go, catalog/resource_catalog_test.go, catalog/resource_external_location.go, catalog/resource_schema.go, catalog/resource_sql_table.go, catalog/resource_volume.go
This is a follow up fix for #2408. It's needed because tables & volumes could be managed, and in this case API populate the `storage_location` with generated value and terraform was removing it because it's empty in the terraform code.
=> Use separate suppress diff function for `databricks_sql_table` and `databricks_volume`

docs/resources/volume.md
=> Polish descriptions for `databricks_volume` resource

internal/acceptance/entitlements_test.go, scim/resource_entitlement.go, scim/resource_entitlement_test.go, scim/scim.go
Fix edge cases behaviour for `databricks_entitlements`
Close #2382
=> Fixed `databricks_entitlements` resource edge behaviour

docs/resources/sql_global_config.md, sql/resource_sql_global_config.go, sql/resource_sql_global_config_test.go
Allow google_service_account to be assigned to SQL warehouse global settings. 
This change impacts GCP Databricks workspace only. Corresponding [REST API endpoint](https://docs.databricks.com/api/gcp/workspace/warehouses/setworkspacewarehouseconfig)
=> Allow assigning GCP SA in `databricks_sql_global_config` resource

pools/resource_instance_pool.go, pools/resource_instance_pool_test.go
REST API supports editing of tags for quite a some time, but the field was still marked as `force_new` leading to recreation of the pool & affecting dependent resources.
Please note that due API bug it's impossible to remove tags completely after they set, you can only change them.
=> Allow to change `custom_tags` in `databricks_instance_pool` resource without recreating a pool

catalog/resource_catalog.go, catalog/resource_catalog_test.go, catalog/resource_catalog_workspace_binding.go, catalog/resource_catalog_workspace_binding_test.go, docs/resources/catalog.md, docs/resources/catalog_workspace_binding.md, internal/acceptance/catalog_workspace_binding_test.go, provider/provider.go
=> Added support for Unity Catalog `databricks_catalog_workspace_binding` resource

internal/acceptance/sql_permissions_test.go
=> Fix TestAccTableACL failing due to defer/t.Cleanup Mixup

go.mod, go.sum
Bump the Go SDK version to 0.12.0. This fixes the terraform provider to work in the DOD environment.
=> Bump Go SDK version to 0.12.0

CHANGELOG.md, common/version.go
* Added suppress diff for `storage_location` in [databricks_sql_table](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_table) and [databricks_volume](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/volume) resources ([#2408](https://github.com/databricks/terraform-provider-databricks/pull/2408)).
* Added option disable_as_user_deletion to disable instead of delete [databricks_user](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/user) and [databricks_service_principal](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/service_principal), enabled by default for user management at the account level …
=> Release v1.20.0

catalog/resource_catalog.go, internal/acceptance/catalog_workspace_binding_test.go
This PR fixes the workspace binding acceptance tests. There are two changes:
1. it simplifies the test cases considerably: two tests, one where a binding is created for the current workspace, and one where a binding is created for a separate workspace.
2. it fixes the delete implementation for catalog to add the current workspace to the workspace bindings for the catalog if the catalog is isolated. If the workspace is not in the bindings for an isolated catalog, even metastore admins cannot delete it via the workspace-level API.
Note that isolated catalogs automatically use the workspace binding mechanism to add the current workspace to the catalog bindings on creation, so the second change is only in case of the workspace being listed in a workspace_binding resource. In this case, the …
=> Fix workspace binding acceptance tests

common/client.go, common/resource.go
Define generic data for both account and workspace data, added account client for getting data for account level resources.
=> Added `AccountData`, `AccountClient` and define generic databricks data for workspace and account

docs/resources/job.md, jobs/resource_job.go
The name of the parameter was incorrect because of the documentation problem, and wasn't rejected by the API as incorrect.
this fixes #2434
=> Change name of one parameter in file arrival trigger

internal/acceptance/model_serving_test.go
getStatus was removed from the newer versions of the mlflow library. This PR fixes this test
Integration test passes now
=> Fixed model serving integration test

internal/acceptance/model_serving_test.go
Uses the default cluster we have in our test infra to run the test. This can cut down on the test time needed to spin up a new cluster
Self testing. Integration test passes now
Builds on top of https://github.com/databricks/terraform-provider-databricks/pull/2460
=> Use default cluster for model serving integration test

compute/compute_api.go, jobs/resource_job.go, jobs/resource_job_test.go
Add support for private preview functionality `compute` and `compute_key`.
Add test case to `resource_job_test.go`
=> Add experimental compute field to `databricks_job` resource

docs/resources/job.md, jobs/resource_job.go, jobs/resource_job_test.go
It's now possible to subscribe to updates of individual dashboards & alerts in the SQL tasks of Databricks Workflows
This fixes #2436
=> Add ability to subscribe to dashboards & alert SQL tasks in `databricks_job`

CHANGELOG.md, common/version.go
Release v1.21.0 of the Terraform Provider for Databricks.
* Added condition_task to the [`databricks_job`](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) resource (private preview) ([#2459](https://github.com/databricks/terraform-provider-databricks/pull/2459)).
* Added `AccountData`, `AccountClient` and define generic databricks data utilites for defining workspace and account-level data sources ([#2429](https://github.com/databricks/terraform-provider-databricks/pull/2429)).
* Added documentation link to existing Databricks Terraform modules ([#2439](https://github.com/databricks/terraform-provider-databricks/pull/2439)).
* Added experimental compute field to [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/do …
=> Release v1.21.0

exporter/context.go, exporter/exporter_test.go, exporter/importables.go
This includes following changes:
* Add user ID to the `databricks_user` resource name to avoid clashes on names like, `user+1` and `user_1`
* Add user/sp/group ID to the name of the `databricks_group_member` resource
* Remove too aggressive name normalization pattern that also leads to the generation of the duplicate resource names for different resources
=> Exporter: make resource names more unique to avoid duplicate resources errors

internal/acceptance/sql_table_test.go
A static value causes interference on concurrent runs.
=> Use random catalog name in SQL table integration tests

docs/guides/troubleshooting.md
It's related to use OAuth for authentication but not providing `account_id` in the provider configuration.
=> Add one more item to the troubleshooting guide

catalog/data_metastore.go, catalog/data_metastore_test.go, docs/data-sources/metastore.md, internal/acceptance/data_metastore_test.go, jobs/resource_job.go, provider/provider.go
Enable fetching account level metastore information through id for a single metastore.
=> Added support for Unity Catalog `databricks_metastore` data source

internal/acceptance/init_test.go
After upgrading delve to latest, isInDebug() no longer works, as the name of the executable generated by Delve is __debug_bin<numbers>. Checking for whether the basename has __debug_bin as a prefix should work for old and new Delve versions.
=> Support new delve binary name format

.vscode/settings.json
The `dlvLoadConfig` setting used to customize the rendering of variables in the explorer pane during debugging [has been deprecated](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#settings). This PR removes this no-longer used configuration. This PR removes the popup that shows up saying that this configuration is no longer used.
Debugged a test, and the warning was no longer present. I could still see debugging information in the debug pane.
=> Remove unused dlvLoadConfig configuration from settings.json

sql/resource_sql_alerts.go, sql/resource_sql_alerts_test.go
SQL alert values can also be booleans
follow up to https://github.com/databricks/terraform-provider-databricks/pull/2494
=> SQL alert values can also be booleans

clusters/clusters_api.go, clusters/resource_cluster_test.go, jobs/resource_job.go, jobs/resource_job_test.go
`NodeTypeID` cannot be set in `jobsAPI.Update()` if `InstancePoolID` is specified.
If both are specified, assume `InstancePoolID` takes precedence and `NodeTypeID` is only computed.
Closes #2502.
Closes #2141.
=> `databricks_job`: `instance_pool_id` takes precedence over `node_type_id` in `Update`

.github/workflows/push.yml
This PR is one of two changes to enable the merge queue for the provider repo. This will allow changes to merge to master without needing to be manually updated to the tip of the release branch. One this change is merged, I will enable the "Require merge queue" setting on the repo. We'll use the same settings as configured for the CLI.
See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue for more information.
=> Configured merge queue for the provider

catalog/resource_grants.go, docs/resources/grants.md
Add support for the USE MARKETPLACE ASSETS privilege for the metastore securable (see [here](https://docs.databricks.com/sql/language-manual/sql-ref-privileges.html#privilege-types)), which allows for access to the Databricks Marketplace without CREATE CATALOG and USE PROVIDER privileges or higher privilege roles.
Tested this to work for Azure manually. Let me know if additional tests are needed.
=> Add support for `USE_MARKETPLACE_ASSETS` privilege to metastore

docs/guides/experimental-exporter.md, exporter/exporter_test.go, exporter/importables.go
=> Exporter: add support for `databricks_model_serving`

clusters/clusters_api.go, docs/resources/cluster.md
New setting allows to specify number of local SSD disks to be attached to each node
Unfortunately we need to wait until Clusters GET is fixed because right now it doesn't return that attribute 🤦
=> Added `gcp_attributes.local_ssd_count` to `databricks_cluster` resource

docs/resources/instance_pool.md, pools/resource_instance_pool.go
Right now added it directly, will start migration to Go SDK soon
Also fixed error in documentation about `gcp_availability` attribute
This fixes #2557
=> Added `gcp_attributes.local_ssd_count` to `databricks_instance_pool` resource

docs/resources/job.md
Add `job_parameters` field to the docs to show support for `run_job_task`
=> Document job_parameters support for run_job_task

docs/guides/experimental-exporter.md, exporter/context.go, exporter/exporter_test.go, exporter/importables.go
Also fixed a bug in `context.go` related to generation of variables for nested attributes
=> Exporter: Added support for `databricks_mlflow_webhook` resources

docs/data-sources/current_user.md, docs/data-sources/group.md, docs/data-sources/service_principal.md, docs/data-sources/user.md, scim/data_current_user.go, scim/data_current_user_test.go, scim/data_group.go, scim/data_group_test.go, scim/data_service_principal.go, scim/data_service_principal_test.go, scim/data_user.go, scim/data_user_test.go
This is to have parity between resources & data sources
=> Added `acl_principal_id` to data sources: `databricks_user`, `databricks_service_principal`, `databricks_group`, `databricks_current_user`

docs/resources/access_control_rule_set.md, internal/acceptance/account_rule_set_test.go
Documentation changes for group rule set management.
=> Add instructions for group rule set management

catalog/resource_grants.go, catalog/resource_grants_test.go, docs/resources/grants.md
Refresh `databricks_grants` with latest permissible grants
=> Refresh `databricks_grants` with latest permissible grants

internal/acceptance/account_rule_set_test.go
This PR makes two changes:
1. Use string prefix to match on the cloud environment rather than exact match. This fixes the underlying issue.
2. Load environment before calling `accountTest`. This allows users to debug this test from VS Code without needing to run it in CI.
=> Fixed databricks_access_control_rule_set integration test in Azure

docs/guides/experimental-exporter.md, exporter/command.go, exporter/context.go, exporter/importables.go, exporter/importables_test.go, exporter/util.go
New command-line option `-notebooksFormat` allows to export notebooks in DBC and IPython formats.
This fixes #2568
=> Exporter: command-line option to control output format for notebooks

CHANGELOG.md, common/version.go, go.mod, go.sum
Release v1.24.0
* Added account-level API support for Unity Catalog objects ([#2182](https://github.com/databricks/terraform-provider-databricks/pull/2182)).
* Added [databricks_connection](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/connection) resource to support Lakehouse Federation ([#2528](https://github.com/databricks/terraform-provider-databricks/pull/2528)).
* Added `owner` parameter to [databricks_share](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/share) resource ([#2594](https://github.com/databricks/terraform-provider-databricks/pull/2594)).
* Added `acl_principal_id` to data sources: [databricks_user](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/user), …
=> Release v1.24.0

mws/resource_mws_workspaces.go, mws/resource_mws_workspaces_test.go, provider/gen/main.go
For PAT token, workspace verification fails if workspace is not configured to allows tokens. This happens because we use `token/list`
To fix this, we use SCIM API that is always available.
Before change the terraform apply doesn't work on the below repro and leads to `provider.terraform-provider-databricks: workspace https:/<test-name>.cloud.databricks.com/ is not yet reachable: Tokens are disabled.`
After change terraform apply is successful.
Repro:
1. Created mws workspace with username and password
2.  enabled pat tokens with "enableTokensConfig" = "true" in databricks_workspace_conf resource
3. run terraform apply --> successful 
4. disable pat token in step 2
5. run terraform apply --> fail
=> Fixed verification of workspace reachability by using scim/me which is always available 

qa/testing.go
The resource fixture struct is important for unit testing and forms a part of our SDK to create new terraform resources. This PR adds some relevant comments to help understanding our testing framework easier.
No need for testing.
=> Add doc strings for ResourceFixtures

docs/data-sources/aws_bucket_policy.md, docs/guides/aws-workspace.md, docs/guides/troubleshooting.md, docs/guides/unity-catalog-azure.md, docs/guides/unity-catalog-gcp.md, docs/guides/unity-catalog.md, docs/resources/external_location.md, docs/resources/mws_customer_managed_keys.md, docs/resources/mws_log_delivery.md, docs/resources/mws_workspaces.md, docs/resources/recipient.md, docs/resources/share.md
Updated `databricks_share` documentation, an owner attribute has to be outside of `object` configuration block.
Added more detailed description to `databricks_recipient` attribute reference `token` attribute.
Updated all docs using 'terrafmt' .
Validated using `make fmt-docs`. Only documentation files are changed.
=> updated share and recipient docs; terrafmt

catalog/resource_recipient.go, catalog/resource_recipient_test.go, docs/resources/recipient.md
This reverts commit 8dc13d4d703fee2ad85b6c60fedba72f0b0b87b1.
PR https://github.com/databricks/terraform-provider-databricks/pull/2592/files refactored `databricks_recepient` resource to Go SDK. This lead to the `CreateRecipientDb2DbAws` test failure with:
```
=== PAUSE ***CreateRecipientDb2DbAws
=== CONT  ***CreateRecipientDb2DbAws
init_test.go:243: Step 1/1 error: Error running apply: exit status 1
Error: cannot create recipient: panic: reflect: call of reflect.Value.SetString on interface Value
with databricks_recipient.db2db,
on terraform_plugin_test.tf line 12, in resource "databricks_recipient" "db2db":
12: resource "databricks_recipient" "db2db" {
```
Running this test on revert passes.
=> Revert "Refactor `databricks_recipient` to Go SDK (#2592)"

internal/acceptance/group_member_test.go, internal/acceptance/init_test.go
Internal terraform helpers provide a `Callback` field that is not a part of the terraform SDK. We already have an alternate available used everywhere else but for `group_member_test.go`
This PR switches to using the `Check` field instead, and removes the callback field.
It's nice to remove this field because it encourages a bad pattern where the assertion is made on the first resource defined in the test template, which is captured using regex capture groups.
The tests still pass. Also manually tested using debugger that the assertions now in `Check` are still called.
=> Remove callback field from acceptance test framework

catalog/resource_metastore_data_access.go, catalog/resource_metastore_data_access_test.go, catalog/resource_storage_credential.go, catalog/resource_storage_credential_test.go, docs/resources/metastore_data_access.md, docs/resources/storage_credential.md
This fixes #2532 
@nkvuong I think that the metastore data access should be also updated, but I couldn't find documentation on that API
=> Add `managed_identity_id` to `databricks_storage_credential` to support user-assigned managed identities

catalog/resource_schema.go, catalog/resource_schema_test.go, catalog/resource_volume.go, catalog/resource_volume_test.go, docs/resources/schema.md, docs/resources/volume.md
- Changing parent catalog name force creation of a new `databricks_schema`
- Changing parent catalog & schema name force creation of a new `databricks_volume`
Close #2246
=> correct `force_new` attributes for `databricks_schema` and `databricks_volume`

docs/resources/catalog.md, docs/resources/connection.md, docs/resources/external_location.md, docs/resources/metastore.md, docs/resources/metastore_assignment.md, docs/resources/metastore_data_access.md, docs/resources/provider.md, docs/resources/recipient.md, docs/resources/schema.md, docs/resources/sql_table.md, docs/resources/storage_credential.md, docs/resources/volume.md
Some customers are confused when to use `id` vs other attributes/parameters when creating dependencies between resources, so adding missing documentation for exported attributes.
Also fixed import documentation for `databricks_connection` resource.
=> Document missing `id` attributes in a number of resources

jobs/resource_job.go
Jobs API allows 0 value for `max_concurrent_runs` attribute [API docs](https://docs.databricks.com/api/workspace/jobs/create), but TF required to specify at least `1`.
This fixes #2681
=> Change validation for `max_concurrent_runs` in `databricjs_job` to allow 0 value

CHANGELOG.md, common/version.go
* Fixed the issue with `cannot reset nil reader` by bumping Go SDK to 0.19.2 ([#2684](https://github.com/databricks/terraform-provider-databricks/pull/2684)).
* Changed validation for `max_concurrent_runs` in `databricjs_job` to allow 0 value ([#2682](https://github.com/databricks/terraform-provider-databricks/pull/2682)).
Integration tests were successful on previous commit (this is a doc change so shouldn't affect). Still triggered integration test but not marking that as blocker for release.
=> Release v1.25.1

docs/resources/git_credential.md
=> Fix incorrect reference in the `databricks_git_credential` documentation

clusters/data_spark_version.go, docs/data-sources/spark_version.md
Since the introduction of the Photon & Graviton support, there were separate DBR versions exposed via APIs for each flavor:
* DBR for Intel CPUs without Photon `13.3.x-scala2.12`
* DBR for Intel CPUs with Photon `13.3.x-photon-scala2.12`
* DBR for Graviton CPUs without Photon `13.3.x-aarch64-scala2.12`
* DBR for Graviton CPUs with Photon `13.3.x-aarch64-photon-scala2.12`
* ML Runtime ...
Since DBR 14.0, no separate DBR versions are exposed for Photon & Graviton flavors, so if you use `photon` and/or `graviton` selectors, then you won't upgrade to DBR 14+.
The migration path is the following:
* Just specify a generic version, like, `14.0.x-scala2.12`.
* To use Photon, you need to specify `runtime_engine="PHOTON"` in the cluster configuration.
* For Graviton, it's just enough to select …
=> Deprecate `photon` and `graviton` selectors in `databricks_spark_version` data source

exporter/exporter_test.go, exporter/importables.go
User names or SP ID weren't resolved for the `run_as` block of `databricks_job` resource.
This fixes #2689
=> Exporter: export references in `run_as` block of `databricks_job`

clusters/clusters_api.go, docs/resources/cluster.md
Since DBR 13.3 we're supporting execution of init scripts from Unity Catalog volumes.
=> Add support for init scripts from Unity Catalog Volumes in `databricks_cluster` resource

CHANGELOG.md, common/version.go
* Removed `computed` for `pause_status` in [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) resource ([#2696](https://github.com/databricks/terraform-provider-databricks/pull/2696)).
* Added support for init scripts from Unity Catalog Volumes in [databricks_cluster](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster) ([#2666](https://github.com/databricks/terraform-provider-databricks/pull/2666)).
* Added deprecation warning for init scripts from DBFS in [databricks_cluster](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster) ([#2667](https://github.com/databricks/terraform-provider-databricks/pull/2667)).
* Deprecated `photon` and `graviton` selectors …
=> Release v1.26.0

catalog/resource_metastore_data_access.go, catalog/resource_metastore_data_access_test.go, catalog/resource_storage_credential.go, catalog/resource_storage_credential_test.go
- Always send empty struct for `databricks_gcp_service_account` in the create request. Closes #2628
Test e2e locally
=> Fix `databricks_metastore_data_access` and `databricks_storage_credential` creation on GCP

clusters/resource_cluster.go, docs/resources/cluster.md
The `cluster_mount_info` isn't part of official Clusters API anymore, and may go away at any point of time, so putting the deprecation message to prevent surprises.
=> Deprecate `cluster_mount_info` block in `databricks_cluster` resource

catalog/resource_metastore_data_access.go, catalog/resource_metastore_data_access_test.go, catalog/resource_storage_credential.go, catalog/resource_storage_credential_test.go, docs/resources/metastore_data_access.md, docs/resources/storage_credential.md
- Refactor to make `databricks_metastore_data_access` consistent with `databricks_storage_credential
- Close #2651
=> Add `owner` & `force_destroy` to `databricks_metastore_data_access`

exporter/importables.go, exporter/util.go, workspace/resource_notebook.go, workspace/resource_notebook_test.go
Right now listing of workspace objects (files/directories) is a bottleneck, especially in the incremental export mode. This PR tries to solve this problem by using multiple goroutines listing multiple directories in parallel
=> Exporter: parallel listing of workspace objects

internal/acceptance/mlflow_model_test.go, mlflow/resource_mlflow_model.go, mlflow/resource_mlflow_model_test.go
This attribute was lost during refactoring in #2257, and it broke the assignment of permissions.  Also expanded the corresponding integration test to have a check for that
This fixes #2730
=> Fix missing `registered_model_id` attribute in `databricks_mlflow_model` resource

exporter/importables.go, exporter/util.go
That check caused repeated re-export of the same notebooks in the incremental mode.  This issue happened only in specific customer environment.
=> Exporter: remove `modifiedAt != 0` check in the incremental mode

logger/logger.go, logger/logger_test.go, provider/provider.go
Terraform never had logging configured correctly (used to log all levels irrespective of log level specified). The issue (api calls not being shown in `DEBUG` log level) surfaced because in the TF version bump to 1.20.9 which had Go SDK version bump to 0.10.0, the PR: https://github.com/databricks/databricks-sdk-go/pull/426 introduced INFO as basic log level leading to debug level never being enabled even if it is passed through the environment variable. 
Note: `terraform apply` does not show INFO level logs by default. For that `TF_LOG=INFO` needs to be passed which I think is the expected (correct) behaviour.
- Tested Manually with using TF_LOG=DEBUG (TF_LOG=debug also works) env which works, not using the env doesn't show logs (correctly), using TF_LOG=TRACE shows right level (TRACE) …
=> Added logger package and fixed issue with API calls not being shown in DEBUG or lower log levels

.github/workflows/schema.yml
A workflow to compute provider schema diff between two versions of the provider. If triggered manually (through the actions UI), it takes inputs for the base ref and head ref to compare. If triggered from a pull request, it compares the schema on the main branch with the schema in the pull request.
The current behavior doesn't fail the workflow if there is a diff. This means folks need to actively look at the output. We can switch this by removing "continue-on-error: true" on the diff command itself.
Example run on my own fork (for the diff between v1.25 and v1.27): https://github.com/pietern/terraform-provider-databricks/actions/runs/6337272638/job/17212054575
=> GitHub Actions workflow to compute provider schema diff

docs/guides/experimental-exporter.md, exporter/command.go, exporter/context.go, exporter/context_test.go, exporter/exporter_test.go, exporter/importables.go, exporter/importables_test.go, exporter/model.go, exporter/util.go, exporter/util_test.go, sql/resource_sql_alerts.go, workspace/resource_notebook.go, workspace/resource_notebook_test.go
This change significantly speeds up the exporting of resources. I.e. for a workspace with approximately 5k TF resources export now takes ~4 minutes vs 50+ minutes.
The following changes are made:
- Isolate mutable parts & protect different mutable objects by dedicated mutexes. 
- Actual export is done in parallel by running listing & exporting operations in separate goroutines. Exporting goroutines are allocated by resource type, with multiple routines per type (configurable). Each resource type also has dedicated channels.
- Code generation is the single-threaded operation performed after export is done
Other changes include:
- Fixed panic when reading SQL Alert without Query attribute (happens when the underlying query is deleted)
- added `-noformat` option to skip running `terraform …
=> Export: parallel export of resources

sql/api/dashboard.go, sql/resource_sql_dashboard.go
When `dashboard_filters_enabled` is set to `true` then filters are shown on the SQL Dashboard level. In this case, the `databricks_sql_widget` should have following block to use it:
```
parameter {
type   = "dashboard-level"
name   = "Limit"
map_to = "Limit"
}
```
This fixes #2172
=> Add `dashboard_filters_enabled` attribute to `databricks_sql_dashboard` resource

docs/resources/sql_alert.md, sql/resource_sql_alerts.go
=> Add `empty_result_state` attribute to the `databricks_sql_alert` resource

exporter/importables.go
`application_id` was ignored on Azure as well, although it's required - because the corresponding field is marked as `computed`. Also, make `display_name` required for AWS/GCP.
=> Exporter: fix a logic for omitting some fields

docs/resources/user.md, internal/acceptance/user_test.go, scim/resource_user.go, scim/resource_user_test.go
The identity management team rolled out the changes for AWS workspaces to force user names be lower-cased by default (to match behavior on GCP & Azure).  But these changes are causing the permanent configuration drift because `user_name` is marked as `force_new`.  To mitigate this problem, added a suppress diff function that ignores changes in case.
=> Suppress diff for `user_name` in `databricks_user` when the changes only in character case

catalog/resource_grants.go, catalog/resource_registered_model.go, catalog/resource_registered_model_test.go, docs/index.md, docs/resources/grants.md, docs/resources/mlflow_experiment.md, docs/resources/mlflow_model.md, docs/resources/model_serving.md, docs/resources/registered_model.md, internal/acceptance/registered_model_test.go, provider/provider.go
This PR adds [Models in UC](https://docs.databricks.com/en/mlflow/models-in-uc.html) as a Terraform resource to the [Databricks Terraform Provider](https://registry.terraform.io/providers/databricks/databricks/latest), named in a future-proof way and to disambiguate from the soon-to-be deprecated [workspace MLflow models](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mlflow_model).
Also tested manually using the `make install`-version of the Terraform provider that includes these changes and the Dogfood staging workspace.
=> Added `databricks_registered_model` resource

catalog/resource_metastore.go, catalog/resource_metastore_test.go
- fix read method for `databricks_metastore` at account level
- add integration tests
=> fix read method for `databricks_metastore` at account level

docs/resources/sql_query.md, sql/resource_sql_query.go
- Fix `run_as_role` drift for `databricks_sql_query` resource
- Add doc for `databricks_sql_query` resource
=> Fix `run_as_role` drift for `databricks_sql_query` resource

docs/guides/experimental-exporter.md, exporter/exporter_test.go, exporter/importables.go, exporter/importables_test.go, exporter/test-data/get-cluster-policy.json
This includes:
- Listing of all cluster policies, not only that are referenced in the jobs/clusters.
- Emit secret scopes when they are referenced in Spark Conf or environment variables
Also, fixes generation of non-existent secret scopes that happens when we emit non-existent secret scope (for example, it's a dangling reference in cluster policy or old job configuration).
This fixes #2664
=> Exporter: improve exporting of `databricks_cluster_policy` resource

catalog/resource_metastore_data_access.go, catalog/resource_metastore_data_access_test.go, catalog/resource_storage_credential.go
- Fix storage credential read method
- Close #2766, #2697, #2749
=> Fixed read method for `databricks_storage_credential` resource

CHANGELOG.md, common/version.go
* Fixed read method for `databricks_storage_credential` resource ([#2804](https://github.com/databricks/terraform-provider-databricks/pull/2804)).
Integration tests are running...
=> Release v1.28.1

catalog/resource_catalog.go, catalog/resource_catalog_test.go, internal/acceptance/catalog_test.go
Fix a bug where it is not possible to update `databricks_catalog` `isolation_mode`
Close #2455
=> Fixed `databricks_catalog` `isolation_mode`

docs/guides/aws-e2-firewall-hub-and-spoke.md, docs/guides/aws-e2-firewall-workspace.md, docs/guides/aws-private-link-workspace.md, docs/guides/aws-workspace.md, docs/guides/unity-catalog-azure.md, docs/guides/unity-catalog-gcp.md
=> Add `account_id` parameter to provider blocks in the guides where it was missing

docs/guides/experimental-exporter.md
=> Exporter: clarify behaviour of services not marked with listing

serving/resource_model_serving.go, serving/resource_model_serving_test.go
=> Fix DiffSuppressFunc for `databricks_model_serving` resource

README.md, exporter/command.go
Exporter is experimental and although we mention that in https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/experimental-exporter but we don't have mention of that in our repository. Adding message. 
Ran: `./terraform-provider-databricks exporter` and Warning is printed.
=> Specify that Exporter is experimental

access/resource_permission_assignment.go, catalog/resource_artifact_allowlist.go, catalog/resource_artifact_allowlist_test.go, catalog/resource_connection.go, catalog/resource_table.go, common/resource.go, common/resource_test.go, docs/resources/artifact_allowlist.md, internal/acceptance/artifact_allowlist_test.go, mlflow/resource_mlflow_experiment.go, mws/resource_mws_permission_assignment.go, provider/provider.go, sql/resource_sql_dashboard.go
- Add new resource `databricks_artifact_allowlist` to support [Unity Catalog allowlist](https://docs.databricks.com/en/data-governance/unity-catalog/manage-privileges/allowlist.html)
- Add `common.NoCustomize` function to simplify schema creation
- 
close #2688
=> add `databricks_artifact_allowlist`

jobs/resource_job.go, jobs/resource_job_test.go
This PR adds the deployment field to the Job resource. This allows jobs created to be aware that they are a part of a bundle, as well as communicate bundle metadata with the job.
Unit test
=> Add deployment field to resource_job

exporter/exporter_test.go, jobs/data_job_test.go, jobs/data_jobs_test.go, jobs/resource_job.go, jobs/resource_job_test.go
As we couldn't easily switch `databricks_job` resource to use Go SDK, we were still using offset-based pagination that has a significant load onto the control plane.  This PR changes list operation to use recommended token-based approach until we switch to Go SDK.
This fixes #2807
=> Use token-based pagination for Jobs List operations

exporter/context.go, exporter/importables.go, exporter/importables_test.go
In `context.go` we had a very aggressive name normalization rule `@.*$` that did not necessarily strip parts of the job name. Also added handling of the empty job name.
=> Exporter: adjust generation & normalization of `databricks_job` names

exporter/context.go, exporter/exporter_test.go, exporter/importables.go, exporter/importables_test.go
Internally, the exporter uses the following resource ID for `databricks_library`: `<cluster_id>/<type>:coordinate` (i.e., `0426-122546-8xi8q5o3/pypi:chispa`).
When generating the final name of the resource, this name is normalized and checked if it's starting with a number, as Terraform doesn't allow identifiers to start with a number. If the final name starts with a number, then the artificial final name is generated consisting in the form of `r<first 12 digits of MD5 of the original name>`.  This leads to the generation of duplicate resources in case if cluster ID starts with a number, and the same library was attached to the cluster multiple times, having only differences in the character case, like, `Chispa` and `chispa` (our clusters UI allows that).
This PR fixes this issue with the …
=> Exporter: fix generation of names for `databricks_library` resources

exporter/context.go, exporter/importables.go, exporter/importables_test.go
Our UI & API allow the creation of directories and notebooks with characters like `\` and `"` in names, but they were incorrectly handled in the exporter.  This PR fixes that by doing the following:
* Correctly handle special characters when generating references
* Sanitizing file names for exported notebooks and workspace files and making them unique on disk by adding the object ID
It also should fix #2661 because we'll remove bad characters from file names
=> Exporter: Correctly handle not allowed characters in the notebooks/directories names

docs/resources/sql_alert.md
=> Doc: put `empty_result_state` under `options` in the `databricks_sql_alert` resource

docs/guides/unity-catalog-azure.md, docs/guides/unity-catalog-gcp.md, docs/guides/unity-catalog.md, docs/resources/grants.md, docs/resources/storage_credential.md
In the documentation, there is `CREATE_TABLE` permissions documented for every `databricks_grants` resource linked to a storage location. This is wrong. Only `CREATE_EXTERNAL_TABLE` exists for the `storage_credential` property. 
I must add, `CREATE_TABLE` does work, but it will set it to `CREATE_EXTERNAL_TABLE` in the UI. The next `terraform apply` will notice a difference, that will not go away until you change it to to the right value: `CREATE_EXTERNAL_TABLE`.
Manual tests:
1. Set it to `CREATE_TABLE` and run `terraform apply`
```hcl
resource "databricks_grants" "external_location_grants_enriched" {
provider          = databricks.workspace
external_location = databricks_external_location.enriched.id
grant {
principal  = var.ad_group_principal_name
privileges = ["CREATE_TABLE"]
} …
```
=> Changed CREATE_TABLE to CREATE_EXTERNAL_TABLE in docs for external storage locations

docs/resources/cluster.md
=> Correct max number of pinned clusters in the `databricks_cluster` docs

docs/guides/experimental-exporter.md, exporter/context.go, exporter/importables.go, exporter/model.go
Added exporting of a given resource. 
Also:
* added some documentation inside the code
* possibility to specify if a resource is a workspace or account level
* fixed bug in the regex matching
There were some problems with emulating account-level APIs, so the unit test will be added a bit later.
=> Exporter: added support for exporting `databricks_access_control_rule_set` on account level

CHANGELOG.md, common/reflect_resource.go, common/version.go
This PR tracks the release of version 1.29.0 of the Terraform Provider for Databricks.
Release notes:
New Features and Improvements:
* Added [databricks_artifact_allowlist](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/artifact_allowlist) ([#27[44](https://github.com/databricks/eng-dev-ecosystem/actions/runs/6635966983/job/18046250964#step:4:45)](https://github.com/databricks/terraform-provider-databricks/pull/2744)).
* Added deployment field to databricks_job ([#2821](https://github.com/databricks/terraform-provider-databricks/pull/2821)).
* Added support for `warehouse_id`, `options`, `partitions` and liquid clustering for [databricks_sql_table](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_table) resource …
=> Release 1.29.0

.github/ISSUE_TEMPLATE/provider-issue.md
Changes issue template, allows us to:
1. Potentially cut down on time to reproduction.
2. Identiy regressions early.
=> Modify github issue template to identify regressions faster

internal/acceptance/pipeline_test.go, pipelines/resource_pipeline.go, pipelines/resource_pipeline_test.go
Add NumWorkers to ForceSendFields in Pipelines if AutoScaling is null
This fixes #1875
=> Add NumWorkers to ForceSendFields in `databricks_pipeline` if `spark_conf` contains config for single-node cluster

exporter/importables.go, exporter/util.go
* Disable generation of empty blocks for `email_notifications`, `webhook_notifications`, and `notification_settings` in `databricks_job`
* Don't produce `spark_conf` & `spark_env_vars` in clusters if they are default values produced by the REST API backend
=> Exporter: disable generation of empty or default blocks for `databricks_job` and `databricks_cluster`

exporter/context.go, exporter/importables.go, exporter/util.go
There was an inconsistency in emitting the `databricks_group_member` - depending on where it was emitted - from a group, or from a user/service principal, the generated name was either with user/SP ID or without.  This behavior was always there, but it wasn't visible until we started to do a parallel processing of resources.
This PR fixes this behavior, and group membership is consistent now.
=> Exporter: fix emitting of group membership

scim/resource_user.go, scim/resource_user_test.go, scim/users.go
The `Update` method wasn't reading the correct set of attributes when updating user (i.e. when having `force = true`) - this lead that groups were reset to empty state, and users were losing their groups association.
This fixes #2648 and #1639
=> Fix `Update` method of `databricks_user` to prevent removal of groups

mlflow/resource_mlflow_model.go, mlflow/resource_mlflow_model_test.go
`StructToData` did use wrong structure to deserialize data, so struct was empty after read. Also, changed to use `CreateModelRequest` as a base struct because we don't use all fields of the `Model` anyway.
=> Fix Read method of the `databricks_mlflow_model` resource

provider/provider.go, provider/provider_test.go
Currently, the client in the provider authenticates when making its first request. This request can have a context with a timeout or cancel func. However, because the OAuth2 caches this context, future token refreshes are subject to this cancellation/timeout. Instead, we call `Config.Authenticate()` during provider configuration. This serves 2 benefits:
1. The provider will fail to be configured if it cannot authenticate, rather than spitting out 1000s of resources with default auth problems.
2. The OAuth2 token source will be constructed with `context.Background()`, so token refreshes will never timeout.
Ideally, we would use the context associated with the request for token refreshes, but the OAuth2 library doesn't currently support this.
=> Authenticate client during configuration

catalog/resource_metastore_assignment.go, catalog/resource_metastore_assignment_test.go, internal/acceptance/metastore_assignment_test.go
Recreate metastore assignment when changing workspace id.
This resolves https://github.com/databricks/terraform-provider-databricks/issues/2876.
=> Recreate `databricks_metastore_assignment` when changing workspace or metastore id

internal/acceptance/tf_provider_test.go, provider/provider.go, provider/provider_test.go
As a follow-up to https://github.com/databricks/terraform-provider-databricks/pull/2885, we should tolerate auth failures for dynamically configured providers during the planning phase. This allows users to create workspaces and then configure a provider to manage resources in that workspace as part of a single template.
=> Allow authentication during configure to fail

docs/resources/group.md, docs/resources/service_principal.md, docs/resources/user.md
The built-in entitlements of `databricks_group`, `databricks_user`, and `databricks_service_principal` are assignable only to workspace-level identities, and for account-level identities we should use `databricks_entitlements`.
=> Documentation: add a note about setting entitlements with `databricks_entitlements` for account-level identities

exporter/importables.go, exporter/importables_test.go
It wasn't put into the generated code because `display_name` is marked as `computed` and we didn't have a dedicated `ShouldOmitField` function in `databricks_user` definition.
=> Exporter: don't omit `display_name` in `databricks_user` if it's not equal to `user_name`

catalog/resource_catalog_workspace_binding.go, catalog/resource_catalog_workspace_binding_test.go, docs/resources/catalog_workspace_binding.md, internal/acceptance/catalog_workspace_binding_test.go
- Refactor to use new APIs. Per doc
>The original path (/api/2.1/unity-catalog/workspace-bindings/catalogs/{name}) is deprecated. Please use the new path (/api/2.1/unity-catalog/bindings/{securable_type}/{securable_name}) which introduces the ability to bind a securable in READ_ONLY mode (catalogs only)
- Close #2792
=> Add `binding_type` attribute to `databricks_catalog_workspace_binding` resource

sql/resource_sql_query.go
SQL Queries API doesn't return those fields if the corresponding option isn't configured, so these fields need to be optional in Terraform, otherwise code generated by the exporter won't include them.
=> Make `prefix` & `suffix` optional in `multiple` block of `databricks_sql_query`

workspace/resource_notebook.go, workspace/resource_notebook_test.go, workspace/resource_workspace_file.go, workspace/resource_workspace_file_test.go
There were problems with the performance of `databricks_notebook` resource:
* There is an explicit Mutex there to coordinate the creation & deletion of directories - use of it led to the situation when notebooks were created sequentially even with high parallelism.
* Both `databricks_notebook` and `databricks_workspace_file` are always called `mkdirs` API to make sure that the parent directory exists.
This PR includes the following changes:
* In both `databricks_notebook` and `databricks_workspace_file`, the `mkdirs` API is called only when the error about "Parent folder doesn't exist". This should decrease the number of API calls.
* Decrease the use of locks in `databricks_notebook`
This fixes #2898
=> Improve performance of `databricks_notebook` and `databricks_workspace_file` resources

jobs/resource_job.go, jobs/resource_job_test.go
This is required to support break-glass UI for DABs. We don't need to document this since the feature is in private-preview and is only meant to be used internally from the CLI for now.
Existing unit test
=> Add edit_mode field to resource_job

internal/acceptance/init_test.go, internal/acceptance/workspace_conf_test.go, workspace/resource_workspace_conf.go, workspace/resource_workspace_conf_test.go
The Terraform SDK by default persists the state, even if apply fails. This PR sets the config back to it's previous value to prevent values not applied being persisted in state. 
This also solves the issue where entering typos for key values would brick the terraform state. 
Manually and new integration test
=> Do not persist state from failed updates in  databricks_workspace_conf 

docs/resources/default_namespace_settings.md, internal/acceptance/default_namespace_test.go, provider/provider.go, settings/resource_default_namespace_setting.go, settings/resource_default_namespace_setting_test.go
Make default_namespace_setting resource name singular
Run existing tests
=> Make default_namespace_setting resource name singular

exporter/importables.go, exporter/importables_test.go
These attributes were omitted from the generated code because they are marked as `computed` in the resource.  This PR fixes this.
This fixes #2927
=> Exporter: fix generation of `branch` & `tag` attributes in `databricks_repo`

internal/acceptance/workspace_file_test.go, workspace/resource_workspace_file.go, workspace/resource_workspace_file_test.go
The issue was reported by the customer who used the exporter to migrate the Azure workspace that they exported many empty `__init__.py` files, but couldn't import them because Terraform gave them an error.  The reason for this error is that in API spec the `content` field is marked as `optional` and correspondingly the `omitempty` was generated in Go SDK, but in fact, this field is required by the API.
To work around this problem until the API spec is fixed, the `Content` field was explicitly added to the `ForceSendFields` array to send the empty content.
=> Force sending the `content` field when creating empty `databricks_workspace_file` resources

exporter/importables.go, exporter/importables_test.go
Cluster policy could be inherited from the cluster policy family - in this case, the `definition` attribute should be ignored as it's coming from the cluster policy family. Also, switch to detection of built-in cluster policies by ID, instead of name.
It should be done together with the fix for #2935
=> Exporter: generate correct code for inherited `databricks_cluster_policy`

docs/resources/cluster_policy.md
With the recent upgrade of Go SDK, we now support libraries in the cluster policies, so added it to the documentation.
=> Documented use of libraries in the `databricks_cluster_policy` resource

docs/resources/sql_permissions.md
- Clarify that `databricks_sql_permissions` `any_file` argument works also for writing files and not only reading them
=> databricks_sql_permmissions: clarify that any_file also works for reading

docs/resources/job.md, jobs/resource_job.go
This PR adds the `description` field to JobSettings struct, allowing users to attach a description to their job.
=> [JOBS-13079] Add description to job settings
