databricks/terraform-provider-databricks

- sql/api/query.go
- sql/resource_sql_query.go
- sql/resource_sql_query_test.go
Fix for: https://github.com/databricks/terraform-provider-databricks/issues/2939
The `run_as_role` property wasn't being applied correctly on a databricks_sql_query resource, as documented in https://github.com/databricks/terraform-provider-databricks/issues/2939. This PR tries to solve this issue by aligning the TF code with the [Databricks Query API](https://docs.databricks.com/api/workspace/queries/create), so that run_as_role is only specified and queried from the top-level object, and not from the `options` block anymore.
Specifically, the `sql/resource_sql_query_test.go` was updated and run to verify this fix. A proper integration test run is still required to validate the fix.
> fix: resolved issue with run_as_role not being applied on databricks_sql_query resource

- internal/acceptance/job_test.go
- jobs/data_job_test.go
- jobs/resource_job.go
Diff suppression meant that once a nested key was set (either `user_name` or `service_principal_name`), it was unable to unset it.  If both are specified, they are ignored. This meant that once a job was configured with a `run_as` user, it was not possible to configure it with a service principal, and vice versa.
Related PRs:
* #2388
* #2626
* #2765
The new integration test passes.
> Remove diff suppression for a job's `run_as` block

- exporter/context.go
- exporter/exporter_test.go
- exporter/importables.go
- exporter/test-data/run-job-child.json
- exporter/test-data/run-job-main.json
Originally exporter generated references only for strings. With introduction of `run_job_task` in `databricks_job` that uses integer type for `job_id` attribute, we need to generate references for integer fields as well, otherwise generated HCL code had a hardcoded Job ID value, and we couldn't use the generated code to apply to other environments.
This fixes #2933
> Exporter: generate references also for integer attributes

- jobs/resource_job.go
- jobs/resource_job_test.go
- Migrate jobs delete to use go-sdk
- Updated test fixture because the go-sdk uses 2.1 api
> Migrate jobs delete to go-sdk

- internal/acceptance/workspace_conf_test.go
There is a race condition causing nightly tests to fail for databricks_workspace_conf. `TestAccWorkspaceConfFullLifecycle` sets enableIpAccessList to true, and `TestAccInvalidWorkspaceConfAreIgnored` sets this to false. However, both tests are operating on the same workspace conf in parallel.
To fix this, I combined both test cases into a single test.
The test passes locally. Triggering nightlies to verify it works properly.
> Fix databricks_workspace_conf nightly race

- scim/resource_group.go
The `databricks_group` resource exposes the `url` attribute that is generated during the read operation. It had incorrect value for groups on account level. This PR fixes this
> Generate correct `url` attribute for `databricks_group` resource on account level

- clusters/clusters_api_sdk.go
- clusters/clusters_api_sdk_test.go
- clusters/resource_library.go
- Add `clusters_api_sdk.go` to implement same functionalities as in `clusters_api.go` with the go-sdk
- Migrate library delete to use the go sdk implementation
> Migrate delete to use go-sdk for library resource

- docs/data-sources/aws_crossaccount_policy.md
- docs/resources/mws_credentials.md
- docs/resources/mws_customer_managed_keys.md
- docs/resources/mws_log_delivery.md
- docs/resources/mws_networks.md
- docs/resources/mws_private_access_settings.md
- docs/resources/mws_storage_configurations.md
- docs/resources/mws_vpc_endpoint.md
- docs/resources/mws_workspaces.md
Remove this incorrect warning in documentation for `databricks_mws_*` resources
> This resource has an evolving API, which may change in future versions of the provider.
> Removing old warnings in documentation

- aws/data_instance_profiles.go
- aws/data_instance_profiles_test.go
- docs/data-sources/instance_profiles.md
- internal/acceptance/data_instance_profiles_test.go
- provider/provider.go
Added a new data source `databricks_instance_profiles` to list all instance profiles and export their properties as a list of objects.
Fixes #2330
> Added `databricks_instance_profiles` data source

- internal/acceptance/metastore_test.go
As a follow up to a regression with delta sharing parameters in the Terraform provider, this PR adds more integration test coverage to the metastore resource to ensure that we submit `0` as a parameter explicitly for `delta_sharing_recipient_token_lifetime_in_seconds`.
> Add integration test coverage for delta sharing parameters

- docs/resources/cluster_policy.md
- docs/resources/default_namespace_settings.md
- exporter/context.go
- exporter/exporter_test.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/util.go
- internal/acceptance/cluster_policy_test.go
- policies/resource_cluster_policy.go
- policies/resource_cluster_policy_test.go
Databricks is shipped with a number of built-in cluster policies that are inherited from the cluster policy families.  For built-in cluster policies we need to provide an override, not the `definition`.  We also need to handle deletes for them differently - just remove the overrides because we can't remove built-in policies.  We also need to distinguish cases when we override built-in policy from cases when we create a new policy based on the cluster policy family.
This PR makes following changes:
* Discovers a list of cluster policies families dynamically instead of relying on hardcoded list of policies
* When creating a new `databricks_cluster_policy`, check if it's built-in policy or not, and if it's built-in, then update it with policy override instead of trying to create.
* When …
> Allow to override built-in `databricks_cluster_policy` resources

- catalog/resource_metastore_data_access.go
- catalog/resource_storage_credential.go
- catalog/resource_storage_credential_test.go
- docs/guides/unity-catalog.md
- docs/resources/grants.md
- docs/resources/metastore_data_access.md
- docs/resources/storage_credential.md
- Update `databricks_storage_credential` with Go SDK struct `AwsIamRole`
- Update doc and UC guide on AWS
- Simplify doc for `databricks_metastore_data_access`
> Add delegation support for `databricks_storage_credential`

- clusters/resource_library.go
- libraries/libraries_api_sdk.go
- libraries/libraries_api_sdk_test.go
- Migrate library read method to use the go-sdk
- Added a `WaitForLibrariesInstalledSdk` method to mirror the one currently used, but implemented with the go-sdk
> Migrate library read to use go-sdk

- docs/resources/workspace_file.md
- workspace/resource_workspace_file.go
- workspace/resource_workspace_file_test.go
This new attribute will help with references to files on WSFS, for example, when using exporter (will be added in a separate PR after testing).
Also, refactored tests a bit.
> Add `workspace_path` attribute to `databricks_workspace_file` resource

- docs/resources/cluster.md
- docs/resources/instance_pool.md
- docs/resources/job.md
- docs/resources/metastore_assignment.md
- docs/resources/mlflow_webhook.md
- docs/resources/mws_workspaces.md
- docs/resources/repo.md
- docs/resources/secret_scope.md
In a number of resources the header levels were inconsistent for documentation about blocks (some were on the 2nd level, some on the 3rd, while most of the resources use the 3rd level).  Also, changed the order of sections a bit to get a uniform order of sections.
> Documentation: consistent header levels and same doc structure

- exporter/exporter_test.go
- exporter/importables.go
- exporter/test-data/get-cluster-permissions-test2-response.json
- exporter/test-data/get-job-12.json
- exporter/test-data/get-job-14.json
- exporter/test-data/get-job-15.json
- exporter/test-data/get-job-16.json
- exporter/test-data/get-job-17.json
- exporter/test-data/get-notebook-permissions.json
- exporter/test-data/get-sql-endpoint-permissions.json
- exporter/test-data/get-workspace-file-permissions.json
As we already switched to API 2.1, the code that is compatible with Jobs API 2.0 isn't necessary anymore and could be removed.
Also fixed a number of tests where JSON files weren't read correctly, or JSON structures were not completely correct.
> Exporter: Remove dead code that reflects old Jobs API 2.0 structures

- common/client.go
- mws/resource_mws_credentials.go
- mws/resource_mws_credentials_test.go
Remove requirement to provide accountId in mws_credentials resource
> Remove requirement to provide accountId in mws_credentials resource

- catalog/resource_artifact_allowlist.go
- catalog/resource_catalog.go
- catalog/resource_catalog_test.go
- catalog/resource_connection.go
- catalog/resource_external_location.go
- catalog/resource_metastore.go
- catalog/resource_schema.go
- catalog/resource_schema_test.go
- catalog/resource_storage_credential.go
- catalog/utils.go
- docs/guides/troubleshooting.md
- docs/guides/unity-catalog-azure.md
- docs/guides/unity-catalog-gcp.md
- docs/guides/unity-catalog.md
- docs/resources/artifact_allowlist.md
- docs/resources/catalog.md
- docs/resources/grants.md
- docs/resources/schema.md
- docs/resources/sql_table.md
- docs/resources/storage_credential.md
- docs/resources/volume.md
- mws/resource_mws_credentials_test.go
Validate metastore_id field in worspace UC resources
> Validate metastore_id field in worspace UC resources

- docs/data-sources/node_type.md
- docs/resources/cluster_policy.md
Fix two typos in docs for readability:
- **cluster_policy** resource: change `library{}` block -> `libraries{}` in example to align with current arguments
- **node_type** data source: use `-o json` for jq input in example cli category dump
> fix two minor docs typos

- catalog/resource_metastore.go
Revert validation in metastore. 
Other UC APIs at the workspace level implicitly use the metastore assigned to the workspace. This validation is only needed for those resources, to ensure that a user isn't trying to update UC resources belonging to a different metastore than the one assigned to the workspace.
> Revert validation in metastore resource

- access/resource_ip_access_list.go
- access/resource_ip_access_list_test.go
- docs/resources/ip_access_list.md
- internal/acceptance/ip_access_list_test.go
This reverts commit 40c92d67d160de37ecd740d771ad3037ae398ab8.
> Revert "Add support for Databricks Account Console IP Access Lists"

- CHANGELOG.md
- common/version.go
New Features and Improvements:
* Improved debugging of errors ([#744](https://github.com/databricks/databricks-sdk-go/pull/744))
* Removed requirement to provide accountId in mws_credentials resource ([#3028](https://github.com/databricks/terraform-provider-databricks/pull/3028)).
* Validated metastore_id field in worspace UC resources except metastore resource ([#3035](https://github.com/databricks/terraform-provider-databricks/pull/3035)), ([#3039](https://github.com/databricks/terraform-provider-databricks/pull/3039)).
* Wait for resource to be updated during grants resource modification ([#3026](https://github.com/databricks/terraform-provider-databricks/pull/3026)).
* Deprecated top level task attributes ([#2993](https://github.com/databricks/terraform-provider-databricks/pull/2993)). …
> Release v1.32.0

- docs/guides/experimental-exporter.md
- exporter/command.go
- exporter/context.go
- exporter/exporter_test.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/util.go
- exporter/util_test.go
Don't export workspace objects (notebooks, workspace files, and directories) of deleted users and service principals.  Otherwise, when importing into another workspace it will be attempted to create them, and the apply step will fail as we can't create folders under the `/Users` folder.
It doesn't cover other objects of deleted users, like SQL queries/alerts/dashboards - this may come in the next PRs.
> Exporter: Ignore workspace assets of deleted users and service principals

- clusters/data_clusters_test.go
- clusters/resource_cluster.go
- common/util.go
- common/util_test.go
- docs/guides/experimental-exporter.md
- exporter/exporter_test.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/util.go
Instead of generating separate `databricks_library` resources, cluster libraries are now generated inside of the `databricks_cluster` definition.  This decreases the number of the generated resources that is important for big workspaces as it decreases the state size.
> Exporter: generate cluster libraries blocks directly in `databricks_cluster`, don't generate `databricks_library` resources

- docs/resources/repo.md
- exporter/exporter_test.go
- exporter/importables.go
- exporter/test-data/get-cluster-policy.json
- exporter/util.go
- repos/resource_repo.go
- repos/resource_repo_test.go
- workspace/resource_directory.go
- workspace/resource_directory_test.go
We now support libraries that are uploaded into the Databricks workspace as files (`databricks_workspace_file` resource). We now support emitting them in jobs, clusters & cluster policies.
Also added the `workspace_path` attribute to the `databricks_repo` and `databricks_directory` resources.
> Exporter: add emitting of libraries that are workspace files

- exporter/importables_test.go
> Exporter: increase coverage for `databricks_mount` resource generation

- .github/ISSUE_TEMPLATE/provider-issue.md
Added an item to check if the ticket opener wants to do a bug fix, referring to the AWS side of Terraform
https://github.com/hashicorp/terraform-provider-aws/issues
> Added an item to check if the ticket opener wants to do a bug fix

- internal/acceptance/user_test.go
- scim/resource_user_test.go
Home folders may not be created in GCP when users are created. Now we ensure it is created to test that we are not cleaning it up when not requested.
> Force creation of home folder if not created

- internal/acceptance/metastore_assignment_test.go
Integration tests are at present making concurrent updates to the metastore assignment for the dummy workspace. This causes race conditions and flaky test failures. This PR removes one unnecessary test (covered by the Reassignment test) and adds a lock preventing this race condition from occurring.
> Lock dummy workspace to limit concurrent changes to its metastore assignment

- exporter/context.go
- exporter/importables.go
- exporter/util.go
When generating HCL code, the `dataToHcl` function checked if the value is zero, and as result, skipped the generation of the attribute even in following cases:
- the attribute is required even with zero value (for example, empty SQL query)
- the attribute has zero value, but attribute has non-zero default (disabled `scale_to_zero` in the model serving).
This PR fixes this issue by always generating required attributes, and also zero values with non-zero defaults.
This fixes #2511, fixes #2162
> Exporter: Generate zero values for required attributes & attributes with non-zero defaults

- clusters/data_clusters_test.go
The `TestClustersDataSourceErrorsOut` wasn't able to resolve a host name, and retries happened for long time, making execution of the test suite very long.  By setting some settings explicitly it fails fast now.
> Fix `TestClustersDataSourceErrorsOut` test that run too long

- .github/workflows/schema.yml
- scripts/diff-schema.sh
The diff-schema workflow doesn't work anymore because it fails to checkout master. This PR should fix this by always checking out the base & head commits and passing those commits via env vars to `diff-schema.sh`. With no variables set, it will show the diff between the current checked-out branch and master.
> Fix diff schema on PRs

- internal/acceptance/service_principal_test.go
- internal/acceptance/user_test.go
TestAccServicePrinicpalHomeDeleteNotDeleted fails today on master. Home folders are created lazily, and if they aren't created when the SP is created, the check at the end fails. This PR forces creation of home folder to ensure it isn't cleaned up by deletion.
> Fix TestAccServicePrinicpalHomeDeleteNotDeleted

- docs/data-sources/directory.md
- docs/resources/directory.md
- workspace/data_directory.go
- workspace/data_directory_test.go
This is for parity with resources
> Add `workspace_path` to the `databricks_directory` data source

- docs/guides/experimental-exporter.md
- exporter/context.go
- exporter/exporter_test.go
- exporter/importables.go
- exporter/importables_test.go
Also refactored a bit to avoid duplicate calls to metastore summary API
> Exporter: add support for `databricks_artifact_allowlist`

- catalog/resource_metastore_data_access.go
- catalog/resource_storage_credential.go
- docs/resources/external_location.md
- docs/resources/storage_credential.md
- internal/acceptance/storage_credential_test.go
- Add `skip_validation` parameter to `databricks_storage_credential`
- Add integration tests for other clouds
> add `skip_validation` to `databricks_storage_credential`

- docs/data-sources/service_principal.md
- scim/data_service_principal.go
- scim/data_service_principal_test.go
Allow searching not only by `application_id`, but also by the exact `display_name`.
This fixes #2959
> Added search by `display_name` to `databricks_service_principal` data source

- docs/data-sources/current_user.md
- docs/guides/unity-catalog-azure.md
- docs/guides/workspace-management.md
- docs/index.md
- docs/resources/catalog.md
- docs/resources/grants.md
- docs/resources/mlflow_webhook.md
- docs/resources/permissions.md
- docs/resources/schema.md
- docs/resources/sql_table.md
- docs/resources/volume.md
We had a number of places, including the main page, where we used old way of tasks specification instead of using `task` blocks, and that generated deprecation warning. This PR fixes that.
Also run `make fmt-docs` to format Terraform code examples.
> Docs: use tasks in the `databricks_job` examples

- common/reflect_resource.go
- common/reflect_resource_test.go
- common/resource.go
- As introduced in this PR, we don't have to use `makeEmptyBlockSuppressFunc` any more, simplifying this so that we can remove `makeEmptyBlockSuppressFunc`
- Meanwhile modified the signature of `diffSuppressor` to take in the schema type so we don't have to use `Sprintf` every time we call this
> Use diffSuppressor instead of makeEmptyBlockSuppressFunc

- catalog/resource_sql_table.go
- go.mod
- go.sum
- mlflow/resource_mlflow_webhook_test.go
- scim/data_service_principal_test.go
Go SDK has been released: https://github.com/databricks/databricks-sdk-go/releases/tag/v0.29.0, updating this in terraform before release.
Integration tests passed
> Update Go SDK to v0.29.0

- CHANGELOG.md
- common/version.go
* Added `workspace_path` to the [databricks_directory](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/directory) data source ([#3051](https://github.com/databricks/terraform-provider-databricks/pull/3051)).
* Added resource [databricks_grant](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/grant) for managing singular principal ([#3024](https://github.com/databricks/terraform-provider-databricks/pull/3024)).
* Added the [databricks_current_metastore](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/current_metastore) data source to retrieve information about a UC metastore attached to the current workspace ([#3012](https://github.com/databricks/terraform-provider-databricks/pul …
> Release v1.34.0

- exporter/command.go
- exporter/context.go
- exporter/context_test.go
- exporter/exporter_test.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/util.go
This PR contains following changes:
* emitting of the parent directory for SQL objects is moved to a separate function to simplify code, and allow refactoring in one place
* enabled services are now represented as slice of strings instead of string - this will allow to avoid matching on a partial line when there are services like `uc` and `uc-system-schemas`
> Exporter: small refactoring

- exporter/importables.go
The Jobs API requires the explicit `source = "WORKSPACE"` value for notebook tasks in case `git_credentials` are configured on the job level if they aren't used for the notebook tasks.  The #2857 was too aggressive in the removal of `source` attributes for notebook tasks.
> Exporter: don't omit `source` for notebook tasks from workspace when there is a Git configuration

- docs/resources/mws_workspaces.md
- internal/acceptance/mws_workspaces_test.go
- mws/resource_mws_workspaces.go
- mws/resource_mws_workspaces_test.go
- Allow Custom Tags to be added on a Workspace level to be propagated to clusters on AWS Customer managed VPC Workspaces only. Note that according to the REST API reference this is only available to AWS and hence ensured it is only set for that cloud.
Reference:
https://docs.databricks.com/api/account/workspaces/create
https://docs.databricks.com/api/account/workspaces/update
This will also solve issue #2938 
At my company we want to try keep as much in terraform code as possible. We have a temporarily call once workspace is created to update the tags for billing purposes but keeping in terraform code would be more suitable!
Manually tested with Company Databricks account and workspace on AWS environment. Note tested via GCP / Azure as currently do not have access.
* On a side note:
This …
> Allow custom tags on AWS customer managed VPC workspaces

- docs/guides/unity-catalog.md
This docs change is for this issue: https://github.com/databricks/terraform-provider-databricks/issues/3110
The[ IAM policy terraform documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/unity-catalog) may be missing the self-assumeRole section. The resulting in-line policy is different from the (correct) policy that we specify in our [UC CreateMetastore documentation page](https://docs.databricks.com/en/data-governance/unity-catalog/create-metastore.html#step-2-optional-create-an-iam-role-to-access-the-storage-location):
```
{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"s3:GetObject",
"s3:PutObject",
"s3:DeleteObject",
"s3:ListBucket",
"s3:GetBucketLocation",
"s3:GetLifecycleConfiguration",
"s3:PutLifecycleConfiguration"
], …
```
> [SC-151274] Add Self-Assume Capability to the Identity-Bound policy for IAM roles provisioned by TF

- catalog/resource_connection.go
- catalog/resource_connection_test.go
- internal/acceptance/connection_test.go
- Allow updating owner of `databricks_connection`, now that the API supports it
- Add `GoogleServiceAccountKeyJson` to list of secret options that are redacted by API
Closes #3079
> Allow updating owner of `databricks_connection`

- exporter/context.go
- exporter/context_test.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/model.go
- exporter/util.go
As we emit resources, some resources are ignored, for example:
* repos without URL
* deleted users & service principals, together with their directories
* ...
Before this change, information about these resources was available only in the logs - now we're collecting such resources in a separate structure, and output them as `ignored_resources.txt` file in the output directory.  This will help people to understand what resources weren't migrated...
> Exporter: better handling of ignored objects

- scim/data_group_test.go
- scim/data_service_principal.go
- scim/data_service_principal_test.go
- scim/data_service_principals.go
- scim/data_service_principals_test.go
- scim/data_user.go
- scim/data_user_test.go
- scim/groups.go
- scim/resource_group_test.go
- scim/resource_service_principal.go
- scim/resource_service_principal_test.go
- scim/resource_user.go
- scim/resource_user_test.go
The SCIM API team is changing the library used to parse SCIM requests. This library is more strict with the interpretation of filters, specifically mandating that string values in filters, like for display name or application ID, must use double quotes instead of single quotes. This PR modifies SCIM APIs to use double quotes for strings in filters instead.
> Use double quotes with filters in SCIM

- exporter/context.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/util.go
This PR includes following changes:
* Emit DBFS & Workspace file references for job tasks parameters.
* For DLT pipelines emit DBFS & Workspace file references, cluster policy, secrets from pipeline configuration
* Fixed generation of cluster policy definition broken after introduction of policy families overrides
> Exporter: improvements in export of jobs, DLT pipelines and policies

- CHANGELOG.md
- common/version.go
* Allow custom tags on AWS customer managed VPC workspaces ([#3114](https://github.com/databricks/terraform-provider-databricks/pull/3114)).
* Allow disabling serverless and photon for [databricks_sql_warehouse](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_warehouse) ([#3128](https://github.com/databricks/terraform-provider-databricks/pull/3128)).
* Allow updating owner of [databricks_connection](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/connection) ([#3080](https://github.com/databricks/terraform-provider-databricks/pull/3080)).
* Fix public_access_enabled property for mws_private_access_settings ([#3132](https://github.com/databricks/terraform-provider-databricks/pull/3132)).
* Reference OpenTofu …
> Release v1.35.0

- catalog/resource_grant.go
- catalog/resource_grant_test.go
- catalog/resource_grants.go
- catalog/resource_grants_test.go
- docs/resources/grant.md
- docs/resources/grants.md
Validate metastore id for databricks_grant and databricks_grants resources
> Validate metastore id for databricks_grant and databricks_grants resources

- clusters/clusters_api.go
- clusters/resource_cluster.go
- clusters/resource_cluster_test.go
- common/customizable_schema.go
- common/reflect_resource.go
- common/reflect_resource_test.go
- Before we are able to migrate the cluster resources to use the go-sdk schema, we need to figure out a way to represent the current `tf` tags on the manually maintained structs
- This PR introduces a new interface `ResourceProviderStruct` which contains a method for aliases and all of the customizations.
- `Aliases() map[string]string`
- `CustomizeSchema(map[string]*schema.Schema) map[string]*schema.Schema`
- Also added a series of customization functions such as `SetOptional`, etc so that we can easily write customization logics into the `CustomizeSchema` function to replace the current `tf` tags
- Migrated the cluster schema into the go-sdk schema with this new interface
> Migrate cluster schema to use the go-sdk struct

- .github/workflows/push.yml
- .github/workflows/release.yml
- .github/workflows/schema.yml
Caching is enabled by default in v5 of the setup-go action.
> Update actions/setup-go to v5

- .codegen.json
- .codegen/changelog.md.tmpl
This PR adds a .codegen.json file to the TF provider, like what we have in the other SDKs (e.g. [Go SDK](https://github.com/databricks/databricks-sdk-go/blob/main/.codegen.json)). This allows us to automate the release process for the provider, including autogenerating the entries in the changelog, and will also allow us to start using code generation for components of the provider.
The generated changelog still needs manual review, but it includes all of the sections that ought to be included in the changelog. It does not include the changes in the OpenAPI spec or provider schema itself for now, but this can be added later.
Ran `deco openapi release-sdk terraform --no-reset-main --dry-run`, which generated this diff: https://github.com/databricks/terraform-provider-databricks/pull/3181
> Add .codegen.json configuration

- common/customizable_schema_test.go
- Add unit tests for all functions in `customizable_schema.go`
> Add unit test for customizable_schema.go

- exporter/exporter_test.go
This PR fixes fixtures in exporter unit tests to make the tests pass on `main`.
> Fix Exporter unit tests

- internal/acceptance/job_test.go
- jobs/resource_job.go
- jobs/resource_job_test.go
Allow using an empty string as the "default" value for job parameters, otherwise, such jobs are rejected because "default" field is required.
Remove "omitempty" modifier because both fields are required.
Verified manually with Terraform
> Allow using empty strings as job parameters

- exporter/context.go
- exporter/context_test.go
- exporter/model.go
- exporter/util.go
Under a very high load, Databricks backend may not answer on time, or return specific errors, so it makes sense to retry operation few times.
This PR uses "naive" implementation, I need to play a bit more with `retries` package before adopting it
> Exporter: Add retries for `Search`, `ReadContext` and `Import` operations when importing the resource

- CHANGELOG.md
- common/version.go
* Added `databricks_volumes` as data source  ([#3150](https://github.com/databricks/terraform-provider-databricks/pull/3150)).
* Fixed updating owners for UC resources ([#3189](https://github.com/databricks/terraform-provider-databricks/pull/3189)).
* Validated metastore id for databricks_grant and databricks_grants resources ([#3159](https://github.com/databricks/terraform-provider-databricks/pull/3159)).
* Fixed `databricks_connection` regression when creating without owner ([#3186](https://github.com/databricks/terraform-provider-databricks/pull/3186)).
* Allow using empty strings as job parameters ([#3158](https://github.com/databricks/terraform-provider-databricks/pull/3158)).
* Changed type of value field of `JobsHealthRule` to `int64` …
> Release v1.36.0

- catalog/resource_storage_credential.go
- catalog/resource_storage_credential_test.go
- internal/acceptance/storage_credential_test.go
For the given account storage credentials definition:
```hcl
resource "databricks_storage_credential" "catalog_staging" {
name  = "catalog_staging"
owner = databricks_service_principal.catalog["staging"].application_id
metastore_id = databricks_metastore.unity_metastore.id
aws_iam_role {
role_arn = "arn:aws:iam::1234567890:role/MyRole-AJJHDSKSDF"
}
provider = databricks.account
}
```
fixes the error:
```bash
Error: cannot create storage credential: Storage Credential '02e010b4-0fdb-46d7-af9f-706e99f2b19b' does not exist.
```
as described in https://github.com/databricks/terraform-provider-databricks/issues/3134#issuecomment-1900468908.
From the logs, before this change, storage credential ID is used instead of a name when calling `PUT`:
```
2024-01-19T13:34:51.868Z [DEBUG] …
```
> Fix create storage credentials with owner for account

- docs/resources/service_principal_secret.md
Tested on both Azure & GCP, and was able to generate a secret for a service principal. Additional work will be required for testing of these service principal secrets on the workspace level (this will be done as part of #3196).
This fixes #3160
> Remove AWS-only note for `databricks_service_principal_secret` resource

- exporter/importables.go
The `git_provider` field is marked as `computed` because we're detecting it for well-known Git providers (GitHub, Azure DevOps, ...).  But because of this it was omitted from the generated code even for other Git providers.  This PR fixes this issue.
> Exporter: omit `git_provider` only for well-known Git URLs

- clusters/clusters_api.go
- Addressing issue raised in https://github.com/databricks/terraform-provider-databricks/issues/3231
> Remove `omitempty` in `destination` fields in clustes_api

- docs/data-sources/aws_unity_catalog_policy.md
- docs/data-sources/volumes.md
- docs/guides/unity-catalog.md
- docs/resources/access_control_rule_set.md
- docs/resources/artifact_allowlist.md
- docs/resources/catalog.md
- docs/resources/cluster_policy.md
- docs/resources/ip_access_list.md
- docs/resources/mlflow_experiment.md
- docs/resources/mlflow_model.md
- docs/resources/mlflow_webhook.md
- docs/resources/mws_log_delivery.md
- docs/resources/mws_permission_assignment.md
- docs/resources/mws_private_access_settings.md
- docs/resources/mws_vpc_endpoint.md
- docs/resources/permission_assignment.md
- docs/resources/permissions.md
- docs/resources/pipeline.md
- docs/resources/recipient.md
- docs/resources/share.md
- docs/resources/sql_alert.md
- docs/resources/sql_dashboard.md
- docs/resources/sql_endpoint.md
- docs/resources/sql_query.md
- docs/resources/system_schema.md
In many resources, we didn't have an attributes reference section at all, or it didn't have information about the `id` attribute.  This PR adds relevant information.
Also run `make fmt-docs` to format code snippets.
This fixes #3235
> Docs: add information on `id` and other exposed attributes where appropriate

- docs/resources/grants.md
Add required `metastore` argument for `databricks_grants` in metastore docs example.
Current example would return an error:
```
Error: Missing required argument
with databricks_grants.catalog_staging,
on [catalogs.tf](http://catalogs.tf/) line 24, in resource "databricks_grants" "catalog_staging":
24: resource "databricks_grants" "catalog_staging" {
"model": one of
`catalog,external_location,foreign_connection,function,metastore,model,schema,share,storage_credential,table,volume`
must be specified
```
> Docs: Fix `databricks_grants` example for metastore

- catalog/resource_grant.go
- catalog/resource_grants.go
- docs/resources/grant.md
- docs/resources/grants.md
The read method of corresponding resources was reading only a list of permissions, but it didn't set the securable field, so when doing the import, that field was empty and this lead to the recreation of the resource after import.  This PR explicitly sets that field on read.
This fixes #3245
> Explicitly set securable field when reading `databricks_grants` or `databricks_grant`

- clusters/resource_cluster.go
- common/reflect_resource.go
- common/reflect_resource_test.go
- Make aliases information from `ResourceProviderStruct` take effect in `iterFields` function so that `StructToData` and `DataToStructPointer` will take information about the aliases
- Taking out `UnderlyingType` method because it is no longer needed
- Adding an anonymous field for the `ClusterResourceProvider` struct so that reflection will work without `UnderlyingType`
- Make `iterField` check alias information
- Adding unit test case
> Make IterFields take in aliases

- docs/resources/job.md
- jobs/resource_job.go
- jobs/resource_job_test.go
Add terraform support for foreach task (going private preview soon). 
Terraform does not support cyclic dependencies, hence we need to limit the nesting depth manually. Implemented using separate structs for the time being.
> [JOBS-16324] Terraform support for Foreach tasks (private preview)

- docs/resources/job.md
- exporter/importables.go
- exporter/util.go
- jobs/resource_job.go
Also added support for it in TF exporter
> Add `source` attribute to `dbt_task` and `sql_task.file` tasks to support files from workspace

- docs/guides/aws-workspace.md
- docs/guides/gcp-workspace.md
- docs/guides/troubleshooting.md
- Fix broken images in the doc
- Describe the `more than one authorization method configured` error for AWS and GCP setup
Resolves #3257
> Docs: Fix images and add note on setting multiple authorizations for workspace setup

- catalog/resource_sql_table.go
- common/util.go
- common/util_test.go
- policies/resource_cluster_policy.go
- sql/resource_sql_query.go
Added suppress diff on whitespace change for following resources where HERE-docs are used most often for some attributes:
* `databricks_sql_table` - for `view_definition`
* `databricks_query` - for `query`
* `databricks_cluster_policy` - for `definition` and `policy_family_definition_overrides`
This fixes #3019
> Suppress diff on whitespace change for resources that often use HERE-docs

- docs/resources/vector_search_endpoint.md
- exporter/exporter_test.go
- internal/acceptance/vector_search_test.go
- provider/provider.go
- vectorsearch/resource_vector_search_endpoint.go
- vectorsearch/resource_vector_search_endpoint_test.go
Added initial support for Databricks Vector Search endpoints that are the base for adding Vector Search Indexes.
It's not clear about adding an integration test - the provisioning of the endpoints is quite a long process (~25-30 minutes).
> Add support for Vector Search Endpoints

- docs/resources/share.md
In UI/API/CLI, creating share at the SCHEMA level is supported, but the doc mentions only TABLE is supported.
The doc(data_object_type field) was last updated on oct-2022.
https://github.com/databricks/databricks-cli/blob/main/databricks_cli/unity_catalog/delta_sharing_cli.py#L213
Updating TF doc to match REST API doc.
https://docs.databricks.com/api/workspace/shares/create#:~:text=The%20type%20of%20the%20data%20object.
- Created a share in TF using `data_object_type=SCHEMA`
- Created new tables in the schema, which are automatically added to the share.
```
resource "databricks_share" "ravi-share-tf" {
name = "ravi-share-tf"
object {
name                        = "ravi_test_catalog.share_schema"
data_object_type            = "SCHEMA"
history_data_sharing_status = "ENABLED"
}
}
```
> Docs: Remove `data_object_type=TABLE` only restriction in `databricks_share`

- exporter/command.go
- exporter/context.go
- exporter/exporter_test.go
- exporter/importables_test.go
- exporter/util.go
When configuring services to list, the old code was relying on the substring match, and this lead to problems when we have overlapping matches, like, `uc` service matched `uc-allowlist`, etc.  This PR changed to use a map to store services to list so we don't have a problem with overlapping services.
Changes also were made to the interactive prompting - instead of asking for each resource type separately, we now ask about service and show which resources belong to that service.
> Exporter: rework handling of listings and interactive prompting

- catalog/resource_volume.go
- catalog/resource_volume_test.go
- docs/resources/volume.md
This attribute will expose path in form of `/Volumes/<catalog>/<schema>/<name>` for use with other resources, such as, `databricks_file`.  Plus it's necessary for Terraform Exporter to detect references between resources.
> Add computed `volume_path` attribute to `databricks_volume` resource

- common/client.go
We want to use basic creds for databricks, while using GOOGLE_CREDENTIALS for another provider.
Specifying `auth_type = "basic"` in the provider configuration did not resolve the `more than one authorization method configured` error, only setting `DATABRICKS_AUTH_TYPE=basic` envvar did.
After analysis, it looks like the databricks-sdk-go client is not receiving the auth_type value.
> fix: properly propagate auth_type to the databricks client

- CHANGELOG.md
- common/version.go
* Add [databricks_file](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/file) resource ([#3265](https://github.com/databricks/terraform-provider-databricks/pull/3265)).
* Add [databricks_storage_credential](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/storage_credential) and [databricks_storage_credentials](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/storage_credentials) data sources ([#3254](https://github.com/databricks/terraform-provider-databricks/pull/3254)).
* Add `source` attribute to `dbt_task` and `sql_task.file` tasks to support files from workspace ([#3208](https://github.com/databricks/terraform-provider-databricks/pull/3208)).
* Add computed `volume_path` …
> Release v1.37.0

- catalog/permissions/permissions.go
- catalog/resource_grants.go
- catalog/resource_grants_test.go
- internal/acceptance/grant_test.go
- internal/acceptance/grants_test.go
We remove client side validation for `databricks_grants`
Integration tests, updated unit tests, manually tested binary.
> Removed `CustomizeDiff` and Client Side Validation for `databricks_grants`

- CHANGELOG.md
- common/version.go
* Removed `CustomizeDiff` and Client Side Validation for [databricks_grants](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/grants) ([#3290](https://github.com/databricks/terraform-provider-databricks/pull/3290)).
* Added terraform support for restrict ws admins setting ([#3243](https://github.com/databricks/terraform-provider-databricks/pull/3243)).
* Migrated [databricks_global_init_script](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/global_init_script) to Go SDK ([#2036](https://github.com/databricks/terraform-provider-databricks/pull/2036)).
* Bump github.com/hashicorp/terraform-plugin-sdk/v2 from 2.31.0 to 2.32.0 ([#3177](https://github.com/databricks/terraform-provider-databricks/pull/3177)).
> Release v1.37.1

- docs/data-sources/current_metastore.md
- docs/data-sources/metastore.md
- docs/resources/metastore.md
Improve documentation for the `INTERNAL` and `INTERNAL_AND_EXTERNAL` values of `delta_sharing_scope` in terraform to clarify what they mean
> [PLAT-101819] Improve documentation for INTERNAL and INTERNAL_AND_EXTERNAL delta sharing scope in terraform 

- docs/guides/experimental-exporter.md
- exporter/command.go
- exporter/context.go
- exporter/context_test.go
- exporter/exporter_test.go
Since version 1.5, Terraform has supported use of the [import blocks](https://developer.hashicorp.com/terraform/language/import) that simplify the importing of existing resources into the state during the plan instead of importing one by one.
fixes #2780
> Exporter: add generation of import blocks for easier importing existing resources in Terraform 1.5+

- scim/resource_user.go
- scim/resource_user_test.go
The support team has reported that there are cases when users are created with the lower-case name, and the user already exists in the account but has the user name in another case, then the `force` option doesn't work correctly.
The fix is to compare error messages and emails in a case-insensitive manner.
Unfortunately, it's hard to test now as our backend now lower-case user names automatically...
> Perform case-insensitive error message checking when using `force` in `databricks_user`

- docs/guides/experimental-exporter.md
- exporter/importables.go
- exporter/importables_test.go
- exporter/util.go
This includes:
- added support for `databricks_sql_table`
- switch to use longest prefix match when generating references to `databricks_external_location`
- added suppression for `storage_location` of managed `databricks_registered_model`
- added references to `databricks_volume` from `databricks_artifact_allowlist`
- updated resources table in documentation to include information on which level (workspace or account) the given resource is handled
> Exporter: More work on Unity Catalog support

- docs/resources/default_namespace_settings.md
- docs/resources/restrict_workspace_admins_setting.md
- settings/generic_setting.go
- settings/generic_setting_test.go
- settings/resource_restrict_workspace_admins_setting_test.go
Before this change, generated settings resource were using `etag` value as resource ID. This lead to a situation that importing of these resources was problematic because ID was changing all the time.
This PR introduces stable IDs for generated resources. By default it uses a constant ID: `global`, similar to other resources, like, `databricks_sql_global_config`, but the resource implementor may provide a function that will generate a resource ID from the settings' data.
This fixes #3270
> Use stable IDs for settings resources

- clusters/resource_cluster.go
- Turns out that we don't need the `cluster_mount_info` alias because it is added only in `customize_schema`
> Remove unnecessary alias from cluster resource

- docs/resources/default_namespace_settings.md
- docs/resources/restrict_workspace_admins_setting.md
- settings/generic_setting.go
- settings/generic_setting_test.go
- settings/resource_restrict_workspace_admins_setting_test.go
This reverts commit 054371306bf6ca0e99889017c3bbd738b5e27fb1.
> Revert "Use stable IDs for settings resources (#3278)"

- common/resource.go
- mws/resource_mws_private_access_settings_test.go
In #3135, the `account_id` resource field is deprecated in favour of the provider level `account_id` attribute. However, it was reported that for the `databricks_mws_private_access_settings` resource, this could lead to a diff for every apply since the API returns the `account_id`. 
The API returns `account_id`, putting the attribute back in the state. But since it is removed in the resource, it will try to set it back to null.
Setting the `account_id` field to `Computed` will use the API provided `account_id` which should not result in diffs.
Resolves #3223 
Set `Computed` field to `true` for `common.Resource` `account_id` attribute.
> Set `Computed` field to `true` for `common.Resource` `account_id` attribute

- docs/guides/experimental-exporter.md
- exporter/importables.go
- exporter/importables_test.go
- exporter/util.go
Only files explicitly referenced as init scripts & libraries are exported.
> Exporter: add support for `databricks_file` resource

- docs/resources/default_namespace_settings.md
- docs/resources/restrict_workspace_admins_setting.md
- internal/acceptance/default_namespace_test.go
- internal/acceptance/restrict_workspace_admins_test.go
- settings/generic_setting.go
- settings/generic_setting_test.go
- settings/resource_restrict_workspace_admins_setting_test.go
Before this change, generated settings resource were using etag value as resource ID. This lead to a situation that importing of these resources was problematic because ID was changing all the time.
This PR introduces stable IDs for generated resources. By default it uses a constant ID: global, similar to other resources, like, databricks_sql_global_config, but the resource implementor may provide a function that will generate a resource ID from the settings' data.
This fixes #3270
> Use stable IDs for settings resources (v2)

- docs/guides/troubleshooting.md
Explained that the private link validation error may happen when an HTTP proxy is used
> Docs: Expanded the note about private link in the troubleshooting guide

- CHANGELOG.md
- common/version.go
* Use workspace-level default for `enable_serverless_compute` if not specified in [databricks_sql_global_config](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_global_config) ([#3279](https://github.com/databricks/terraform-provider-databricks/pull/3279)). Previously, this resource would disable serverless unless you set the deprecated `enable_serverless_compute` attribute to true. From this release, this resource will not modify `enable_serverless_compute`, leaving it as its default value (enabled) if unspecified.
* Fixed webhook_notifications diff suppression for [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) ([#3309](https://github.com/databricks/terraform-provider-databricks/pull/3309)). …
> Release v1.38.0

- exporter/importables.go
- exporter/importables_test.go
> Exporter: Remove too aggressive omitting for `volume_type` attribute of `databricks_volume` resource

- clusters/resource_cluster.go
- common/recursion_tracking.go
- common/reflect_resource.go
- common/reflect_resource_test.go
- This is a prerequisite PR for onboarding jobs foreach task to terraform because it contains recursive reference
- Added `recursion_tracking` utility functions and `recursionTrackingContext` struct to track recursion depth
- Added `MaxDepthForTypes` into `ResourceProvider` to limit recursion depth per type
- Added unit test
- Updated `SchemaPath` helper function to fix a bug that could make this function return early
> Make StructToSchema work for recursive data types

- exporter/context.go
- exporter/importables.go
- exporter/util.go
- exporter/util_test.go
Very often we emit resources that don't exist on the backend, and this creates incorrect resources without actual data. Typically this happens when objects are deleted but still referenced from jobs, dashboards, etc.
This PR skips the generation of resources where the `name` is the required attribute but it's empty in the state, meaning that resource doesn't exist on the backend.  This is done for the following resources:
* `databricks_sql_query`
* `databricks_sql_endpoint`
* `databricks_sql_alert
* `databricks_catalog`
* `databricks_schema`
* `databricks_volume`
* `databricks_sql_table`
* `databricks_registered_model`
> Exporter: Don't generate resources with empty names

- clusters/resource_cluster.go
- common/recursion_tracking.go
- common/reflect_resource.go
- common/reflect_resource_test.go
- This is a sub PR of https://github.com/databricks/terraform-provider-databricks/pull/3320
- Make `Aliases` function return a map of map which can derive aliases from the parent type name and field name.
- The goal is to avoid redundantly specifying the aliases in recursive data types such as the jobs for_each_task
- Also updating the `recursion_tracking.go` functions to make `getNameForType` more sharable
> Update Aliases function for ResourceProvider to handle recursive structures more gracefully

- clusters/resource_cluster.go
- clusters/resource_library.go
- common/reflect_resource.go
- Part of https://github.com/databricks/terraform-provider-databricks/pull/3320
- Add resource provider registry to avoid redundant alias and customization definitions
- Update `Library` resource to follow the ResourceProvider interface
> Add resource provider registry

- CONTRIBUTING.md
- README.md
- docs/guides/aws-e2-firewall-hub-and-spoke.md
- docs/guides/aws-e2-firewall-workspace.md
- docs/guides/aws-private-link-workspace.md
- docs/guides/aws-workspace.md
- docs/guides/azure-private-link-workspace-simplified.md
- docs/guides/azure-private-link-workspace-standard.md
- docs/index.md
- docs/resources/mws_workspaces.md
- docs/resources/permissions.md
- Change branch `master` to `main` in GitHub links
- Change raw links (for consistency with rest of repo)
- from: `https://github.com/databricks/terraform-provider-databricks/raw`
- to: `https://raw.githubusercontent.com/databricks/terraform-provider-databricks`
I manually clicked through each new link to make sure it works
Note on `docs/resources/permissions.md` --> `resource_permissions.go` link - this file no longer exists on main, and I decided to change from master to main anyway.  Here's permalink to last time I see this in commit history: https://github.com/databricks/terraform-provider-databricks/blob/41ea13b5605278c115dba30092d66c814d7c9791/access/resource_permissions.go#L261-L271
Maintainers, I'm glad to track down what that should be updated to.  Please lmk in comments
> [DOCS] change master to main & GH image raw links

- docs/resources/service_principal.md
- docs/resources/user.md
`disable_as_user_deletion` is a bit confusing for users. This PR updates the docs to make its behavior more obvious.
> Clarify disable as user deletion

- internal/acceptance/lakehouse_monitor_test.go
> Disable Lakehouse Monitoring integration tests on GCP

- vectorsearch/resource_vector_search_endpoint.go
- vectorsearch/resource_vector_search_endpoint_test.go
If we get an error while waiting for the endpoint creation we simply return that error.  But when we got a timeout, we didn't clean the endpoint and this led to the resource not being destroyed in the tests as the backend continued to provision it.
This PR deletes the vector search endpoint when we get a creation error during the wait phase. This behaviour is similar to the current behaviour of clusters.
> Delete Vector Search Endpoint when we get an error while waiting for creation

- internal/acceptance/group_test.go
- scim/resource_group.go
- scim/resource_group_test.go
Existing group names can now be modified via API without forcing new creation.
Closes #2578
Update data model for group's display_name to longer `force_new`. Modify corresponding unit tests and add acceptance tests.
> Allow changes to `display_name` of `databricks_group` resource without recreating a group

- catalog/resource_registered_model.go
- catalog/resource_registered_model_test.go
- docs/resources/registered_model.md
- internal/acceptance/registered_model_test.go
As a follow up from #2771, add support for `owner` attribute in `databricks_registered_model`
Also refactor unit tests to use Mocks
> Added `owner` attribute to `databricks_registered_model`

- docs/guides/experimental-exporter.md
- exporter/context.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/model.go
- exporter/model_test.go
- exporter/util.go
If UC objects, such as metastore, catalogs, schemas, volumes, etc. have an owner other than the current user, then it's impossible to create child objects during apply.  To mitigate this, the list of grants is expanded/changed to allow the creation of child objects by the identity who does the export (it's done only on the workspace level, and the same identity must be used when doing import).
TODOs:
- we need to discuss if we should use `ALL_PRIVILEGES` for catalogs/schemas/... vs. specific permissions like, `CREATE_SCHEMA` for catalogs, etc. @nkvuong What do you think?
- investigate if we can get the owner of the object, and don't add permissions if it's the current user - this may lead to increased API calls
> Exporter: modify grants for some UC objects to allow handling of other owners

- docs/guides/experimental-exporter.md
- exporter/importables.go
- exporter/importables_test.go
* `databricks_metastore` will be listed and emitted only on the account-level - it makes little sense to list metastores on the workspace level.
* `databricks_storage_credential` is listed only on the workspace level as we don't have a specific metastore ID on the account level.  Also, we don't have a simple way of importing new storage credentials on the account level - we need to have `metastore_id` as a part of the storage credential ID.
> Exporter: change listing behavior for metastore and storage credentials

- common/reflect_resource.go
- common/reflect_resource_test.go
Some APIs legitimately return empty objects in fields, but StructToData does not persist these objects (e.g. #3351). This is caused by a filter in collectionToMaps that removes data structures that don't have any non-optional fields or optional fields set to a non-empty/non-nil value.
This PR removes this check. I need to do a bit more work to verify the impact of removing this on the rest of the provider.
> Support persisting empty fields in StructToData

- catalog/resource_sql_table.go
- catalog/resource_sql_table_test.go
- internal/acceptance/sql_table_test.go
- Addresses https://github.com/databricks/terraform-provider-databricks/issues/3341
- Add support for update `ColumnInfo` fields by issuing `ALTER` commands
> Added support for updating columns in `databricks_sql_table` resource

- catalog/resource_catalog_workspace_binding.go
- catalog/resource_catalog_workspace_binding_test.go
- docs/resources/catalog_workspace_binding.md
- exporter/importables.go
During work on exporter, we found that the Read operation for this resource doesn't work when
it's used from scratch, so we needed to explicitly fill the TF state with data.   This
also doesn't allow to import of this resource.  This PR fixes the problem and uses data from
`Id` to retrieve all necessary information.
> Fix Read operation in `databricks_catalog_workspace_binding` so we can perform import

- docs/resources/job.md
Documentation change only. Improves the documentation regarding multiple upstream dependencies. This confused me as well as [my google result](https://community.databricks.com/t5/community-discussions/terraform-provider-problemi-in-creating-dependant-task/m-p/46515/highlight/true#M2145).
N/A
> Docs: Improve description of depends_on block

- internal/acceptance/metastore_assignment_test.go
The `databricks_metastore_assignment` tests race against one another. This PR adds our lock to ensure that they don't run in parallel.
> Add lock to `databricks_metastore_assignment` test

- docs/resources/job.md
Documentation only change. Improve the documentation of the library parameter.
It could however be argued that the Terraform implementation is also non ideal as it silently fails if you try to include more than one library per block instead of detecting it and raising an error
N/A
> Docs: Improve job library documentation

- docs/resources/lakehouse_monitor.md
- docs/resources/model_serving.md
- docs/resources/vector_search_endpoint.md
- docs/resources/vector_search_index.md
- provider/provider.go
- vectorsearch/resource_vector_search_endpoint.go
- vectorsearch/resource_vector_search_endpoint_test.go
- vectorsearch/resource_vector_search_index.go
- vectorsearch/resource_vector_search_index_test.go
This is initial work - right now things are blocked by errors in OpenAPI spec, and as result, Go SDK has incorrect structs. So we need to wait until spec is fixed
> Add support for Vector Search Indexes

- exporter/context.go
- exporter/context_test.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/model.go
- exporter/util.go
Now we can correct dependencies between some UC objects and their parent's grants in case if the owner of these objects is different than the current user and grants should be adjusted to provide a possibility to create sub-resources.
This fixes #3057
> Exporter: add support for generation of dependencies between resources

- go.mod
- go.sum
- jobs/resource_job.go
> Bump go-sdk version to 0.37.0

- docs/resources/model_serving.md
This PR is to rename `AWS Bedrock` to `Amazon Bedrock` in the doc, as part of a series of bedrock renaming efforts. Context: https://databricks.atlassian.net/browse/DOC-12764
> [MLOPS-717] Rename Amazon Bedrock

- aws/data_aws_crossaccount_policy.go
- docs/data-sources/aws_crossaccount_policy.md
- internal/acceptance/data_aws_crossaccount_policy_test.go
This data source is typically run in context of the account provider, so it couldn't instantiate a workspace client
This fixes #3421
> Use Account client in the `databricks_aws_crossaccount_policy` data source

- pipelines/resource_pipeline.go
- pipelines/resource_pipeline_test.go
This PR adds the `deployment` field to DABs. This will be used for DBU attribution and at some point in the future break-glass UI for DABs and Terraform.
OpenAPI changes are yet to go in, thus the structs are handwritten. Since this field is only meant for internal use we will not document it.
Unit test and manually.
For manual testing I created a pipeline with `deployment` set:
```
resource "databricks_pipeline" this {
name = "test-deployment"
library {
notebook {
path = "/abc"
}
}
deployment {
kind = "BUNDLE"
metadata_file_path = "/def/ghi"
}
}
```
And checked it's `GET` output:
```
shreyas.goenka@THW32HFW6T terraform-playground % curl --request GET "https://e2-dogfood.staging.cloud.databricks.com/api/2.0/pipelines/0bc2bb77-7a32-44ff-99e4-129c0245f158" \
--header "Authorization: Bearer …
```
> Add deployment field to the databricks_pipeline resource

- docs/resources/job.md
- jobs/resource_job.go
- FIxing issue: https://github.com/databricks/terraform-provider-databricks/issues/1585
- Right now the libraries are not ordered, this PR fixes the issue by removing `slice_set` tag
> Make libraries in `resource_job` `slice` instead of set

- docs/guides/aws-workspace.md
We didn't declare the default `databricks` provider, so the code from the guide won't work until we add explicit aliases to data sources
> Docs: Use correct provider alias in AWS E2 provisioning guide

- catalog/data_metastore.go
- catalog/data_metastore_test.go
- docs/data-sources/metastore.md
Sometimes it would be easier to fetch metastore information by a workspace region or by a metastore name compared to fetching metastore information by ID.  This PR adds ability to specify either `name` or `region` to perform a metastore lookup.
> Add lookup by name or region to `databricks_metastore` data source

- docs/resources/job.md
- exporter/importables.go
- jobs/resource_job.go
For notebook tasks it's now possible to specify `warehouse_id` to execute SQL notebooks on SQL warehouses.
This fixes #3414
> Added support for SQL Notebooks execution in `databricks_job`

- internal/acceptance/entitlements_test.go
- scim/data_group.go
- scim/resource_entitlement.go
- scim/resource_entitlement_test.go
- scim/resource_group.go
- scim/resource_service_principal.go
- scim/resource_user.go
- scim/scim.go
It seems that updating entitlements may not be working properly, see #1840. I think there might be some issue with the way that updates are being sent to Databricks. Here's an example from a test I've written in this PR:
```
024-04-04T18:39:26.412+0200 [DEBUG] databricks: PATCH /api/2.0/preview/scim/v2/Groups/234408399693172
> {
>   "Operations": [
>     {
>       "op": "remove",
>       "path": "entitlements",
>       "value": [
>         {
>           "value": "allow-cluster-create"
>         },
>         {
>           "value": "allow-instance-pool-create"
>         },
>         {
>           "value": "databricks-sql-access"
>         },
>         {
>           "value": "workspace-access"
>         }
>       ]
>     },
>     {
>       "op": "add",
>       "path": "entitlements",
> …
```
> Fix `databricks_entitlement` Update & Delete

- catalog/resource_sql_table.go
- internal/acceptance/account_rule_set_test.go
- internal/acceptance/catalog_test.go
- internal/acceptance/data_current_config_test.go
- internal/acceptance/init_test.go
- internal/acceptance/job_test.go
- internal/acceptance/metastore_test.go
- internal/acceptance/model_serving_test.go
- internal/acceptance/schema_test.go
- internal/acceptance/secret_acl_test.go
- internal/acceptance/sql_global_config_test.go
- internal/acceptance/storage_credential_test.go
- internal/acceptance/vector_search_test.go
This PR introduces two key improvements in the integration test library:
* `isAws()`, `isGcp()` and `isAzure()` can be used to determine whether the integration test runner is targeting a specific cloud.
* `loadWorkspaceEnv()`, `loadAccountEnv()`, `loadUcwsEnv()` and `loadUcacctEnv()` simplify loading a specific debug environment for integration tests that rely on environment variables before calling `workspaceLevel()`/`accountLevel()`/`unityWorkspaceLevel()`/`unityAccountLevel()` test helpers.
I've gone through the codebase and replaced usage of the confusing `CLOUD_ENV` variable with these helpers.
Additionally, I found several integration tests that are not running correctly due to their naming, which I've corrected.
> Clean up integration tests and expose helper functions for identifying cloud

- common/reflect_resource.go
- jobs/resource_job.go
- pipelines/resource_pipeline.go
- sql/resource_sql_alerts.go
- sql/resource_sql_query.go
https://github.com/databricks/terraform-provider-databricks/commit/602bff98b6f80720927a145a82b8bc371b7a7cde fixed an issue in `webhook_notifications` where the provider would fail if a user removed the last webhook notification of a particular type. However, this only applied at the job level, not at the task level.
This PR removes diff suppression on the webhook notifications at the task level. As part of this, it introduces a new pair of helper methods, `SchemaMap` and `MustSchemaMap`. These behave similarly to `SchemaPath` and `MustSchemaPath`. The latter two return the entry in the `map[string]*schema.Schema` for a particular field recursively, but if you need to get that field's schema, you need to subsequently inspect the `Elem` field and assert that its type is `*schema.Resource` …
> Fix suppress_diff for webhook notifications at the task level in `databricks_job`

- docs/guides/experimental-exporter.md
- exporter/importables_test.go
- exporter/util.go
Because these jobs could be deployed with DABs it makes little sense to export them into Terraform...
> Exporter: skip listing of jobs deployed with DABs

- exporter/importables.go
- exporter/importables_test.go
- exporter/util.go
Before this PR, when we list workspace objects we just emitted the corresponding object with just ID (path) -> this led to the need to call the `Read` operation on the resource that led to an additional `get-status` REST API call.  But `get-status` returns the same data that are returned by the `list` operation.  With this PR we generate resource data from object status data returned by the `list` - this decreases the number of REST API calls necessary to import a notebook (this is critical for handling workspaces with a huge number of notebooks and workspace files).
> Exporter: generate resource data from the object status obtained during the listing operation

- common/customizable_schema.go
- common/customizable_schema_test.go
- jobs/resource_job.go
- jobs/resource_job_test.go
This PR introduces the `SetSuppressDiffWithDefault` which allows us to suppress diff in one of the most common cases. The first use of it is for `run_if`.
When a `run_if` is not defined for a task, the platform assigns it a default of `ALL_SUCCESS`. This PR fixes the suppress diff behaviour to only suppress the diff if the platform returns the default value, and not suppress it in all cases.
This PR treats one of the symptoms of job tasks being reordered during diff computation, and tasks that do not have a run_if defined ending up with one in the final job.
Unit tests and manually. Task reordering during diff computation no longer incorrectly sets run_if.
> Only suppress diff for `run_if` when it is `ALL_SUCCESS`

- docs/resources/mws_private_access_settings.md
- mws/resource_mws_private_access_settings.go
- mws/resource_mws_private_access_settings_test.go
- `account_id` was not set correctly during creation, leading to failure during read
Closes #3409
> Fix `databricks_mws_private_access_settings` creation

- exporter/importables.go
- exporter/util.go
This includes:
* Don't try to emit directories for SQL objects if `directories` service isn't enabled
* Don't split/join strings to extract directory path - just do search from the right
> Exporter: improve emitting of directories

- internal/acceptance/service_principal_test.go
- internal/acceptance/user_test.go
- scim/resource_service_principal.go
- scim/resource_service_principal_test.go
- scim/resource_user.go
- scim/resource_user_test.go
The recent Go SDK upgrade caused a small regression for these test cases. If the home folder was never provisioned for the user/service principal, deleting with force_delete_home_dir should not cause deletion failures. Here, we only return the failure if the path deletion fails due to the folder not existing. The same logic is applied to repos.
> Fix `databricks_user` and `databricks_service_principal` integration tests

- jobs/resource_job.go
- jobs/resource_job_test.go
These new fields has been added to the API, and are required in the public preview of Serverless compute for notebooks and workflows.
> [JOBS-17558] Add environment and environment_key to job settings in terraform

- .gitignore
- internal/acceptance/entitlements_base_resources.go
- internal/acceptance/entitlements_test.go
The integration tests for `databricks_entitlements` are now failing. I believe this is caused by a race condition between `databricks_group` and `databricks_entitlements` resources. In practice, these resources should not be used at the same time; instead, you should the former when you need to define the group in TF and the latter if the group is defined externally to TF.
First, I've improved the test coverage for entitlements to cover all resource types (user, group, service principal). As part of this, I've rewritten the tests to manage the resources externally from Terraform's perspective, so there are no more race conditions. Because of this, I'm able to remove the other integration tests, including the flaky one.
> Fix integration tests for `databricks_entitlements`

- internal/acceptance/init_test.go
- internal/acceptance/job_test.go
TestUcAccJobRunAsMutations fails today in Azure because the run_as field must use the attribute matching the principal type. Azure tests are run using a service principal, and AWS tests are run using a user. Thus, we need to change the attribute accordingly.
This PR adds some helper method for determining whether we are authenticated as an SP or user, then uses that to choose the correct attribute to set when constructing the template for `run_as` in `databricks_job`.
> Fix TestUcAccJobRunAsMutations

- internal/acceptance/model_serving_test.go
Integration tests for model serving were failing due to a change in library support in DBR 15. Additionally, this test has had a history of flakiness and difficulty of maintenance due to the test training a model itself.
To address these points, I've made a model fixture called `experiment-fixture-model` that can be used for this model serving test. This should reduce test time by removing the need to start a cluster & train a model, as well as remove the dependency on the actual training process in this test.
Ran locally in Azure, and this passed.
> Improve integration tests for `databricks_model_serving`

- docs/index.md
We now support Databricks-managed service principals in all clouds and can use them to authenticate at account and workspace levels.
> Docs: update about using Databricks-managed service principals in all clouds

- test-config.yaml
This PR adds a test config to ignore test failures in `TestAccGroupsUpdateDisplayName`, which is currently flaky due to transient read-after-write inconsistencies.
> Add test config for ignoring failed integration tests

- exporter/util.go
When exporting permissions, error message contains just `deadline exceeded` instead of `context deadline exceeded` used by other services, so export of permissions didn't retry.
```
[ERROR] 2024-04-18T20:18:08.611476683Z: Error reading databricks_permissions#/notebooks/2370766168973066 after 0 retries: [{0 cannot read permissions: grpc_shaded.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 5000000000ns. []}]
```
> Exporter: adjust retry error on deadline exceeded

- catalog/data_current_metastore.go
- docs/data-sources/current_metastore.md
> data source `databricks_current_metastore` should not error out for non-UC workspaces

- CHANGELOG.md
- common/version.go
* Added resources for configuring Serverless network connectivity ([#3402](https://github.com/databricks/terraform-provider-databricks/pull/3402)).
* Data source `databricks_current_metastore` should not error out for non-UC workspaces ([#3497](https://github.com/databricks/terraform-provider-databricks/pull/3497)).
* Adjust retry error on deadline exceeded ([#3491](https://github.com/databricks/terraform-provider-databricks/pull/3491)).
* Added account workspace setting type ([#3415](https://github.com/databricks/terraform-provider-databricks/pull/3415)).
* Added test config ([#3487](https://github.com/databricks/terraform-provider-databricks/pull/3487)).
* Refactor `CustomizeSchema` for `ResourceProvider` to skip unfeasible customizations …
> Release v1.41.0

- docs/resources/job.md
- jobs/resource_job.go
- jobs/resource_job_test.go
When legacy tasks are used the `databricks_job` resource uses REST API 2.0 that doesn't support `parameters`.
> Added `ConflictsWith` to legacy tasks in `databricks_job` to avoid erors when job parameters are used

- docs/data-sources/current_metastore.md
- docs/guides/unity-catalog-default.md
I noticed that example codes provided in databricks_current_metastore docs aren't working - the data source name differs between definition and reference. Go tests use this data source correctly so it's only docs issue
I ran script with updated example code locally
> Fix databricks_current_metastore data source names in docs examples

- aws/data_aws_crossaccount_policy.go
- common/resource.go
- common/resource_test.go
The `databricks_aws_crossaccount_policy` and some other data sources really don't need any client to work, so they could be used with both account and workspace-level providers. To simplify things, the `common.NoClientData` was introduced, and the implementation `databricks_aws_crossaccount_policy` has changed to use it.
This fixes #3505
> Introduce `common.NoClientData` helper function and use it in `databricks_aws_crossaccount_policy` data source

- docs/data-sources/clusters.md
- docs/data-sources/sql_warehouses.md
> Docs: remove confusing mention of cloud types for `databricks_clusters` and `databricks_sql_warehouses` data sources

- provider/provider.go
- provider/provider_test.go
Support DATABRICKS_USER_AGENT_EXTRA environment variable.
It contains a list of products to add as extras to the user agent header. Product strings must follow RFC 9110, contain version numbers, and can't contain comments. E.g:
```
DATABRICKS_USER_AGENT_EXTRA="databricks-cli/0.1.2 my-project/0.0.1"
```
I added unit tests
> Add DATABRICKS_USER_AGENT_EXTRA

- catalog/resource_storage_credential.go
- catalog/resource_storage_credential_test.go
- The API marked `client_secret` field as sensitive and does not return it. We need to persist in the state manually
> Fix permanent drift for `azure_service_principal` in resource `databricks_storage_credential`

- catalog/data_metastore.go
- catalog/data_metastore_test.go
- docs/data-sources/metastore.md
In addition to filling `metastore_id` we set `id` to the same value
> Set `id` attribute of `databricks_metastore` data source

- exporter/importables.go
- exporter/importables_test.go
Instance pools must have a name, but sometimes the resource don't have it because an instance pool was used in the `databricks_job` but was deleted, keeping the reference in the job definition.
Fixes #3521
> Exporter: ignore instance pools with the empty name

- docs/resources/service_principal.md
- internal/acceptance/service_principal_test.go
- scim/resource_service_principal.go
- scim/resource_service_principal_test.go
We now allow to change display name of service principals, so we can remove `force_new` for it.
Fixes #3519
> Allow to change `display_name` for `databricks_service_principal`

- provider/provider.go
The SDK currently sets a default retry timeout of 5 minutes for all API requests. This is convenient for users who call APIs with contexts with no timeout or that can't be cancelled, like context.Background(). However, in Terraform, the context timeout is determined by a combination of instance-level timeouts, resource-level timeouts, and a default timeout of 20m.
This PR changes the provider to use an indefinite retry timeout for all API requests. This allows API calls to be retried for the entire length of the resource creation operation, e.g. in case there is a low rate limit for an API and the resources in question cannot all be created within 5 minutes.
> Retry API calls until context timeout

- docs/resources/job.md
Merge the separated job and task level sections of email_notifications and notification_settings into two unified sections. This limits copy pasting and makes it easier to navigate
Also move parameter section about notification sections
> [DOC] Squash job and task level sections to unified sections

- internal/acceptance/account_rule_set_test.go
- test-config.yaml
Recently, I observed a couple of issues with integration tests:
* TestMwsAccGroupDataSplitMembers and TestAccServicePrincipalResourceOnAws failed due to the API not responding with the correct information after update. I've added these to flaky tests.
* TestMwsAccAccountServicePrincipalRuleSetsFullLifeCycle failed flakily because we use no ETag, which as a result returns a stale version of the setting. I changed the check to use the ETag stored in TF state, which should ensure that the latest version of the setting is always returned.
> Stabilize integration tests

- aws/data_aws_crossaccount_policy.go
- aws/data_aws_crossaccount_policy_test.go
String with formatting wasn't passed to `fmt.Sprintf` resulting in the actual policy containing '%s' e.g. 'arn:aws:ec2:%s:%s:volume/*'. Passing the string to `fmt.Sprintf` results in the desired iam policy json.
> Update data_aws_crossaccount_policy to format resource string with account and region

- storage/mounts.go
- storage/mounts_test.go
> Fix error message typo in mounts.go

- docs/resources/job.md
Stating the different options available for run_if. Not sure about `ALL_FAIL` or `ALL_FAILED` to be honest, but perhaps this is a first step in the right direction.
> [DOC] State the options for run_if

- docs/guides/experimental-exporter.md
- exporter/context.go
- exporter/importables.go
- exporter/importables_test.go
Right now, if we discover any UC dependency, we emit upstream objects as well, such as schemas, catalogs, etc., but in their `Import` operations we're doing all nested objects unnecessarily - so emit one init script from a UC Volume may lead to emitting of the whole UC Catalog with all schemas/tables/volumes...
With this change, we list all nested objects (schemas in catalog, tables/models/volumes in a schema) only if these services are explicitly specified in the `-listing` option.
Fixes #3555
> Exporter: don't emit all UC objects when handling dependencies

- exporter/importables.go
- exporter/importables_test.go
- exporter/model.go
- exporter/util.go
- exporter/util_test.go
In the current implementation when TF resource data has `.id` set to an empty string this means the following:
* object doesn't exist on the backend - a common situation for jobs and DLT pipelines when dependencies are deleted.
* Grants or Permissions are empty, so we don't need to generate a code for that.
Right now, all such objects are tracked and reported individually via the `Ignore` function, but not all objects have it. Also, for big exports, unnecessary objects pollute the internal state without any useful effect.
The current PR checks if `.id` is empty during the `Emit` phase, adds them to the list of ignored objects (except permissions & grants), and doesn't propagate them to the internal state.
> Exporter: track removed objects during the `Emit` phase

- clusters/resource_cluster.go
- clusters/resource_library.go
- common/customizable_schema.go
- common/reflect_resource.go
- jobs/resource_job.go
- Make `typeToSchema` check and reuse information for registered resources in the `resourceProviderRegistry`
- Taking `Library` out of the registry because the only customization is not needed in other resources
- Migrating jobs resource schema to use the GoSDK schema
- Constructed resource provider with `CustomizeSchema` function that takes in all of the existing customizations
- Tried making the new schema as similar as possible to the original schema
- Updated the schema used in the resource as well as in `DataToStructPointer` and `StructToData` function calls
- Updated `resource_job_test`
- Adding `CustomizeSchemaResourceSpecific` function so that customizations don't always have to be shared for registry references
> Jobs GoSDK schema migration

- exporter/importables.go
- exporter/util.go
With this change we're generating resource data directly because we have all necessary information - this should decrease the number of REST API calls to SCIM API because the Read operation of `databricks_group_member` reads a group for each group member.
> Exporter: optimize generation of `databricks_group_member` resource

- exporter/command.go
The `uc-schemas`, `uc-models`, `uc-tables`, and `uc-volumes` services don't have explicit `List` operation, but we need to include them into the default listing so they will be exported in the default mode.
> Exporter: follow up for #3556 - we need to include some UC objects into default listing

- clusters/resource_cluster.go
- clusters/resource_cluster_test.go
- internal/acceptance/cluster_test.go
We earlier used to have only one spec that we used to pass for all the requests, after migration since we use different requests, we need to modify the fields for them as well. 
Fixes: https://github.com/databricks/terraform-provider-databricks/issues/3533 
Updated unit tests and integration test to check for this. Also, manually used this change (local binary) to run tf apply over test infra.
This wasn't caught in unit or integration test so there is a gap in our tests. The above step in integration test updates `autotermination_minutes` and this should repro this issue and changes should fix it. 
Integration test passes on PR and fail on main.
> Fixed Issue: The field `node_type_id` cannot be supplied when an instance pool ID is provided

- exporter/context.go
> Exporter: fix rare race condition with variables map

- catalog/resource_sql_table.go
- catalog/resource_sql_table_test.go
- docs/resources/sql_table.md
- internal/acceptance/sql_table_test.go
> Added owner support to `databricks_sql_table`

- catalog/data_catalog.go
- catalog/data_catalog_test.go
- docs/data-sources/catalog.md
- internal/acceptance/data_catalog_test.go
- provider/provider.go
It could be used to retrieve information about specific catalogs inside UC metastore.
> Add `databricks_catalog` data source

- catalog/data_table.go
- catalog/data_table_test.go
- docs/data-sources/table.md
- internal/acceptance/data_table_test.go
- provider/provider.go
- Add `databricks_table` data source. This should simplify use cases where customers need to retrieve a specific table for permissions granting & other purposes
> add `databricks_table` data source

- go.mod
- go.sum
This change bumps the version of the Databricks Go SDK to 0.40.1, including improved monitoring and telemetry for API requests.
> Bump Go SDK to 0.40.1

- CHANGELOG.md
- common/version.go
* Add owner support to `databricks_sql_table` ([#3570](https://github.com/databricks/terraform-provider-databricks/pull/3570)).
* Add `databricks_catalog` data source ([#3573](https://github.com/databricks/terraform-provider-databricks/pull/3573)).
* Add `databricks_table` data source ([#3571](https://github.com/databricks/terraform-provider-databricks/pull/3571)).
* Add `databricks_mlflow_experiment` data source ([#2389](https://github.com/databricks/terraform-provider-databricks/pull/2389)).
* Fix rare race condition with variables map ([#3568](https://github.com/databricks/terraform-provider-databricks/pull/3568)).
Dependency updates:
* Bump go SDK to 0.40.1 ([#3574](https://github.com/databricks/terraform-provider-databricks/pull/3574)), featuring improvements in tracing and …
> Release v1.44.0

- test-config.yaml
Adding another SCIM test that is flaky to the test-config.yaml to allow it to be ignored on failures.
> Add TestMwsAccServicePrincipalResourceOnAws to flaky tests

- common/reflect_resource.go
- common/reflect_resource_test.go
- As mentioned in this [thread](https://github.com/databricks/terraform-provider-databricks/pull/3564#issuecomment-2104175779), there is a bug with `collectionToMaps`
- The reason is that in `collectionToMap`, in the callback function we pass into `iterFields`, we are not handling the case where a list schema's Elem` is a `*schema.Schema`.
- This PR basically takes the [block](https://github.com/databricks/terraform-provider-databricks/blob/ff8f028786eb146887cace71b6781c892c42a25e/common/reflect_resource.go#L773-L778) in the callback function in `StructToData` into `collectionToMaps` 
- Tested by executing the failing unit test on the mentioned PR, verified it works
> Fix bug in collectionToMaps

- common/customizable_schema.go
- Make customizable schema error messages more readable by providing the entire path with prefix
- This made debugging much easier, as I encountered such cases myself during the jobs go-sdk migration
- Before: `[DEBUG] ConflictsWith skipped for driver_instance_pool_id, path contains TypeList block with MaxItems not equal to 1`
- After `[DEBUG] ConflictsWith skipped for jobs.job_settings.new_cluster.driver_instance_pool_id, path contains TypeList block with MaxItems not equal to 1`
> Make customizable error logs more readable

- docs/guides/experimental-exporter.md
- exporter/importables.go
- exporter/util.go
- exporter/util_test.go
Because directories don't have timestamps, we're ending up emitting all of them anyway...
Instead, rely on the behavior of them emitted as dependencies for notebooks
> Exporter: Don't list directories in the incremental mode

- jobs/resource_job.go
- jobs/resource_job_test.go
When changing a continuous job from status paused to unpaused, the Jobs service will trigger a run of the job after the update. To avoid race conditions between checking for the active run and updating the job, the TF provider always calls RunNow to ensure that a new run is triggered. However, this can race with the Jobs service's own trigger for the job. In this case, a 409 is returned indicating that there is a concurrent trigger for the job.
This PR tolerates this 409 response, allowing the job to be successfully updated, when the RunNow() API fails for this reason.
Unit tests cover this specific behavior.
> Fix control run state failures for `databricks_job` resource

- clusters/resource_cluster.go
Modify state upgrader to remove aws_attributes.ebs_volume_iops
Tested manually, I was able to modify the cluster after using the repro
```
resource "databricks_cluster" "shared_autoscaling" {
cluster_name            = "Shared Autoscaling"
spark_version           = data.databricks_spark_version.latest_lts.id
node_type_id            = data.databricks_node_type.smallest.id
autotermination_minutes = 20
aws_attributes {
availability     = "SPOT" # Change to SPOT_WITH_FALLBACK
ebs_volume_count = null
ebs_volume_size  = null
ebs_volume_type  = null
}
autoscale {
min_workers = 1
max_workers = 3
}
}
```
And changing "SPOT" to "SPOT_WITH_FALLBACK"
Resolves issue #3599
> Modify state upgrader to remove `ebs_volume_iops` set to zero

- docs/guides/azure-private-link-workspace-simplified.md
- docs/guides/azure-private-link-workspace-standard.md
> Docs: remove usage of deprecated `azurerm` options from PL guides

- clusters/resource_cluster.go
- common/reflect_resource.go
- docs/resources/job.md
- jobs/jobs_api_go_sdk.go
- jobs/resource_job.go
- jobs/resource_job_test.go
- jobs/resource_job_webhook_test.go
- Migrated `Read, Update, Create` methods to the go-sdk migration for the jobs resource
- Updated cluster related methods to accept `compute.ClusterSpec` as a valid input in `resource_cluster.go`
- Created `jobs_api_go_sdk.go` to replicate go-sdk versions of necessary methods that were part of `JobsApi`
- Updated jobs manually written schema to be consistent with the go-sdk schema, mostly taking out some `omitempty`
- Updated the `Read, Update, Create` methods to have two branches, if it's api2.0, make it run the exact same code as before, otherwise, use the go-sdk to perform the same actions
- Updated unit tests to include some missing fields that are newly marked as required, such as `task_key`
- Updated doc about schema changes
- Removed `autotermination_minutes` from the cluster spec …
> Jobs Methods GoSDK Migration 

- docs/resources/job.md
Remove table update trigger from `job.md` since this feature is only in private preview and we don't want customer outside of the private preview to know about it.
No needed
> Remove table update trigger from `job.md`

- clusters/resource_cluster.go
- internal/acceptance/cluster_test.go
- jobs/jobs_api_go_sdk.go
- jobs/resource_job.go
- Fixing issues mentioned: https://github.com/databricks/terraform-provider-databricks/issues/3599
- Removing unnecessary fields from force_send_fields when sending the update_cluster request
- Have to maintain these hacks for now, until we move to the new plugin framework, which will systematically address issue like this
- Updating jobs to also reference this function, remove the duplicated one
- Updating jobs error handling
- Added new integration test case in `cluster_test.go`
> Fix resource_cluster bug with ebs volume fields

- clusters/resource_cluster.go
- jobs/jobs_api_go_sdk.go
- Revert `RemoveUnnecessaryFieldsFromForceSendFields` from jobs and clusters resources, as we decided to revert https://github.com/databricks/terraform-provider-databricks/pull/3385
> Revert `RemoveUnnecessaryFieldsFromForceSendFields `

- clusters/resource_cluster.go
- clusters/resource_cluster_test.go
We always force send the local ssd count if gcp attribute is specified. 
Updated unit test
> Added `LocalSsdCount` in `GcpAttributes` to ForceSendFields for `databricks_cluster` resource

- docs/resources/mws_workspaces.md
- mws/resource_mws_workspaces.go
- mws/resource_mws_workspaces_test.go
This attribute simplifies references to the service account that is created together with workspace on GCP
> Added `gcp_workspace_sa` computed attribute to `databricks_mws_workspaces`

- docs/resources/job.md
> Clarify about trailing slash character in file arrival trigger URL in `databricks_job` resource

- clusters/clusters_api.go
- clusters/resource_cluster.go
- internal/acceptance/job_test.go
- jobs/jobs_api_go_sdk.go
- jobs/resource_job.go
- Addressing https://github.com/databricks/terraform-provider-databricks/issues/3632
- Always add `NumWorkers` into `ForceSendFields` if a cluster is non-autoscaling. Before the go-sdk migraiton, it wasn't an issue because `num_workers` was a required field
> Fix bug with job create zero values

- docs/resources/job.md
> [DOC] Clarify about `autotermination_minutes` in `databricks_job` clusters

- CHANGELOG.md
- common/version.go
* Added `gcp_workspace_sa` computed attribute to `databricks_mws_workspaces` ([#3617](https://github.com/databricks/terraform-provider-databricks/pull/3617)).
* Added `storage_credential_id` attribute to `databricks_storage_credential` resource ([#3636](https://github.com/databricks/terraform-provider-databricks/pull/3636)).
* Added `full_name` attribute to `databricks_system_schema` resource ([#3634](https://github.com/databricks/terraform-provider-databricks/pull/3634)).
* Fix SQL table column type throws error ([#3501](https://github.com/databricks/terraform-provider-databricks/pull/3501)).
* Add `aws_unity_catalog_assume_role_policy` data source ([#3622](https://github.com/databricks/terraform-provider-databricks/pull/3622)).
* Fix bug for job creation with `num_workers = 0` …
> Release v1.47.0

- .github/workflows/release.yml
GoReleaser was bumped to 2.0 recently and we didn't pin it.
The `--rm-dist` flag was removed in 2.0 so it no longer works.
n/a
> Use latest version of goreleaser action

- .github/workflows/codeql-analysis.yml
This fixes deprecation notices.
Also see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
n/a
> Update CodeQL actions to v3

- catalog/permissions/permissions.go
- catalog/resource_grant.go
- catalog/resource_grant_test.go
- catalog/resource_grants.go
- catalog/resource_grants_test.go
- internal/acceptance/grant_test.go
- internal/acceptance/grants_test.go
- Normalized privileges (make upper, replacing spaces with underscores), switched principal comparison to `EqualFold` to allow validation to complete.
- Added `DiffSuppressFunc` for `principal` attribute in `databricks_grant`
- Added customized hash function for Sets to avoid drifts
- Fixed #3654, #3566, #3261, #3313
- Superseded #3292
> Add customize diff for `databricks_grant` and `databricks_grants` for case insensitivity & spaces in grants

- jobs/resource_job_test.go
- Make sure all jobs tests use ApplyNoError or explicitly check the error.
- Fix the test that was failing due to improper HCL and api v2.1 usage.
- make test
- [N/A] relevant change in `docs/` folder
- [N/A] covered with integration tests in `internal/acceptance`
- [N/A] relevant acceptance tests are passing
- [N/A] using Go SDK
> Ensure jobs tests check for error

- clusters/resource_cluster.go
compute.InstallLibraries doesn't have Aliases and since it isn't local we can't add alias using Aliases(), to solve this we abstract out the compute.Library with alias and use it to while write to resource data
Fixes: https://github.com/databricks/terraform-provider-databricks/issues/3558
Created a cluster with library and used exporter on main branch which shows no library block reproducing the issue. After changes, libraries are shown.
> Fixed: Issue with `databricks_cluster` resource using `exporter` does not include cluster libraries

- access/resource_sql_permissions.go
- access/resource_sql_permissions_test.go
- docs/resources/sql_permissions.md
- Allowed shared clusters to be specified for `databricks_sql_permissions`
- Updated cluster creation to use `data_security_mode` instead of `spark_conf`
- Updated documentation
> Relaxed cluster check for `databricks_sql_permissions`

- jobs/resource_job.go
- jobs/resource_job_test.go
- Ordering is important, updating the library fields in jobs schema from set to list
- Previously it wasn't updated because during the go-sdk schema migration we wanted to minimize breaking schema changes
> Update jobs library fields from set to list

- docs/resources/cluster_policy.md
> Updated `databricks_cluster_policy` documentation

- catalog/resource_grant.go
- catalog/resource_grant_test.go
- catalog/resource_grants.go
- catalog/resource_grants_test.go
- internal/acceptance/grant_test.go
- internal/acceptance/grants_test.go
- Don't normalize principals to lower case, as group names are case sensitive
- Closes #3705
> Fixed case sensitivity for principals in `databricks_grants` and `databricks_grant`

- docs/resources/job.md
- internal/acceptance/job_test.go
- jobs/resource_job.go
- jobs/resource_job_test.go
- Add terraform support for periodic trigger for workflows. 
- New test added to validate periodic triggers.
```
➜  terraform-provider-databricks git:(periodic_triggers) ✗ CLOUD_ENV=aws go test -timeout 4800s -run ^TestAccPeriodicTrigger$ github.com/databricks/terraform-provider-databricks/internal/acceptance
ok  	github.com/databricks/terraform-provider-databricks/internal/acceptance	5.003s
```
> Add terraform support for periodic triggers

- docs/guides/aws-private-link-workspace.md
- docs/guides/unity-catalog-azure.md
- docs/guides/unity-catalog-gcp.md
- docs/index.md
- docs/resources/user.md
> Removed references to basic auth in Terraform documentation

- docs/resources/grants.md
Fixes the example docs so correct privileges are used when granting permissions on External Locations.
See https://docs.databricks.com/en/data-governance/unity-catalog/manage-privileges/privileges.html#privilege-types-by-securable-object-in-unity-catalog
N/A
> Fix invalid priviledges in grants.md

- exporter/context.go
- exporter/exporter_test.go
- exporter/importables.go
- exporter/test-data/run-job-child.json
- exporter/test-data/run-job-main.json
Because the `run_as` was marked as `computed` it was ignored when generating the code.
Fixes #3723
> Exporter: fix generation of `run_as` blocks in `databricks_job`

- catalog/resource_quality_monitor.go
- docs/resources/quality_monitor.md
This PR will resolve https://github.com/databricks/terraform-provider-databricks/issues/3691.
- Make the `schedule.pause_status` field read-only.
- Remove the description of the field from the documentation.
I locally confirmed that the `terraform plan` command no longer showed any change for the `schedule.pause_status` field.
> Make the schedule.pause_status field read-only

- .github/workflows/release.yml
- .goreleaser.yml
Running this action before doing an actual release should prevent situations like #3645 where it doesn't work on release.
See workflows.
> Run goreleaser action in snapshot mode from merge queue

- exporter/util.go
The exporter emitted directories even if they were specified only in `-services`, leading to the exporting of unnecessary objects.  To return to the behavior between 1.38 and 1.45, add `directories` to the `-listing`
> Exporter: Emit directories during the listing only if they are explicitly configured in `-listing`

- common/reflect_resource_plugin_framework.go
- common/reflect_resource_plugin_framework_test.go
- go.mod
As illustrated in the diagram, we need converter function between tfsdk and gosdk structs to support the plugin framework migration
This PR adds converter functions as well as related unit tests
> Add tfsdk <> gosdk structs converter functions and tests

- clusters/data_clusters.go
- internal/acceptance/data_clusters_test.go
This PR fixes a small regression introduced during the migration of the `databricks_clusters` resource to the Go SDK. That change accidentally made `cluster_name_contains` mandatory for this data source. This PR makes this field optional again.
Added integration tests to verify that we can optionally specify this field.
> [Fix] Make `cluster_name_contains` optional in `databricks_clusters` data source

- internal/acceptance/cluster_test.go
This ensures proper attribution in our test infrastructure.
> Add "Owner" tag to test cluster in acceptance test

- CHANGELOG.md
This updates the changelog for Release v1.48.3 that was done over the PR: https://github.com/databricks/terraform-provider-databricks/pull/3767 which will not be merged.
Release has been done: https://github.com/databricks/terraform-provider-databricks/releases/tag/v1.48.3
> [Internal] Updated Changelog for Release v1.48.3

- internal/acceptance/restrict_workspace_admins_test.go
This test requires the authenticated user to be an account administrator. Our non-UC test environments don't use identity federation and are therefore by definition not account admins.
Require a UC test environment to get around this limitation.
> [Fix] Integration test for restrict workspace admins setting

- internal/acceptance/sql_endpoint_test.go
This ensures proper attribution in our test infrastructure.
The same fix for clusters was applied in #3771.
> [Fix] Add "Owner" tag to test SQL endpoint in acceptance test

- exporter/context.go
- exporter/exporter_test.go
- exporter/importables.go
- exporter/model.go
- Always generate `enable_serverless_compute` attribute for `databricks_sql_endpoint` and `databricks_sql_global_config` - this is required when there is a mix of serverless & non-serverless SQL endpoints
- Don't generate `channel` when it's empty or is current
- Don't generate `tags` block when there are no tags
- Importable can define `ShouldGenerateField` function to specify if the code for a field should be generated even if it's `omitempty` and having the zero or default value.  This was required for generation of `enable_serverless_compute = false` that is marked as `omitempty`
Fixes #3758
> [Exporter] Improve code generation for SQL Endpoints

- internal/acceptance/sql_table_test.go
These properties showed up as diffs in integration tests, thus are new defaults on latest DBR.
> [Fix] Update properties for managed SQL table on latest DBR

- catalog/resource_sql_table.go
This property is automatically added if the SQL table uses `cluster_keys`.
I ran:
```sh
$ go test ./internal/acceptance -timeout 30m -v -run TestUcAccResourceSqlTable_Liquid
```
> [Fix] Ignore managed property for liquid clustering integration test

- common/reflect_resource_plugin_framework.go
- common/reflect_resource_plugin_framework_test.go
- Baisc functionality for `StructToSchema`, everything is `Optional` now
- Need to do:
- Implement equivalent for `CustomizableSchema`
- Make tfsdk structs contain information about optional and computed
- Handle recursive data types
> Implement basic functionality for StructToSchema

- docs/resources/mws_ncc_binding.md
- docs/resources/mws_ncc_private_endpoint_rule.md
- docs/resources/mws_network_connectivity_config.md
* Document missing `egress_conf` attribute - the information about `default_rules.azure_service_endpoint_rule` was incorrect
* Fix the name of NCC - we don't allow spaces in the name
> [Doc] Improve docs for Network Connectivity Config

- docs/guides/experimental-exporter.md
- exporter/exporter_test.go
- exporter/importables.go
This adds support for exporting of `databricks_dashboard` resource and dependencies.
Current limitations:
- No support for incremental mode
- List operation fails on big lists (not clear if it's a problem with API or Go SDK)
> [Exporter] Add support for exporting of Lakeview dashboards

- catalog/resource_metastore.go
- catalog/resource_metastore_test.go
- don't update `databricks_metastore` during creation if not required. This was previously done for account-level provider. Extend this to workspace-level provider
> [Fix] don't update `databricks_metastore` during creation if not required

- docs/resources/external_location.md
- docs/resources/storage_credential.md
> [Doc] Use correct names for isolation mode for storage credentials and external locations

- access/resource_sql_permissions.go
- access/resource_sql_permissions_test.go
- catalog/resource_sql_table.go
- catalog/resource_sql_table_test.go
- clusters/clusters_api.go
- clusters/clusters_api_sdk.go
- clusters/clusters_api_test.go
- clusters/data_spark_version.go
- clusters/data_spark_version_test.go
- clusters/data_zones.go
- clusters/data_zones_test.go
- common/resource.go
- exporter/exporter_test.go
- storage/gs_test.go
- storage/mounts.go
- storage/mounts_test.go
- storage/resource_mount_test.go
- storage/s3_test.go
- `LatestSparkVersionOrDefault` now returns 11.3 LTS, as 7.3 LTS is deprecated
- Refactored `databricks_zones` to Go SDK
- Refactored `databricks_spark_versions` to Go SDK. This refactoring require one additional change to `resource.go`:
- Add new method `WorkspaceDataWithCustomizeFunc` to allow customization of the data source schema
- Removed Spark versions related methods, as these have now moved to Go SDK. This requires migrating the function `LatestSparkVersionOrDefault` to a Go SDK method, which requires changing existing structs in Terraform provider to equivalent in Go SDK (`clusters.SparkVersionsList` to `compute.GetSparkVersionsResponse`, etc.)
> [Internal] Refactored `databricks_zones` and `databricks_spark_versions` data sources to Go SDK

- CHANGELOG.md
- common/version.go
* Fixed reading of permissions for SQL objects ([#3800](https://github.com/databricks/terraform-provider-databricks/pull/3800)).
* don't update `databricks_metastore` during creation if not required ([#3783](https://github.com/databricks/terraform-provider-databricks/pull/3783)).
* Clarified schedule block in `databricks_job` ([#3805](https://github.com/databricks/terraform-provider-databricks/pull/3805)).
* Use correct names for isolation mode for storage credentials and external locations ([#3804](https://github.com/databricks/terraform-provider-databricks/pull/3804)).
* Fix incomplete note in databricks_workspace_binding resource ([#3806](https://github.com/databricks/terraform-provider-databricks/pull/3806))
* Refactored `databricks_zones` and `databricks_spark_versions` data sources …
> [Release] Release v1.49.1

- docs/guides/experimental-exporter.md
- exporter/importables.go
- exporter/importables_test.go
- exporter/util.go
Switch to `databricks_workspace_binding` adds support for isolation mode on external locations and storage credentials.
> [Exporter] Generate `databricks_workspace_binding` instead of legacy `databricks_catalog_workspace_binding`

- exporter/exporter_test.go
- exporter/importables.go
- exporter/util.go
- emitting references to UC models
- emitting references to UC catalog and schema for auto-capture
- emitting secrets from environment variables and external models configuration
- generation of some required fields
- expanding test coverage
> [Exporter] Improve exporting of `databricks_model_serving`

- aws/data_aws_unity_catalog_policy.go
- aws/data_aws_unity_catalog_policy_test.go
- docs/data-sources/aws_unity_catalog_assume_role_policy.md
- docs/data-sources/aws_unity_catalog_policy.md
- docs/guides/unity-catalog.md
> [Fix] Corrected kms arn format in `data_aws_unity_catalog_policy`

- docs/resources/mlflow_webhook.md
- mlflow/resource_mlflow_webhook.go
This includes:
- `http_url_spec.secret`
- `job_spec.access_token`
> [Feature] Mark attributes as sensitive in `databricks_mlflow_webhook`

- catalog/resource_metastore_assignment.go
- catalog/resource_metastore_assignment_test.go
- docs/resources/metastore_assignment.md
The `Read` method on workspace level wasn't filling all attributes and this led to the configuration drift after import.
Fixes #3756
> [Fix] reading `databricks_metastore_assignment` when importing resource

- common/customizable_schema_plugin_framework.go
- common/customizable_schema_plugin_framework_test.go
- common/reflect_resource_plugin_framework.go
- common/reflect_resource_plugin_framework_test.go
- Added basic supports for CustomizableSchema
- Able to add, remove fields and navigate through the schema
- Feature support matrix: https://docs.google.com/document/d/1ofoLi9vlu-4L-89kBOYPbpOpPk0GZghZcC5SgnBH4ZM/edit#heading=h.wi3qt4pwk7q4
> Make CustomizableSchema work for Plugin Framework

- docs/data-sources/user.md
- scim/data_user.go
- scim/data_user_test.go
Add `active` attribute to `databricks_user` data source.
Resolves #3731 
Acceptance test and verified using the following code:
```
terraform {
required_providers {
databricks = {
source = "databricks/databricks"
}
}
}
profile = "<REDACTED>"
}
data "databricks_user" "this" {
user_name = "<REDACTED>"
}
output "user" {
value = data.databricks_user.this.active
}
```
Output:
```
❯ terraform apply
data.databricks_user.this: Reading...
data.databricks_user.this: Read complete after 1s [id=<REDACTED>]
Changes to Outputs:
+ user = true
```
> [Feature] Add `active` attribute to `databricks_user` data source

- common/client.go
- Use Go SDK to construct workspace client from account client, instead of manual replacement
- Closes #3734
> [Internal] Refactored `client.ClientForHost` to use Go SDK method

- catalog/resource_sql_table.go
- catalog/resource_sql_table_test.go
- docs/resources/sql_table.md
> [Fix] cluster key update for `databricks_sql_table` should not force new

- catalog/resource_metastore_data_access.go
- catalog/resource_storage_credential.go
- catalog/resource_storage_credential_test.go
- docs/resources/storage_credential.md
- internal/acceptance/storage_credential_test.go
- Updated the struct, and added necessary secret handling
- Resolves #3834
> [Feature] added support for `cloudflare_api_token` in `databricks_storage_credential` resource

- common/customizable_schema_plugin_framework.go
- common/customizable_schema_plugin_framework_test.go
- pluginframework/resource_quality_monitor.go
- Support `SetReadOnly` in `CustomizableSchema` for terraform plugin framework
> Support read only in plugin framework CustomizableSchema

- exporter/exporter_test.go
- exporter/importables.go
We need to skip model serving endpoints that serve foundational models because they are provided by Databricks and we don't have ability to create serving endpoint for foundational models.
> [Exporter] Don't export model serving endpoints with foundational models

- docs/data-sources/schema.md
- docs/resources/metastore_assignment.md
- Fixed typos in `databricks_schemas` data sources doc. Resolve #3849
- Clarified `default_catalog_name` attribute is deprecated. Resolve #3850
> [Doc] Fixed documentation for `databricks_schemas` data source and `databricks_metastore_assignment` resource

- pluginframework/resource_quality_monitor.go
- Part of making acceptance test pass: https://github.com/databricks/terraform-provider-databricks/pull/3841
- Update `ResourceQualityMonitor` to make it pass acceptance test
- Commented out adding two new fields temporarily because we need to have those fields in the tfsdk struct, otherwise `.get()` and `.set()` don't work
- Updated the target struct for `.get` calls to be `MonitorInfo` because terraform requires that to be consistent with the schema
- Added logic at the end of `Create` and `Update` to read the latest `monitorInfo` and set the state
> Update resource quality monitor in plugin framework

- .codegen/model.go.tmpl
- service/billing_tf/model.go
- service/catalog_tf/model.go
- service/compute_tf/model.go
- service/dashboards_tf/model.go
- service/iam_tf/model.go
- service/jobs_tf/model.go
- service/marketplace_tf/model.go
- service/ml_tf/model.go
- service/pipelines_tf/model.go
- service/provisioning_tf/model.go
- service/serving_tf/model.go
- service/settings_tf/model.go
- service/sharing_tf/model.go
- service/sql_tf/model.go
- service/vectorsearch_tf/model.go
- service/workspace_tf/model.go
- These enums have to be strings instead of the indirect types that they used to be, otherwise `.get` and `.set` does not work properly
- First part of making the acceptance test work as specified here https://github.com/databricks/terraform-provider-databricks/pull/3841
> Make tfsdk struct enums into types.String

- scim/resource_entitlement.go
- scim/resource_entitlement_test.go
- Populate missing ids when importing `databricks_entitlements` resource. Resolve #3856
> [Fix] Fixed read method of `databricks_entitlements` resource

- docs/guides/experimental-exporter.md
- exporter/exporter_test.go
- exporter/importables.go
- exporter/importables_test.go
This PR adds support for exporting of `databricks_vector_search_endpoint` and `databricks_vector_search_index` resources.
> [Exporter] Add support for Vector Search assets

- docs/guides/experimental-exporter.md
- docs/resources/notification_destination.md
- exporter/exporter_test.go
- exporter/importables.go
- exporter/util.go
Now we can export `databricks_notification_destination` resources.
Extended `databricks_job` to emit email notifications on the task level, and webhooks on job and task levels
> [Exporter] Add support for `databricks_notification_destination`

- exporter/importables.go
- exporter/importables_test.go
When we deploy resources with DABs it's expected that source code exists outside of the workspace, so we don't need to export it and related resources (libraries).
Fixes #3436
> [Exporter] Ignore DLT pipelines deployed via DABs

- docs/resources/permissions.md
- permissions/resource_permissions.go
- permissions/resource_permissions_test.go
- SQL warehouses supports specifying `IS_OWNER` permission and therefore requires the same workaround as jobs & pipelines.
- Resolves #3730
> [Fix] Automatically assign `IS_OWNER` permission to sql warehouse if not specified

- internal/acceptance/init_test.go
- internal/acceptance/quality_monitor_test.go
- Add two more test cases replicating existing test case for quality monitor resource, but for the plugin framework
- Manually executed the tests to make sure they are passing
- Taking out the manual read check at the end of each test step as suggested [here](https://github.com/databricks/terraform-provider-databricks/pull/3867#discussion_r1709278870) because the type casting for clients is causing issue for plugin framework tests
> Add quality monitor acceptance test for plugin framework

- exporter/exporter_test.go
- exporter/test-data/get-cluster-test2-response.json
- exporter/util_compute.go
The code that evaluated if field should be skipped or not, was incorrectly omitting zero value for `autotermination_minutes` attribute.
> [Exporter] Fix generation of `autotermination_minutes = 0`

- docs/resources/compliance_security_profile_setting.md
- settings/generic_setting.go
- settings/resource_compliance_security_profile_setting.go
- settings/resource_compliance_security_profile_setting_test.go
The `databricks_compliance_security_profile_workspace_setting` didn't have a `deleteFunc` defined and this lead to the crash when destroying the resource.  This PR fixes this issue in two places:
1. Adding explicit `deleteFunc` that will just print warning into the log
1. Checking that `deleteFunc` is not null in `workspaceSetting` and `accountSetting` implementations to avoid similar problems in the future.
Fixes #3675
> [Fix] Fix crash when destroying `databricks_compliance_security_profile_workspace_setting`

- docs/resources/permissions.md
Clarify that permissions on workspace objects (directories/files/notebooks) could be set either by path or by the object ID, and the import will use only object ID.
This should help with issues like #3882
> [Doc] Clarify setting of permissions for workspace objects

- exporter/util.go
This happens sometimes when reading notebooks so we need to retry it
> [Exporter] Add retry on "Operation timed out" error

- access/resource_ip_access_list_test.go
- catalog/resource_volume_test.go
- clusters/data_spark_version.go
- common/client.go
- common/client_test.go
- exporter/importables.go
- exporter/util.go
- go.mod
- go.sum
This PR bumps the Databricks SDK for Go to v0.44.0.
This version removes the Impl()/WithImpl() methods of the SDK. The cachedMe implementation is slightly dependent on this interface, so I changed how it is initialized to work with the new version of the SDK. Additionally, there were two tests depending on this and one line in the exporter. The tests are probably left-over from when the provider contained its own client implementation, but now that it uses the SDK's client for these resources, they can be removed. 
The only difference in schema is:
```
@ ["provider_schemas","registry.terraform.io/databricks/databricks","resource_schemas","databricks_cluster_policy","block","attributes","name","required"]
- true
@ ["provider_schemas","registry.terraform.io/databricks/databricks","resource_s …
```
> [Dependency] Bump databricks-sdk-go to 0.44.0

- docs/data-sources/notebook.md
- docs/resources/notebook.md
- workspace/data_notebook.go
- workspace/data_notebook_test.go
- workspace/resource_notebook.go
- workspace/resource_notebook_test.go
This unifies these resources/data sources with other workspace objects - it will be useful to support it as we adopt `/Workspace/...` paths in jobs and other resources
> [Feature] Add `workspace_path` attribute to `databricks_notebook` resource and data source

- common/util.go
- mws/resource_mws_permission_assignment.go
- mws/resource_mws_permission_assignment_test.go
- qa/testing.go
- test-config.yaml
- refactored `databricks_mws_permission_assignment` to Go SDK
- added `TestUcAccAssignGroupToWorkspace` to flaky tests
> [Internal] refactored `databricks_mws_permission_assignment` to Go SDK

- internal/acceptance/mws_network_connectivity_config_test.go
- internal/acceptance/sql_endpoint_test.go
- internal/acceptance/workspace_conf_test.go
TestAccSQLEndpoint and TestAccWorkspaceConfFullLifecycle are currently failing on `main`. The former fails in GCP because @ is not allowed in a tag, so I've replaced it with _at_. The latter fails because of some checks of capitalization which I've fixed in this PR.
Finally, TestMwsAccNetworkConnectivityConfig is failing on main but is a regression server-side. The test passed on commit 7a2fc352f77101b89c3692ab34c82606605cceed when it ran on August 8, but it now fails on the same commit.
Ran these integration tests locally, they pass.
> [Internal] Fix integration tests

- internal/acceptance/online_table_test.go
The TestUcAccOnlineTable test fails because it uses a SQL warehouse that does not have an owner tag, as required by policy for our internal accounts. This PR adds this tag.
Ran the test locally, and it passes.
> [Internal] Add tag for SQL warehouse used in Online Table tests

- CHANGELOG.md
- common/version.go
* Added `databricks_notification_destination` resource ([#3820](https://github.com/databricks/terraform-provider-databricks/pull/3820)).
* Added support for `cloudflare_api_token` in `databricks_storage_credential` resource ([#3835](https://github.com/databricks/terraform-provider-databricks/pull/3835)).
* Add `active` attribute to `databricks_user` data source ([#3733](https://github.com/databricks/terraform-provider-databricks/pull/3733)).
* Add `workspace_path` attribute to `databricks_notebook` resource and data source ([#3885](https://github.com/databricks/terraform-provider-databricks/pull/3885)).
* Mark attributes as sensitive in `databricks_mlflow_webhook` ([#3825](https://github.com/databricks/terraform-provider-databricks/pull/3825)).
* Automatically assign `IS_OWNER` permission …
> [Release] Release v1.50.0

- jobs/resource_job.go
The `TimeoutSeconds` field was shadowing the same field in the parent struct, but it wasn't filled, leading to the configuration drift.
Resolves #3878
> [Fix] Remove not necessary field in `databricks_job` schema

- go.mod
- go.sum
- main.go
Merging https://github.com/databricks/terraform-provider-databricks/pull/3719 in main branch before release.
Nightly tests are running...
> [Internal] Added support to use protocol version 6 provider server for SDK plugin

- exporter/exporter_test.go
- exporter/importables.go
- exporter/test-data/get-job-12.json
- exporter/util_workspace.go
Jobs, DLT and other services are switching to use paths starting /Workspace for all objects (notebooks, ...), not only for workspace files.  This PR improves handling of such objects in exporter.
Resolves #3195
> [Exporter] Better support for notebooks with /Workspace path

- internal/acceptance/init_test.go
- logger/logger.go
- logger/logger_test.go
- provider/provider.go
Go SDK doesn't contain valid context for terraform logger, due to this we get a nil logger from context: https://github.com/hashicorp/terraform-plugin-log/blob/main/tflog/provider.go#L40. 
We always use the context from terraform and ignore the one from Go SDK. 
`TF_LOG=TRACE terraform apply` won't print: https://github.com/databricks/databricks-sdk-go/blob/main/config/auth_default.go#L54 on main, prints it after change. Also tested manually for some debug statements.  
Ran integration tests and see debug logs.
> [Fix] Fixed logging for underlying Go SDK

- internal/pluginframework/tfschema/customizable_schema.go
- Addressed comments in https://github.com/databricks/terraform-provider-databricks/pull/3880
- Add CustomizableSchema for PluginFramework
> [Internal] Add CustomizableSchema for Plugin Framework

- dashboards/resource_dashboard.go
- dashboards/resource_dashboard_test.go
- docs/resources/dashboard.md
This makes behavior consistent with other workspace objects - notebooks, workspace files, etc.
I have the skeleton of the test for it, but it doesn't work because I can't mock the same API call two times with different return results
> [Feature] Automatically create `parent_path` folder if it doesn't exist

- Makefile
- clusters/resource_cluster.go
- commands/commands.go
- common/commands.go
- pipelines/resource_pipeline.go
- provider/provider_test.go
- qa/testing.go
- scim/resource_user_test.go
The old version (v0.4.0) is crashing when used with Go 1.23, so I was need to bump the version and fix new findings (use of `fmt.Errorf` instead of direct creation of errors from string).
> [Internal] Upgrade `staticcheck` to v0.5.1 to get Go 1.23 support

- clusters/resource_cluster_test.go
- common/client_test.go
- go.mod
- go.sum
- provider/provider_test.go
Bumps the Go SDK to latest version and fix some tests related to changes in:
- https://github.com/databricks/databricks-sdk-go/pull/1014
- https://github.com/databricks/databricks-sdk-go/pull/1021
Unit tests, nightly will run over release PR.
> [Internal] Bump Go SDK to v0.45.0

- internal/pluginframework/tfschema/customizable_schema_test.go
- internal/pluginframework/tfschema/struct_to_schema.go
- internal/pluginframework/tfschema/struct_to_schema_test.go
- Addressed comments in https://github.com/databricks/terraform-provider-databricks/pull/3893
- Adding `StructToSchema` and corresponding unit tests, as well as tests for `CustomizableSchema`
> [Internal] Add StructToSchema for Plugin Framework

- CHANGELOG.md
- common/version.go
* Automatically create `parent_path` folder if it doesn't exist ([#3778](https://github.com/databricks/terraform-provider-databricks/pull/3778)).
* Fixed logging for underlying Go SDK ([#3917](https://github.com/databricks/terraform-provider-databricks/pull/3917)).
* OPENAPI_SHA check ([#3935](https://github.com/databricks/terraform-provider-databricks/pull/3935)).
* Remove not necessary field in `databricks_job` schema ([#3907](https://github.com/databricks/terraform-provider-databricks/pull/3907)).
* Add AttributeBuilder for Plugin Framework schema ([#3922](https://github.com/databricks/terraform-provider-databricks/pull/3922)).
* Add CustomizableSchema for Plugin Framework ([#3927](https://github.com/databricks/terraform-provider-databricks/pull/3927)).
* Add StructToSchema for Plugin …
> [Release] Release v1.51.0

- CONTRIBUTING.md
- Makefile
- README.md
Remove mentions of Terraform versions earlier than 1.0
> [Doc] Document Terraform 1.0 as minimum version

- test-config.yaml
Vector Search endpoints has a regression with get after create. I've filed a ticket, linked in the comment of the test config, to ignore test failures for this test in the meantime.
> [Internal] Allow vector search tests to fail

- docs/guides/troubleshooting.md
Older versions of `terraform` may generate errors when using the newest provider. We ask users to upgrade to at least 1.0.0 to continue using the latest versions of Terraform.
> [Doc] Add troubleshooting guide for Provider "registry.terraform.io/databricks/databricks" planned an invalid value

- CHANGELOG.md
- docs/guides/troubleshooting.md
https://developer.hashicorp.com/terraform/plugin/mux/translating-protocol-version-5-to-6 indicates that 1.1.5 is the earliest supported version for protocol v6 providers using the v5->v6 upgrader. This PR updates the documentation to reflect that.
> [Doc] Update minimum supported terraform version to 1.1.5

- docs/resources/vector_search_endpoint.md
- docs/resources/vector_search_index.md
Changed Vector Search naming to official naming "Mosaic AI Vector Search", addressing #3280.
This does not cover instances of the term for the following cases:
> [Doc] Adopt official naming of Mosaic AI Vector Search

- docs/resources/dashboard.md
- docs/resources/job.md
- docs/resources/mws_credentials.md
- docs/resources/notification_destination.md
- docs/resources/permissions.md
Updated **`docs/resources/mws_credentials.md`** to reflect that `account_id` is deprecated from the `mws_credentials` resource and should be specifically added under a provider instance where `host = "https://accounts.cloud.databricks.com"`. Additionally, updated the code example to reflect this change. Ran `make fmt-docs`.
Closes [#3217](https://github.com/databricks/terraform-provider-databricks/issues/3217)
> [Doc] Resolves #3127: Remove deprecated account_id field from mws_credentials resource

- internal/acceptance/data_volumes_test.go
- internal/acceptance/quality_monitor_test.go
- internal/providers/pluginfw/common/common.go
- internal/providers/pluginfw/resources/qualitymonitor/resource_quality_monitor.go
- internal/providers/pluginfw/resources/volume/data_volumes.go
- Add integration tests for resource and data source introduced [here](https://github.com/databricks/terraform-provider-databricks/pull/3958)
- Small updates to `ConfigureDataSource` function to handle nil case
- In `data_volumes`, we don't support `computed` tf tag yet, so we need to do that in customizable schema
> [Internal] Add integration tests for volumes and quality monitor plugin framework

- clusters/resource_cluster.go
- clusters/resource_cluster_test.go
- docs/resources/cluster.md
- internal/acceptance/cluster_test.go
Added no_wait option for clusters to skip waiting to start on cluster creation
Fixes https://github.com/databricks/terraform-provider-databricks/issues/3837
Also required for https://github.com/databricks/cli/pull/1698
Manually run the following configuration to confirm everything works
```
data "databricks_node_type" "smallest" {
local_disk = true
}
data "databricks_spark_version" "latest_lts" {
long_term_support = true
}
resource "databricks_cluster" "shared_autoscaling" {
cluster_name            = "Andrew Nester TF Test"
spark_version           = data.databricks_spark_version.latest_lts.id
node_type_id            = data.databricks_node_type.smallest.id
autotermination_minutes = 20
autoscale {
min_workers = 1
max_workers = 50
}
no_wait = true
library {
pypi {
package = "fbprophet==0.6" …
```
> [Feature] Added `no_wait` option for clusters to skip waiting to start on cluster creation

- docs/resources/automatic_cluster_update_setting.md
- docs/resources/compliance_security_profile_setting.md
- docs/resources/enhanced_security_monitoring_setting.md
- settings/resource_automatic_cluster_update_setting.go
- settings/resource_automatic_cluster_update_setting_test.go
- settings/resource_compliance_security_profile_setting.go
- settings/resource_compliance_security_profile_setting_test.go
- settings/resource_enhanced_security_monitoring_setting.go
- settings/resource_enhanced_security_monitoring_setting_test.go
There was a problem that `databricks_automatic_cluster_update_setting` wasn't applied because `minutes` attribute was set to 0, and it wasn't sent in the JSON payload because it's marked as `omitempty` in the API.  After analysis, it was found that there are other places where we need to send data but the corresponding fields were marked as `omitempty`.
This PR includes following changes:
- in 3 resources force sending of boolean and numeric fields with 0 values
- add customize schema for `databricksenhanced_security_monitoring_setting`, `databricks_automatic_cluster_update_setting` and `databricks_enhanced_security_monitoring_setting` as fields are declared as required in documentation/API, but not enforced in Terraform because they are marked as `omitempty`
- expand documentation to …
> [Fix] Force send fields for settings resources

- common/resource.go
- exporter/importables_test.go
- sharing/data_share.go
- sharing/data_share_test.go
- sharing/data_shares_test.go
- sharing/resource_share.go
- sharing/resource_share_test.go
This PR is my first attempt at migrating the Share resource from using hand-crafted API calls to the Databricks Go SDK. I’ve updated the `Read` function to use the SDK’s `Get` method. Next, I’ll work on migrating the remaining CRUD operations. I’ve run the existing tests to ensure everything is still working as expected.
Update: also included Create & Update here, which makes the Share resource go through the Go SDK for all CRUD operations.
> [Internal] Migrate Share resource to Go SDK

- docs/resources/job.md
- jobs/resource_job.go
Make subscriptions optional for SqlAlertTask since it is optional in our API.
> [Fix] Make subscriptions optional for SqlAlertTask

- clusters/resource_library.go
- clusters/resource_library_test.go
- common/util.go
- common/util_test.go
- permissions/resource_permissions.go
We now don't return an error when reading a library that belongs to the cluster deleted outside of the Terraform.
Resolves #3679
> [Fix] Handle cluster deletion in `databricks_library` read

- internal/providers/pluginfw/resources/volume/data_volumes_test.go
- Moving the test file to be next to the data source definition
> [Internal] Move volumes test next to plugin framework data source

- docs/index.md
Update documentation regarding authentication with Azure-managed Service Principal using GITHUB OIDC.
> [Doc] Update documentation regarding authentication with Azure-managed Service Principal using GITHUB OIDC

- internal/acceptance/init.go
- internal/providers/pluginfw/resources/qualitymonitor/resource_quality_monitor.go
- internal/providers/pluginfw/resources/qualitymonitor/resource_quality_monitor_test.go
- Add `ImportState` method for `quality monitor` resource
- Make acceptance test infrastructure able to test importing behavior
- Add integration test for import state for quality monitor
> [Internal] Support import in acceptance test + adding import state for quality monitor

- internal/providers/pluginfw/converters/converters_test.go
- internal/providers/pluginfw/converters/go_to_tf.go
- internal/providers/pluginfw/converters/tf_to_go.go
I noticed few irregularities in converter functions while working on clusters plugin framework migration, creating a PR to address those: 
1. Typo in error message -- in `GoSdkToTfSdkStruct` we say: `tfsdk to gosdk struct conversion failure`. It should be `gosdk to tfsdk struct conversion failure`
2.  In `GoSdkToTfSdkStruct ` we don't specify destination value type but we do it in `TfSdkToGoSdkStruct`. 
3. Abstract the error message out to reduce redundancy 
4. Standardise similar types of error messages to be same so it's easier to maintain. 
Added unit tests.
> [Internal] Fix irregularities in plugin framework converter function errors

- clusters/data_clusters.go
- docs/data-sources/clusters.md
- internal/acceptance/data_clusters_test.go
Version 1.50 of the Terraform Provider featured an upgrade to the Go SDK affecting cluster listing. The new List Clusters API returns all terminated clusters in the last 30 days without a limit. This results in the list operation taking considerably longer for some workspaces, especially workspaces with many jobs where clusters are frequently created. This impacts the `databricks_clusters` data source, which can be slow.
This PR partially addresses this by adding support for `filter_by` to the `databricks_clusters` API. Filters expressed here are pushed to the server and result in fewer clusters being returned by the API. Users of this data source can specify a particular cluster state, cluster source, pinned status, or cluster policy ID to limit the number of clusters returned by the …
> [Feature] Add support for filters in `databricks_clusters` data source

- clusters/resource_cluster.go
- clusters/resource_cluster_test.go
If we get error or terminated cluster (after getting WaitGetClusterRunning in Create) then we permanently delete them. 
Unit tests
> [Fix] Permanently delete `ERROR` and `TERMINATED` state clusters if their creation fails

- exporter/importables.go
- exporter/importables_test.go
Don't generate `databricks_artifact_allowlist` when no `artifact_matcher` blocks are defined
> [Exporter] Ignore `databricks_artifact_allowlist` with zero `artifact_matcher` blocks

- docs/guides/authenticate-with-oidc.md
- docs/guides/azure-authenticate-with-oidc.md
- docs/guides/gcp-authenticate-with-oidc.md
To encourage users to follow best security practices, we recommend authenticating to Databricks using OIDC where possible. This PR introduces a guide for setting up OIDC from GitHub Actions and Azure DevOps when authenticating to Azure and GCP Databricks.
Currently, Databricks on AWS doesn't support OIDC authentication natively.
> [Doc] Add guide for OIDC authentication

- catalog/resource_online_table.go
- docs/resources/online_table.md
New attribute was added, but it wasn't marked as `computed` in the TF resource definition
> [Feature] Add computed attribute `table_serving_url` to `databricks_online_table`

- common/resource.go
- common/resource_test.go
- dashboards/resource_dashboard.go
- internal/acceptance/dashboard_test.go
Users may choose to include the `/Workspace` prefix in the `parent_path` attribute of a dashboard to unambiguously refer to the workspace file system. This prefix is not included in reads, triggering a recreate.
This change ignores this type of diff.
> [Fix] Ignore presence or absence of `/Workspace` prefix for dashboard resource

- internal/acceptance/budget_test.go
It looks like we have environment problem on CGP (manual tests are working), so let skip tests until we fix internal environments.
> [Internal] Skip Budget tests on GCP

- internal/acceptance/permissions_test.go
It seems like we need to specify the `serialized_dashboard` field to be able to create the dashboard. I have raised this concern with the responsible team. But for unblocking our integration tests we can specify this for now.
Integration Tests Passing
> [Fix] Fix Permissions Dashboard Test

- catalog/resource_online_table.go
- catalog/resource_online_table_test.go
We should set the id right after creation and before waiting for online table to be available. This is because in case when online table isn't available, we still should have that resource in the state.
Also the timeout has been increased to 2x (I am going to following up with online tables team for suitable timeout but since we have to do a release, going ahead with small time increase should be good) 
Note: We should add setting id right after creation for similar resources to CONTRIBUTING guide (which I will do in a separate PR)
Added unit test to check that pathway, id is set (which wasn't the case before)
> [Fix] Set ID for online table resource if creation succeeds but it isn't available yet

- CONTRIBUTING.md
Update the guide to give detailed information on how to navigate and get started with adding / migrating resources to plugin framework.
NA
> [Doc] Update CONTRIBUTING guide for plugin framework resources

- CHANGELOG.md
- common/version.go
* Add `databricks_budget` resource ([#3955](https://github.com/databricks/terraform-provider-databricks/pull/3955)).
* Add `databricks_mlflow_models` data source ([#3874](https://github.com/databricks/terraform-provider-databricks/pull/3874)).
* Add computed attribute `table_serving_url` to `databricks_online_table` ([#4048](https://github.com/databricks/terraform-provider-databricks/pull/4048)).
* Add support for Identity Column in `databricks_sql_table` ([#4035](https://github.com/databricks/terraform-provider-databricks/pull/4035)).
* Add Sufficient Network Privileges to the Databricks Default Cross Account Policy ([#4027](https://github.com/databricks/terraform-provider-databricks/pull/4027))
* Ignore presence or absence of `/Workspace` prefix for dashboard resource …
> [Release] Release v1.53.0

- catalog/resource_external_location.go
- catalog/resource_external_location_test.go
See linked issue for details
Resolves #4037, Resolves #4004
> [Fix] force send `read_only` in `databricks_external_location` when it's changed

- catalog/resource_storage_credential.go
- catalog/resource_storage_credential_test.go
It's similar to #4067 - the `read_only = false` wasn't sent for storage credentials as well
> [Fix] force send `read_only` in `databricks_storage_credential` when it's changed

- internal/providers/pluginfw/common/common.go
- internal/providers/pluginfw/common/common_test.go
- internal/providers/pluginfw/context/context.go
- internal/providers/pluginfw/context/context_test.go
- internal/providers/pluginfw/resources/cluster/data_cluster.go
- internal/providers/pluginfw/resources/library/resource_library.go
- internal/providers/pluginfw/resources/qualitymonitor/resource_quality_monitor.go
- internal/providers/pluginfw/resources/volume/data_volumes.go
Set `resource` and `data` context for each resource in their respective CRUD operations. Two methods are defined to make setting resources / datasources as default easier: `GetDatabricksProductionName` and `GetDatabricksStagingName`.
Note: Library update isn't supported and hence we shouldn't inject useragent there. 
Every resource has:
`````
ctx = pluginfwcommon.SetResourceNameInContext(ctx, resourceName)
w, diags := r.Client.GetWorkspaceClient()
resp.Diagnostics.Append(diags...)
if resp.Diagnostics.HasError() {
return
}
`````
We could avoid the repetition by creating a common base struct but since this is going to be autogenerated soon, I think it's fine to have these as is due to return statements / clarity of reading the code. 
Unit tests
> [Internal] Support adding context in resources and data sources

- internal/providers/pluginfw/resources/cluster/data_cluster.go
After https://github.com/databricks/terraform-provider-databricks/commit/bac842d603465ddbf3582e2dab2d9189c17e3113 , the autogenerated structures used for interacting with state/config/plan always use Lists for nested structures, even if there is only ever at most one, for compatibility with older versions of the TF provider. The cluster data source on the plugin framework is handwritten and also needs to be converted to use lists instead of a pointer as well.
Ran the `TestAccDataSourceClusterByID` and `TestAccDataSourceClusterByName` integration tests, which now pass.
> [Fix] Fix databricks_cluster_pluginframework data source

- .codegen/model.go.tmpl
This PR introduces changes to the TFSDK generator to support “effective fields” for server-provided values. When fields are marked with the new proto annotation `ServerProposedIfEmpty` (name pending final decision, until then the `computed` annotation is used to indicate these fields, while specific fields are excluded), the generator will create an additional computed field (e.g., `Effective<FieldName>`) and add two sync functions to ensure proper handling of user-provided and server-determined values.
```
type ResourceModel struct {
OriginalField    types.String `tfsdk:"original_field" tf:"optional"`
EffectiveField   types.String `tfsdk:"effective_field" tf:"computed"`
}
```
```
func (newState *ResourceModel) SyncEffectiveFieldsDuringCreateOrUpdate(plan ResourceModel) { …
```
> [Internal] Generate Effective Fields

- catalog/resource_online_table.go
- docs/resources/online_table.md
In a recent update to the GoSDK, a new field called `unity_catalog_provisioning_state` was added. This field changes values based on server decisions, so it's supposed to be marked as computed. This pull request sorts out that issue.
> [Fix] Mark unity_catalog_provisioning_state as ReadOnly

- docs/resources/job.md
- docs/resources/pipeline.md
`databricks_pipeline` already has this change and for `databricks_job` we need to merge Go SDK 0.49.0
> [Doc] Document `budget_policy_id` in `databricks_pipeline` and `databricks_job`

- internal/acceptance/workspace_conf_test.go
- workspace/resource_workspace_conf.go
Occasionally, support for configuration keys is removed from the GetStatus/SetStatus APIs used to manage workspace configuration. When this happens, users who depended on those keys are in a bad state. The provider queries for the values for each configuration by key in the Terraform state, but those keys no longer exist.
To work around this, this PR makes `databricks_workspace_conf` resilient to keys being removed. On the read path, the provider queries for the status of all keys in state. If any key is no longer valid, it is removed from the request and the request is retried. Setting the value for invalid configuration keys is not supported. When removing an unsupported configuration key, the provider resets the key to an original state (`false` or `""`). Failures to reset invalid keys …
> [Fix] Tolerate invalid keys in `databricks_workspace_conf`

- CHANGELOG.md
- common/version.go
* Add `databricks_registered_model` data source ([#4033](https://github.com/databricks/terraform-provider-databricks/pull/4033)).
* Add data source `databricks_notification_destinations` ([#4087](https://github.com/databricks/terraform-provider-databricks/pull/4087)).
* Fix databricks_cluster_pluginframework data source ([#4097](https://github.com/databricks/terraform-provider-databricks/pull/4097)).
* Mark unity_catalog_provisioning_state as ReadOnly ([#4116](https://github.com/databricks/terraform-provider-databricks/pull/4116)).
* Tolerate invalid keys in `databricks_workspace_conf` ([#4102](https://github.com/databricks/terraform-provider-databricks/pull/4102)).
* force send `read_only` in `databricks_external_location` when it's changed …
> [Release] Release v1.54.0

- internal/acceptance/permissions_test.go
> [Fix] Change repo used in test

- docs/guides/experimental-exporter.md
- exporter/command.go
- exporter/context.go
- exporter/exporter_test.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/util_test.go
- exporter/util_workspace.go
Move `databricks_workspace_file` to a separate service `wsfiles`, so we can list and export them separately from notebooks.  If you used `notebooks` in `-listing` or `-services` options, then you need to append `wsfiles` to these options.
> [Exporter] **Breaking change**: Move `databricks_workspace_file` to a separate service

- docs/data-sources/node_type.md
When used on Azure the `databricks_node_type` will search for VMs built on Azure Cobalt CPUs.
> [Doc] Clarify that `graviton` option of `databricks_node_type` could be used on Azure

- exporter/context.go
- exporter/importables.go
This change significantly improve performance of export for resources with big number of objects because we're starting to export objects as soon as we get first page with list of objects.  I.e., for Lakeview dashboards, the export time for ~10k dashboards went from 47 minutes down to 22 minutes.
Resolves #4119
> [Exporter] Use `List` + iteration instead of call to `ListAll`

- docs/resources/custom_app_integration.md
> [Doc] Fix argument in example for `databricks_custom_app_integration`

- docs/resources/job.md
- docs/resources/pipeline.md
- pipelines/resource_pipeline.go
The new `schema` attribute was added to support direct publishing mode.  Besides documentation we were need to add TF schema customization as it conflicts with the `target` attribute.
> [Feature] Handle `schema` attribute in `databricks_pipeline`

- docs/resources/alert.md
- docs/resources/job.md
- docs/resources/query.md
- internal/acceptance/alert_test.go
- internal/acceptance/permissions_test.go
- internal/acceptance/query_test.go
- internal/acceptance/sql_query_test.go
- internal/providers/sdkv2/sdkv2.go
- sql/resource_alert.go
- sql/resource_alert_test.go
- sql/resource_query.go
- sql/resource_query_test.go
- sql/resource_sql_query.go
- sql/resource_sql_query_test.go
This PR is built on top of #4051 which should be merged first.
The new resource uses the new [Queries API](https://docs.databricks.com/api/workspace/queries/create) instead of the legacy one that will be deprecated. Since the new resource has a slightly different set of parameters, it was decided to create a new resource and deprecate the old one.
This resource uses old TF SDK to be compatible with TF exporter (until #4050 is implemented).
TODOs:
- Need to discuss how to handle permissions - `sql_query` permissions look like working, but not sure if we should continue to use that API
- Support in the exporter will be in a separate PR
> [Feature] Add `databricks_query` resource instead of `databricks_sql_query`

- CHANGELOG.md
- common/version.go
* Add `databricks_alert` resource to replace `databricks_sql_alert` ([#4051](https://github.com/databricks/terraform-provider-databricks/pull/4051)).
* Add `databricks_query` resource instead of `databricks_sql_query` ([#4103](https://github.com/databricks/terraform-provider-databricks/pull/4103)).
* Added resource `databricks_custom_app_integration` ([#4124](https://github.com/databricks/terraform-provider-databricks/pull/4124)).
* Handle `schema` attribute in `databricks_pipeline` ([#4137](https://github.com/databricks/terraform-provider-databricks/pull/4137)).
* Change repo used in test ([#4122](https://github.com/databricks/terraform-provider-databricks/pull/4122)).
* Clarify that `graviton` option of `databricks_node_type` could be used on Azure …
> [Release] Release v1.55.0

- exporter/exporter_test.go
- exporter/importables.go
- exporter/importables_test.go
- Use `List` + iterator instead of waiting for full list - improves performance in big workspaces with a lot of DLT pipelines
- Better handling of pipelines deployed via DABs - fix error that lead to emitting of notebooks even for DLT pipelines deployed with DABs.
- Emit `databricks_schema` for pipelines with direct publishing mode enabled.
> [Exporter] Improve exporting of `databricks_pipeline` resources

- internal/acceptance/permissions_test.go
- permissions/permission_definitions.go
#4143 reported a regression to the `databricks_permissions` resource caused by https://github.com/databricks/terraform-provider-databricks/pull/3956. Normally, the ID for this resource when configured for a SQL warehouse is `/sql/warehouses/<ID>`. However, it seems like at some point in the past, some users may have had an ID of `/warehouses/<ID>`. It's possible that importing this resource worked like this: when calling the permissions REST API, whether using object type `sql/warehouses` or `warehouses`, the API returns permissions for the same resources:
```
15:13:01 DEBUG GET /api/2.0/permissions/sql/warehouses/<ID>
< HTTP/2.0 200 OK
< {
<   "access_control_list": [
<     {
<       "all_permissions": [
<         {
<           "inherited": false,
<           "permission_level": …
```
> [Fix] Tolerate `databricks_permissions` resources for SQL warehouses with `/warehouses/...` IDs

- docs/resources/grant.md
I found the mistakes in the doc: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/grant
so let me fix them 🙇
> [Doc] Fix `databricks_grant` regarding metastore_id description

- exporter/codegen.go
- exporter/context.go
I found in the large-scale testing that sometimes we don't handle emitting of the same resource reliably, and this may lead to generation of duplicate resources (very small amount, but still) - found this in a very specific case when notebooks were listed without directories.
This PR fixes this problem:
- by tracking if resource is already in importing queue
- detecting duplicates during code generation
It also may improve performance a bit (2-3%).
> [Exporter] Improving reliability of `Emit` function

- CHANGELOG.md
- common/version.go
* Recreate missing system schema  ([#4068](https://github.com/databricks/terraform-provider-databricks/pull/4068)).
* Tolerate `databricks_permissions` resources for SQL warehouses with `/warehouses/...` IDs ([#4158](https://github.com/databricks/terraform-provider-databricks/pull/4158)).
* Fix `databricks_grant` regarding metastore_id description ([#4164](https://github.com/databricks/terraform-provider-databricks/pull/4164)).
* Automatically trigger integration tests on PR ([#4149](https://github.com/databricks/terraform-provider-databricks/pull/4149)).
* **Breaking change** Use new query and alert resources instead of legacy resources ([#4150](https://github.com/databricks/terraform-provider-databricks/pull/4150)).
* Improve exporting of `databricks_pipeline` resources …
> [Release] Release v1.56.0

- catalog/resource_sql_table.go
- catalog/resource_sql_table_test.go
It was reported in #4098 that some of the specified options, like, `multiLine`, `recursiveFileLookup` and potentially more, aren't returned as `option.multiLine`, etc., but instead are expanded into full names, like, `spark.sql.dataSourceOptions.multiLine`.
This PR changes lookup logic a bit, and if we can't find `option.something`, then we're looking for all options ending with `.something` (only if there are no `.` in the name).
Resolves #4098
> [Fix] Handle edge case for `effective_properties` in `databricks_sql_table`

- clusters/clusters_api.go
- clusters/resource_cluster.go
- clusters/resource_cluster_test.go
- jobs/resource_job_test.go
A better error message is warranted because many DABs customers have reportedly run into this. Original issue: https://github.com/databricks/cli/issues/1546
Unit test
> [Fix] Provide more prescriptive error when users fail to create a single node cluster

- docs/data-sources/functions.md
- internal/providers/pluginfw/pluginfw.go
- internal/providers/pluginfw/resources/catalog/data_functions.go
It's now possible to fetch information about functions defined in a specific UC schema.
No integration test yet because we don't have `databricks_function` resource yet.
Resolves #4111
> [Feature] Added `databricks_functions` data source

- common/resource.go
- common/resource_test.go
This PR adds the ability for a resource to specify that it may not need to call `Read` after `Create` and `Update` operations so we can avoid performing another API call(s). The resource may implement `CanSkipReadAfterCreateAndUpdate` function that can decide if the `Read` operation should be skipped.
I decided to move common part from #4173 to make it easier to review
> [Internal] Make `Read` after `Create`/`Update` configurable

- CHANGELOG.md
- common/version.go
* Added `databricks_functions` data source ([#4154](https://github.com/databricks/terraform-provider-databricks/pull/4154)).
* Handle edge case for `effective_properties` in `databricks_sql_table` ([#4153](https://github.com/databricks/terraform-provider-databricks/pull/4153)).
* Provide more prescriptive error when users fail to create a single node cluster ([#4168](https://github.com/databricks/terraform-provider-databricks/pull/4168)).
* Add test instructions for external contributors ([#4169](https://github.com/databricks/terraform-provider-databricks/pull/4169)).
* Always write message for manual test integration ([#4188](https://github.com/databricks/terraform-provider-databricks/pull/4188)).
* Make `Read` after `Create`/`Update` configurable …
> [Release] Release v1.57.0

- clusters/data_cluster.go
- clusters/data_cluster_test.go
> [Fix] Always fill `cluster_name` in `databricks_cluster` data source

- CHANGELOG.md
- common/version.go
* Always fill `cluster_name` in `databricks_cluster` data source ([#4197](https://github.com/databricks/terraform-provider-databricks/pull/4197)).
* Suppress equal fold diff for DLT pipeline resource ([#4196](https://github.com/databricks/terraform-provider-databricks/pull/4196)).
* Upload content `databricks_workspace_file` using raw format ([#4200](https://github.com/databricks/terraform-provider-databricks/pull/4200)).
* Update to latest OpenAPI spec and bump Go SDK ([#4199](https://github.com/databricks/terraform-provider-databricks/pull/4199)).
* Bump github.com/golang-jwt/jwt/v4 from 4.5.0 to 4.5.1 ([#4191](https://github.com/databricks/terraform-provider-databricks/pull/4191)).
> [Release] Release v1.58.0

- aws/constants.go
- aws/data_aws_assume_role_policy.go
- aws/data_aws_assume_role_policy_test.go
- aws/data_aws_bucket_policy.go
- aws/data_aws_bucket_policy_test.go
- aws/data_aws_crossaccount_policy.go
- aws/data_aws_crossaccount_policy_test.go
- aws/data_aws_unity_catalog_assume_role_policy.go
- aws/data_aws_unity_catalog_assume_role_policy_test.go
- aws/data_aws_unity_catalog_policy.go
- aws/data_aws_unity_catalog_policy_test.go
- docs/data-sources/aws_assume_role_policy.md
- docs/data-sources/aws_bucket_policy.md
- docs/data-sources/aws_crossaccount_policy.md
- docs/data-sources/aws_unity_catalog_assume_role_policy.md
- docs/data-sources/aws_unity_catalog_policy.md
- Resolves https://github.com/databricks/terraform-provider-databricks/issues/4054
- Resolves https://github.com/databricks/terraform-provider-databricks/issues/4152
- Add optional argument `aws_partition` to all aws policy data sources to allow usage in all aws partitions
> [Feature] Add support partitions in policy data sources

- clusters/resource_cluster.go
- clusters/resource_cluster_test.go
- exporter/exporter_test.go
- internal/acceptance/cluster_test.go
Modify `setPinnedStatus` to use the clusters list API internally for determining the pinning status of a cluster. The existing implementation using the cluster events API subjects the resource to drift as events expire after a period of time.
Closes #3616 
* Coverage added to `TestResourceClusterCreate` and `TestResourceClusterCreatePinned`.
* Fixtures modified to mock the necessary API calls in all other relevant tests.
* `TestAccClusterResource_PinAndUnpin` acceptance test added
> [Fix] Use cluster list API to determine pinned cluster status

- clusters/clusters_api.go
- clusters/resource_cluster.go
- jobs/jobs_api_go_sdk.go
- jobs/resource_job.go
- jobs/resource_job_test.go
Fixes https://github.com/databricks/cli/issues/1896. Introducing this validation has caused a regression for both DABs and TF customers. This PR removes the validation for job clusters.
Unit tests.
> [Fix] Remove single-node validation from jobs clusters

- dashboards/resource_dashboard.go
- dashboards/resource_dashboard_test.go
If a dashboard created by TF was trashed out of band, it could no longer be deleted by TF.
Example TF configuration:
```hcl
terraform {
required_providers {
databricks = {
source = "databricks/databricks"
version = "1.58.0"
}
}
}
data "databricks_current_user" "me" {
// This data source is used to get the current user's username
}
resource "databricks_dashboard" "this" {
display_name = "Terraform test"
parent_path = "/Workspace/Users/${data.databricks_current_user.me.user_name}/tf-dashboard-oob-deletion"
warehouse_id = "58aa1b363649e722"
serialized_dashboard = file("nyc_taxi_trip_analysis.lvdash.json")
}
```
If you apply this, and then run:
```
databricks lakeview trash <dashboard id>
```
The subsequent apply would error out with:
```
Error: cannot delete dashboard: dashboard …
```
> [Fix] Fix deletion of dashboard if it was trashed out of band

- docs/resources/mws_ncc_private_endpoint_rule.md
NCC [now supports](https://learn.microsoft.com/en-us/azure/databricks/release-notes/product/2024/november#private-connectivity-from-serverless-compute-support-for-azure-managed-resources) connections to any Azure service that supports private link.  So update docs to point to corresponding documentation.
> [Doc] Update description of `group_id` in `databricks_mws_ncc_private_endpoint_rule`

- qa/testing.go
- qa/testing_test.go
- Make `ApplyAndExpectData` work with nested set, instead of just set of strings.
> [Internal] make `ApplyAndExpectData` work with nested set

- catalog/resource_catalog.go
- catalog/resource_catalog_test.go
- catalog/resource_registered_model.go
- catalog/resource_registered_model_test.go
- catalog/resource_schema.go
- catalog/resource_schema_test.go
- catalog/resource_volume.go
- catalog/resource_volume_test.go
Force sending of fields when `comment` is changing to empty value. Also, don't call Update API when the only change is in `force_destroy` attribute of schemas and catalogs
Resolves #4045
> [Fix] Correct handling of updates for empty comments and `force_destroy` in UC catalog, schema, registered models and volumes

- docs/guides/experimental-exporter.md
- exporter/exporter_test.go
- exporter/importables.go
Now we can list users and service principals directly, not only as groups dependency.
> [Exporter] Add `List` operation for `users` service

- docs/resources/grants.md
Commit fixes all the broken references in `grants.md`.
> [Doc] Update `grants.md` references

- vectorsearch/resource_vector_search_index.go
- vectorsearch/resource_vector_search_index_test.go
Change the wait condition from waiting for the index to be fully ready to either fully ready or started indexing.
Resolves #4144
> [Fix] Fix waiting for `databricks_vector_search_index` readiness

- dashboards/resource_dashboard.go
- dashboards/resource_dashboard_test.go
This is a follow-up to #4235, where the deletion of a trashed dashboard was fixed. This change treats trashed dashboards as deleted at read time, such that the resource shows up in the plan as new instead of a delete+create.
> [Fix] Treat trashed dashboard as deleted

- CHANGELOG.md
- common/version.go
* Add `databricks_mws_network_connectivity_config` and `databricks_mws_network_connectivity_configs` data source ([#3665](https://github.com/databricks/terraform-provider-databricks/pull/3665)).
* Add support partitions in policy data sources ([#4181](https://github.com/databricks/terraform-provider-databricks/pull/4181)).
* Added `databricks_registered_model_versions` data source ([#4100](https://github.com/databricks/terraform-provider-databricks/pull/4100)).
* Update databricks_permissions resource to support vector-search-endpoints ([#4209](https://github.com/databricks/terraform-provider-databricks/pull/4209)).
* add `databricks_serving_endpoints` data source ([#4226](https://github.com/databricks/terraform-provider-databricks/pull/4226)).
* Add validation for `run_as_mode` in …
> [Release] Release v1.59.0

- .github/dependabot.yml
It make sense to silence dependabot on Go SDK upgrades because we need to generate code from the OpenAPI spec and bump SDK SHA checksum.
> [Internal] Ignore Databricks Go SDK updates by dependabot

- docs/resources/mws_log_delivery.md
without this sleep, 
I faced the following error:
```log
02:58:20.315 STDERR tofu: │ Error: cannot create mws log delivery: Failed to perform putObject operations on s3Bucket:dbx-dev-logging-audit with deliveryPathPrefix:dbx-dev-logging-audit with the IAM Role:arn:aws:iam::577638361399:role/dbx-dev-logging-audit-delivery-role provided. Please add all required s3 actions as mentioned in API docs to role policy of your IAM Role.
02:58:20.315 STDERR tofu: │ 
02:58:20.315 STDERR tofu: │   with databricks_mws_log_delivery.audit_logs,
02:58:20.315 STDERR tofu: │   on main.tf line 42, in resource "databricks_mws_log_delivery" "audit_logs":
02:58:20.315 STDERR tofu: │   42: resource "databricks_mws_log_delivery" "audit_logs" {
```
Related issue: …
> [Doc] Update mws_log_delivery.md to add time_sleep

- catalog/resource_sql_table.go
- Switch the if else flow to prioritise the `warehouse_id` check
- Resolves #2992
> [Fix] don't start cluster if `warehouse_id` is specified for `databricks_sql_table` resource

- sql/resource_sql_endpoint.go
- sql/resource_sql_endpoint_test.go
- Forced send `auto_stop_mins` for `databricks_sql_endpoint` resource. This allows creating SQL warehouses with auto stop turned off
> [Fix] Forced send `auto_stop_mins` for `databricks_sql_endpoint` resource

- .codegen.json
This PR updates Terraform code generation by switching to the new "tf_v1" mode in genkit. Right now, it replicates the existing process, but a future PR will enable support for templating and automatic creation of new resources.
> [Internal] Use tf_v1 genkit mode

- clusters/resource_cluster.go
- internal/providers/pluginfw/products/library/resource_library.go
- internal/providers/pluginfw/products/library/resource_library_acc_test.go
When migrating the `databricks_library` resource to the Plugin Framework, some logic that handled missing clusters was unintentionally reverted. This PR adds (back) explicit handling for deleted clusters in `databricks_library` resources.
Resolves #4277.
Added an integration test that permanently deletes the cluster before running apply again. The cluster and library are then recreated.
> [Fix] Handle deleted cluster gracefully

- .codegen/model.go.tmpl
This PR is a follow-up to #4057 and #4112. We're shifting away from using the "computed" annotation to decide if a field should have "effective field" behavior. Instead, we're adopting the more precise "isServiceProposedIfEmpty" annotation. This lines up better with what we aim to achieve with effective fields, without making all regular computed and non-effective fields generate effective field code.
We'll only merge this once the relevant fields are updated accordingly in the OpenAPI spec.
> [Internal] Use isServiceProposedIfEmpty annotations for effective fields

- internal/providers/pluginfw/tfschema/attribute_builder.go
- internal/providers/pluginfw/tfschema/base_schema_builder.go
- internal/providers/pluginfw/tfschema/bool_attribute.go
- internal/providers/pluginfw/tfschema/customizable_schema.go
- internal/providers/pluginfw/tfschema/customizable_schema_test.go
- internal/providers/pluginfw/tfschema/float64_attribute.go
- internal/providers/pluginfw/tfschema/int64_attribute.go
- internal/providers/pluginfw/tfschema/list_attribute.go
- internal/providers/pluginfw/tfschema/list_nested_block.go
- internal/providers/pluginfw/tfschema/map_attribute.go
- internal/providers/pluginfw/tfschema/map_nested_attribute.go
- internal/providers/pluginfw/tfschema/single_nested_attribute.go
- internal/providers/pluginfw/tfschema/single_nested_block.go
- internal/providers/pluginfw/tfschema/string_attribute.go
- internal/providers/pluginfw/tfschema/struct_to_schema.go
Currently, our schema builder elements in the plugin framework components allow you to set Computed/Optional/Required/Sensitive fields on Block schema elements. However, these are simply dropped when converting to actual schema elements: only attributes have these fields. This PR moves the SetComputed/SetOptional/SetRequired/SetSensitive/SetReadOnly methods to the AttributeBuilder interface and panics if you attempt to set them on a block.
Added a unit test to verify that these methods panic when called on an element that is converted into a block.
> [Internal] Remove unused configuration from blocks

- catalog/resource_volume.go
- catalog/resource_volume_test.go
This PR adds validation that the value provided for `volume_type` is one of the correct values. The server today provides an incorrect error message:
```
10:30:10 DEBUG POST /api/2.1/unity-catalog/volumes
> {
>   "catalog_name": "main",
>   "name": "cli-volume",
>   "schema_name": "schema-dec-dabs",
>   "volume_type": "managed"
> }
< HTTP/2.0 400 Bad Request
< {
<   "details": [
<     {
<       "@type": "type.googleapis.com/google.rpc.ErrorInfo",
<       "domain": "unity-catalog.databricks.com",
<       "metadata": {
<         "field_name": "volume_type"
<       },
<       "reason": "INVALID_FIELD"
<     },
<     {
<       "@type": "type.googleapis.com/google.rpc.RequestInfo",
<       "request_id": "2ca7e630-ce06-4c85-ad95-9b3b52987009",
<       "serving_data": ""
<     }
<   ],
< …
```
> [Fix] Add client side validation for `volume_type`

- catalog/resource_credential.go
The same as in `databricks_storage_credential` - because Azure SP secret is sensitive value, it isn't returned by API, and we need to copy it from the previous state.
> [Fix] Remove config drift if Azure SP is used in `databricks_credential`

- CHANGELOG.md
- common/version.go
* Add `databricks_credential` resource ([#4219](https://github.com/databricks/terraform-provider-databricks/pull/4219)).
* Allow to filter jobs by name in `databricks_jobs` data source ([#3395](https://github.com/databricks/terraform-provider-databricks/pull/3395)).
* Add client side validation for `volume_type` ([#4289](https://github.com/databricks/terraform-provider-databricks/pull/4289)).
* Add missing H2 header in `mws_network_connectivity_configs.md` and optimization in `data_mws_network_connectivity_configs` ([#4256](https://github.com/databricks/terraform-provider-databricks/pull/4256)).
* Forced send `auto_stop_mins` for `databricks_sql_endpoint` resource ([#4265](https://github.com/databricks/terraform-provider-databricks/pull/4265)).
* Handle deleted cluster gracefully …
> [Release] Release v1.60.0

- internal/providers/pluginfw/tfschema/customizable_schema.go
Callers of `CustomizableSchema`'s methods can supply invalid paths. Currently, this returns an error, but this is never OK and should always be fixed before making any changes to a resource. Here, I change `navigateSchemaWithCallback` to panic if the supplied path does not exist.
> [Internal] Panic if the provided path is invalid

- internal/acceptance/account_rule_set_test.go
- internal/acceptance/budget_test.go
- internal/acceptance/catalog_test.go
- internal/acceptance/cluster_test.go
- internal/acceptance/credential_test.go
- internal/acceptance/custom_app_integration_test.go
- internal/acceptance/data_current_config_test.go
- internal/acceptance/data_mws_network_connectivity_config_test.go
- internal/acceptance/data_mws_network_connectivity_configs_test.go
- internal/acceptance/entitlements_test.go
- internal/acceptance/init.go
- internal/acceptance/job_test.go
- internal/acceptance/metastore_test.go
- internal/acceptance/model_serving_test.go
- internal/acceptance/mws_network_connectivity_config_test.go
- internal/acceptance/mws_workspaces_test.go
- internal/acceptance/permissions_test.go
- internal/acceptance/schema_test.go
- internal/acceptance/service_principal_test.go
- internal/acceptance/sql_global_config_test.go
- internal/acceptance/sql_permissions_test.go
- internal/acceptance/sql_table_test.go
- internal/acceptance/storage_credential_test.go
- internal/acceptance/vector_search_test.go
- internal/acceptance/workspace_conf_test.go
Plugin Framework resources may have integration tests that depend on some of the methods defined in `internal/acceptance/init.go`, namely the isAws/isGcp/isAzure functions, skipF, and load*Env functions. These are now exported and can be used by those integration test authors.
> [Internal] Expose several integration test helpers for use in plugin framework integration tests

- internal/providers/pluginfw/tfschema/customizable_schema.go
- internal/providers/pluginfw/tfschema/customizable_schema_test.go
- internal/providers/pluginfw/tfschema/list_nested_attribute.go
- internal/providers/pluginfw/tfschema/nested_attribute_object.go
Two small internal bugfixes in plugin framework support:
* ReadOnly() when applied to a list nested attribute should propagate recursively to all fields of the schema contained within the list.
* It should be possible to add a validator for a ListNestedBlock.
Added unit tests for the ReadOnly() logic.
> [Internal] Fix ReadOnly() for ListNestedAttribute and Validators for ListNestedBlock

- .github/PULL_REQUEST_TEMPLATE.md
To facilitate migration to plugin framework :-)
> [Internal] Added TF Plugin Framework checkbox item to PR template and removed checkbox for integration tests passing

- catalog/resource_metastore_data_access.go
- catalog/resource_storage_credential.go
- docs/resources/storage_credential.md
Previously, the `DatabricksGcpServiceAccount` type was defined as `any` and the led to the problems sending the Create request. Now this type is declared as struct, so we don't need the workaround anymore.
> [Internal] Simplify `databricks_storage_credential` code

- docs/resources/permissions.md
> [Doc] Add a warning that attribute should be used in `databricks_permissions` for `databricks_vector_search_endpoint`

- CHANGELOG.md
- common/version.go
* Add `databricks_app` resource and data source ([#4099](https://github.com/databricks/terraform-provider-databricks/pull/4099)).
* Add a warning that attribute should be used in `databricks_permissions` for `databricks_vector_search_endpoint` ([#4312](https://github.com/databricks/terraform-provider-databricks/pull/4312)).
* Added TF Plugin Framework checkbox item to PR template and removed checkbox for integration tests passing ([#4227](https://github.com/databricks/terraform-provider-databricks/pull/4227)).
* Expose several integration test helpers for use in plugin framework integration tests ([#4310](https://github.com/databricks/terraform-provider-databricks/pull/4310)).
* Fix ReadOnly() for ListNestedAttribute and Validators for ListNestedBlock …
> [Release] Release v1.61.0

- catalog/resource_credential.go
- docs/resources/credential.md
- internal/acceptance/credential_test.go
Right now, it's only possible to use it only with `purpose = "STORAGE"`.
> [Feature] Allow to use GCP SA in `databricks_credential` (storage only)

- docs/guides/experimental-exporter.md
- exporter/context.go
- exporter/exporter_test.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/util.go
- exporter/util_test.go
- exporter/util_workspace.go
- workspace/resource_notebook.go
> [Exporter] export `databricks_repo` for Git Folders outside of `/Repos`

- CHANGELOG.md
- common/version.go
* Allow to use GCP SA in `databricks_credential` (storage only) ([#4302](https://github.com/databricks/terraform-provider-databricks/pull/4302)).
* Support for databricks_credential in databricks_workspace_binding
* Bump Golang x/crypto to 0.31 ([#4319](https://github.com/databricks/terraform-provider-databricks/pull/4319)).
* Generate models with correctly computed annotations ([#4316](https://github.com/databricks/terraform-provider-databricks/pull/4316)).
* Update Go SDK to 0.54.0 ([#4328](https://github.com/databricks/terraform-provider-databricks/pull/4328)).
* Bump github.com/hashicorp/terraform-plugin-framework-validators from 0.15.0 to 0.16.0 ([#4320](https://github.com/databricks/terraform-provider-databricks/pull/4320)).
* Correctly handle DB-managed UC objects …
> [Release] Release v1.62.0

- test-config.yaml
Mark TestAccServicePrincipalResourceOnAzure test as flaky
> [Internal] Mark TestAccServicePrincipalResourceOnAzure test as flaky

- internal/providers/pluginfw/products/app/resource_app.go
- internal/providers/pluginfw/products/app/resource_app_acc_test.go
Following #4099, updates to Databricks Apps only reflected the ones in the plan, and not the ones coming back from the backend call to update the app. This PR includes those changes in.
> [Fix] Reflect backend updates in state for databricks_app

- common/retry.go
- common/retry_test.go
- permissions/resource_permissions.go
- permissions/resource_permissions_test.go
This PR adds logic to retry failed get calls to the permissions API when the error is a 504. This solution is meant to be temporary and will be removed as soon as such retries are handled natively in the Databricks Go SDK. 
Complete coverage of the added retrier.
> [Internal] Retry on 504 when calling the permission API

- CHANGELOG.md
- common/version.go
* Reflect backend updates in state for databricks_app ([#4337](https://github.com/databricks/terraform-provider-databricks/pull/4337)).
* Update `databricks_workspace_conf` documentation ([#4334](https://github.com/databricks/terraform-provider-databricks/pull/4334)).
* apply `make fmt-docs` to all docs ([#4344](https://github.com/databricks/terraform-provider-databricks/pull/4344)).
* Generate both SdkV2-compatible and Plugin Framework-compatible structures ([#4332](https://github.com/databricks/terraform-provider-databricks/pull/4332)).
* Mark TestAccServicePrincipalResourceOnAzure test as flaky ([#4333](https://github.com/databricks/terraform-provider-databricks/pull/4333)).
* Retry on 504 when calling the permission API ([#4355](https://github.com/databricks/terraform-provider-databric …
> [Release] Release v1.62.1

- docs/resources/job.md
> [Doc] Document job edit_mode

- catalog/resource_external_location.go
- catalog/resource_external_location_test.go
- docs/resources/external_location.md
- exporter/importables.go
To support the new feature, I switched to the use of Go SDK instead of a manually crafted structure.
Resolves #4369
> [Feature] Add `fallback` to `databricks_external_location`

- catalog/resource_credential.go
- catalog/resource_storage_credential.go
- internal/acceptance/credential_test.go
- internal/acceptance/storage_credential_test.go
This is a workaround for a problem in the API spec - right now, the Update operation tries to send the full struct, although the API accepts only one attribute of that struct.   For GCP we should omit the struct completely...
The problem doesn't exist for `storage_credential` on AWS as it uses the correct structure for the Update request, but problem exists for GCP.
Resolves #4335
> [Fix] Send only what is required in Update of `databricks_credential`

- docs/resources/sql_table.md
Added links to DBSQL SME blog that describe the schema evolution on Databricks.
Also run through grammar check
> [Doc] Add a note about schema evolution and `databricks_sql_table`

- docs/resources/permissions.md
- exporter/importables.go
There were missing references:
- permissions: model serving and vector search endpoints
- grants: service credentials
> [Exporter] Add references for missing permissions/grants types

- exporter/exporter_test.go
- exporter/importables_test.go
> [Internal] Disable `terraform fmt` in exporter to workaround build issues

- docs/resources/automatic_cluster_update_setting.md
- docs/resources/compliance_security_profile_setting.md
- docs/resources/enhanced_security_monitoring_setting.md
On Azure, enhanced security compliance and monitoring settings need to be enabled using the `azurerm_databricks` resource from the `azurerm` provider.
> [Doc] Add note about use of `azurerm_databricks` for enhanced security settings

- exporter/exporter_test.go
- exporter/impl_compute.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/test-data/clusters-list-response.json
- exporter/util_compute.go
This helps us with the following:
- use paginated output that is more efficient
- automatically filter non-interactive clusters instead of doing it ourselves
P.S. We still have usage of 2.0 API coming from mounts and some other places
> [Exporter] Use Go SDK to list clusters

- CHANGELOG.md
- common/version.go
* Add `fallback` to `databricks_external_location` ([#4372](https://github.com/databricks/terraform-provider-databricks/pull/4372)).
* Send only what is required in Update of `databricks_credential` ([#4349](https://github.com/databricks/terraform-provider-databricks/pull/4349)).
* Add `MANAGE` privilege to the relevant UC resources ([#4371](https://github.com/databricks/terraform-provider-databricks/pull/4371)).
* Add a note about schema evolution and `databricks_sql_table` ([#4352](https://github.com/databricks/terraform-provider-databricks/pull/4352)).
* Add description of `clean_rooms_notebook_task` in `databricks_job` ([#4368](https://github.com/databricks/terraform-provider-databricks/pull/4368)).
* Add docs for cluster attributes for clusters assigned to groups …
> [Release] Release v1.63.0

- .github/workflows/tagging.yml
- .package.json
- NEXT_CHANGELOG.md
- tagging.py
Introduce automated tagging.
* `tagging.py` script has been tested using mocks in a separate repository.
* `tagging.yml` can only be tested by executing a release. We will test this after merging and fix forward if needed.
> [Internal] Introduce automated tagging

- tagging.py
> [Internal] Account for historical release headers when filtering on past changelog sections

- docs/guides/unity-catalog-azure.md
The Queue Data Contributor role is required to support managed file events on Azure. This is already covered in the [Databricks user docs](https://learn.microsoft.com/en-us/azure/databricks/data-governance/unity-catalog/azure-managed-identities#grant-files), but not the terraform docs until now.
> [Doc] Added Queue Data Contributor role to Azure terraform docs

- mws/data_mws_workspaces.go
- mws/data_mws_workspaces_test.go
This PR fixes the `databricks_mws_workspaces` datasource to correctly return an empty list when no mws workspaces are configured. It would previously return a nil, which caused certain Terraform programs to misbehave.
For example this would error instead of correctly returning 0:
```
data "databricks_mws_workspaces" "example" {}
output "workspace_ids" {
value = data.databricks_mws_workspaces.example.ids
}
output "workspace_count" {
value = length(data.databricks_mws_workspaces.example.ids)
}
```
I've added a test similar to the existing tests for the mws_workspaces data source
> [Fix] mishandling empty response in `databricks_mws_workspaces` data source

- tokens/resource_obo_token.go
- tokens/resource_obo_token_test.go
The backend still returns a token if it's expired. This PR recreates OBO token when it's removed or expires.
Resolves #4427
> [Fix] recreate `databricks_obo_token` if it's removed/expired

- exporter/context.go
- exporter/context_test.go
- exporter/model.go
We may still have (theoretically) a race condition in `Add`/`Emit` operations due to the checks performed in separate functions, not directly in corresponding functions.  This PR should prevent that theoretical possibility.
> [Exporter] improve handling of Emit/Add operations under the heavy load

- docs/resources/token.md
- tokens/resource_obo_token.go
- tokens/resource_obo_token_test.go
- tokens/resource_token.go
- tokens/resource_token_test.go
This is similar to #4428, but for `databricks_token`.
> [Fix] Recreate `databricks_token` if it's not found or expired

- docs/guides/experimental-exporter.md
- exporter/exporter_test.go
- exporter/importables.go
- exporter/test-data/get-tokens-permissions.json
It was a missing functionality when we emitted all permissions on existing objects, but didn't do it for permissions of personal access tokens.
Resolves #4389
> [Exporter] Add listing for `databricks_permissions` so we can emit permissions for tokens

- CHANGELOG.md
- common/version.go
* Add `no_compute` attribute to `databricks_app` ([#4364](https://github.com/databricks/terraform-provider-databricks/pull/4364)).
* Skip calling Read after Create/Update operations for `databricks_notebook` ([#4173](https://github.com/databricks/terraform-provider-databricks/pull/4173)).
* Recreate `databricks_token` if it's not found or expired ([#4431](https://github.com/databricks/terraform-provider-databricks/pull/4431)).
* Handle empty response properly in `databricks_mws_workspaces` data source ([#4414](https://github.com/databricks/terraform-provider-databricks/pull/4414)).
* Recreate `databricks_obo_token` if it's removed or expired ([#4428](https://github.com/databricks/terraform-provider-databricks/pull/4428)).
* Added Queue Data Contributor role to Azure terraform docs …
> [Release] Release v1.64.0

- docs/resources/instance_profile.md
> [Doc] Fix attribute name in `databricks_instance_profile` examples

- internal/acceptance/data_clusters_test.go
- internal/acceptance/provider_test.go
- internal/providers/pluginfw/products/notificationdestinations/data_notification_destinations_acc_test.go
This PR fixes a few integration tests that fail because of parallel running.
- Give different names for each resource that is created.
- Modify the notification test to verify the presence of the newly created notification destination within the existing notification destination resources, rather than checking if it is the sole resource in existence.
> [Internal] Fix integration tests failing due to parallel running

- NEXT_CHANGELOG.md
- jobs/resource_job.go
> [Fix] Mark `task.spark_jar_task.run_as_repl` as `computed` to fix configuration drift

- .github/workflows/codeql-analysis.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
- .github/workflows/schema.yml
This is a small cleanup that reduces duplication of the go version used throughout our testing infra. The go version is defined in the `go.mod` once and used everywhere.
> [Internal] Use go-version-file to configure the go version in Github actions

- NEXT_CHANGELOG.md
- docs/resources/credential.md
- internal/acceptance/credential_test.go
As we started supporting service credentials on GCP, documentation should be updated to remove that `databricks_credential` could be used only with `purpose = "STORAGE"`.
Also, updated integration test to use `purpose = "SERVICE"`.
> [Doc] Remove mention that `databricks_credential` is storage-only on GCP

- NEXT_CHANGELOG.md
- catalog/resource_table.go
- docs/resources/sql_table.md
Some customers are confused about the inconsistent state of the `databricks_table` resource. It is not documented, but it is also not deprecated officially. This PR clarifies this by finally marking the resource as deprecated, as it has been replaced by `databricks_sql_table`. The documentation explains how to migrate from the old resource to the new.
> [Doc] Officially deprecate `databricks_table` and add migration instructions

- NEXT_CHANGELOG.md
- catalog/resource_external_location.go
- catalog/resource_external_location_test.go
I forgot to add `force_new` on the name of external location when I was switching to Go SDK structs in https://github.com/databricks/terraform-provider-databricks/pull/4372
Resolves #4466
> [Fix] Recreate `databricks_external_location` when its name changes

- NEXT_CHANGELOG.md
- pipelines/pipeline_test.go
- pipelines/resource_pipeline.go
A recent change to add support for `run_as` in pipelines causes pipeline update requests to include the `run_as` field. The Get Pipeline always returns the `run_as_user_name` for a pipeline, even for workspaces not in the private preview. Some users may have `run_as` in their TF state now, even if they did not specify it in their configuration. As we are using SDKv2 for this resource, it isn't straightforward to see whether the user actually included `run_as` in their configuration or if it is only in the state because of the change to the `Read` method.
This PR addresses this by only sending `run_as` if there is a planned change in the `run_as` field. If the user doesn't set `run_as` explicitly (as in existing customers not in the private preview), or if it is set to the same value as …
> [Fix] Do not send `run_as` when updating `databricks_pipeline` when not specified

- NEXT_CHANGELOG.md
- catalog/resource_catalog.go
The `options` field was previously not exposed in the REST API, so it was not possible for Terraform to update options for a catalog. This has now been added, so we can remove `force_new` from `options`.
> [Feature] Support updating `options` in `databricks_catalog`

- NEXT_CHANGELOG.md
- internal/providers/pluginfw/products/library/resource_library.go
Currently, `databricks_library` waits for 15m for libraries to install. We received a report that this was a bit too short for some use cases. For now, I'll bump this up to 30m to mitigate the issue faced by this customer.
The long-term plan to fix this should be based on adopting https://developer.hashicorp.com/terraform/plugin/framework/resources/timeouts in our provider.
I did not do any tests for this change.
> [Fix] Increase `databricks_library` installation timeout from 15m to 30m

- NEXT_CHANGELOG.md
- internal/providers/pluginfw/products/sharing/resource_acc_test.go
- internal/providers/pluginfw/products/sharing/resource_share.go
This PR fixes an issue where reordering objects in a (pluginfw) Share would fail unless other changes were made to the objects. The bug caused the new order to be ignored if no additional modifications were present. With this fix, reordering now correctly updates the Share, whether or not other changes are made.
> [Fix] Share Reordering Issue

- NEXT_CHANGELOG.md
- docs/guides/troubleshooting.md
Many customers regularly raise questions about timeouts within the TF provider and Databricks. This PR adds some documentation explaining the main kinds of timeouts, how to diagnose which timeout you've experienced, and how to adjust it if possible.
> [Doc] Timeout troubleshooting

- tagging.py
Remove prefix from github reference. 
GitHub API requires the full reference, but the PyGitHub library adds it automatically.
> [Internal] Remove prefix from github reference

- tagging.py
Fix relative path for tagging workflow
Run script locally (commenting the API calls)
```
Processing package 
adding file CHANGELOG.md
adding file NEXT_CHANGELOG.md
adding file common/version.go
adding file .release_metadata.json
```
> [Internal] Fix relative path for tagging workflow

- NEXT_CHANGELOG.md
- docs/data-sources/cluster.md
- docs/data-sources/clusters.md
We get periodic questions about how to use `databricks_cluster` and `databricks_clusters`, both around performance and errors with multiple clusters with the same name. This PR adds some examples and extra documentation about how to use these resources.
> [Doc] Improve documentation for databricks_cluster and databricks_clusters

- Makefile
0.5.1 doesn't work with Go 1.24
> [Internal] Upgrade `staticcheck` to compatible with Go 1.24

- docs/data-sources/cluster.md
The `ids` field is a set type, so you can't index into it. You can, however, convert it to a list first, then index into it.
Ran the following template locally, and this did not fail:
```hcl
data "databricks_clusters" "my_cluster" {
filter_by {
cluster_states = ["RUNNING"]
}
}
data "databricks_cluster" "my_cluster" {
cluster_id = tolist(data.databricks_clusters.my_cluster.ids)[0]
}
```
> [Doc] Small fix to docs for data source `databricks_cluster`

- NEXT_CHANGELOG.md
- exporter/impl_jobs.go
- exporter/importables.go
- exporter/util.go
- exporter/util_compute.go
- exporter/util_workspace.go
- workspace/resource_directory.go
- workspace/resource_notebook.go
- workspace/resource_workspace_file.go
During optimization of workspace objects handling we started to generate WS resources directly, but forgot to set properties like `workspace_path` that are used in the matching, so no references were generated (not critical, but still incorrect).  It did happen only when notebooks/directories were listed in the same execution.
Also refactored code a bit to avoid code duplicates, and improve matching.
> [Exporter] Fix matching on `workspace_path` and refactoring

- NEXT_CHANGELOG.md
- commands/commands.go
- go.mod
- mws/resource_mws_workspaces.go
Let's upgrade the version of go we use to latest, so we can take advantages of new language features like range expressions and the iter library.
Existing tests should cover this.
> [Dependency] Bump to 1.24.0

- NEXT_CHANGELOG.md
- sql/resource_sql_endpoint.go
- sql/resource_sql_endpoint_test.go
- If SQL warehouse is created but failed to start, we need to delete it to avoid failure in the next apply. Resolves #4496
> [Fix] Delete `databricks_sql_endpoint` that failed to start

- NEXT_CHANGELOG.md
- catalog/resource_metastore_assignment.go
- catalog/resource_metastore_assignment_test.go
- docs/guides/unity-catalog-azure.md
- docs/guides/unity-catalog-gcp.md
- docs/guides/unity-catalog.md
- Mark `default_catalog_name` attribute in `databricks_metastore_assignment` as deprecated, as `databricks_default_namespace_setting` should be used instead. 
- Resolves #4147
> [Fix] Mark `default_catalog_name` attribute in `databricks_metastore_assignment` as deprecated

- internal/providers/pluginfw/products/sharing/data_shares_acc_test.go
When multiple integration tests are running in parallel, the count of `databricks_shares_pluginframework` data sources will change. This means tfplan is not clean and the test fails
```
Changes to Outputs:
~ shares = 6 -> 4
```
We should inspect tf state instead of the output.
> [Internal] fix `TestUcAccDataSourceShares` flakiness

- NEXT_CHANGELOG.md
- catalog/catalog_test.go
- catalog/resource_catalog.go
- internal/acceptance/init.go
There was a misunderstanding with the Unity Catalog API in connection with https://github.com/databricks/terraform-provider-databricks/pull/4476. Apparently, only `authorized_paths` is eligible for update in the UC Catalog API. Otherwise, any other changes to `options` must trigger resource recreation.
This PR customizes the logic of `databricks_catalog` to do this. To be specific:
* `CustomizeDiff` marks the `options` field as `ForceNew` if there is a key other than `authorized_paths` which was updated.
* The `Update` command removes any options that aren't `authorized_paths`. This might be the case in the future if other options are added for HMS catalogs that can be set at create time but not updated.
* The `Create` command removes any options from the `UpdateCatalog` RPC.
Added two …
> [Fix] Only allow `authorized_paths` to be updated in the `options` field of `databricks_catalog`

- catalog/quality_monitor_test.go
This PR removes parallelism in the quality monitor test. Currently, we create multiple databricks_sql_table concurrently, which causes the following error: `[OCC check failure] Entity proto at /metastores:<metastore_id> may have been updated during the transaction`.
> [Internal] Fix Quality Monitor test by removing parallelism

- NEXT_CHANGELOG.md
- docs/resources/grants.md
- Add a note on how `databricks_grants` work with `MANAGE` permission
> [Doc] add clarification note for `databricks_grants`

- NEXT_CHANGELOG.md
- catalog/resource_system_schema.go
- catalog/resource_system_schema_test.go
- catalog/system_schema_test.go
- docs/resources/system_schema.md
- Handle new error message `billing system schema can only be enabled by Databricks`. Resolves #4539
- Update documentation with warnings about auto-enabled system schemas.
- Enable system schema integration test on GCP
> [Fix] handle auto-enabled errors with`databricks_system_schema`

- NEXT_CHANGELOG.md
- catalog/resource_credential.go
- catalog/resource_storage_credential.go
> [Fix] Fix creation of `databricks_storage_credential` and `databricks_credential` resources on GCP with isolation mode

- test-config.yaml
With https://github.com/databricks/terraform-provider-databricks/pull/4597, we found that the clusters and instance pools permissions APIs were simply taking longer than a minute to respond to APIs, exceeding the server-side timeout. Because of this, these tests fail irrecoverably. For now, we can ignore these test failures. In parallel, we will investigate the reason for these APIs exceeding their server-side timeout.
> Tolerate test failures for permissions APIs

- NEXT_CHANGELOG.md
- exporter/exporter_test.go
- exporter/util.go
- exporter/util_test.go
The cluster policy is supposed to use `string` type for `value` and `defaultValue` fields of the cluster policy, so explicit cast was done in the code. But it caused the crash when reading an incorrectly specific cluster policy (the user error).  This PR checks if interface type is correct before casting
> [Exporter] Fix panic caused by incorrect values in the cluster policies

- NEXT_CHANGELOG.md
- exporter/importables.go
Also, remove reference to unsupported resources in `databricks_mount`.
> [Exporter] Fix incorrect reference to model serving endpoint

- serving/resource_model_serving.go
- serving/resource_model_serving_test.go
Importing model serving with empty config should not throw `Error: cannot read model serving: panic: runtime error: invalid memory address or nil pointer dereference`
> [Fix] Reading model serving endpoint with no config

- permissions/permissions_test.go
- sql/sql_dashboard_test.go
https://docs.databricks.com/aws/en/sql/user/dashboards/ describes how legacy dashboards are no longer creatable via the API from April 7. This will cause our integration tests to start failing. For now, we will disable legacy dashboard testing in the provider. Later, once legacy dashboards are completely unsupported, we can remove them from the provider.
> Disable legacy SQL dashboard tests in GCP

- NEXT_CHANGELOG.md
- test-config.yaml
GCP workspace creation has been unstable due to stale resource cleanups such as policy limit, VPC limits, firewall limits etc.. We are marking them as flaky to have a stable infrastructure. 
N/A
> [Internal] Add `TestMwsAccGcpWorkspaces` to flaky test

- mws/mws_networks_test.go
- mws/mws_workspaces_test.go
GKE-based GCP workspaces are no longer supported, and all newly created workspaces are backed by GCE. The current GKE-based network and workspace tests can race because it is forbidden to use the same IP ranges in two different networks. As that feature is deprecated, we should be safe to simply remove these tests entirely.
Resolves #4618
N/A.
> Remove GKE test cases from databricks_mws_workspaces and databricks_mws_networks

- workspace/data_directory_test.go
- workspace/resource_directory_test.go
- workspace/resource_global_init_script_test.go
- workspace/resource_workspace_file_test.go
> [Internal] Move some tests from HTTPFixture to Go SDK mocks

- common/constants.go
- common/version.go
The constants in `version.go` are being moved to the internal repository. However, we need to maintain control over the dynamic versioning aspect through the public tagging process. This pull request separates the constants from `version.go` and transfers them to `constants.go`, which will also move to the internal repository. The version-related components will remain in `version.go`, allowing the public tagging process to continue incrementing versions as needed.
> [Internal] Split Constants Outside Version File

- .github/workflows/release.yml
https://github.com/databricks/terraform-provider-databricks/actions/runs/14443278474 shows that the release workflow is currently failing after my changes to publish the correct release notes. This seems to be due to an issue with the process substitution recommended at https://goreleaser.com/customization/release/#gitea, maybe to do with github actions behavior. Here, I've modified the process to configure the goreleaser arguments in a separate step.
Ran the if/else parts on my own machine with the `github.ref` interpolated.
> Set release notes in a separate step during the release workflow

- docs/resources/access_control_rule_set.md
Because of the missing new line, the warning note isn't rendered correctly
> [Doc] fix warning markup in  `databricks_access_control_rule_set` docs

- NEXT_CHANGELOG.md
- docs/resources/sql_alert.md
- docs/resources/sql_dashboard.md
- docs/resources/sql_query.md
- sql/resource_sql_dashboard.go
Also added corresponding warnings to documentation for `sql_query` and `sql_alert`
> Mark `databricks_sql_dashaboard` as deprecated

- NEXT_CHANGELOG.md
- docs/guides/experimental-exporter.md
- exporter/exporter_test.go
- exporter/impl_scim.go
- exporter/util_scim.go
- scim/scim.go
When Unity Catalog metastore is attached to a workspace, the Identity Federation is enabled on it.  With Identity Federation users, service principals, and groups are coming from the account level via assignment to a workspace.  But there is still an ability to create workspace-level groups via API, and the `databricks_group` resource uses it and always creates workspace-level.  As a result, we shouldn't generate resources for account-level groups because they will be turned into workspace-level groups.  Due to the limitations of APIs, we can't use `databricks_permission_assignment` on the workspace level to emulate the assignment.
See further explanation in the doc
> [Exporter] Correctly handle account-level identities when generating the code

- NEXT_CHANGELOG.md
- exporter/importables.go
The lack of `Ignore` led to the situation when we added a `depends_on` on grant and grants list was empty, but the reference wasn't removed from `depends_on` list because we didn't have `Ignore` implementation.
Resolves #4025
> [Exporter] Add `Ignore` implementation for `databricks_grants` to fix issue with wrongly generated dependencies

- catalog/data_current_metastore_test.go
- catalog/data_metastores_test.go
- catalog/data_tables_test.go
- catalog/data_views_test.go
- catalog/data_volumes_test.go
- catalog/resource_catalog_workspace_binding_test.go
- jobs/data_jobs_test.go
- mlflow/data_mlflow_experiment_test.go
- mlflow/data_mlflow_model_test.go
> [Internal] Move some tests from HTTPFixture to Go SDK mocks, part 2

- NEXT_CHANGELOG.md
- exporter/impl_uc.go
- exporter/impl_uc_test.go
- exporter/importables.go
Changes include emitting of `owner` for UC resources and handling dependencies to corresponding users/SPS/groups.
> [Exporter] Improve handling of `owner` for UC resources

- NEXT_CHANGELOG.md
- README.md
Currently, the minimum supported version of `terraform` with the Databricks TF Provider is documented as v1.0. However, there is an issue with too-strict validation of resources using SDKv2. This updates the guidance for customers to use `terraform` from v1.1.5, which mitigates this issue. Generally, new resources will be implemented using the Plugin Framework, which does have strict enforcement of these bugs. Over time, we will migrate resources to use the plugin framework, and when we do so, we will need to address them, but for now, the status quo is that they are tolerated. By using v1.1.5 and later, this will not result in errors in plan/apply steps.
No tests needed, this is a docs-only change.
> Update minimum supported Terraform version in `README.md`

- workspace/resource_notebook.go
Check that parent folder doesn't exist in `databricks_notebook` and `databricks_workspace_file` is too specific and leads to an error in staging.  This PR relax this check a bit to avoid problems.
> [Internal] Relax the check for "parent folder doesn't exist" error

- NEXT_CHANGELOG.md
- aws/constants.go
- aws/data_aws_bucket_policy.go
- aws/data_aws_unity_catalog_policy.go
- aws/data_aws_unity_catalog_policy_test.go
- docs/data-sources/aws_bucket_policy.md
- docs/data-sources/aws_unity_catalog_policy.md
AWS S3 allows only alphanumeric, hyphens and dots in the S3 bucket names. Full list of naming rules is in the [docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html#general-purpose-bucket-names).
Resolves #4689
> Fix validation of S3 bucket name in `databricks_aws_unity_catalog_policy` and `databricks_aws_bucket_policy`

- NEXT_CHANGELOG.md
- catalog/resource_schema.go
- catalog/resource_schema_test.go
- Use https://docs.databricks.com/api/workspace/schemas/delete#force when deleting schemas
- No longer delete all the contained resources manually.
Existing tests.
I haven't check if there is integration test for this.
Resolves #3388, resolves #3375
> Use force flag for schema deletion

- NEXT_CHANGELOG.md
- docs/resources/group.md
- docs/resources/group_member.md
- docs/resources/service_principal.md
- docs/resources/user.md
It looks like customers are confused what ID should be used in `databricks_group_member` resource, so it makes sense to explicitly mention that it's SCIM ID.
Resolves #4194
> [Doc] Explicitly mention SCIM ID in `databricks_group_member` docs

- NEXT_CHANGELOG.md
- docs/index.md
Replaced dbfs related resources in the Storage section with volume, external location and storage credential resources.
> [Doc] Update storage section in index.md to complement Unity Catalog, removed DBFS related resources

- NEXT_CHANGELOG.md
- exporter/codegen.go
- exporter/impl_jobs.go
- exporter/impl_uc.go
- exporter/importables.go
- exporter/importables_test.go
- exporter/model.go
- exporter/util.go
- exporter/util_compute.go
- exporter/util_workspace.go
We should generate `application_id` only for Azure-managed service principals, while Databricks-managed SPs should have only name.
Should be merged after #4712
> [Exporter] Generate correct code for Databricks and Azure-managed service principals

- NEXT_CHANGELOG.md
- catalog/resource_system_schema.go
- catalog/resource_system_schema_test.go
- docs/resources/system_schema.md
Also rewrote corresponding tests to use the mock framework from Go SDK
> [Fix] Don't fail delete when `databricks_system_schema` can be disabled only by Databricks

- NEXT_CHANGELOG.md
- catalog/system_schema_test.go
- internal/providers/client/databricks_client.go
- internal/providers/pluginfw/pluginfw.go
- internal/providers/providers_test_utils.go
- internal/providers/sdkv2/sdkv2.go
Currently, the SDKv2 and Plugin Framework provider implementations have slightly different behavior in how the provider is configured. The SDKv2's schema.Schema is constructed using `DefaultFunc`, which allows setting provider-level configuration attributes to have default values based on environment variables. The specific environment variables are taken from struct tags in the Go SDK's Config object. On the other hand, the Plugin Framework's provider.Schema has no support for default values. Eventually, when the config.Config from the Databricks Go SDK is resolved, those attributes will be populated from the environment anyways. Thus, it should be safe to remove these environment variable defaults from the SDKv2 implementation, ensuring a uniform treatment of provider configuration …
> Unify client construction pathways and logging between SDKv2 and Plugin Framework implementations

- NEXT_CHANGELOG.md
- aws/data_aws_unity_catalog_assume_role_policy.go
- aws/data_aws_unity_catalog_assume_role_policy_test.go
- `databricks_aws_unity_catalog_assume_role_policy` data source requires external id in the self-assumption trust relationship
> [Fix] Add missing external Id in trust relationship for `databricks_aws_unity_catalog_assume_role_policy`

- NEXT_CHANGELOG.md
- docs/data-sources/aws_unity_catalog_assume_role_policy.md
- docs/data-sources/aws_unity_catalog_policy.md
- docs/guides/unity-catalog.md
`managed_policy_arns` are deprecated - https://github.com/hashicorp/terraform-provider-aws/issues/39771
> [Doc] Replaced `managed_policy_arns` with `aws_iam_role_policy_attachment` in guides

- NEXT_CHANGELOG.md
- docs/resources/cluster.md
- docs/resources/job.md
- docs/resources/library.md
- docs/resources/notebook.md
- docs/resources/pipeline.md
- docs/resources/repo.md
- docs/resources/secret.md
- docs/resources/workspace_file.md
Docs team reorganized docs structure and links to DLT pieces became broken
Resolve #4730
> [Doc] Fix links to Delta Live Tables docs

- NEXT_CHANGELOG.md
- clusters/cluster_test.go
- clusters/resource_cluster.go
- clusters/resource_cluster_test.go
- pipelines/resource_pipeline.go
- pools/resource_instance_pool.go
- Cluster API now correctly returns `zone_id`, so removing `ZoneDiffSuppress`
- Resolves #1700
> [Fix] Support updating `databricks_cluster` to Auto AZ

- serving/model_serving_test.go
TestUcAccModelServingProvisionedThroughput times out today while waiting for the mistral model to load. This PR changes this test to use a different model type which seems to work. After this PR, the test takes around 10 minutes.
Ran locally, the test passes.
> Fix TestUcAccModelServingProvisionedThroughput

- test-config.yaml
Tests fails flakily due to stale data being returned from cache. 
N/A
> [Internal] Disable tests for `databricks_access_control_rule_set`

- NEXT_CHANGELOG.md
- catalog/resource_schema.go
- catalog/schema_test.go
- docs/data-sources/schema.md
- docs/resources/schema.md
Schema now exports a stable UUID identifier in the `schema_id` field. This PR adds this to the model for schema as a computed attribute.
Manually verified that the schema_id was populated in state in GCP. I don't want to add a test for this per se since it's possible that it isn't populated in all environments (yet).
> Add `schema_id` to the output of `databricks_schema` resource

- NEXT_CHANGELOG.md
- docs/resources/instance_pool.md
As of now, auto is only supported for fleet node types, highlighting this as a note for instance pool resource.
N/A
> [Documentation] `databricks_instance_pool`: auto zone_id can only be used for fleet node types

- NEXT_CHANGELOG.md
- docs/resources/service_principal_role.md
This PR makes changes to docs only, no code changes. The `databricks_service_principal_role` is capable of giving account admin role to a service principal; however, this was not very clear in the docs whereas we do have an example given in `databricks_user_role` for users. 
I added an example demonstrating this capability of setting `role = "account_admin"` and a note that it can only be used with an account-level provider.
> [DOCS] added example of granting Account Admin role to a service principal

- NEXT_CHANGELOG.md
- docs/resources/cluster.md
The `is_single_node` field was recently introduced for clusters to simplify creation of single-node clusters. This PR updates the Terraform documentation for `databricks_cluster` to show how to configure the cluster resource using this new flag. This simplifies the process from before, which required a number of settings to be configured simultaneously.
Manually tested by creating a cluster with the documented template.
> Add documentation for single-node clusters in `databricks_cluster`

- NEXT_CHANGELOG.md
- docs/resources/connection.md
- docs/resources/external_location.md
1. In `databricks_external_location` the AWS and Azure examples included a grant to show how to grant permission on the External Location. I updated the GCP example to match, for clarity.
2. In `databricks_connection` resource, I fixed the HTTP connection example missing closing backticks for the HCL code block.
> [Docs] minor example updates

- NEXT_CHANGELOG.md
- docs/resources/disable_legacy_dbfs_setting.md
This PR updates the documentation for the `databricks_disable_legacy_dbfs_setting` resource by removing the mention to workspace internal storage which is not consumer facing, mentioning the restriction to DBR versions 13.3+, and removing the warning that the feature is in private preview (planning to go public preview next Monday)
> [Doc] Update disable_legacy_dbfs setting documentation

- NEXT_CHANGELOG.md
- docs/resources/model_serving.md
- serving/resource_model_serving.go
- serving/resource_model_serving_test.go
- Added output attribute `endpoint_url` in `databricks_model_serving`
- Resolve #4858
> [Feature] Added output attribute `endpoint_url` in `databricks_model_serving`

- NEXT_CHANGELOG.md
- clusters/resource_cluster.go
- clusters/resource_library.go
- internal/providers/pluginfw/products/library/resource_library.go
- jobs/resource_job.go
EGG libraries aren't supported since DBR 14, so it makes sense to put a deprecation message in relevant resources
> Deprecate `egg` library type in `databricks_cluster`, `databricks_job`, and `databricks_library`

- NEXT_CHANGELOG.md
- docs/data-sources/service_principal.md
- docs/data-sources/service_principals.md
- docs/resources/permissions.md
Explicitly documented `application_id` in `databricks_service_principal` data source. Also, put emphasis that `service_principal_name` in `databricks_permissions` is Application ID, not SP name.
Resolves #4604
> [Doc] Improve documentation for service principal data sources

- NEXT_CHANGELOG.md
- sharing/resource_share.go
This PR adds diff suppression to the `string_shared_as` field of the legacy SDKv2 `databricks_share` resource to match the behavior of the new plugin framework implementation. The new version treats `string_shared_as` as a user-settable field with a server-settable effective companion field.
> Set suppressDiff on string_shared_as in the Legacy databricks_share Resource

- NEXT_CHANGELOG.md
- docs/resources/cluster.md
> Document `gcp_attributes.first_on_demand` attribute in `databricks_cluster`

- NEXT_CHANGELOG.md
- internal/providers/pluginfw/products/sharing/data_shares_acc_test.go
- internal/providers/pluginfw/products/sharing/resource_acc_test.go
- sharing/data_shares_acc_test.go
- sharing/share_test.go
Replace deprecated `databricks_table` with `databricks_sql_table` in sharing tests.
This PR migrates all share-related acceptance tests from the deprecated `databricks_table` resource to `databricks_sql_table to` resolve test failures caused by:
1. Partition spec validation errors when sharing tables created with the deprecated resource
2. Delta deletion vectors conflicts that prevent table sharing without full history
> Use databricks_sql_table Instead of databricks_table in Sharing Tests

- NEXT_CHANGELOG.md
- docs/resources/model_serving.md
- docs/resources/vector_search_index.md
There are new fields in Go SDK for `databricks_vector_search_index` and `databricks_model_serving` resources, so documenting them.
> [Doc] Update existing docs to match Go SDK 0.81.0
