databricks/terraform-provider-databricks

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
README.md

Add devcontainer configuration to enable working with the repo easily in Visual Studio Code using devcontainers.
Closes #39

Add devcontainer support

---

vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing.go
vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/set.go
vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go
vendor/modules.txt

Updating vendor due to dependabot update

updated vendor files

---

databricks/resource_databricks_secret.go
databricks/resource_databricks_secret_test.go

This PR fixes #68 
The code now checks to see if the error returned when attempting to list the secrets in the scope is caused by the secret-scope being deleted somehow.
Now the plan can be re-run and the resource correctly identifies it needs to be re-created

Fix for secret throwing error when its secret scope is deleted

---

client/model/cluster.go
databricks/resource_databricks_cluster.go
website/content/Resources/cluster.md

Add single_user_name to cluster resource

---

docs/index.md
docs/resources/secret_scope.md

generate basic terraform registry style documentation

generate basic terraform registry style documentation

---

databricks/resource_databricks_instance_pool.go

fix sparkVersions list in databricks_instance_pool

---

.travis.yml
CONTRIBUTING.md
Makefile
README.md

This pull request contains fix for installing from source properly.

Install from source fix & doc

---

databricks/resource_databricks_instance_pool.go

fix instance pool update recursive call

---

client/service/client.go
databricks/resource_databricks_instance_profile.go

Increase API connection timeouts and support instance profile import

---

databricks/resource_databricks_azure_adls_gen2_mount.go

add missing json tags for ADLS2 mounts

---

client/model/cluster.go
client/service/clusters.go
client/service/commands.go
databricks/mounts.go
databricks/resource_databricks_cluster.go

allow cluster resizing when executing commands

---

scripts/az-common/main.tf
scripts/azcli-integration/main.tf
scripts/azsp-integration/main.tf
scripts/azvnet-integration/init.tf
scripts/azvnet-integration/main.tf
scripts/azvnet-integration/vnet.tf

My formatters keeps automatically formatting them, so I might as well commit and PR them.

Format Terraform files

---

README.md

Update project disclaimer at the bottom, per JDO and Abhinav

Update project disclaimer at the bottom, per JDO and Abhinav

---

docs/data-sources/dbfs_file.md
docs/data-sources/dbfs_file_paths.md
docs/data-sources/notebook.md
docs/data-sources/notebook_paths.md

Added missing data source documentation

---

docs/resources/mws_workspaces.md

setting `customer_managed_key_id` -  to (Optional)

Update mws_workspaces.md - setting `customer_managed_key_id` -  to (Optional)

---

provider/provider.go

Fixes #420
It looks like the `config_file` setting has never been set and consumed properly.

Set ConfigFile when one is specified

---

common/azure_auth.go

So this will offload ID format maintainance to SDK

Parse and construct Azure resource id with Azure SDK

---

importer/command.go
importer/importables.go

I tried using the importer against a set of mounts and needed this fix for it to work.

Minor fixes to importer

---

CHANGELOG.md
compute/clusters.go
storage/mounts.go

Fixed redundant multiple mounting clusters

---

CHANGELOG.md
identity/data_group.go

Sort outputs in group data source

---

CHANGELOG.md
go.sum
internal/util/common_resource.go
internal/util/common_resource_test.go

Mark resources as new when doing import

---

common/client.go
common/context.go
common/context_test.go
docs/guides/aws-workspace.md
docs/index.md
docs/resources/notebook.md
docs/resources/token.md
internal/util/common_resource_test.go
mws/resource_workspace.go
provider/provider.go
workspace/file_resource_test.go
workspace/resource_notebook_test.go

Added more test coverage and fixed documentation.

Minor fixes

---

provider/provider.go

Simplify configuration debugging

---

CHANGELOG.md
README.md
docs/index.md
docs/resources/global_init_script.md
provider/provider.go
workspace/acceptance/global_init_script_test.go
workspace/file_resource.go
workspace/global_init_scripts.go
workspace/resource_global_init_script.go
workspace/resource_global_init_script_test.go

Add resource for global init scripts

---

docs/resources/cluster.md
docs/resources/global_init_script.md
docs/resources/job.md

Add missing documentation on docker_image block

---

docs/resources/cluster.md

This clarifies the issue I found here: #525

Clarify single node cluster syntax

---

CHANGELOG.md
docs/guides/workspace-management.md
docs/resources/mws_credentials.md
docs/resources/mws_customer_managed_keys.md
docs/resources/mws_networks.md
docs/resources/mws_storage_configurations.md
docs/resources/mws_workspaces.md
docs/resources/sql_endpoint.md

Prepare version 0.3.1

---

compute/resource_cluster.go
compute/resource_cluster_test.go
compute/resource_job_test.go
storage/mounts.go

should fix the root cause for #527

add custom tag ResourceClass for single node cluster

---

workspace/resource_global_init_script.go

allow spaces in the name of the global init script

---

docs/resources/sql_permissions.md

Remove R and make config match default settings when enabling via workspace UI

Update cluster config for Table ACLs

---

compute/resource_instance_pool.go

Mark instance pool attributes as ForceNew when it's requited

---

mws/resource_log_delivery.go
mws/resource_log_delivery_test.go

Fix for issue #635... switching WorkspaceIdsFilter from []string to []int (the Databricks API returns an array of integers rather than strings)

Fix for issue #635 

---

storage/aws_s3_mount.go

Change that fixes: https://github.com/databrickslabs/terraform-provider-databricks/issues/651
I tried to see if I can write a test, but my knowledge of go projects is too limited. The existing tests obviously pass.

Allow instance profiles with paths

---

docs/index.md

use https for host rather than http, provider throws an error when using http

update index.md to use https for host

---

docs/resources/cluster.md

fix doc for spot instances on azure

---

exporter/importables.go

* files with the same names but different paths aren't overwriting each other, and don't have the same resource name - fixed by adding the MD5 sum of the file path
* jobs that have the same name (allowed by our UI) - fixed by adding the the job ID as suffix
* permissions that have the same name (for example, cluster & job have the same name) - fixed by adding the prefix that specifies the object type: cluster/job/instance pool/...

fixed generation of duplicate resources when exporting

---

common/azure_cli_auth.go

Force az cli to output data in JSON format

---

compute/resource_pipeline.go
docs/resources/pipeline.md
docs/resources/sql_permissions.md

* updated documentation
* added support for missing attribute `target` that was documented, but not implemented

Small fixes for DLT pipelines

---

access/resource_permissions.go
access/resource_sql_permissions.go
common/http.go
common/resource.go
compute/clusters.go
compute/resource_cluster.go
compute/resource_pipeline.go
mws/resource_network.go
mws/resource_workspace.go
storage/mounts.go

Unify HTTP 404 handling

---

docs/guides/workspace-management.md

Fix a typo in the documentation
Replace "ths" by "the"

Fix a typo

---

docs/guides/aws-workspace.md

- fixed broken link
- removed not necessary pieces

fixes in AWS Workspace guide

---

compute/clusters.go
compute/data_spark_version_test.go
compute/model.go
docs/data-sources/spark_version.md
go.mod

- added selector for Photon-based DBR
- expanded long_term selector to ESR versions
- implemented correct sorting of the version strings

Improving data source for spark versions

---

docs/guides/experimental-exporter.md
exporter/context.go

Add basic telemetry to track adoption of exporter feature

Added missing exporter telemetry

---

access/resource_secret_scope.go
access/resource_sql_permissions.go
common/reflect_resource.go
common/reflect_resource_test.go
common/version.go
compute/model.go
compute/resource_cluster.go
compute/resource_instance_pool.go
identity/resource_service_principal.go
identity/resource_user.go
mws/resource_customer_managed_key.go
mws/resource_log_delivery.go
mws/resource_mws_vpc_endpoint.go
sqlanalytics/resource_visualization.go
sqlanalytics/resource_widget.go
workspace/resource_repo.go

introduce the force_new annotation for terraform fields

---

CHANGELOG.md
common/azure_auth.go
common/client.go

this fixes #831 that was caused by use of non-Azure authentication to mount Azure resources

Always initialize Azure Environment

---

docs/resources/mws_customer_managed_keys.md

- Splitting example usage code for storage and managed services, as KMS policies are different between the two
- Updating wordings to cover both storage and managed services CMK features

update cmk doc

---

common/client.go
common/client_test.go
common/context.go
common/version.go
provider/provider_test.go

Clarify empty host error

---

compute/resource_job.go

convert job ID to int64 instead of int32

---

workspace/resource_repo.go

use path instead of path/filepath

---

docs/resources/global_init_script.md

Document `position` of `global_init_script`

---

docs/resources/job.md

Added `url` attribute documentation to `databricks_job`

---

CHANGELOG.md
docs/resources/permissions.md
permissions/acceptance/permissions_test.go
permissions/resource_permissions.go
permissions/resource_permissions_test.go

Fix for https://github.com/databrickslabs/terraform-provider-databricks/issues/875

add repo_path for permissions

---

.github/workflows/docker-it.yml
scripts/it.sh
scripts/nightly/azureit.tf

Create integration test image only from master

---

CHANGELOG.md
clusters/resource_cluster.go
clusters/resource_cluster_test.go
libraries/libraries_api.go
libraries/libraries_api_test.go

Return library status on a terminated cluster

---

workspace/global_init_scripts.go

don't use omitempty for enabled field in the global init scripts

---

common/http.go

Make auth issue debugging easier

Log host on `debug_headers` conf

---

common/reflect_resource.go
common/reflect_resource_test.go

Easily mark fields as sensitive

Added `tf:"sensitive"` tag

---

common/http.go

Retry on TLS timeout

---

CHANGELOG.md
README.md
clusters/data_clusters.go
clusters/data_clusters_test.go
clusters/databricks_library.go
clusters/databricks_library_test.go
common/resource.go
docs/resources/cluster.md
docs/resources/dbfs_file.md
docs/resources/library.md
provider/provider.go

```hcl
data "databricks_clusters" "all" {
}
resource "databricks_library" "cli" {
for_each = data.databricks_clusters.all.ids
cluster_id = each.key
pypi {
package = "databricks-cli"
}
}
```
Fix #904 #954

Added `databricks_library` resource

---

scripts/modules/workspace-in-shared-vpc/main.tf

Work in progress for module to define workspaces in a shared VPC. 
Essentially, given VPC ID, credentials and storage configurations, create subnets in all regions of the given VPC, add route table associations and register a network. And create the workspace.

New module - workspace in a shared VPC

---

CONTRIBUTING.md

Get new developers started easier

Update developer documentation

---

.github/dependabot.yml

Change `dependabot` schedule to weekly

Check dependencies weekly

---

CHANGELOG.md
catalog/resource_storage_credentials.go
catalog/resource_storage_credentials_test.go
provider/provider.go

```hcl
resource "databricks_storage_credential" "this" {
name = "abc"
aws_iam_role {
role_arn = "arn:aws:iam::########:role/some-role"
}
comment = "Managed by TF"
}
```

Add experimental resources

---

README.md
docs/guides/aws-e2-firewall-hub-and-spoke.md
docs/guides/aws-e2-firewall-workspace.md
docs/guides/aws-workspace.md
docs/guides/workspace-management.md
docs/index.md

* Added support for `databricks_permissions` for `databricks_mlflow_experiment` and `databricks_mlflow_model` ([#1013](https://github.com/databrickslabs/terraform-provider-databricks/pull/1013)).
* Added `Using XXX auth` explanation to HTTP 403 errors, which should help troubleshooting misconfigured authentication or provider aliasing. Example error message now looks like: *cannot create group: /2.0/preview/scim/v2/Groups is only accessible by admins. Using databricks-cli auth: host=https://XXX.cloud.databricks.com/, token=`***REDACTED***`, profile=demo.* All sensitive configuration parameters (`token`, `password`, and `azure_client_secret`) are redacted and replaced with `***REDACTED***` ([#821](https://github.com/databrickslabs/terraform-provider-databricks/issues/821)).
* Improved …

Release v0.4.3

---

catalog/resource_external_location.go
catalog/resource_external_location_test.go
catalog/resource_grants.go
catalog/resource_grants_test.go
catalog/resource_table.go
catalog/resource_table_test.go
provider/provider.go

Added `databricks_table` resource

Adding new experimental resources

---

CHANGELOG.md
README.md
docs/guides/aws-e2-firewall-hub-and-spoke.md
docs/guides/aws-e2-firewall-workspace.md
docs/guides/aws-workspace.md
docs/guides/workspace-management.md
docs/index.md

* Added support for [running provider in a debug mode](https://www.terraform.io/plugin/sdkv2/debugging#running-terraform-with-a-provider-in-debug-mode) from Visual Studio Code through `Debug Provider` run configuration in order to troubleshoot more complicated issues.
* Allowed managing of libraries on `databricks_cluster` outside of Terraform state for resources without any `library` configuration blocks. This should simplify PaaS-like CI/CD workflows ([#1024](https://github.com/databrickslabs/terraform-provider-databricks/pull/1024)).
* Added experimental resources.
**Behavior changes**
* Whenever library is installed on `databricks_cluster` without any [`library` configuration blocks](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster#library …

Release v0.4.4

---

CHANGELOG.md
README.md
docs/guides/aws-e2-firewall-hub-and-spoke.md
docs/guides/aws-e2-firewall-workspace.md
docs/guides/aws-workspace.md
docs/guides/workspace-management.md
docs/index.md

* Cross-linked resource documentation ([#1027](https://github.com/databrickslabs/terraform-provider-databricks/pull/1027)).
* Added Azure example for sql_global_config ([#1028](https://github.com/databrickslabs/terraform-provider-databricks/pull/1028)).
* Bump google.golang.org/api from 0.63.0 to 0.65.0

Release v0.4.5

---

docs/resources/mlflow_experiment.md
docs/resources/mlflow_model.md
mlflow/resource_model.go
mlflow/resource_webhook.go
mlflow/resource_webhook_test.go
provider/provider.go
qa/testing.go
qa/testing_test.go

also removed some recursive doc references :-)

Added a new resource

---

common/http.go

This fixes #1034
Also, added printing of response headers when debugging is enabled

Explicitly set charset for SCIM requests

---

CHANGELOG.md
common/azure_auth.go
common/azure_auth_test.go
docs/index.md
docs/resources/sql_global_config.md

Clarified error messages around `azure_workspace_resource_id`

---

CHANGELOG.md
aws/resource_user_instance_profile_test.go
aws/resource_user_role.go
aws/resource_user_role_test.go
docs/resources/user_role.md
provider/provider.go
qa/testing.go

Adding AWS instance profile to a user
```hcl
resource "databricks_instance_profile" "instance_profile" {
instance_profile_arn = "my_instance_profile_arn"
}
resource "databricks_user" "my_user" {
user_name = "me@example.com"
}
resource "databricks_user_role" "my_user_role" {
user_id = databricks_user.my_user.id
role    = databricks_instance_profile.instance_profile.id
}
```
Adding user as administrator to Databricks Account
```hcl
host       = "https://accounts.cloud.databricks.com"
account_id = var.databricks_account_id
username   = var.databricks_user
password   = var.databricks_password
}
resource "databricks_user" "my_user" {
user_name = "me@example.com"
}
resource "databricks_user_role" "my_user_account_admin" {
user_id = databricks_user.my_user.id
role    = …
```

Added `databricks_user_role` resource

---

CHANGELOG.md
common/http.go
scim/resource_service_principal.go

Improved SCIM error message propagation and now include `scimType` field.
Fixes #1065
Fixes #1051

Don't include `application_id` in SP update

---

CHANGELOG.md
common/reflect_resource.go
common/reflect_resource_test.go
common/version.go
pools/resource_instance_pool.go
scripts/gcp-integration/main.tf

Added support for `tf:suppress_diff` on primitive types

---

README.md
docs/guides/aws-workspace.md
docs/guides/unity-catalog.md
docs/guides/workspace-management.md
docs/index.md

* Added support for `tf:suppress_diff` on primitive types ([#984](https://github.com/databrickslabs/terraform-provider-databricks/issues/984)).
* Fixed issue arises when destroying `databricks_sql_global_config` with instance profile set ([#1076](https://github.com/databrickslabs/terraform-provider-databricks/issues/1076)).
* Added setting of SQL configuration parameters in `databricks_sql_global_config` ([#1080](https://github.com/databrickslabs/terraform-provider-databricks/pull/1080)).
* Added support for release channels in `databricks_sql_endpoint` configuration ([#1078](https://github.com/databrickslabs/terraform-provider-databricks/pull/1078)).
* Added documentation for `databricks_mlflow_webhook` resource ([#1086](https://github.com/databrickslabs/terraform-provider-databricks/pull …

Release v0.4.8

---

CHANGELOG.md
scim/acceptance/group_test.go
scim/resource_group.go

Suppress diff for `databricks_group`.`external_id`

---

CHANGELOG.md
scim/acceptance/resource_user_test.go
scim/resource_user.go

Suppress diff for `databricks_user`.`external_id`

---

sql/resource_sql_endpoint.go

Suppress diff for `num_clusters` in SQL Endpoint

---

docs/resources/mws_networks.md

Updated the documentation databricks_mws_networks resource in order to clarify that the public subnet can be limited to few IP addresses by adding a secondary cidr_block to the managed vpc.

Update databricks_mws_networks Resource doc

---

catalog/resource_table.go

Skip sending empty `storage_location`

---

docs/resources/table.md

Fix `databricks_table` docs

---

CHANGELOG.md
catalog/resource_table.go

Fixed `databricks_table` updates

---

docs/resources/cluster.md

Fix `databricks_cluster` `is_pinned` limit in docs

---

permissions/resource_permissions.go
permissions/resource_permissions_test.go

Delete permissions resource for auto-purged cluster

---

CONTRIBUTING.md

This adds documentation format conventions and reference

Adding doc requirements

---

docs/resources/cluster.md

Align docs with https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/library#javascala-maven

Fix doc in `databricks_cluster`

---

go.mod
go.sum
permissions/resource_permissions.go
permissions/resource_permissions_test.go

Remove unused extra dependency

Remove `github.com/pkg/errors` dependency

---

docs/resources/job.md

Changelog entry will be added after git credentials PR is merged, otherwise we'll get conflict

Added docs for Jobs/Repos integration

---

.github/workflows/push.yml

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths

Skip `make test` on doc-only changes

---

docs/resources/sql_dashboard.md
docs/resources/sql_query.md
docs/resources/sql_visualization.md
docs/resources/sql_widget.md

update docs regarding importing of SQL resources

---

docs/guides/troubleshooting.md

Added a bit of clarification to workaround the TF repository change with GA.

Add instructions to re-create .terraform.lock.hcl

---

common/resource.go

Right now, when importing we're reading data, and ignoring the missing resources.  But it
doesn't work well, and users get a cryptic error, like this:
```
>terraform import databricks_cluster.this 12313231232
databricks_cluster.this: Importing from ID "12313231232"...
╷
│ Error: The provider returned a resource missing an identifier during
ImportResourceState. This is generally a bug in the resource implementation for
import. Resource import code should not call d.SetId("") or create an empty
ResourceData. If the resource is missing, instead return an error. Please report this to
the provider developers.
```
With this PR, error message is clear:
```
Error: Cannot import non-existent remote object
While attempting to import an existing object to "databricks_cluster.this",
the provider …
```

Better handling of missing objects during import

---

docs/resources/permissions.md

clarified `databricks_permissions` doc for service principals

---

catalog/resource_grants.go
docs/resources/grants.md

Adds support for `metastore` grants and few other things.

Added `metastore` to `databricks_grants`

---

clusters/clusters_api_test.go
clusters/data_spark_version_test.go
common/http.go
common/http_test.go
pools/resource_instance_pool.go

P.S. Also added reporting of actual error when unmarshall JSON, otherwise it's hard to debug issues

Add more attributes to `databricks_instance_pool`

---

scim/resource_user_test.go
scim/scim.go

Fix sending of `active` flag in the `resource_user`

---

CONTRIBUTING.md

Use proper name in intro, fix the link for terraform12 setup.

Minor link and text fix

---

docs/guides/unity-catalog-azure.md
docs/resources/storage_credential.md

Also switch to `azure/azapi` provider to create Databricks Access Connector

Update Unity Catalog Azure guide to use MI

---

docs/data-sources/current_user.md
docs/resources/catalog.md
docs/resources/external_location.md
docs/resources/metastore.md
docs/resources/schema.md
docs/resources/storage_credential.md
docs/resources/table.md

- Update current_user outputs
- Update various UC docs

Various doc updates

---

catalog/acceptance/external_location_test.go
catalog/acceptance/metastore_assignment_test.go
catalog/acceptance/metastore_data_access_test.go
catalog/acceptance/recipient_test.go
catalog/acceptance/schema_test.go
catalog/resource_metastore.go
internal/acceptance/acceptance.go
mws/acceptance/mws_permissionassignments_test.go

Added some coverage for:
* `databricks_grants`
* `databricks_schemas`
* `databricks_schema`
* `databricks_catalogs`
* `databricks_catalog`
* `databricks_external_location`
* `databricks_storage_credential`
* `databricks_metastore_assignment`
* `databricks_metastore_data_access`
* `databricks_metastore`

Added initial Unity Catalog integration tests

---

docs/resources/entitlements.md
provider/provider.go
scim/acceptance/entitlements_test.go
scim/groups.go
scim/resource_entitlement.go
scim/resource_entitlement_test.go
scim/resource_service_principal.go
scim/scim.go
scim/users.go

The new resource will set entitlements on existing identities in a workspace
Closes #1532,  closes #1438

Added `databricks_entitlements` resource

---

mlflow/resource_mlflow_webhook.go

fix `secret` field name in `databricks_mlflow_webhook` resource

---

docs/data-sources/job.md
jobs/acceptance/data_job_test.go

Fix test for `databricks_job` data source

---

docs/resources/sql_global_config.md

As per subject, just added the parameter in the documentation.

Added `enable_serverless_compute` in the documentation for the `sql_global_config`

---

exporter/importables.go

this will help avoiding errors when applying to another workspace with existing users

Export users and groups with the `force` flag

---

docs/guides/unity-catalog-azure.md
docs/resources/storage_credential.md

Replace resources under `azapi` provider with [azurerm_databricks_access_connector](https://github.com/hashicorp/terraform-provider-azurerm/issues/18709)

Update Azure Unity Catalog guide to use `azurerm_databricks_access_connector`

---

sql/acceptance/sql_dashboard_test.go
sql/api/visualization.go
sql/api/visualization_test.go
sql/resource_sql_visualization.go
sql/resource_sql_visualization_test.go

Add query_plan attribute to visualization

---

docs/resources/job.md
jobs/resource_job.go

Add `catalog` parameter to `dbt_task` in `databricks_job` resource

---

exporter/context.go
exporter/exporter_test.go
exporter/importables.go

Fix for issue #1725 
Generate workspace conf with workspace in -services

First commit to fix databricks_workspace_conf generation 

---

exporter/context.go
exporter/exporter_test.go
exporter/importables.go
exporter/importables_test.go
exporter/util.go
sql/api/query.go
sql/api/query_test.go
sql/api/visualization.go
sql/resource_sql_query.go
sql/resource_sql_query_test.go

This includes:
* Fixing problems with listing of objects
* Correct export of queries with date/time range parameters
* Introduced separate categories for queries, dashboards & SQL endpoints to allow granular export

Improve export of DBSQL objects

---

exporter/importables.go

Exporter: correct reference to `databricks_cluster_policy` in `databricks_job`

---

docs/guides/experimental-exporter.md
exporter/command.go
exporter/context.go
exporter/importables.go
exporter/importables_test.go
exporter/model.go

Fix for issue #1688
Issue with exporter emittingdatabricks_user resource - unable to handle multidomain

Fixed multidomain `databricks_user` in exporter

---

pipelines/resource_pipeline.go

Also, add other now supported attributes:
* `enable_local_disk_encryption`
* `availability` and `spot_bid_price_percent` in `aws_attributes`
* `availability` and `zone_id` in `gcp_attributes`

Add `azure_attributes` to clusters in `databricks_pipeline` resource

---

docs/resources/cluster.md

Ref: https://github.com/databricks/terraform-provider-databricks/issues/1867

Add num_workers optional argument

---

clusters/acceptance/data_cluster_test.go
sql/acceptance/data_sql_warehouse_test.go

Added acceptance tests for `databricks_cluster` data and `databricks_sql_endpoint` data

---

catalog/acceptance/provider_test.go
catalog/resource_provider.go
mws/acceptance/mws_workspaces_test.go

Makes `recipient_profile_str` a write only field thus fixing the ACC test

Fix UC secret update and correct syntax of a gcp test

---

catalog/resource_catalog.go
catalog/resource_catalog_test.go
docs/resources/catalog.md

Extend `databricks_catalog` resource to support Delta Sharing Catalog

---

clusters/acceptance/clusters_api_test.go
common/client.go
docs/data-sources/directory.md
docs/guides/unity-catalog.md
docs/resources/cluster.md
docs/resources/job.md
docs/resources/mws_workspaces.md
docs/resources/provider.md
internal/compute/common_instances.go
provider/gen/main.go
sql/api/api.go

run `make fmt` & `make fmt-docs`

fix formatting of the code & documentation

---

docs/resources/mws_permission_assignment.md
docs/resources/permission_assignment.md

add doc for `databricks_permission_assignment`

---

internal/acceptance/acceptance.go
mws/acceptance/mws_workspaces_test.go
mws/resource_mws_storage_configurations_test.go
mws/resource_mws_workspaces_test.go
scim/acceptance/data_group_test.go
scim/acceptance/group_member_test.go
scim/acceptance/group_test.go
scim/acceptance/service_principal_test.go
scim/acceptance/user_test.go
scim/resource_service_principal.go

Verified for:
* azure-acct
* aws-acct
* aws-ucacct
* gcp-acct
* azure-prod
* aws-prod

Enable account level SCIM tests for azure

---

docs/resources/sql_dashboard.md
docs/resources/sql_query.md
sql/api/dashboard.go
sql/api/query.go
sql/resource_sql_dashboard.go
sql/resource_sql_query.go

Added `parent` attribute to `databricks_sql_query` and `databricks_sql_dashboard`

---

docs/resources/cluster_policy.md
policies/data_cluster_policy.go
policies/resource_cluster_policy.go

Add `max_clusters_per_user` to `databricks_cluster_policy` resource

---

policies/resource_cluster_policy.go
policies/resource_cluster_policy_test.go

:facepalm: we need to get rid from the non-struct schemas

Fix `max_clusters_per_user` to `databricks_cluster_policy` resource

---

docs/resources/job.md

Clarify SQL warehouse types for `sql_task` in `databricks_job`

---

docs/resources/job.md

https://github.com/databricks/terraform-provider-databricks/issues/1950

Add documentation around webhooks_notifications

---

catalog/resource_grants.go
docs/resources/grants.md

Fix #1961, which is due to a typo (missing underscore)

fix `CREATE_MANAGED_STORAGE` permission

---

exporter/importables.go
internal/acceptance/workspace_conf_test.go
workspace/resource_workspace_conf.go

Swaps implementation of workspace conf API to Go SDK

Migrate `databricks_workspace_conf` to Go SDK

---

exporter/context.go
exporter/context_test.go
exporter/exporter_test.go
exporter/importables.go
exporter/model.go
exporter/test-data/get-directory-permissions.json
exporter/test-data/get-sql-dashboard.json
exporter/test-data/get-sql-dashboards.json
exporter/test-data/get-sql-query.json
exporter/util.go

First use is for creating references to parent folder in the DBSQL queries/dashboards

Add `MatchRegexp` match type for partial matches

---

docs/resources/mws_vpc_endpoint.md
go.mod
internal/acceptance/mws_vpc_endpoint_test.go
mws/mws.go
mws/resource_mws_vpc_endpoint.go
mws/resource_mws_vpc_endpoint_test.go

Add TF for vpc endpoint on GCP.

Add TF for vpc endpoint on GCP.

---

docs/resources/mws_networks.md
docs/resources/mws_private_access_settings.md
docs/resources/mws_vpc_endpoint.md
docs/resources/mws_workspaces.md

[PLAT-76310] Link [Provisioning GCP workspace with Private Service Connect] to all PSC related resources.
[PLAT-76310]: https://databricks.atlassian.net/browse/PLAT-76310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PLAT-76310] Link GCP PSC guides to all PSC resources.

---

jobs/resource_job.go

Add support for private preview functionality `run_if`.

Add run_if condition in jobs

---

jobs/resource_job.go
jobs/resource_job_test.go

Add support for private preview functionality queueing.

Added experimental queue field

---

docs/data-sources/aws_crossaccount_policy.md
docs/data-sources/service_principal.md
docs/guides/aws-private-link-workspace.md
docs/guides/unity-catalog-azure.md
docs/guides/unity-catalog-gcp.md
docs/guides/unity-catalog.md
docs/index.md
docs/resources/external_location.md
docs/resources/instance_profile.md
docs/resources/mws_workspaces.md
docs/resources/permissions.md

Clean up various doc issues
- Mention GCP on main doc page
- Closes #2079
- Closes #2063
- Closes #2014
- Closes #2005
- Closes #2092
- Closes #1942
- Closes #1962

misc doc fixes

---

go.mod
go.sum

Bumps go sdk from v0.5.0 to v0.6.0

Update SDK to v0.6.0

---

docs/resources/job.md
jobs/resource_job.go

Added file task to the `sql_task` block

Add SQL File task to `databricks_job` resource

---

README.md
docs/data-sources/mws_credentials.md
docs/data-sources/pipelines.md
docs/resources/pipeline.md
internal/acceptance/data_pipelines_test.go
pipelines/data_pipelines.go
pipelines/data_pipelines_test.go
provider/provider.go

Adding data provider for DLT (pipelines) - [Issue-1926](https://github.com/databricks/terraform-provider-databricks/issues/1926)
In addition to the test below, local tests using the developed data provider were conducted against an internal Databricks workspace.

Added `databricks_pipelines` data source

---

exporter/importables.go

The dependency referenced the wrong resource

Fix dependency when exporting `databricks_service_principal_role`

---

docs/resources/pipeline.md

(#2319) Update `edition` and `channel` values in docs.

---

docs/index.md
docs/resources/service_principal_secret.md

- Fix some typo in `docs/resources/service_principal_secret.md`
- Update description of the provider's attribute `client_id`

Document fix for `databricks_service_principal_secret`

---

docs/resources/cluster_policy.md

Update language in Cluster Policy doc.
Doc change- examined diff.
- [N/A] `make test` run locally
- [N/A] covered with integration tests in `internal/acceptance`
- [N/A] relevant acceptance tests are passing

Clean up cluster policy resource doc page.

---

.github/ISSUE_TEMPLATE/config.yml

Point to StackOverflow for general questions about Databricks terraform provider

---

catalog/resource_external_location.go
docs/resources/external_location.md
internal/acceptance/external_location_test.go

Added `force_destroy` to `databricks_external_location` resource

---

catalog/resource_grants.go
docs/resources/grants.md
docs/resources/volume.md

Update `databricks_grant` resource with latest set of permissions (mostly for `databricks_volume`)
Close #2384

Update `databricks_grant` resource with latest set of permissions

---

docs/index.md

Add to documentation a link to existing Databricks Terraform modules

---

docs/resources/group_member.md

Add import example to doc for `databricks_group_member` resource

---

jobs/resource_job.go

Add condition_task (private preview)

Add condition_task (private preview)

---

internal/acceptance/model_serving_test.go

Installs mlflow using pip  in model serving test incase default cluster is running
Self testing

Fix model serving acceptance test

---

CODEOWNERS

Auto-assign all PR reviews for Terraform to @databricks/field-dev-ecosystem and @databricks/eng-dev-ecosystem.

Add code owners for Terraform

---

pools/resource_instance_pool.go

Added suppress diff for `aws_attributes.zone_id` with value `auto` in `databricks_instance_pool`

---

access/resource_ip_access_list.go
access/resource_ip_access_list_test.go

Fix a bug in the Read method for IP Access List
Close #2504

Fixed `databricks_ip_access_list` read method

---

docs/index.md

Document missing environment variables for authentication

---

docs/guides/experimental-exporter.md
exporter/exporter_test.go
exporter/importables.go
exporter/importables_test.go

Exporter: add List operation for `databricks_instance_pool` resource

---

exporter/exporter_test.go
mlflow/resource_mlflow_webhook.go
mlflow/resource_mlflow_webhook_test.go

Port `databricks_mlflow_webhook` to Go SDK

---

catalog/data_schemas_test.go
catalog/resource_catalog_test.go
catalog/resource_schema.go
catalog/resource_schema_test.go
catalog/resource_table.go

- Refactor `databricks_schema` to Go SDK

Refactor `databricks_schema` to Go SDK

---

docs/guides/troubleshooting.md
docs/index.md

Some minor changes to our docs
- Add troubleshooting guide for grants/permissions config drifts
- Update authentication details in index.md

Documentation changes

---

mws/resource_mws_workspaces.go
mws/resource_mws_workspaces_test.go

Fix reflection method marshallJSON for GCP CMK in mws workspace

Fix reflection method marshallJSON for CMK in mws workspace

---

docs/resources/mws_customer_managed_keys.md
docs/resources/mws_workspaces.md

- Add missing documentation for CMK support on GCP

Add missing documentation for CMK support on GCP

---

catalog/resource_metastore.go
internal/acceptance/metastore_data_access_test.go

Fix UC acceptance test

---

CHANGELOG.md
common/version.go
go.mod
go.sum

Release 1.24.1
* Fixed verification of workspace reachability by using scim/me which is always available  ([#2618](https://github.com/databricks/terraform-provider-databricks/pull/2618)).
Also ran: `go get -u && got mod tidy`

Release v1.24.1

---

docs/resources/access_control_rule_set.md

Updated access control rule set docs to include information about marketplace admin role. 
Only change in docs

Updated docs for `marketplace admin` role

---

docs/guides/unity-catalog.md

Typo in path fixed
Simple typo fix in reference to #2693

Fix Service Principal reference

---

catalog/resource_grants.go
docs/resources/grants.md

Another refresh until we have #2745

Refresh `databricks_grants` with latest permissible grants

---

catalog/resource_system_schema.go
catalog/resource_system_schema_test.go
docs/resources/system_schema.md
internal/acceptance/system_schema_test.go
provider/provider.go

- add `databricks_system_schema` resource to enable [system tables](https://docs.databricks.com/en/administration-guide/system-tables/index.html)
close #2663

add `databricks_system_schema` resource

---

docs/resources/external_location.md
docs/resources/grants.md

Also updated missing grants
This fixes #2653
This fixes #2702

[DOC] Updated `databricks_grants` examples for `databricks_external_location`

---

mws/resource_mws_workspaces.go
mws/resource_mws_workspaces_test.go

Mask token value field in logs
- []  N/A covered with integration tests in `internal/acceptance`
- [] N/A using Go SDK

Mask sensitive field

---

CODEOWNERS

The new team was created for work on Terraform code base

Use `terraform-field-dev` as code owner instead of `field-dev-ecosystem`

---

docs/resources/schema.md

Fix documentation for `databricks_schema` about default value for `storage_root`

---

docs/resources/secret_acl.md

Clarify possible values for `principal` attribute of `databricks_secret_acl`

---

internal/acceptance/cluster_test.go

Enable the test
Integration test is running ...

Enabled`TestAccClusterResource_CreateClusterWithLibraries` integration test

---

exporter/importables.go
exporter/importables_test.go

Exporter: Make sure that name of `databricks_repo` is unique

---

internal/acceptance/permissions_test.go

Add integration test for SQL warehouse permissions in `databricks_permissions`

---

.github/ISSUE_TEMPLATE/docs-issue.md

We don't have `documentation` label but `docs`

Use correct label in the issue template for documentation

---

sql/api/dashboard.go
sql/resource_sql_dashboard.go
sql/resource_sql_dashboard_test.go

Add support for `run_as_role` in `databricks_sql_dashboard` resource

---

docs/resources/job.md

- update `databricks_job` documentation with `queue` block

update `databricks_job` documentation with `queue` block

---

docs/resources/connection.md

Update bigquery connection type to terraform provider doc
N/A

Update bigquery connection type to terraform provider doc

---

internal/acceptance/instance_profile_test.go
internal/acceptance/sql_table_test.go

Enable and fix tests
Run those tests against AWS

Enable and fix tests

---

catalog/resource_schema.go
catalog/resource_schema_test.go

Also delete volumes, functions & models when force destroy a schema
Closes #2906

Fix `force_destroy` behaviour for `databricks_schema`

---

docs/resources/job.md
exporter/exporter_test.go
exporter/importables.go
jobs/resource_job.go
jobs/resource_job_test.go

Also, replaced email notifications with corresponding structs from Go SDK to make it matching to the API specification, and updated docs correspondingly
This fixes #2951

Add `webhooks_notifications` on task levels in `databricks_job` resource

---

exporter/exporter_test.go
exporter/importables_test.go
go.mod
go.sum

This PR fixes unit failing tests with regards to SCIM pagination added in https://github.com/databricks/databricks-sdk-go/commit/fe6b76828faa081a7328846d4cd97f662d8d745c

Fixed unit tests for the upcoming Go SDK release

---

docs/data-sources/current_config.md
internal/acceptance/data_current_config_test.go
mws/data_current_config.go
mws/data_current_config_test.go
provider/provider.go

add `databricks_current_config` data source

---

docs/resources/job.md
jobs/resource_job.go

Add documentation for `condition_task` in `databricks_job` resource

---

exporter/importables.go

Exporter: fix suppression of empty `webhook_notifications` blocks in tasks

---

catalog/resource_grants.go
catalog/resource_grants_test.go

Wait for resource to be updated during grants resource modification
Added unit test

Wait for resource to be updated during grants resource modification

---

internal/acceptance/grants_test.go

add acceptance tests for `databricks_grants`

---

docs/resources/connection.md

add BQ example for `databricks_connection`

---

.github/workflows/schema.yml
Makefile
scripts/diff-schema.sh
scripts/libschema.sh
scripts/print-schema.sh

Make it possible to print and diff the provider schema locally. Check in your changes and run `make diff-schema to see the changes your PR makes in the provider schema.

Diff Schema locally

---

CHANGELOG.md
common/version.go

New Features and Improvements:
* Added support for ownership changes for unity catalog resources ([#3029](https://github.com/databricks/terraform-provider-databricks/pull/3029)).
Exporter:
* Ignore workspace assets of deleted users and service principals ([#2980](https://github.com/databricks/terraform-provider-databricks/pull/2980)).

Release v1.33.0

---

catalog/data_current_metastore.go
catalog/data_current_metastore_test.go
docs/data-sources/current_metastore.md
docs/data-sources/metastore.md
internal/acceptance/data_current_metastore_test.go
provider/provider.go

Add the `databricks_current_metastore` data source to retrieve information about a UC metastore attached to the current workspace

---

internal/acceptance/metastore_assignment_test.go

This reverts commit c78101e881cb512edc9c8c778047ef7c9ab78773.

Revert "Lock dummy workspace to limit concurrent changes to its metastore assignment (#3053)"

---

docs/guides/experimental-exporter.md
exporter/context.go
exporter/exporter_test.go
exporter/importables.go
exporter/importables_test.go

Exporter: added export of `databricks_system_schema` resources

---

exporter/importables.go

This PR includes the following changes:
* Don't emit notebooks and Python scripts that are stored in Git repositories
* Emit `databricks_workspace_file` for the Python Script task
* Correctly handling references for wheel files and python scripts from repo
*

Exporter: Improve handling of referenced objects & dependencies in `databricks_job`

---

catalog/resource_grants.go
catalog/resource_grants_test.go
internal/acceptance/grant_test.go

Follow on from #3024 and update resource_grants to use Go SDK.

catalog/resource_grants: Refactor to use Go SDK

---

README.md

To clarify the state of the world for OpenTofu, we mention that the provider should work with OpenTofu but it isn't tested and should be considered experimental.

Reference OpenTofu support in TF Readme

---

go.mod
go.sum

Update go SDK to 0.30.0

---

.github/workflows/codeql-analysis.yml
.github/workflows/push.yml
.github/workflows/release.yml

* Update the action to the latest version
* Remove unnecessary unshallow step on tests
* Fold unshallow step into actions/checkout on release

Update actions/checkout to v4

---

exporter/command.go
exporter/context.go
exporter/util.go
workspace/resource_notebook.go

This is necessary for performance investigations

Exporter: timestamps are now added to log entries

---

exporter/importables.go

Exporter always skipped clusters that came from the `JOB` cluster sources when it did the listing of clusters.  But clusters may come from other sources us well, like, DLT pipeline maintenance, and as result, they were emitted as normal clusters.
This PR adds checks for more cluster sources

Exporter: Skip emitting of clusters that come from more cluster sources

---

docs/guides/unity-catalog-azure.md
docs/guides/unity-catalog-gcp.md
docs/guides/unity-catalog.md

Fix typo in docs

---

docs/resources/grant.md
docs/resources/grants.md
docs/resources/permission_assignment.md
docs/resources/storage_credential.md

Closes #3139, closes #3036, closes #2778

Various documentation updates

---

catalog/resource_connection.go
internal/acceptance/connection_test.go

Closes #3162, closes #3175. Add extra integration tests to cover these

Fix `databricks_connection` regression when creating without owner

---

internal/acceptance/job_test.go

Fix notebook parameters in acceptance test. 
See https://github.com/databricks/terraform-provider-databricks/pull/3158/files#r1475839010

Fix notebook parameters in acceptance test

---

jobs/resource_job.go
jobs/resource_job_test.go

- Changes the data type of value field to int64 from int32.
Unit tests updated.

Change type of value field to int64

---

internal/acceptance/sql_table_test.go

We don't support column updates

Fixed `TestUcAccResourceSqlTable_Managed` test

---

CHANGELOG.md
common/version.go

* Explicitly set securable field when reading [databricks_grants](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/grants) or [databricks_grant](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/grant) ([#3246](https://github.com/databricks/terraform-provider-databricks/pull/3246)).
* Added information on `id` and other exposed attributes where appropriate ([#3237](https://github.com/databricks/terraform-provider-databricks/pull/3237)).
* Fixed docs in metastore databricks_grants example ([#3239](https://github.com/databricks/terraform-provider-databricks/pull/3239)).
* Detect & handle deleted workspace objects (notebooks/files/directories) when running in incremental mode …

Release v1.36.3

---

docs/guides/experimental-exporter.md
exporter/exporter_test.go
exporter/importables.go
exporter/importables_test.go

UC exporter databricks storage credential feature.

UC exporter databricks storage credential feature

---

catalog/data_storage_credential.go
catalog/data_storage_credential_test.go
catalog/data_storage_credentials.go
catalog/data_storage_credentials_test.go
docs/data-sources/catalogs.md
docs/data-sources/metastore.md
docs/data-sources/metastores.md
docs/data-sources/schemas.md
docs/data-sources/storage_credential.md
docs/data-sources/storage_credentials.md
docs/data-sources/tables.md
docs/data-sources/volumes.md
internal/acceptance/data_storage_credential_test.go
internal/acceptance/data_storage_credentials_test.go
provider/provider.go

Add `databricks_storage_credential` and `databricks_storage_credentials` data sources

Add `databricks_storage_credential` and `databricks_storage_credentials` data sources

---

docs/resources/job.md

[Context](https://github.com/databricks/universe/pull/496812)

Update `for_each_task` docs.

---

docs/guides/troubleshooting.md
docs/guides/unity-catalog-azure.md
docs/guides/unity-catalog-default.md
docs/guides/unity-catalog-gcp.md
docs/guides/unity-catalog.md
docs/resources/file.md
docs/resources/grants.md
docs/resources/share.md
docs/resources/sql_widget.md
docs/resources/vector_search_endpoint.md

- Add user guide for UC by default
- `make fmt-docs`

Add user guide for new behaviours with UC by default

---

docs/data-sources/storage_credentials.md

Fix code example in the docs of `databricks_storage_credentials` data source

---

scripts/diff-schema.sh

When we changed from master to main for the default branch, we needed to update this as well.

Update master to main in diff schema

---

vectorsearch/resource_vector_search_endpoint.go

Increase default timeout for `databricks_vector_search_endpoint`

---

go.mod
go.sum
internal/acceptance/default_namespace_test.go
internal/acceptance/restrict_workspace_admins_test.go
settings/generic_setting_test.go
settings/resource_default_namespace_setting.go
settings/resource_restrict_workspace_admins_setting.go
settings/resource_restrict_workspace_admins_setting_test.go

Updating Go SDK to new release https://github.com/databricks/databricks-sdk-go/releases/tag/v0.34.0 and fixing backwards incompatible changes
Unit tests, triggered nightly run.

Update Go SDK to latest + Fix backwards incompatible change

---

docs/resources/metastore_assignment.md
docs/resources/metastore_data_access.md

Docs: fix broken links in metastore-related docs

---

docs/resources/service_principal.md

Clarify in the docs that Databricks-managed service principals could be used on all clouds

Docs: update documentation about databricks-managed service principals

---

exporter/exporter_test.go
exporter/importables.go
exporter/importables_test.go
internal/acceptance/secret_acl_test.go
internal/acceptance/secret_scope_test.go
secrets/resource_secret.go
secrets/resource_secret_acl.go
secrets/resource_secret_acl_test.go
secrets/resource_secret_scope.go
secrets/resource_secret_scope_test.go
secrets/resource_secret_test.go

Port `databricks_secret_scope`, `databricks_secret` and `databricks_secret_acl` to Go SDK

---

internal/acceptance/job_test.go

Add integration test for ForEachTask

Add integration test for ForEachTask

---

catalog/resource_sql_table.go
catalog/resource_sql_table_test.go
internal/acceptance/group_test.go
internal/acceptance/sql_table_test.go

- These test cases shouldn't be using the same table name so that we can avoid race conditions

Fix integration test for sql column update

---

serving/resource_model_serving.go
serving/resource_model_serving_test.go

With switch to `served_entities` the `scale_to_zero_enabled` became optional, and as result, `false` value wasn't sent.  This PR fixes this issue by always sending that field.
Besides that, PR contains following changes:
* Delete model serving if error happened during the wait time (like it was done for Vector Search endpoints and online tables)
* Instead of using deprecated `CreateAndWait` function, use `wait.GetWithTimeout`

Fix sending `scale_to_zero_enabled` for `served_entities` in `databricks_model_serving` resource

---

docs/resources/share.md

Docs: add `MODEL` to documentation about `data_object_type` in `databricks_share` resource

---

docs/resources/instance_pool.md
pools/resource_instance_pool.go

Added `zone_id` to `gcp_attributes` of `databricks_instance_pool`

---

catalog/resource_catalog.go
catalog/resource_catalog_test.go
catalog/resource_schema.go
catalog/resource_schema_test.go
docs/resources/catalog.md
docs/resources/schema.md
internal/acceptance/catalog_test.go
internal/acceptance/schema_test.go

- Add `enable_predictive_optimization` parameter for `databricks_catalog` and `databricks_schema` resources.
- Refactor all catalogs & schemas unit tests to use Mocks

Add `enable_predictive_optimization` parameter for `databricks_catalog` and `databricks_schema` resources.

---

docs/resources/mws_workspaces.md
mws/resource_mws_workspaces.go

Also add, diff suppress with case-insensitive check
Fixes #3429

Document `pricing_tier` of `databricks_mws_workspaces` resource

---

exporter/importables.go
exporter/util.go

Exporter: don't emit permissions and grants if object is going to be ignored

---

clusters/resource_cluster.go
clusters/resource_cluster_test.go

Use ClusterSpec instead of other structs and fix bug due to ForceSendFields. Use Set method for library.

Used `ClusterSpec` in `databricks_cluster` resource

---

catalog/data_external_location.go
catalog/data_external_location_test.go
catalog/data_external_locations.go
catalog/data_external_locations_test.go
docs/data-sources/external_location.md
docs/data-sources/external_locations.md
internal/acceptance/data_external_locations_test.go
provider/provider.go

- Add 2 data sources `databricks_external_locations` and `databricks_external_location`
Resolves #3456

add data sources `databricks_external_locations` and `databricks_external_location`

---

settings/generic_setting.go

Add two new types to `settings/generic_setting.go` - `accountWorkspaceSettingDefinition` and `accountWorkspaceSetting`, to allow settings that can be set at both workspace & account level
This may simplify PRs like #3325

Add account workspace setting type

---

internal/acceptance/directory_test.go
workspace/data_directory.go
workspace/resource_directory.go
workspace/resource_directory_test.go

Switch to Go SDK for `databricks_directory` resource and data source

---

godownloader-databricks-provider.sh

Adjust list of supported platforms in `godownloader-databricks-provider.sh`

---

docs/resources/automatic_cluster_update_setting.md
settings/all_settings.go
settings/generic_setting.go
settings/resource_automatic_cluster_update_setting.go
settings/resource_automatic_cluster_update_setting_test.go

- Added `databricks_automatic_cluster_update_workspace_setting` resource

Added `databricks_automatic_cluster_update_workspace_setting` resource

---

docs/guides/experimental-exporter.md
exporter/importables.go

This resource could be exported only on account level

Exporter: Add support for `databricks_mws_permission_assignment` resource

---

clusters/resource_cluster_test.go
common/reflect_resource.go
common/reflect_resource_test.go

Do not suppress diff if it is explicitly changed to zero
Added regression tests

Do not suppress diff if it is explicitly changed to zero

---

catalog/resource_system_schema.go
catalog/resource_system_schema_test.go
docs/resources/system_schema.md

This will simplify references to the system schemas from other resources, such as, grants.

Added `full_name` attribute to `databricks_system_schema` resource

---

docs/data-sources/aws_unity_catalog_assume_role_policy.md
docs/data-sources/aws_unity_catalog_policy.md

[DOC] Fix errors in Unity Catalog data sources documentation

---

docs/guides/azure-private-link-workspace-simplified.md

[DOC] Fix private DNS zone resource name in ADB PL Simplified guide

---

internal/acceptance/job_test.go
jobs/jobs_api_go_sdk.go

- Apply cluster validation and various other cluster spec updates 
- Address issue like: https://github.com/databricks/terraform-provider-databricks/issues/3533 but for jobs
- Updated `job_test.go` to make the new_cluster config accurate for single node clusters

Apply all cluster validations to jobs cluster references

---

docs/resources/permissions.md
permissions/resource_permissions.go

Added `CAN_MONITOR` permission to SQL warehouses in `databricks_permissions`

---

catalog/bindings/bindings.go
catalog/resource_catalog.go
catalog/utils.go

- Refactored some common functions for workspace bindings

Refactored common functions for workspace bindings

---

CHANGELOG.md
common/version.go

* Fixed case sensitivity for principals in `databricks_grants` and `databricks_grant` ([#3708](https://github.com/databricks/terraform-provider-databricks/pull/3708)).
* Update cluster policy doc ([#3707](https://github.com/databricks/terraform-provider-databricks/pull/3707)).
* Refactor some common functions for workspace bindings ([#3702](https://github.com/databricks/terraform-provider-databricks/pull/3702)).

Release v1.48.1

---

CHANGELOG.md
common/version.go

* Added isolation mode support for `databricks_external_location` & `databricks_storage_credential` ([#3704](https://github.com/databricks/terraform-provider-databricks/pull/3704)).
* Add terraform support for periodic triggers ([#3700](https://github.com/databricks/terraform-provider-databricks/pull/3700)).

Release v1.48.2

---

exporter/importables.go
exporter/util.go

Exporter: use Go SDK structs for `databricks_job` resource

---

.terraform-registry

Quick PR to change the ownership of the TF registry to myself.

Change TF registry ownership

---

catalog/data_schema.go
catalog/data_schema_test.go
docs/data-sources/schema.md
docs/data-sources/volume.md
internal/acceptance/data_schema_test.go
provider/provider.go

Adding a new data source for completeness of our data sources for UC objects.
Also fixed some problems in `databricks_volume` docs.

Add `databricks_schema` data source

---

exporter/importables.go
exporter/util.go

Exporter: export libraries specified as `requirements.txt`

---

go.mod
go.sum

Bump Go SDK to v0.43.1
Unit tests. Integration tests will run on release PR

Upgraded `databricks-sdk-go` to latest version

---

.codegen.json
.codegen/changelog.md.tmpl
.codegen/changelog_config.yml
.github/dependabot.yml
.github/workflows/push.yml

Improve Changelog by grouping changes
```
Release v1.49.0
* Add `databricks_schema` data source ([#3732](https://github.com/databricks/terraform-provider-databricks/pull/3732)).
* Bump golang.org/x/mod from 0.18.0 to 0.19.0 ([#3739](https://github.com/databricks/terraform-provider-databricks/pull/3739)).
* Exporter: Emit directories during the listing only if they are explicitly configured in `-listing` ([#3673](https://github.com/databricks/terraform-provider-databricks/pull/3673)).
* Exporter: export libraries specified as `requirements.txt` ([#3649](https://github.com/databricks/terraform-provider-databricks/pull/3649)).
* Update cluster.md: add data_security_mode parameters `NONE` and `NO_ISOLATION` ([#3740](https://github.com/databricks/terraform-provider-databricks/pull/3740)).
```

[Internal] Improve Changelog by grouping changes

---

go.mod
go.sum

Bump Go SDK to latest version
Unit tests, Nightly tests will be run on Release PR

[Dependency] Upgrade Go SDK to v0.43.2

---

docs/guides/experimental-exporter.md

[Exporter] clarify use of `-listing` and `-services` options

---

common/reflect_resource_plugin_framework.go

- There were two cases that should never occur given that we decided to use go native maps and slices. Make those panic

Clean up converter function edge cases

---

go.sum

Clearing old values of Go SDK in go.sum
Unit tests

[Internal] Clear stale go.sum values

---

docs/resources/job.md

[Doc] Clarified schedule block in `databricks_job`

---

docs/guides/troubleshooting.md

[Doc] Add troubleshooting instructions for `databricks OAuth is not supported for this host` error

---

docs/resources/job.md

- Added documentation for `description` and `disable_auto_optimization` attributes.
- Sorted task attributes by name for easier search

[Doc] Document missing task attributes in `databricks_job` resource

---

catalog/permissions/permissions.go
exporter/exporter_test.go
exporter/importables.go
exporter/importables_test.go
go.mod
go.sum
sharing/data_shares.go
sharing/data_shares_test.go

Fixed some errors in TF provider which came due to use of latest GO SDK version

[Fix] Update Go SDK

---

docs/guides/experimental-exporter.md
exporter/importables.go
exporter/importables_test.go

[Exporter] Add support for `databricks_online_table`

---

docs/resources/cluster.md
docs/resources/instance_pool.md

[Doc] clarified `spot_bid_max_price` option for `databricks_cluster`

---

docs/resources/pipeline.md
exporter/exporter_test.go
exporter/importables.go
exporter/importables_test.go
internal/acceptance/pipeline_test.go
pipelines/data_pipelines_test.go
pipelines/resource_pipeline.go
pipelines/resource_pipeline_test.go

Reverts databricks/terraform-provider-databricks#3792

[Internal]  Revert "Rewriting DLT pipelines using SDK"

---

internal/acceptance/data_volumes_test.go
pluginframework/data_volumes.go

- Make `ids` computed
- Add test case for `data_volumes_pluginframework`

Add acceptance test for volumes data source

---

clusters/resource_cluster.go
clusters/resource_cluster_test.go

Clusters can only be updated while in Running and Terminated state. This causes TF to fail
to update Autoscaling Clusters if there is an ongoing resize.

[Fix] Retry cluster update on "INVALID_STATE"

---

exporter/exporter_test.go
exporter/importables.go
exporter/test-data/get-dlt-pipeline.json

This PR includes following changes:
- emitting of email notifications recipients
- checking the generated code to detect problems earlier

[Exporter] Improve exporting of DLT and test coverage

---

.github/workflows/validate-sha.yml

This PR checks if the openapi_sha is equal with the one used in databricks-sdk-go dependency.

[Fix] OPENAPI_SHA check

---

docs/resources/workspace_binding.md

[Doc] fix possible values for `securable_type` in `databricks_workspace_binding`

---

docs/resources/workspace_binding.md

Small docs fix to update the example import command for the `databricks_workspace_binding` resource.

[Doc] Update workspace_binding import command

---

docs/resources/connection.md

[Doc] Mention Salesforce as supported type in `databricks_connection`

---

docs/data-sources/aws_unity_catalog_assume_role_policy.md

Closes #3966 
Fixed example issue.
Fixed example

[Doc] Update aws_unity_catalog_assume_role_policy.md

---

docs/resources/metastore_assignment.md

Update metastore_assignment.md to properly reflect possible usage.
Related to #3963

[Doc] Update metastore_assignment.md to properly reflect possible usage

---

pools/resource_instance_pool.go

[Fix] Add suppress diff for `azure_attributes.spot_bid_max_price` in `databricks_instance_pool`

---

internal/providers/pluginfw/tfschema/struct_to_schema.go
internal/providers/pluginfw/tfschema/struct_to_schema_test.go

Added support for `computed` tag in TfSDK Structs making code easier to maintain and read, minimising the lines of code required in customizing the schema 
Unit test

[Internal] Add support for `computed` tag in TfSDK Structs

---

docs/resources/vector_search_index.md

[Doc] Update `databricks_vector_search_index` docs to match latest SDK

---

internal/providers/pluginfw/tfschema/bool_attribute.go
internal/providers/pluginfw/tfschema/customizable_schema.go
internal/providers/pluginfw/tfschema/customizable_schema_test.go
internal/providers/pluginfw/tfschema/float64_attribute.go
internal/providers/pluginfw/tfschema/int64_attribute.go
internal/providers/pluginfw/tfschema/list_attribute.go
internal/providers/pluginfw/tfschema/list_nested_attribute.go
internal/providers/pluginfw/tfschema/map_attribute.go
internal/providers/pluginfw/tfschema/map_nested_attribute.go
internal/providers/pluginfw/tfschema/single_nested_attribute.go
internal/providers/pluginfw/tfschema/string_attribute.go

- Add `AddPlanModifier` methods for all AttributeBuilders so that we can do things equivalent to set supress diff or force new

[Internal] Add `AddPlanModifer` method for AttributeBuilder

---

internal/providers/pluginfw/pluginfw.go
internal/providers/pluginfw/resources/library/resource_library.go
internal/providers/pluginfw/resources/library/resource_library_test.go

- Add library resource to plugin framework, not officially migrating because it has suffix `_pluginframework`
- Added integration test for creation and importing

[Feature] Library plugin framework migration

---

internal/providers/pluginfw/resources/library/resource_library.go

[Internal] Clean up comments in library resource

---

exporter/importables.go

So we can avoid generation of not related cluster resources

[Exporter] Expand list of non-interactive clusters

---

docs/data-sources/mlflow_models.md
internal/acceptance/data_mlflow_models_test.go
internal/providers/sdkv2/sdkv2.go
mlflow/data_mlflow_models.go
mlflow/data_mlflow_models_test.go

Add `databricks_mlflow_models` data source
Add integration and acceptance test
Resolves #3791

[Feature] Add `databricks_mlflow_models` data source

---

docs/data-sources/mlflow_models.md
docs/guides/azure-authenticate-with-oidc.md
docs/resources/budget.md
docs/resources/sql_table.md

[Doc] Reformat code examples in documentation

---

internal/acceptance/registered_model_test.go

Remove unsupported attribute `include_model_versions`

[Internal] Fix acceptance test for `databricks_registered_model` data source

---

exporter/importables.go
exporter/importables_test.go

[Exporter] Exclude some system schemas from export

---

docs/guides/unity-catalog.md

[Doc] Fix for UC on AWS guide - use `databricks_aws_unity_catalog_assume_role_policy` where necessary

---

.github/workflows/external-message.yml
.github/workflows/integration-tests.yml

Old script could not be run from master due to security restrictions and there is no reliable way to detect if a user as secrets.
Opened a PR in SDK Java from fork
https://github.com/databricks/databricks-sdk-java/pull/375

[Internal] Always write message for manual test integration

---

docs/guides/gcp-workspace.md

Match the corresponding (upcoming) changes to https://docs.gcp.databricks.com/en/admin/cloud-configurations/gcp/permissions.html#required-permissions-for-the-workspace-creator

[Doc] Update "Databricks Workspace Creator" permissions on gcp-workspace.md

---

exporter/command.go
exporter/command_test.go

[Exporter] Fix interactive selection of services

---

docs/data-sources/mws_network_connectivity_configs.md
mws/data_mws_network_connectivity_configs.go

- Add missing H2 header in `mws_network_connectivity_configs.md` 
- Remove unnecessary variable in `data_mws_network_connectivity_configs`
Ran integration test

[Fix] Add missing H2 header in `mws_network_connectivity_configs.md` and optimization in `data_mws_network_connectivity_configs`

---

docs/resources/mws_customer_managed_keys.md
docs/resources/mws_networks.md
docs/resources/mws_private_access_settings.md
docs/resources/mws_storage_configurations.md
docs/resources/mws_workspaces.md

Some resources are documented as not being importable, but some actually are. This PR adds docs to a few that I was able to test out myself.
Imported existing resources into a local TF project, which worked.

[Doc] Update documentation for importing some MWS resources

---

docs/resources/notification_destination.md

[Doc] Document import support for `databricks_notification_destination`

---

storage/adls_gen1_mount.go
storage/adls_gen2_mount.go
storage/adls_gen2_mount_test.go
storage/aws_s3_mount.go
storage/azure_blob_mount.go
storage/azure_blob_mount_test.go
storage/generic_mounts.go
storage/gs.go
storage/mounts.go
storage/mounts_test.go
storage/resource_mount_test.go
storage/s3.go

[Fix] Use correct domain for Azure Gov and China

---

exporter/importables.go

Right now, to export vector search indexes and online tables, the `uc-tables` needs to be specified in the listing. This PR removes this limitation by checking if the corresponding service is enabled without requiring `uc-tables` to be enabled as well.

[Exporter] better handling of online tables/vsis in listing

---

exporter/importables.go

During refactoring, the exact references to user's home were removed, leading to the problems with references when doing initial import

[Exporter] Fix generation of references to users for user directories

---

docs/guides/experimental-exporter.md
exporter/context.go
exporter/exporter_test.go
exporter/importables.go
exporter/importables_test.go
exporter/util.go

[Exporter] add support for `databricks_credential`

---

.github/workflows/codeql-analysis.yml
.github/workflows/external-message.yml
.github/workflows/integration-tests.yml
.github/workflows/release.yml

Fixes #4376.
Supersedes #4080.
Note: the YAML files were unformatted; please review with "hide whitespace".

[Internal] Migrate workflows that need write access to use hosted runners

---

.github/workflows/tagging.yml

[Internal] Remove .extraheader config

---

.github/workflows/tagging.yml
tagging.py

[Internal] Remove tag signing in tagging.py script

---

CHANGELOG.md
NEXT_CHANGELOG.md

[Internal] Document transition to new release infrastructure

---

.github/workflows/tagging.yml
NEXT_CHANGELOG.md

[Internal] Use github app token in checkout action

---

.github/workflows/next-changelog.yml
.github/workflows/tagging.yml
tagging.py

Update the tagging.py tool and workflows to latest internal version.

[Internal] Update tagging resources

---

NEXT_CHANGELOG.md
docs/resources/job.md

- The `environment` block is defined on a job level, not on the task level
- Showed that library is defined on the task level
Also removed the entries for already released PRs

[Doc] Improve examples and fix headers layout for `databricks_job`

---

internal/acceptance/init.go
jobs/job_test.go
pipelines/pipeline_test.go
pipelines/resource_pipeline.go

Resolves https://github.com/databricks/terraform-provider-databricks/issues/4398. No updates to docs or changelog, because feature is in private preview

[Feature] Support `run_as` in pipelines

---

NEXT_CHANGELOG.md
docs/resources/permissions.md

[Doc] Add an example for Databricks Apps permissions

---

NEXT_CHANGELOG.md
exporter/impl_dbsql.go
exporter/impl_scim.go
exporter/impl_uc.go
exporter/importables.go
exporter/util.go

[Exporter] Refactor UC, SQL and SCIM objects into separate files

---

NEXT_CHANGELOG.md
internal/providers/pluginfw/products/library/resource_library_acc_test.go

[Internal] Remove incorrectly working integration test `TestAccLibraryUpdateTransitionFromPluginFw`

---

NEXT_CHANGELOG.md
catalog/resource_connection.go
docs/resources/connection.md

Switch to Go SDK structs for `databricks_connection` resource.
Resolves #4494

[Feature] Expose more attributes for `databricks_connection` resource

---

docs/resources/credential.md
docs/resources/volume.md

- UC volume & service credential are both GA

[Doc] mark `databricks_volume` and `databricks_credential` as GA

---

NEXT_CHANGELOG.md
docs/data-sources/dashboards.md
internal/providers/pluginfw/pluginfw_rollout_utils.go
internal/providers/pluginfw/products/dashboards/data_dashboards.go
internal/providers/pluginfw/products/dashboards/data_dashboards_acc_test.go

- Add `databricks_dashboards` data source. Resolve #4451

[Feature] add `databricks_dashboards` data source

---

NEXT_CHANGELOG.md
docs/data-sources/app.md
docs/data-sources/apps.md
docs/resources/app.md

[Doc] Document `budget_policy_id` in `databricks_app` resource and data sources

---

exporter/exporter_test.go
exporter/importables_test.go

[Exporter] Improve test coverage and some refactoring

---

NEXT_CHANGELOG.md
docs/resources/model_serving.md

Add more model serving examples

[Doc] Add more model serving examples

---

NEXT_CHANGELOG.md
docs/resources/job.md

Document `performance_target` in `databricks_job`

---

NEXT_CHANGELOG.md
docs/resources/job.md
jobs/job_test.go
jobs/resource_job.go
jobs/resource_job_test.go

Supporting dashboard task in terraform. 
For some contexts, see: https://databricks.slack.com/archives/C07K5C17CKC/p1742922037539009

[FEATURE] Support dashboard task in Terraform

---

NEXT_CHANGELOG.md
docs/resources/job.md

Updated `spark_python_task` option in `databricks_job`

[Doc] Updated `spark_python_task` option in `databricks_job`

---

NEXT_CHANGELOG.md
docs/resources/job.md
jobs/resource_job.go

Document `on_streaming_backlog_exceeded` in email/webhook notifications in `databricks_job`

---

.github/ISSUE_TEMPLATE/provider-issue.md

Also, added a link to Databricks community site

[Internal] Add link to troubleshooting guide to the issue template

---

NEXT_CHANGELOG.md
docs/data-sources/budget_policies.md
docs/data-sources/budget_policy.md
docs/resources/budget_policy.md

This needs to be fixed in proto as it's autogenerated, fixing it here for time being as we have a ticket to follow up with cluster team. 
N/A

[Internal] Fixed documentation for budget_policy until it's fixed in proto

---

NEXT_CHANGELOG.md

We use tagging.py which automatically infers version from NEXT_CHANGELOG. Updating it to patch as we already had SDK generation and we need to release: https://github.com/databricks/terraform-provider-databricks/pull/4622
N/A

[Internal] Update next release version to be patch

---

NEXT_CHANGELOG.md
docs/guides/aws-workspace.md
docs/guides/gcp-private-service-connect-workspace.md
docs/guides/gcp-workspace.md
docs/index.md
docs/resources/mws_workspaces.md

- Recommend OAuth instead of PAT

[Documentation] Recommend OAuth instead of PAT

---

NEXT_CHANGELOG.md
docs/resources/connection.md

- Add examples on how to create PowerBI & HTTP connection

[Doc] Added more examples for `databricks_connection`

---

NEXT_CHANGELOG.md
serving/resource_model_serving.go

The corresponding field wasn't specified in the code for updating AI Gateway settings.
Resolves #4798

Fix updating of of `fallback_config` in `databricks_model_serving`

---

NEXT_CHANGELOG.md
docs/resources/git_credential.md

- removing mention of a single Git credential
- Add example of using `azureDevOpsServicesAad` for SP federation

[Doc] Improve documentation for `databricks_git_credential` resource

---

NEXT_CHANGELOG.md
docs/guides/unity-catalog-azure.md

The Azure Databricks UC documentation lists four required roles, but we had only two. See https://learn.microsoft.com/en-us/azure/databricks/connect/unity-catalog/cloud-storage/manage-external-locations#for-azure-data-lake-storage-containers

[Doc] Update the list of UC permissions in UC guide for Azure

---

NEXT_CHANGELOG.md
docs/resources/model_serving.md
serving/resource_model_serving.go

Document new fields in `databricks_model_serving` and deprecate `invalid_keywords` and `valid_topics` in AI Gateway configuration

---

NEXT_CHANGELOG.md
docs/data-sources/app.md
docs/data-sources/apps.md
docs/resources/app.md

Add description of `database` resource in Apps. Should be merged after #4844

Document new attributes in `databricks_app` resource and data sources

---

NEXT_CHANGELOG.md
docs/resources/pipeline.md

Document `environment` block in `databricks_pipeline`

---

docs/data-sources/service_principal.md
docs/data-sources/service_principals.md
docs/data-sources/user.md
docs/resources/entitlements.md
docs/resources/group_instance_profile.md
docs/resources/group_member.md
docs/resources/group_role.md
docs/resources/mws_permission_assignment.md
docs/resources/permission_assignment.md
docs/resources/service_principal.md
docs/resources/sql_permissions.md
docs/resources/user.md

[Doc] Fix references to `databricks_group` + other small changes

---

test-config.yaml

[Internal] Remove system schema tests from flacky tests list

---

NEXT_CHANGELOG.md
docs/resources/grant.md
docs/resources/grants.md

- Clarify difference between `databricks_grants` resources

[Doc] Clarify difference between `databricks_grants` resources

---

NEXT_CHANGELOG.md
docs/resources/sql_visualization.md
docs/resources/sql_widget.md
sql/resource_sql_visualization.go
sql/resource_sql_widget.go

These resources are deprecated.
Existing tests

[Documentation] Deprecate `databricks_sql_visualization` and `databricks_sql_widget` resource.

---

NEXT_CHANGELOG.md
docs/resources/sql_endpoint.md

[Doc] Deprecate `data_source_id` attribute in `databricks_sql_endpoint` resource

---

NEXT_CHANGELOG.md
catalog/grant_test.go
catalog/grants_test.go
docs/resources/sql_table.md

Verify that METRIC_VIEW table works for both grant and grants terraform resource
Integration tests

[Internal] Added integration test for METRIC_VIEW table type in `databricks_grant` and `databricks_grants`

---

NEXT_CHANGELOG.md
docs/resources/grant.md

It was a bit vague to understand the difference between grant and grants based on the current description. The text made sense after you understood the difference, but this small change will make it instantly understandable.

DOCS: Clarify grant vs grants

---

NEXT_CHANGELOG.md
exporter/impl_jobs.go
exporter/importables.go

- handling of email notifications in model serving
- handling of root path, run as, environment in DLT pipelines
- handling of environments in jobs

[Exporter] Improve handling of new dependencies in jobs, pipelines, model serving

---

docs/resources/budget.md

`databricks_budget` is the only resource in the `FinOps` category, so it makes sense to unify with the rest of billing-related resources

[Doc] Change category to `Billing` for `databricks_budget`

---

NEXT_CHANGELOG.md
docs/resources/mws_ncc_private_endpoint_rule.md
mws/resource_mws_ncc_private_endpoint_rule.go
mws/resource_mws_ncc_private_endpoint_rule_test.go

[Fix] enable updating `databricks_mws_ncc_private_endpoint_rule`

---

NEXT_CHANGELOG.md
docs/resources/notification_destination.md
settings/resource_notification_destination.go

Document and handle additional Microsoft Teams options in `databricks_notification_destination`

---

NEXT_CHANGELOG.md
docs/resources/job.md

Document task_retry_mode

---

NEXT_CHANGELOG.md
exporter/importables.go

[Exporter] Handle new attributes for Slack and MS Teams in `databricks_notification_destination`

---

NEXT_CHANGELOG.md
catalog/resource_catalog.go
catalog/resource_catalog_test.go
docs/resources/catalog.md

[Fix] Mark `storage_location` as read-only in `databricks_catalog`
